### ISSUE TITLE
Add ability to send pre-GZIPPED static files

### ISSUE THREAD

**Issue by mozumder** [h2o/h2o#1024]
Hi,

Nginx has a feature where it can send pre-Gzipped static files when those static files exist with a .gz extension.

Would it be possible to add this feature to h2o?  Instead of on-the-fly compression (which increases latency), I'd like to serve either the .gz file (if it exists) or an uncompressed static file.

**Comment by skirsten** [comment]
This feature already exists see [https://h2o.examp1e.net/configure/file_directives.html#send-compressed](https://h2o.examp1e.net/configure/file_directives.html#send-compressed).

**Comment by mozumder** [comment]
thanks.   missed that!
