### ISSUE TITLE
Does libh2o parse query parameters?

### ISSUE THREAD

**Issue by kishorenc** [h2o/h2o#1026]
I'm trying to use libh2o, and was looking at the `simple.c` example. I could not find a way to fetch the parsed query params from the `req` struct. Do I have to parse the `req->path` manually?

**Comment by deweerdt** [comment]
Hello @kishorenc! I believe you should be able to access the query by using `req->query_at`. See https://github.com/h2o/h2o/blob/master/lib/handler/status.c#L216
