### ISSUE TITLE
Not possible to create shared libs

### ISSUE THREAD

**Issue by daniel-lucio** [h2o/h2o#1055]
I am using the following cmake line 
cmake -DWITH_BUNDLED_SSL=on -DWITH_MRUBY=on -DCMAKE_INSTALL_PREFIX=%{_prefix} -DBUILD_SHARED_LIBS=on -DBUILD_SHARED_LIBS=yes .
It builds okay, but after the make install. I dont find any libh20.so* files. What is the correct flag?

**Comment by daniel-lucio** [comment]
I think I found it, I will confirm later. It requires libuv > 1.0 to create shared libraries.

**Comment by daniel-lucio** [comment]
-- checking for module 'libuv>=1.0.0'
--   found libuv, version 1.9.1
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:117 (set):
  Syntax error in cmake code at

    /usr/share/cmake/Modules/FindPkgConfig.cmake:117

  when parsing string

    ;\{includedir\}

  Invalid escape sequence \{
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPkgConfig.cmake:144 (_pkgconfig_set)
  /usr/share/cmake/Modules/FindPkgConfig.cmake:151 (_pkgconfig_invoke)
  /usr/share/cmake/Modules/FindPkgConfig.cmake:313 (_pkgconfig_invoke_dyn)
  /usr/share/cmake/Modules/FindPkgConfig.cmake:333 (_pkg_check_modules_internal)
  CMakeLists.txt:107 (PKG_CHECK_MODULES)


-- Configuring incomplete, errors occurred!
error: Bad exit status from /var/tmp/rpm-tmp.dfWOGD (%build)



Any pointer?

**Comment by syohex** [comment]
Which CMake version did you use ? I didn't get such error with CMake version 3.6.1.

**Comment by daniel-lucio** [comment]
Fixed, i was having a typo in the libuv.pc file. I can confirm you must have libuv-devel in order to create the .so files

**Comment by iceb0y** [comment]
I have recently used `cmake -DBUILD_SHARED_LIBS=ON ..` to build shared lib (`libh2o-evloop.so.0.11.4`) for h2o-2.0.4 on linux.
