### ISSUE TITLE
http1client: unable to get local issuer certificate

### ISSUE THREAD

**Issue by trss** [h2o/h2o#1072]
I get the error "unable to get local issuer certificate" when I compile and run `examples/libh2o/http1client.c`.

Steps to add error reporting:

1. Include the header `<openssl/err.h>`.
1. Paste the function definition for `print_errors` at https://github.com/openssl/openssl/blob/5ae4ceb92c2ae6c677b1de2c477dce71a4d94716/test/danetest.c#L57 after all the includes.
1. Change the line at https://github.com/h2o/h2o/blob/v2.0.3/examples/libh2o/http1client.c#L151 to the following.

    ```
        if (!SSL_CTX_load_verify_locations(ctx.ssl_ctx, H2O_TO_STR(H2O_ROOT) "/share/h2o/ca-bundle.crt", NULL))
            print_errors();
    ```

Error report:
```
Error: error:02001002:system library:fopen:No such file or directory:bss_file.c:175:fopen('H2O_ROOT/share/h2o/ca-bundle.crt','r')
Error: error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:178
Error: error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:by_file.c:253
unable to get local issuer certificate
```

Workaround:

Of course, when I change the argument `H2O_TO_STR(H2O_ROOT) "/share/h2o/ca-bundle.crt"` to just `"share/h2o/ca-bundle.crt"` in `examples/libh2o/http1client.c` and run the program from the H2O root directory, this error doesn't occur.

**Comment by kazuho** [comment]
Please run make install to install the files before using the example.

**Comment by trss** [comment]
Oh, alright. I just did an out of source build of libh2o. All the other examples under libh2o worked fine. Using the workaround for `http1client` for now. Thanks.
