### ISSUE TITLE
http1client: unreachable code

### ISSUE THREAD

**Issue by trss** [h2o/h2o#1073]
There's an `if (1)` in `examples/libh2o/http1client` at https://github.com/h2o/h2o/blob/v2.0.3/examples/libh2o/http1client.c#L65 which got introduced at https://github.com/h2o/h2o/commit/5e2dda2b58d4431872589089e062da5761966ae3#diff-49504e3c92df67724ec0c756e1b4b838R63 and that commit has `[wip]` in its description.

I'd like to know if this example needs a bit more work to be complete as I'm learning from it.

Thank you.

**Comment by kazuho** [comment]
It's intentional. The taken-side of the if branch contains code using a connection pool. The not-taken side contains code that doesn't use it.

If you run git log --branch then you'd notice that the commit has been a WIP of a PR.

**Comment by trss** [comment]
It did look that way but wanted to be sure. Thanks a lot for the clarification.
