### ISSUE TITLE
Where can I find "uvwslay" library?

### ISSUE THREAD

**Issue by rock59** [h2o/h2o#1081]
I read this blog post (http://blog.kazuhooku.com/2014/09/the-reasons-why-i-stopped-using-libuv.html)
Where can I find "uvwslay" library? 
(https://github.com/kazuho/h2o/tree/73c5ec99cb186c0d2328c0d65599bd3ba948c3a6/deps/uvwslay)
The url returns 404

**Comment by deweerdt** [comment]
That might because the repo moved since, this URL should work: https://github.com/h2o/h2o/tree/73c5ec99cb186c0d2328c0d65599bd3ba948c3a6/deps/uvwslay

**Comment by rock59** [comment]
@deweerdt It works . thanks a million
