### ISSUE TITLE
Does H2O support WINDOWS X86/X64 platform?

### ISSUE THREAD

**Issue by zjbqk521** [h2o/h2o#1086]
Hi, my master,
I download the H2O, but how to compile and run on windows 32 or 64bits platform? i want to code and make some testing, finally deployed on ubuntu server?

i use CMake tool on windows.

Please give some suggestion.

Thanks.

**Comment by kazuho** [comment]
Please refer to #329.

**Comment by metalwood** [comment]
libh2o official support list doesn't have windows, I think this is a bad idea.
