### ISSUE TITLE
H2 connection stuck in H2O_HTTP2_CONN_STATE_IS_CLOSING

### ISSUE THREAD

**Issue by deweerdt** [h2o/h2o#1088]
I've been investigating an issue where the frontend H2 socket never gets closed. I've seen instances where the socket is left open for days, with the other end having closed it for a while. Examining a running instance, I can see that the connection is in `H2O_HTTP2_CONN_STATE_IS_CLOSING` state, and has in fact a stream that is still attached in `H2O_HTTP2_STREAM_STATE_SEND_BODY` state.
A couple of observations:
- The connection idle timeout is not linked
- both the connection and stream window are ~16M
- the read and write callbacks are set to `NULL`
- there's no inflight buffer
- `_write.buf.size` is 0
- `_write.timeout` is not linked
- the epoll socket has `_flags` set to only `H2O_SOCKET_FLAG_IS_ACCEPTED_CONNECTION`
-  the stream has pending data, `size` is 1

Looking at the code, i wondered if the following scenario would trigger that:
- the connection is closed for whatever reason in `parse_input`
- we call `close_connection(conn);`
- `conn->_write.buf_in_flight` is `NULL` but `h2o_timeout_is_linked(&conn->_write.timeout_entry)` is true so we _don't_ call `close_connection_now()`, instead we return `0` from `parse_input()`
- `conn->state` is now `H2O_HTTP2_CONN_STATE_IS_CLOSING`
- back in `on_read()`, timeout is still linked, we unlink it and call `do_emit_writereq(conn)`
- in `do_emit_writereq()`, because state is `H2O_HTTP2_CONN_STATE_IS_CLOSING`, we don't call `emit_writereq_of_openref` on `conn->scheduler` so nothing is emitted
- `conn->_write.buf->size` is `0`, so we exit

At this point,  `timeout_entry` is not linked anymore, and `conn->_write.buf->size`, so nothing will end up calling `on_write_complete` to close the connection.
Thoughts?

**Comment by kazuho** [comment]
Thank you for reporting the issue and debugging through the details.

The scenario sounds logical. I've opened a PR (linked above) that hopefully fixes the issue. Please let me know if it works for you.

**Comment by deweerdt** [comment]
Thank you, i think the PR should address that scenario.

**Comment by kazuho** [comment]
Thank you for the review!
