### ISSUE TITLE
umask for fastcgi.spawn socket

### ISSUE THREAD

**Issue by dpk** [h2o/h2o#1089]
Using the directive `user` in a `fastcgi.spawn` block results in the socket (in `/tmp`) being owned by the correct given user but with mode 700, meaning the web server running as user `www` can't connect to the socket.

I worked around the issue by creating a setuid wrapper in C which simply `exec`s the actual FastCGI script, but it would be nice not to have to do this.

If it makes a difference I'm using Python's flup as a FastCGI server. (And I did try setting the `umask` option provided there, but that did nothing.)

**Comment by kazuho** [comment]
Thank you for noticing this.

By looking at the source code it is obvious that `chmod` is missing, and that explains that one might fall into the issue depending on the value of the default umask.

**Comment by worenga** [comment]
I am running flap aswell in a test scenario where h2o is run as root inside a container.
When i quit H2O via SIGTERM it is unable to remove socket.

> received SIGTERM, gracefully shutting down
> /bin/rm: cannot remove '/tmp/h2o.fcgisock.8wYFgc': Operation not permitted

This is very annoying, as i do have to clean it up manually.

**Comment by kazuho** [comment]
relates to #443

**Comment by kazuho** [comment]
Sorry for taking time. The issue has been fixed with the merger of the PR above. Please let us know if the issue persists.
