### ISSUE TITLE
Feature Request: LibreSSL 2.4.3 or later

### ISSUE THREAD

**Issue by Tintinabula** [h2o/h2o#1094]
On September 27th, 2016 the LibreSSL group made LibreSSL 2.4.3 the latest stable release.

Would it be possible to bundle LibreSSL 2.4.3 or later so H20 can support the IETF version of ChaCha20 in order for Firefox to connect to H20 using aead_chacha20_poly1305() ?

**Comment by kazuho** [comment]
Thank you for the suggestion. Will be done before the release of 2.1.
