### ISSUE TITLE
Server push not working on page reloads

### ISSUE THREAD

**Issue by alfredxing** [h2o/h2o#1101]
Server push seems to be working fine with an MRuby handler:

<img width="451" alt="screen shot 2016-10-05 at 10 52 46 am" src="https://cloud.githubusercontent.com/assets/2704010/19124930/f77afe50-8ae9-11e6-95a2-9812a6f0fad1.png">

But when I refresh the page (and the socket is still open), the server does not push the resources:

<img width="473" alt="screen shot 2016-10-05 at 10 54 13 am" src="https://cloud.githubusercontent.com/assets/2704010/19124970/16f2b05c-8aea-11e6-904a-c5aafe0029a5.png">

Cache is disabled in the developer tools, but I haven't enabled casper either...

Any ideas why this might be the case? I can post the contents of my config file if need be.

**Comment by deweerdt** [comment]
I believe that what you are seeing is the fact that h2o tracks pushed resources for a given connection, so that the same resource isn't pushed twice over the same connection.

**Comment by alfredxing** [comment]
Ah, that's probably it, thanks! Do you know of any way to disable this behaviour, or is it unreasonable to do so?

**Comment by deweerdt** [comment]
I think it serves two purposes:
- it avoids PUSH loops: A pushes B which pushes A (or A which pushes A)
- a PUSH is a bet that the client doesn't have the resource, and we're willing to trade bandwidth for faster page load times. However, if we know we've already sent a resource, what would be the benefit of sending it again?

Do you have a scenario in mind where that would be useful?

**Comment by deweerdt** [comment]
I forgot to mention that I don't believe this behavior can be disabled (grep for `push_memo` in the source). If you're concerned about being able to reproduce pushes in a dev environment, Chrome has a 'Flush sockets' in the right upper corner of chrome://net-internals/#http2 in order to be able to close the sockets from the browser.

**Comment by alfredxing** [comment]
Hmm, that makes sense. Thanks!
