### ISSUE TITLE
Possible memory leak in h2o_context_dispose().

### ISSUE THREAD

**Issue by trss** [h2o/h2o#1107]
Valgrind reports the following memory leak for an adaptation of [`examples/libh2o/simple.c`](https://github.com/h2o/h2o/blob/v2.0.4/examples/libh2o/simple.c) that displays "Hello, world!" at `/`, restarts the server at `/restart`, and stops the server at `/stop`.

```
...
==505==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==505==    by 0x431334: h2o_mem_alloc (memory.h:308)
==505==    by 0x43184A: h2o_mem_alloc_shared (memory.c:175)
==505==    by 0x4160F8: h2o_context_update_timestamp_cache (context.c:184)
==505==    by 0x419F96: h2o_get_timestamp (h2o.h:1706)
==505==    by 0x41AAD2: h2o_accept (util.c:277)
...
```

In Instruments on the Mac, the leak gets reported only when `/restart` or `/stop` is hit.

So I added the following to the end of [`h2o_context_dispose()`](https://github.com/h2o/h2o/blob/v2.0.4/lib/core/context.c#L125) and the leak no longer occurred.

```
    if (ctx->_timestamp_cache.value != NULL)
        h2o_mem_release_shared(ctx->_timestamp_cache.value);
```

Took this snippet from [`h2o_context_update_timestamp_cache()`](https://github.com/h2o/h2o/blob/v2.0.4/lib/core/context.c#L178).

**Comment by kazan417** [comment]
fixed with this  [commit](https://github.com/h2o/h2o/commit/945d5a61ee4362af1a350ad7da51a33c40113110) 
Please close
