### ISSUE TITLE
Supporting an HTTP/2 extension with libh2o.

### ISSUE THREAD

**Issue by kevinswiber** [h2o/h2o#1129]
Hi there.

I'm looking at the possibility of using libh2o and including support for an HTTP/2 server extension that was proposed a while ago, [Peer-to-peer Extension to HTTP/2](https://tools.ietf.org/html/draft-benfield-http2-p2p-02).

This would require inspecting the HTTP/2 communication for a specific setting, `SETTINGS_PEER_TO_PEER`, and adding support for a `CLIENT_AUTHORITY` frame.

Is this possible through libh2o or would I have to fork the h2o project to accomplish this?  Any insight would be helpful.

Thanks!

**Comment by kazuho** [comment]
Thank you for opening the issue. Sounds interesting.

Unfortunately, H2O does not provide a mechanism to add new settings or frames. You might want to look into nghttp2; my understanding is that it provides interface to add new frames, at least.

However, also note that (per my understanding) that the I-D changes the behavior of frames defined in HTTP/2 as well as the state machine. Therefore, regardless of which HTTP2 library you choose, I believe that you would need to modify the library itself.

**Comment by kevinswiber** [comment]
@kazuho Of course. Thank you!
