### ISSUE TITLE
Casper cookies aren't secure

### ISSUE THREAD

**Issue by mozumder** [h2o/h2o#1132]
Hi,

I just did an audit on a server running h2o and found that the CASPER cookies aren't sent with the Secure instruction.  A cookie sent from the server to a web browser via the HTTPs protocol should only transit on a secure connection (except for some specific cases).

Please let me know if that's supposed to be the correct procedure or a bug?

Thank you,

-bobby

**Comment by kazuho** [comment]
Thank you for reporting this.

I consider this as a bug that needs to be fixed in the upcoming 2.1 release as well as backported to previous releases.

**Comment by mozumder** [comment]
thank you!
