### ISSUE TITLE
Run in daemon mode without root

### ISSUE THREAD

**Issue by kikacaty** [h2o/h2o#1137]
I am wondering if we can manage to run h2o without root privilege. I am having this error when trying to spawn several reverse proxy for sites:
```
failed to bind to xxx.xxx.xxx.xxx:80:Permission denied at PATH_TO_H2O/h2o/start_server line 9.
```
I thought binding should not require root permission since I did successfully handle it with nghttpx. Any idea why we need root permission here?

**Comment by skirsten** [comment]
You need root to bind to any port < 1024. This is a kernel thing and can't be changed.
Your nghttpx is probably binding to a port > 1024.

See this SE answer if you are interested why this restriction exists: http://unix.stackexchange.com/a/16568

**Comment by Varbin** [comment]
At least on linux it is possible to give certain programs the permission to port < 1024:

 `setcap 'cap_net_bind_service=+ep' /usr/local/bin/h2o` (not tested).

But I think that h2o does not drop such capabilities.
