### ISSUE TITLE
optional use of uri_escape in build_destination

### ISSUE THREAD

**Issue by felipewd** [h2o/h2o#1148]
Hi,

I have a little issue using H2O as HTTP/2 reverse proxy: it calls h2o_build_destination, which in turn always uses h2o_uri_escape.

But a have a problem with such a URI:

`/Lh6MLTAjW2akTD9bglppPJhCbxo=/1920x440/https://asdf33243.cloudfront.net/images/test.jpg
`

and then 'https://' becomes 'https%3A//' which gives me a 404 in my backend. I could do a decode in the backend, but then it would work for for this URI, but could (and possibly would) harm another.

So it would be great if H2O could have some kind of uri_escape option (default: ON, obviously) so this sort of thing could be avoided.

I'm using v2.0.5 (a6f40e40).

Thanks a lot!

**Comment by kazuho** [comment]
I believe the issue has been fixed #985 which is merged in 2.1-beta series. Could you give it a try?

**Comment by felipewd** [comment]
You're right, sorry the noise! :)
