### ISSUE TITLE
setting default log string for missing values

### ISSUE THREAD

**Issue by yannick** [h2o/h2o#1155]
it should be possible to set the default string used for values that are empty/inexistent.
currently its always `-`.

rationale: when logging as json it would be nice to be able to log numbers as such, however `-` is not a valid number

**Comment by kazuho** [comment]
Thank you for opening the issue.

I agree that we need (and can have) something better for JSON. OTOH, I am negative about making it configurable. I would prefer if we could hard-code how we should represent missing values based on the selected escape sequence (apache or json).

Therefore, my preference goes to continue using `-` for apache-style escapes, and hard-code `null` for missing values in JSON-style output.

What do you think?

@deweerdt IIRC you added some attributes to the status handler that emits JSON. Does the change discussed in my comment affect you?

**Comment by deweerdt** [comment]
@kazuho it doesn't, I added counters so they're rendered as `0` when no increment has been seen yet. Thanks for the heads up.

**Comment by yannick** [comment]
@kazuho i don't understand why the default can't be a pointer to some configurable string so people logging as json can set this. 
what is the alternative to make sure valid json is emitted? that you compare each string and if its `"-"` then replace it with `null` ??

**Comment by kazuho** [comment]
@yannick Does #1208 look sufficient to you?

**Comment by kazuho** [comment]
Closing the issue now that #1208 has landed. Please reopen if you think we need more knobs for configuration.
