### ISSUE TITLE
Enhancement: remote port in access-log

### ISSUE THREAD

**Issue by felipewd** [h2o/h2o#1160]
Hi,

I'd be great to be able to to log remote port in access-log, much like haproxy's client_port.

Their definition: "client_port" is the TCP port of the client which initiated the connection. If the connection was accepted on a UNIX socket instead, the port would be replaced with the ID of the accepting socket.

http://cbonte.github.io/haproxy-dconv/1.6/configuration.html#8.2.3

**Comment by brunohass** [comment]
+1

**Comment by kazuho** [comment]
Logging of the TCP port number has been landed in #1166.

@felipewd If you are interested in logging the unix path, please let us know. Otherwise, please close the issue.

**Comment by felipewd** [comment]
great, thanks!
