### ISSUE TITLE
dependencies: update brotli

### ISSUE THREAD

**Issue by jbergstroem** [h2o/h2o#1167]
It looks like upstream is releasing a new version [shortly](https://github.com/google/brotli/issues/483). The API has changed and we're now back in C land, meaning we can drop c++ for compiling brotli/h2o.

Updating looks pretty straightforward. Is there a reason we should stick with the current version?

**Comment by kazuho** [comment]
Thank you for opening the issue!

I'm happy to hear that we can get rid C++ code, and since we have the source code of brotli embedded, there's no reason to wait for upstream to make a formal release.

**Comment by jbergstroem** [comment]
@kazuho the reason I thought we should wait until release is that the api/abi might change between now and then. It seems the author will soon release 0.6, then move to 1.0.0. As part of this patch I also want to support building against a shared version of brotli.

**Comment by kazuho** [comment]
I agree that we do not need to be in hurry considering the fact that we already have a working implementation (though it is C++).

OTOH I think that we should continue to bundle the library even after 1.0.0, since the library might not become available (as a package) on older versions of major distributions that people are still using (e.g. Ubuntu 14.04 LTS).

**Comment by jbergstroem** [comment]
@kazuho just to clarify; I just wanted to introduce shared builds as an alternative; similar to what h2o does for other libraries.

**Comment by jbergstroem** [comment]
Looks like its time to look into this; according to upstream the C API will freeze for 1.0: https://github.com/google/brotli/releases/tag/v0.6.0

**Comment by csmk** [comment]
Finally, 1.0 was just released :point_right:  https://github.com/google/brotli/releases/tag/v1.0.0
