### ISSUE TITLE
h2o.examp1e.net inaccessible 'SEC_ERROR_OCSP_OLD_RESPONSE'

### ISSUE THREAD

**Issue by louwers** [h2o/h2o#1178]
Couldn't find another issue about this. Using Firefox 50.1.0

---
### Secure Connection Failed

An error occurred during a connection to h2o.examp1e.net. The OCSP response contains out-of-date information. Error code: SEC_ERROR_OCSP_OLD_RESPONSE

- The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.  
- Please contact the website owners to inform them of this problem.

**Comment by louwers** [comment]
Works again.

**Comment by kazuho** [comment]
Interesting.

note to myself: since we have not been sending OCSP stapling for h2o.examp1e.net, the stale OCSP response must have been sent from the OCSP responder of letsencrypt...
