### ISSUE TITLE
TLS session resumption using memcached

### ISSUE THREAD

**Issue by kazuho** [h2o/h2o#118]
We should better support session resumption using memcached considering the fact that there are web browsers that do not support session tickets (i.e. Internet Explorer and Safari).

part of #39

**Comment by kazuho** [comment]
relates to https://github.com/cybozu/yrmcds/issues/41

**Comment by kazuho** [comment]
It would be good if the master key for session tickets were governed on memcached as well, with automatic rollover.

**Comment by nickdesaulniers** [comment]
Does this have to use memcached?  Could redis be swappable?

**Comment by kazuho** [comment]
@nickdesaulniers Technically speaking the answer depends on if Redis supports the binary protocol of Memcached.

OTOH I would not recommend using Redis for storing session information, since it is not a in-memory cache.  Session keys / master keys of session tickets are kinds of data that should not be stored in persistent storage.  https://timtaubert.de/blog/2014/11/the-sad-state-of-server-side-tls-session-resumption-implementations/ might be a good read regarding the issue.

**Comment by bax-** [comment]
Maybe ´EXPIRE`would work with Redis?
http://www.redis.io/commands/expire

**Comment by bax-** [comment]
so no Redis support?

**Comment by kazuho** [comment]
@bax- Thank you for bringing the point up.

I assume with the #854 being merged it would be possible to use H2O's session resumption support together with Redis (assuming that Redis support text-based memcached protocol).

We should open a new issue if the assumption turns out to be incorrect.

**Comment by dantman** [comment]
As I understand it, Redis does not support either Memcached protocol; you'd have to run a proxy shim server.

**Comment by yannick** [comment]
since this is the top google result: it will be possible from 2.3 via https://github.com/h2o/h2o/pull/1087

```
ssl-session-resumption:
   lifetime: 3
   mode: cache
   cache-store: redis
   redis:
     host: 127.0.0.1
     port: 6379
```
