### ISSUE TITLE
Finding yourself in the h2o_http1client handler

### ISSUE THREAD

**Issue by rayrapetyan** [h2o/h2o#1193]
Hi.
So far I've found the way of getting context in a server handler (using a sort of dirty hack) and timeout handlers (pretty clean), but can't find any way to do the same in httpclient handler.
Because user can't create st_h2o_http1client_private_t from high-level code (correct?), and that's the only pointer we have in on_head, on_body etc handlers...
All I need is to find a context without using a global hash table. I would prefer to extend h2o_http1client_t structure instead.
 Any reason you are not allowing "void *user_data" in h2o_http1client_t?

**Comment by i110** [comment]
@rayrapetyan You can use `*data` for such use case.
https://github.com/h2o/h2o/blob/master/include/h2o/http1client.h#L73

**Comment by rayrapetyan** [comment]
*data is already taken by req (see create_client function).

**Comment by i110** [comment]
What do you actually want to get in http1 client callbacks (`on_connect`, `on_head`, `on_body`)? Is `h2o_context_t`?
I believe you can set arbitrary data in `*data`. For example, `proxy.c` sets a private struct in *data, which contains various data and pointers, and uses it in callbacks. Isn't it what you need?
https://github.com/h2o/h2o/blob/master/lib/core/proxy.c#L575
https://github.com/h2o/h2o/blob/master/lib/core/proxy.c#L379

**Comment by rayrapetyan** [comment]
Oh ok, without API docs it was not so easy to predict... In example above a req is submitted as data, so I thought it's already taken. Thank you, closing the issue...
