### ISSUE TITLE
h2o.examp1e.net site still fails with early PRIORITY frames

### ISSUE THREAD

**Issue by Kriechi** [h2o/h2o#1201]
Although https://github.com/h2o/h2o/pull/1043 and https://github.com/h2o/h2o/pull/1136 have been fixed & merged long ago, the public https://h2o.examp1e.net site seems still to suffer from these issues.

h2o 2.1.0 was released a about a month ago - it would be nice to see the official website conforming and behaving to the h2 RFC. 

Is this a newly introduces issue, or are you not running the latest version of your own webserver? 😄

**Comment by kazuho** [comment]
You are correct in noticing that I have failed to upgrade the server. Thank you for the ping :+1:

**Comment by Kriechi** [comment]
I think this is fixed now. Thanks!
