### ISSUE TITLE
Custom Paths

### ISSUE THREAD

**Issue by GuacheSuede** [h2o/h2o#1212]
Hello

how would one retrieve paths like `/username/:id` and get id param in H2O, i cannot seem to find any docs abt it?

Thank You

**Comment by GuacheSuede** [comment]
@kazuho

**Comment by yannick** [comment]
this is not supported directly, it would be too expensive to build that tree or parse it. h2o is not a web framework. 
that being said you can still do it with mruby but you need to implement it yourself.
