### ISSUE TITLE
2.2.0-beta1: `%{local|remote}p` is undocumented

### ISSUE THREAD

**Issue by chabu-jp** [h2o/h2o#1215]
And, #1166 is not in **Changes**?

`%{remote}p` is my fav in v2.2. Thanks.
e.g. Abuse reporting with MAP-E networks: http://abuse.jpne.co.jp/

**Comment by kazuho** [comment]
Thank you for reporting the issue. Fixed in the commit above.

And I am happy to hear that you are happy for the directive being added!
