### ISSUE TITLE
Seamless libh2o <-> µWebSockets integration

### ISSUE THREAD

**Issue by alexhultman** [h2o/h2o#1228]
Hi,

I want to integrate µWS with libh2o so that http2/websockets are handled respectively by the two projects. To do this I need a file descriptor, an SSL pointer and a common event-loop. Looking at the websockets example the two first requirements seem easy to solve but the event-loop integration will probably need some work.

We both can run on libuv but I read that libh2o is better off without libuv and I'm personally looking to distance µWS from libuv with next release. By default I run on raw epoll now and this layer is separate from the application level so if necessary I could write a small libh2o event-loop backend.

What event-loop is used in libh2o? libev? Raw epoll? To build an event-loop integration for libh2o I need to have: Polls, Timers, Async and Loop components. Async would be as in uv_async_t.

**Comment by kazuho** [comment]
Libh2o can be used with two event loops: libuv and H2O's own event loop (which calls epoll, kqueue or poll), often referred to as evloop. Above the two exists an abstraction layer, mostly defined in include/h2o/socket.h and lib/common/socket*.

Evloop has following characteristics when compared to libuv:
* only one write per socket can be executed at once
* is not designed to have timers with many different values of timeout
 * instead, it is designed to efficiently handle many timeout callbacks sharing a small number of timeout values (e.g. many sockets that use a 10 second idle timeout)

For async, you should refer to include/h2o/multithread.h and lib/common/multithread.c.

That said, we do not have documentation for libh2o at the moment, nor have short-term plans to finalize the API. So you _might_ want to continue using libuv for bridging between µWS and libh2o.

**Comment by alexhultman** [comment]
For this project I will probably just have two threads then, and run both servers with their respective non-libuv optimized sockets (both projects have major loss in performance/memory usage when using libuv).

But as a long term goal it would probably be a good idea to look into this? I took a look at how you use epoll and it seems to be very tightly integrated with the sockets code - if you could somehow separate the "event-loop" from the socket code then integration could be very simple.

What I did myself is I recently moved from using uv_poll_t directly in the socket code to using an abstraction that can be implemented using any event-loop, like Boost, epoll, libuv, libev or whatever really. It currently looks a bit like this (in heavy development still):

https://github.com/uWebSockets/uWebSockets/blob/tinymem/src/Epoll.h

This way it becomes more flexible with other projects (µWS can now run in the same event-loop as most other projects). Performance should be identical if you inline your abstractions and of course you do not have to follow the µWS interfaces at all - it only has to expose enough features to implement my interface using the libh2o event-loop components (polls, timers, and async).

You get the idea here? Thoughts? It would allow better integration between libh2o and any other project also.

**Comment by alexhultman** [comment]
So I'm looking more at this now and I'm having a little bit of problem getting to the h2o_socket_t from within an HTTP/1.1 request handler:

static int on_req(h2o_handler_t *self, h2o_req_t *req) {
}

I get that req->conn is aliasing another struct that holds the h2o_socket_t pointer but obviously I cannot rely on this information as that is supposed to be unknown. What I need is a clear way to tear down the underlying connection and leave only the FD and the SSL pointer, or leave a working h2o_socket_t that I can do things with via for instance h2o_socket_get_fd and similar. I see that you have various functions that sounds intereseting like h2o_http1client_steal_socket and h2o_export_socket but I don't think these functions do what I need.

I could of course follow the flow of h2o_upgrade_to_websocket and learn what the internals do, and try and "hack" around what it does. But I would like to have a clear and official way to tear down the connection into only those 2 components I meantioned. Any hints on this?

I did manage to test the current websocket support with both libuv and evloop and I did some benchmarks so I know this will be worth the effort.

**Comment by deweerdt** [comment]
`h2o_conn_t` has a `h2o_conn_callbacks_t` struct which has a `h2o_socket_t *(*get_socket)(h2o_conn_t *_conn);` member. `h2o_socket_get_fd` can then be used on the `h2o_socket_t` to obtain the fd.

**Comment by alexhultman** [comment]
Thanks that's helpful but now I need to properly "steal" this socket from h2o. If I dup the FD I get internal epoll errors from h2o so that doesn't seem to work in this case.

What is the deal with h2o_socket_export? Can I use this? Returning -1 is supposed to close the socket or only the request?

**Comment by deweerdt** [comment]
I'm not sure I understand enough about what you're trying to achieve, but it does sound like you want to take owner ship of the fd. In that case something like `h2o_http1client_steal_socket` should do the trick (in essence calling `h2o_socket_read_stop` will lead to the fd being deregistered from the epoll set).

**Comment by alexhultman** [comment]
I have libh2o as HTTP2 server, and I want to have µWS handle websockets. So I need to have a clean point at which FD and SSL pointers are given (and from that point never touched by h2o).

µWS takes FD, SSL pointer, secKey string and extensions. I can get all of these things via that h2o_socket_t that you showed how to get, but I need to properly take ownership of it yes. This is not a client so I don't see how h2o_http1client_steal_socket applies here? h2o_socket_export gives me FD and SSL pointer which sounds like exactly what I need, but I can't get it to properly give me the owenership (memory usage does not indicate that h2o is properly releasing the socket).

**Comment by deweerdt** [comment]
> This is not a client so I don't see how h2o_http1client_steal_socket applies here

Yes, sorry I wasn't being clear: `h2o_http1client_steal_socket` calls `h2o_socket_read_stop` which will de-register the FD from the epoll loop. Calling `h2o_socket_read_stop` is what you want.

**Comment by alexhultman** [comment]
So this is what I'm working with right now:

```c++
static int on_req(h2o_handler_t *self, h2o_req_t *req)
{
    const char *client_key;

    if (h2o_is_websocket_handshake(req, &client_key) != 0 || client_key == NULL) {
        return -1;
    }

    if (req->version < 0x200) {

        h2o_socket_t *s = req->conn->callbacks->get_socket(req->conn);

        // get fd
        int fd = h2o_socket_get_fd(s);
        // stop polling on it
        h2o_socket_read_stop(s);
        // dup it
        fd = dup(fd);
        // close h2o resources - doesn't really work
        h2o_socket_close(s);

        // this can be anything
        h.upgrade(fd, client_key, nullptr, nullptr, 0, nullptr, 0);

        // I assume 0 is returned here to mark "handled"?
        return 0;
    }

    return -1;
}
```

It "kind of works" but not really great. It doesn't properly release resources and it still gets internal epoll errors when I disconnect later on. The dup strategy is suboptimal (I know it works, from doing this with Node.js, but I would like it if I didn't have to dup at all). I can kind of get the same thing working without closing the socket and simply upgrading on it so this is not really working as it should.

**Comment by deweerdt** [comment]
I see, is there anyway you can pass a callback to`h.upgrade()` so that  µWS ends up calling `h2o_socket_close(s);` when it's done with the socket? The dup would become unnecessary in that case.

**Comment by alexhultman** [comment]
No it has to be a completely clean transfer, nothing but FD and SSL pointers should survive this (an h2o socket is 80x the size of an µWS socket so that would be like shoving your hand in a spinning lawn mower :wink:). Like mentioned, I do this with Node.js so its not a completely uncommon thing to do.

**Comment by deweerdt** [comment]
I suspect there's nothing in the current code base that does exactly this, but @kazuho might know for sure.

The `h2o_socket_t` is 96 bytes on my 64 bit system, and you would only to keep a pointer to it around (in addition to the callback).

**Comment by alexhultman** [comment]
So what's the deal with h2o_export_socket? I feel this is what I need to use. It takes an h2o_socket_t and gives FD and SSL. But I cannot get it to work. I'm not going to hold excess h2o_socket_t's alive, from my benchmark h2o requires 8gb of user space memory per 1 million connections and that is about 8gb too much for me.

**Comment by Suicosmos** [comment]
Has this changed in the recent three years or is the situation the same?

**Comment by alexhultman** [comment]
The situation is probably worse now (caused by me); I don't support dup/transfer of sockets anymore.

Best would be to stick with any of the two solutions, or just listen to two different ports or use a proxy or whatever. I think my original idea here was kind of stupid.
