### ISSUE TITLE
Problem with connection to nghttpx frontend with TLS

### ISSUE THREAD

**Issue by kapekto1** [h2o/h2o#1233]
I have a problem with this settings of nghttpx:
`nghttpx -f0.0.0.0,443 -bnginx.domain.com,443;;proto=h2;tls ./nghttpx.key ./nghttpx.crt`

When I try to connect to nghttpx with curl `https://app.mydomain2.com -k` i get:

`HTTP/1.1 503 Service Unavailable`
There are no any traces in nginx logs

The same problem doesn't exist with:
`nghttpx -f'*,80;no-tls' -b'nginx.domain.com,443;;proto=h2;tls' -k`

Any clues where should I search for answer?

**Comment by yannick** [comment]
hi @kapekto1 i think this is the wrong issue tracker here. you where probably looking for https://github.com/nghttp2/nghttp2 
you should try h2o as your http2 webserver ;)

looking at your description its maybe because nghttpx only serves http2 and your curl version is too outdated to do that

**Comment by kapekto1** [comment]
Thanks, @yannick Yes, you are right thanks, wrong issue tracker, but - are you sure nghttpx in TLS mode only servers HTTP2 protocol? I cannot find this in documentation...
