### ISSUE TITLE
mruby tests using Regexp fails in some environment

### ISSUE THREAD

**Issue by i110** [h2o/h2o#1236]
After https://github.com/h2o/h2o/commit/ebe4db2570628e7b39f1e8df7cc064e17aa4f6f0, some tests started to fail (ex: https://github.com/h2o/h2o/blob/master/t/00unit.mruby/acl.rb) in the environments where oniguruma in installed.
This problem can be fixed by applying latest mruby upstream (the commit is  https://github.com/mruby/mruby/pull/3381/commits/ee7fc56dd0d7bd2aa8be8a24290ae1de32b0dcec)

**Comment by kazuho** [comment]
Fixed in 9153a98; likely to be included in 2.2.
