### ISSUE TITLE
Reverse Proxy in HTTP/2

### ISSUE THREAD

**Issue by HoneyryderChuck** [h2o/h2o#1245]
First of all, thank you for contributing this server! I've been finding configuring it a breeze when comparing with apache or nginx, the (m)ruby handlers are great, and a few naive benchmarks show that h2o can fly! 

I was looking for a proxy server which could proxy HTTP/2 frames. I tried nginx (as this used to be my go-to option), but it only proxies HTTP/1.1. I'm developing a server that could stay behind such a proxy and could consume unencrypted HTTP/2, as encryption/decryption is quite expensive in scripting languages. 

I tried h2o, but it is doing the same behaviour by default as nginx. I've been looking at the docs, but sadly can't seem to find anything. Is this configurable, or is it also a no-op? If so, any specific reason why not?

**Comment by yannick** [comment]
hi!
it's simply not implemented yet
see https://github.com/h2o/h2o/issues/609 
and https://github.com/h2o/h2o/issues/170

**Comment by HoneyryderChuck** [comment]
Thx for the response. Closing as duplicated then.
