### ISSUE TITLE
'Expect: 100-Continue' support in libh2o

### ISSUE THREAD

**Issue by Lupus** [h2o/h2o#1247]
Is it possible to handle 'Expect: 100-Continue' request with libh2o? It might be useful for checking auth/acls/whatever business logic before the client sends large file.

**Comment by kazuho** [comment]
Unfortunately not. At the moment, there is no such interface. The only thing that you can do is set an upper bound to the size of the request body.

**Comment by Lupus** [comment]
Got it, thanks @kazuho !
