### ISSUE TITLE
crash in h2o_buffer_dispose

### ISSUE THREAD

**Issue by dmitri--** [h2o/h2o#1249]
This crash is not something trivial to reproduce. You need a) sever built with libh2o v2.1.0 and libuv 1.11.0 b) very simple and short content (I used just constant string) c) large number of client connections (~5K-8K) c) high level of parallelism on the client side that uses http2 with multiplexing. I ran h2load with the following arguments on 8 hosts, different than the server:
h2load -m 256 -c 1024 -t 32 -n 100000000 http://myipaddress/
Under these conditions, crash happens in 10-20 seconds.

```
(gdb) bt
#0  0x000000000062ce20 in h2o_buffer_dispose (_buffer=0x7f84cc9a5618) at h2o/include/h2o/memory.h:354
#1  0x0000000000630436 in on_write_complete (sock=0x7f84cc761590, err=0x0) at h2o/lib/http2/connection.c:955
#2  0x000000000061a36c in on_write_complete (sock=0x7f84cc761590, err=0x0) at h2o/lib/common/socket.c:628
#3  0x0000000000618e7f in on_do_write_complete (wreq=0x7f84cc761600, status=0) at h2o/lib/common/socket/uv-binding.c.h:89
#4  0x000000000078d098 in uv__write_callbacks (stream=stream@entry=0x7f84cc1517b0) at uv/src/unix/stream.c:944
#5  0x000000000078d749 in uv__stream_destroy (stream=stream@entry=0x7f84cc1517b0) at uv/src/unix/stream.c:453
#6  0x00000000007880c9 in uv__finish_close (handle=0x7f84cc1517b0) at uv/src/unix/core.c:254
#7  uv__run_closing_handles (loop=0x1f7bb60) at uv/src/unix/core.c:284
#8  uv_run (loop=0x1f7bb60, mode=UV_RUN_DEFAULT) at uv/src/unix/core.c:354

(gdb) p buffer
$1 = (h2o_buffer_t *) 0x0
(gdb) up
#1  0x0000000000630436 in on_write_complete (sock=0x7f84cc761590, err=0x0) at h2o/lib/http2/connection.c:955
955         h2o_buffer_dispose(&conn->_write.buf_in_flight);
(gdb) p conn->state
$2 = H2O_HTTP2_CONN_STATE_IS_CLOSING
(gdb) p conn->_write
$3 = {buf = 0x0, buf_in_flight = 0x0, streams_to_proceed = {next = 0x7f84cc9a5620, prev = 0x7f84cc9a5620}, timeout_entry = {registered_at = 0, cb = 0x6306b6 <emit_writereq>, _link = {next = 0x0, prev = 0x0}}, window = {_avail = 1073669053}}
(gdb) p *sock
$4 = {data = 0x7f84cc9a5490, ssl = 0x0, input = 0x0, bytes_read = 1400, bytes_written = 29, on_close = {cb = 0x0, data = 0x0}, _cb = {read = 0x6300d2 <on_read>, write = 0x0}, _peername = 0x0, _latency_optimization = {state = 2 '\002', notsent_is_minimized = 0 '\000', suggested_tls_payload_size = 16384, suggested_write_size = 18446744073709551615}}
```
so it looks like the buffer has already been destroyed in previous on_write_complete() call and that's why it is NULL. 

**NOTE** on_write_complete() was called when UV was closing the socket. It means -- there were entries in the UV connection QUEUE, and uv__write_callbacks(stream) called this callback when it in its turn was called from uv__stream_destroy.
Under normal conditions (no high-load), the queue is empty when uv__stream_destroy is called.

PLATFORM:
CentOS linux version 7.3
gcc 4.93
libuv 1.11.0
libh2o 2.1.0
all compiled wth CFLAGS -O0 -g -DNDEBUG 
(without NDEBUG all asserts slow the process down, and crash does not happen or may be happens in much longer run)

**Comment by kazuho** [comment]
Thank you for reporting the issue. Looks like a bug in libh2o.

The stack trace looks like that libuv is closing a socket, and as part of that, calling the write callback.

Would you mind checking efc17b8 fixes the issue? It should change the behavior of our libuv binding to match the behavior of evloop, our internal event loop that we use for the standalone server.

**Comment by dmitri--** [comment]
**It helped**
thank you. I don't see the problem anymore.
