### ISSUE TITLE
reverse-proxy over HTTP/2

### ISSUE THREAD

**Issue by bax-** [h2o/h2o#1261]
Is it possible to have a reverse-proxy h2o and a backend h2o instance communicate over HTTP/2?
I might have overlooked something but I didn't find anything in the documentation on when HTTP/2 is enabled in h2o.
Does the backend need a certificate and listen on 443?

**Comment by yannick** [comment]
not possible atm.
see:
https://github.com/h2o/h2o/issues/170
https://github.com/h2o/h2o/issues/1245

**Comment by bax-** [comment]
thanks, sorry for the duplicate
