### ISSUE TITLE
websocket proxy will lost first frame if backend server fast enough.

### ISSUE THREAD

**Issue by wuhanck** [h2o/h2o#1272]
I test h2o as https(1.1) front-server and hit a strange BUG.
The version is 2.2.0.
If backend accept a websocket and send a frame immediately, h2o will drop the frame silently.
I change to http and capture all traffic to find out that if a tcp-frame happens to contain both http-upgrade-frame and websocket-frame, h2o will drop the websocket-frame.
So I dig into the source code and find that when h2o estable a tunnel, it will trash all data received before...
That is the BUG.

I make a quick fix. I explain here.
Pass the consumed rlen to
h2o_http1client_body_cb
and when establish tunnel
use on_read(sock2, NULL) intead of trash sock2.

The fix is naive. 
I think the point is:
When establish-tunnel, the only thing the tunnel may do is on_read both socks.
Establish-tunnel don't know how to trash sock.
The upper-layer know which part of data need trash.
So the better solution is that upper-layer trash or consume sock(it knows howto), and the establish-tunnel on_read both socks.

**Comment by kazuho** [comment]
Thank you for reporting the issue. Could you please file a PR?

**Comment by wuhanck** [comment]
I file a PR. Please help check it.

**Comment by wuhanck** [comment]
@kazuho 
I am not familiar with github.
When I follow the guide to sync the upstream and push to my fork, I found that the merge become the part of pull-request automatically...
And I don't find any method to remove it.
May you help remove the un-needed submit from the my pull-request?

**Comment by wuhanck** [comment]
@kazuho 
What is the further processing of this BUG?

**Comment by wuhanck** [comment]
OK. I close it and remove fork.
