### ISSUE TITLE
Can change "host" configuration and make it not contain "port" inforamtion?

### ISSUE THREAD

**Issue by wuhanck** [h2o/h2o#1273]
Version 2.2.0.
I know in http-spec host means “example.com:8080" or something like that.
But conf is not http-spec.
Current conf has two places store the port info.
Port in "host" and port in "port".
This can cause issues.
For example, it is hard to check that host: example.com:8443 port:8433 don't work.
For example, client can send http-request using host: example.com:80 or example.com:443.
For example, when you use named-rule-set(refer to rules defined before), you have problems to check port in host and port in port.

Maybe, host in conf just means the host-name(dns-name or any other name) will be better.

**Comment by kazuho** [comment]
`hosts` and `port` (which is part of `listen`) represent two distinct concepts.

The keys in the `hosts` mapping are the authorities (e.g. `example.com:8080`). When receiving a HTTP request, H2O looks for an entry in the `hosts` mapping that corresponds to the value of the `Host` header. If none of the entry match, the first entry will be elected to handle the request.

The `listen` directive defines at which port the server should bind.

The flexibility provided by the distinction is essential in some deployments. For example, one might be running a TLS terminator in front of H2O. In such case, you need to setup H2O on a port that is not 443, and at the same time capture a HTTP request that has a host header indicating port 443 in the H2O configuration.

If the explanation does not resolve the problem you are facing; please explain what you are trying to achieve along with the configuration you have.

**Comment by wuhanck** [comment]
If we want to change the "port" in listen, we had to change  the hosts(which also contains port info).
If we share the listen conf, things get worse.

I need lots of subdomain to route the request. They share the listen conf.
When I change the port in listen conf, it is annoy to change each hosts....

I also need serve client which is not browser adn send request with Host header "example.com:80"  instead of "example.com" (as a coder, example.com:80 is consistence and nature).

I think it is better for H2O to combin host info and port info in listen to check whether a request's Host header belong or not belong the host rule.
That is:
"example.com"//Used by DNS or host-name
    listen:
       port: 80//Combine with example.com to check the Host-header.(here, example.com:80 or example.com both are qualified)

**Comment by kazuho** [comment]
> If we want to change the "port" in listen, we had to change the hosts(which also contains port info).
> If we share the listen conf, things get worse.
> 
> I need lots of subdomain to route the request. They share the listen conf.
> When I change the port in listen conf, it is annoy to change each hosts....

There are at least two ways to handle that kind of complexity.

One is to create a `listen` node at the top level, which would affect all the listed hosts; i.e.
```yaml
listen:
  port: 8080
hosts:
  a.example.com:
    ...
  b.example.com:
```

The other is to use YAML alias and merge. Please refer to https://h2o.examp1e.net/configure/syntax_and_structure.html#yaml_merge for how to use it.

> I also need serve client which is not browser and send request with Host header "example.com:80" instead of "example.com" (as a coder, example.com:80 is consistence and nature).

A HTTP request with `host: example.com:80` will match against a `hosts` entry with a key having `example.com` if the protocol is HTTP. If it doesn't match, then it is a bug in H2O.

**Comment by wuhanck** [comment]
Thx.
In your conf, hosts don't contain any port info that is great.
That is what I need but I can not get from the doc. Sighn...
I will try it.
Thx again.

**Comment by wuhanck** [comment]
@kazuho 
It doesn't work.

listen:
  port: 8443
  ssl:
    certificate-file: /xxx/yyy/server.crt
    key-file:         /xxx/yyy/server.key
hosts:
  "a.example.com":
    ...
  "b.example.com":
Configuration like this doesn't work.  Always go to a.example.com!

listen:
  port: 8443
  ssl:
    certificate-file: /xxx/yyy/server.crt
    key-file:         /xxx/yyy/server.key
hosts:
  "a.example.com:8443":
    ...
  "b.example.com:8443":
Configuration like this does work.

So my problem returns, can we remove the need of "port" in the host info?

**Comment by kazuho** [comment]
> So my problem returns, can we remove the need of "port" in the host info?

Generally speaking we should avoid compatibility-breaking changes. So if we are to allow users create a `hosts` entry that matches against any port, then it should look like `example.com:*`.

That said, I still do not understand why you need to change the port mapping so frequently, at the same time doing virtual hosts (i.e. routing requests based on the value of the host header). Would you mind elaborating?

Note: we would have a corner case issue if we are to support wildcard ports since we already support host-level wildcards. The question is that which of the following two has precedence when we receive a request far `a.example.comcom:8443`: `*.example.com:8443` or `a.example.com:*`.

**Comment by wuhanck** [comment]
I am testing the solution and there are many ports need to arrange.
So I change it a bit more than normal case.
OK.
I get the point.
