### ISSUE TITLE
TLS 1.3 is broken

### ISSUE THREAD

**Issue by KenanSulayman** [h2o/h2o#1282]
Hey,

I opened an issue with the Chrome team about a seemingly newly introduced regression that breaks our website in Chromium, effectively making 844 people unable to access the site.

https://bugs.chromium.org/p/chromium/issues/detail?id=717083

Turns out Chromium is enabling all experiments by default, including TLS 1.3; H2O indicates support but fails to reply in a compliant way, killing the connection.

H2O version:

h2o version 2.3.0-DEV
OpenSSL: LibreSSL 2.4.5

H2O configuration:

```
user: nobody

access-log: /dev/null
error-log: /dev/null
pid-file: /tmp/h2o.pid

num-threads: 4
expires: 1 day
file.send-gzip: on
compress: ON
limit-request-body: 21474836480
http2-casper: ON
http2-idle-timeout: 180

proxy.preserve-host: ON
proxy.timeout.io: 59000
proxy.timeout.keepalive: 59000

ssl-session-resumption:
  mode: all

header.setifempty: "X-Xss-Protection: 1; mode=block"
header.setifempty: "X-Content-Type-Options: nosniff"
header.setifempty: "Access-Control-Allow-Origin: https://psychonautwiki.org"
header.setifempty: "Access-Control-Allow-Origin: https://psychonaut.wiki"
header.setifempty: "Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept"

listen: &pw_listen
  host: 0.0.0.0
  port: 80

listen: &pw_secure_listen
  host: 0.0.0.0
  port: 443
  ssl: &pw_secure_listen_config
    minimum-version: TLSv1
    cipher-preference: &cipher-preference server
    cipher-suite: &cipher-suite ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-CHACHA20-POLY1305:EDH+CAMELLIA:EDH+aRSA:EECDH+aRSA+AESGCM:EECDH+aRSA+SHA256:EECDH:+AESCBC:+CAMELLIA128:+AES128:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!DSS:!RC4:!SEED:!IDEA:!ECDSA:kEDH:CAMELLIA128-SHA:AES128-SHA:ECDHE-RSA-AES256-SHA:!SSLv3
    dh-file:          ..
    certificate-file: ..
    key-file:         ..

listen: &newtld_pw_secure_listen
  host: 0.0.0.0
  port: 443
  ssl:
    minimum-version: TLSv1
    cipher-preference: *cipher-preference
    cipher-suite: *cipher-suite
    dh-file:          /tls/dhparams.pem
    certificate-file: ..
    key-file:         ..

hosts:
  "psychonautwiki.org:80":
    listen: *pw_listen
    paths: &pw_redirect
      "/":
        redirect: https://psychonautwiki.org/

  "psychonautwiki.org:443":
    listen: *pw_secure_listen
    paths: &pw_proxy
      "/":
        proxy.reverse.url: "http://varnish:80"
        proxy.preserve-host: ON
```

**Comment by kazuho** [comment]
> h2o version 2.3.0-DEV

Could you please specify the exact commit you are using? Couple of bugs related to TLS 1.3 were fixed two weeks ago (#1264, #1265) and you might be seeing them.

**Comment by kazuho** [comment]
PS. also, you might want to disable TLS 1.3 in the server configuration by adding `max-version: tlsv1.2` to the SSL mapping.

**Comment by kazuho** [comment]
Looking at below, it's apparent that your server is failing to decode incoming request. To me it looks like the regression we had between #1264 and #1265.

```
$ (echo "GET / HTTP/1.0"; echo "Host: psychonautwiki.org"; echo) | build/openssl110/cli psychonautwiki.org 443
HTTP/1.1 400 Bad Request
Date: Tue, 02 May 2017 09:59:31 GMT
Connection: close
Content-Length: 11
Server: h2o/2.3.0-DEV
content-type: text/plain; charset=utf-8
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
access-control-allow-origin: https://psychonautwiki.org
access-control-allow-headers: Origin, X-Requested-With, Content-Type, Accept

Bad Requestptls_receive:256
```

**Comment by csmk** [comment]
@KenanSulayman, I've visited your website and seems to be _speeking_ TLS 1.3 just fine.

If you have fixed the issue, it will be nice to close this one.

**Comment by KenanSulayman** [comment]
I deployed an updated version of h2o just before you wrote that comment. Nevertheless, I am *very certain* that this issue has never actually been a fault in h2o, but rather a lack of honesty on the side of the Chrome developers<sup>1</sup> -- an update to Chromium fixed it.

<sup>1</sup> Their reaction wasn't exactly investigative and they immediately made h2o responsible for it, claiming a *broken implementation*. Apparently that's bullshit and I can continue to rely on h2o.

**Comment by concatime** [comment]
@KenanSulayman As I understand, we can close this issue?

**Comment by KenanSulayman** [comment]
I would still be interested in whether something was fixed in h2o, or if that indeed was a bug in Chrome, but the developers denied their responsibility.

However, everything seems to be stable now. Thanks!
