### ISSUE TITLE
libh2o Reproxy - connecting to https

### ISSUE THREAD

**Issue by INRIX-joel-winarske** [h2o/h2o#1287]
What is required to make a X-Reproxy-URL header value of https:// type work in simple.c?

I added this setup prior to uv_run():

    SSL_load_error_strings();
    SSL_library_init();
    OpenSSL_add_all_algorithms();
    ctx.proxy.client_ctx.ssl_ctx = SSL_CTX_new(SSLv23_server_method());
    SSL_CTX_load_verify_locations(ctx.proxy.client_ctx.ssl_ctx, H2O_TO_STR(H2O_ROOT) "share/h2o/ca-bundle.crt", NULL);
    SSL_CTX_set_verify(ctx.proxy.client_ctx.ssl_ctx, SSL_VERIFY_PEER, NULL);

Is this the proper way to setup the SSL context for the reproxy http1client?

With a reproxy of "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png", I get I/O error:
[lib/core/proxy.c] in request:/images/branding/googlelogo/1...:I/O error

**Comment by INRIX-joel-winarske** [comment]
This is with libh2o.

**Comment by kazuho** [comment]
You are correct in assuming that you should set up `proxy.client_ctx.ssl_ctx` of `h2o_globalconf_t`.

The reason you are seeing an error might be related to the fact that you are calling `SSLv23_server_method`. What you need here is a client-side context, considering the fact that the reverse proxy handler of H2O needs to act as a client. For more information, please consult OpenSSL documentation.

**Comment by INRIX-joel-winarske** [comment]
Ah!  I missed that.  Thank you.  Changing to below I get client_verify_cb called.

    SSL_load_error_strings();
    SSL_library_init();
    OpenSSL_add_all_algorithms();
    ctx.proxy.client_ctx.ssl_ctx = SSL_CTX_new(SSLv23_client_method());
    SSL_CTX_load_verify_locations(ctx.proxy.client_ctx.ssl_ctx, H2O_TO_STR(H2O_ROOT) "share/h2o/ca-bundle.crt", NULL);
    SSL_CTX_set_verify(ctx.proxy.client_ctx.ssl_ctx, SSL_VERIFY_PEER, client_verify_cb);
