### ISSUE TITLE
libh2o Reproxy - Sending Body

### ISSUE THREAD

**Issue by INRIX-joel-winarske** [h2o/h2o#1288]
How do I POST a body via reproxy?  There is no working example of this.  This is my current scheme; which doesn't appear to work:

    static const char send_token[] = "My Token";

    req->res.status = 307;
    req->res.reason = "OK";
    req->method = h2o_strdup(&req->pool, "POST", SIZE_MAX);
    h2o_send_inline(req, send_token, strlen(send_token));

**Comment by kazuho** [comment]
Are you trying to transfer (i.e. reverse-proxy) a request received by libh2o to a different server? Or are you trying to build a request by yourself and send it to an origin?

In the case of former, your handler should call `h2o_reprocess_request`. In the case of latter, you should use http1client directly.

**Comment by INRIX-joel-winarske** [comment]
I was trying both approaches.  I wasn't able to get examples-http1client working due to incorrect SSL setup, so I went with the re-proxy scheme.  I now have examples-http1client running with change indicated in issue 1287.

Thank you!

**Comment by INRIX-joel-winarske** [comment]
I am getting results using h2o_send_inline().  When sending with body, I use result status 308, and it works every time.  When requesting HEAD method to the Google endpoint, I see name resolution fails very frequently, and the client is getting 502 status.

I have not been able to make `h2o_reprocess_request` work.  I see that with this code path, the result values are reset, so setting result status to 100, 307, or 308, has no effect.  What is the proper setup for using `h2o_reprocess_request` so the http1client results are sent back to the client?  Is H2O_TOKEN_X_REPROXY_URL still required in the result header?

**Comment by INRIX-joel-winarske** [comment]
The problematic name resolution is directly related to issue [1294](https://github.com/h2o/h2o/issues/1294).

Once I addressed this, all problems went away and it works great.
