### ISSUE TITLE
Multiple mruby.handler's?

### ISSUE THREAD

**Issue by jslabovitz** [h2o/h2o#1290]
How do I declare multiple MRuby handlers?

I love the integrated MRuby, and already have a complex handler that I use on my sites. I'd like to use the Htpasswd handler as well. But I can't figure out how to 'chain' multiple MRuby handlers together. All the examples assume that there is just one mruby.handler, one file.handler, etc.

**Comment by yannick** [comment]
hi @jslabovitz , 
you can have multiple routes easily, the only caveat is that if your handler is written as an actual ruby class (instead of anonymous proc/lambda) you need to make sure that each handler has an unique class name. 
see also https://h2o.examp1e.net/configure/mruby.html for using 399 return code to move requests to the next handler.

**Comment by jslabovitz** [comment]
I understand the return codes, having done a lot of Rack programming in MRI Ruby. But I still don't understand how to configure multiple chained handlers (not multiple routes or multiple paths).

For example, let's say I already have a class-based handler, called MyHandler. I want add basic authentication, without having to rewrite my code. I could imagine a configuration like this, except I didn't think multiple mruby.handler lines are allowed -- are they?

  path: "/"
    mruby.handler: |
      require "htpasswd.rb"
      Htpasswd.new
    mruby.handler: |
      MyHandler.new

What should the configuration look like to make that happen?

**Comment by jslabovitz** [comment]
I did some research and found that the ACL handler might do what I want, if I specify it like this:

````
require 'htpasswd'
require '.../path/to/my-handler'
acl {
  use Htpasswd.new('.../path/to/.htpasswd', 'my-realm')
  use MyHandler.new
}
````

The authentication is indeed called, but MyHandler is never called.

So I'm still stuck. Any suggestions?

**Comment by i110** [comment]
@jslabovitz To chain multiple handlers for the same path, you can use yaml sequence like the following:

```
paths:
  "/":
    - mruby.handler:  |
        require "htpasswd.rb"
        Htpasswd.new
    - mruby.handler: |
        MyHandler.new
```
Starting from 2.1, this is recommended way to configure handlers for paths. see https://h2o.examp1e.net/configure/syntax_and_structure.html

Apart from that, your code using `acl` seems to work. Doesn't Your `Htpasswd` handler reject all requests before `MyHandler` gets invoked? (but I think that you shouldn't use `acl` feature to chain normal handlers)

**Comment by jslabovitz** [comment]
Thanks! This worked very well.

It's not very clear that this is possible from  the documentation, but I think this is a very powerful feature of H2O. Perhaps it would be good to add an explanation and example to https://h2o.examp1e.net/configure/mruby_directives.html ?

**Comment by i110** [comment]
I agree with you. I'll add an explanation and an example to the mruby document.
