### ISSUE TITLE
Why OpenSSL is required but not optional for library build?

### ISSUE THREAD

**Issue by kuraga** [h2o/h2o#130]
Good day!

Why OpenSSL is required but not optional for **library** build?

Thanks.

**Comment by kazuho** [comment]
Since my expectation is (was) that the most attractive feature of libh2o is its support for HTTP/2.  And TLS support is near to mandatory for HTTP/2.

If there is need for libh2o without dependency against OpenSSL, then it might be worth to make it optional.

**Comment by kazuho** [comment]
relates to #39

**Comment by kuraga** [comment]
Well it's a good syntax **library** too.

offtopic *I find a C library for RESTful HTTP server and is a difficult task (ooops?). And yours is cool! But my system is embedded uClibc. OpenSSL is a bad idea (and impossible for now). Well and SSL is needless for me. Just embedded C HTTP server.* /offtopic

Thanks!

**Comment by taqtiqa-mark** [comment]
There are many use cases where HTTP servers are part of the application server layer of a site.  That is h2o would sit in secured networks behind [high perfromance SSL termination servers](https://aws.amazon.com/blogs/aws/elastic-load-balancer-support-for-ssl-termination/). In these networks traffic is passed around encrypted for performance reasons - the same performance reasons that h2o would lead one to select.... h2o

I think that #131 scartches this itch.

**Comment by kuraga** [comment]
Yeah! Closed in favour of #131 .
