### ISSUE TITLE
Missing "as" attribute in documentation on server push

### ISSUE THREAD

**Issue by utrenkner** [h2o/h2o#1303]
Due to [my problems with pushing assets to Chrome](https://github.com/h2o/h2o/issues/1302), I learned that the "as" attribute of the preload link is not optional but required, e.g. ``<link rel=preload as=script href=...>``. 

In the h2o documentation, this is not mentioned, see several code examples on the [HTTP/2 Directives](https://h2o.examp1e.net/configure/http2_directives.html).

And the example for "Pushing asset files" given on [Using Mruby](https://h2o.examp1e.net/configure/mruby.html) must actually be written with two separate mruby-handlers - one for the CSS file with "as=style" and one for the JS file with "as=script"
```
paths:
  "/":
    mruby.handler: |
      Proc.new do |env|
        push_paths = []
        # push css and js when request is to dir root or HTML
        if /(\/|\.html)\z/.match(env["PATH_INFO"])
          push_paths << "/css/style.css"
        end
        [399, push_paths.empty? ? {} : {"link" => push_paths.map{|p| "<#{p}>; rel=preload; as=style"}.join("\n")}, []]
      end
    mruby.handler: |
      Proc.new do |env|
        push_paths = []
        # push css and js when request is to dir root or HTML
        if /(\/|\.html)\z/.match(env["PATH_INFO"])
          push_paths << "/js/app.js"
        end
        [399, push_paths.empty? ? {} : {"link" => push_paths.map{|p| "<#{p}>; rel=preload; as=script"}.join("\n")}, []]
      end
    fastcgi.connect: ...
```
The relative attribute for each content type can be found in the [draft standard](https://www.w3.org/TR/preload/#link-element-interface-extensions).

**Comment by worenga** [comment]
The problem is that we are using link headers to control the server's push behavior. However the link headers are also dasy-chained to the browser which in the case of a client that does not support H2 Push or H1 will lead to an invalid link header.

If you are interested only in controlling H2 Server Push then you might add the  `x-http2-push-only` attribute to the link header. Newer h2o versions will then remove the pushed path from the link header.

For backwards compatibility with H1 and H2 NoPush i think that should be mentioned in the docs.

**Comment by utrenkner** [comment]
Interesting - I had seen that change, but at the time I did not understand what it should be used for.

However, I am not quite sure how to implement this. Do I just include in the above example a ``x-http2-push-only=true``, e.g.
```
..
        [399, push_paths.empty? ? {} : {"link" => push_paths.map{|p| "<#{p}>; rel=preload; as=script x-http2-push-only=true"}.join("\n")}, []]
...
```

**Comment by deweerdt** [comment]
@utrenkner the link header should look like this:
```
Link: </assets/index.txt.gz?push-only>; rel=preload; x-http2-push-only
```

**Comment by deweerdt** [comment]
Note that [the spec](https://www.w3.org/TR/preload/) says that the element is optional.

> The `as` attribute's value must be a valid request destination. If the provided value is omitted, the value is initialized to the empty string.

It also says that it is appropriate to preload when:

> When the `as` attribute of the link element of a preload link that is already in a Document is set or changed to a value that does not or no longer matches the request destination of the previous obtained external resource, if any.

which is what I assume makes Chrome re-fetch the resource. I think the spec is missing a piece indicating how pushes are supposed to set their `request destination`.

**Comment by utrenkner** [comment]
Thank you for the clarification. As for the specs, I must admit that you are right. 

I had read this recent [article on Smashing Magazine](https://www.smashingmagazine.com/2017/04/guide-http2-server-push/), which received clarification on exactly this issue by Yoav Weiss. The article says:``The as=style portion of the header is not optional. It informs the browser of the pushed asset’s content type. In this case, we use a value of style to indicate that the pushed asset is a style sheet. You can specify other content types. It’s important to note that omitting the as value can result in the browser downloading the pushed resource twice. So don’t forget it!``

So technically, one can omit the 'as' argument - but then one cannot expect that the browser does what one wants: To download the resource early and only once.

**Comment by worenga** [comment]
I just tested `x-http2-push-only` via mruby and it does not seem to remove the link header or the path as expected.

**Comment by utrenkner** [comment]
@worenga I can confirm this. I just tried it on a test domain - here the [result of WPT with IE10](https://www.webpagetest.org/result/170519_V3_KYF/1/details/#step1_request4).

**Comment by utrenkner** [comment]
Looking at [this discussion on the W3-Preload standard](https://github.com/w3c/preload/issues/80), I would like to emphasize my original proposal, that we should really include the "as" attribute in the documentation. In the discussion the editors of the draft standard explain that it is de-facto required, even though it is not universally implemented this way in client software.

That said, I was wondering, if we could add a feature to h2o, which would automatically map mime-types to request destinations. As @igrigorik [explains](https://github.com/w3c/preload/issues/94#issuecomment-302445294), this is not in the specs. But I think it could be included in h2o, at least as a default which can be overriden. Then we would not have to include separate mruby handlers for each request destination, when we add resources to push-paths. For our site in question, we now have 4 such mruby-handlers (for style, script, image and font).

**Comment by jbergstroem** [comment]
> @utrenkner said:
> That said, I was wondering, if we could add a feature to h2o, which would automatically map mime-types to request destinations. As @igrigorik explains, this is not in the specs. But I think it could be included in h2o, at least as a default which can be overriden.

I like this idea.

**Comment by deweerdt** [comment]
>  that we should really include the "as" attribute in the documentation.

https://github.com/h2o/h2o/pull/1307

**Comment by utrenkner** [comment]
Thanks to @deweerdt for the patch to the docs. 

And it contains a much simpler way to [add several different resources types within the same mruby-handler](https://github.com/h2o/h2o/pull/1307/commits/86fc18302bb13f59db9f6c90a14129a542228d2e#diff-09a25de2ccfa48104ce6afc941888a6d).
