### ISSUE TITLE
libh2o -> life cycle of a request?

### ISSUE THREAD

**Issue by INRIX-joel-winarske** [h2o/h2o#1308]
What is the life cycle of a request?

Does it get cleaned up after handler call, or can I stash a pointer to it, and use it later?

I want to spin up http1client based on incoming request, download a file to the server, then respond to the originating client with body response.  It's similar to a reproxy (preserve headers from server file was downloaded from), but it needs to return an alternate body back to the client; and the file is stored on the server.

Thanks,
Joel

**Comment by kazuho** [comment]
You can use the memory pool associated with the request (i.e. `h2o_req_t::pool`) for freeing resources that are allocated for handling the request. Unless you do, life cycles of the object you allocate will not be bound to that of the request.

**Comment by INRIX-joel-winarske** [comment]
The endpoint callback is passed in a request.  This is the request I am referring to.  

I want to persist this request until my client load is done, then I respond with the client body response to the request.

How do I ensure the request is not culled until after I have my client response?
