### ISSUE TITLE
MacOSX [lib/core/proxy.c] ssl handshake failure

### ISSUE THREAD

**Issue by INRIX-joel-winarske** [h2o/h2o#1313]
I'm hitting a problem only on the Mac.  Linux works flawless.

[lib/core/proxy.c] in request:/v1/signin?appkey=674a5b78-55...:ssl handshake failure
Bus Error: 10

I ran the http1client example on the Mac with the same CA file.  It's fine.

Is there special setup for running re-proxy on the Mac?
Are there any suggested steps to troubleshoot this?

**Comment by jwinarske** [comment]
After Mac Sierra update things were a mess.  This script proved vital in helping sort things out, as it was indicating an insufficient security handshake.  Which was a result of an older OpenSSL version. 

https://github.com/noxxi/p5-ssl-tools/blob/master/analyze-ssl.pl
