### ISSUE TITLE
[FreeBSD] failed to open pid file:/var/run/h2o.pid:Permission denied

### ISSUE THREAD

**Issue by herrbischoff** [h2o/h2o#1354]
## Environment

```
❯ uname -a
FreeBSD vandusen.home.lan 11.0-RELEASE-p10 FreeBSD 11.0-RELEASE-p10 #4 r318311M: Fri Jun 30 23:49:33 CEST 2017     root@vandusen.home.lan:/usr/obj/usr/src/sys/VANDUSEN  amd64
```

```
❯ h2o -v
h2o version 2.2.2
OpenSSL: OpenSSL 1.0.2k-freebsd  26 Jan 2017
mruby: YES
```

```
❯ cat /usr/local/etc/h2o/h2o.conf
# vi: ft=yaml
# see https://h2o.examp1e.net/ for detailed documentation
# see h2o --help for command-line options and settings
user: www
pid-file: /var/run/h2o.pid
access-log: /var/log/h2o/h2o-access.log
error-log: /var/log/h2o/h2o-error.log
listen: 80
# listen:
#     port: 443
#     ssl:
#         minimum-version: TLSv1.2
#         # generate your own certificates
#         certificate-file: /usr/local/etc/h2o/server.crt
#         key-file: /usr/local/etc/h2o/server.key
# enable Apache-style directory listings
# file.dirlisting: on
# per-host configuration
hosts:
    vandusen:
        paths:
            "/":
                file.dir: "/usr/local/www"
```

## Issue

I installed `h2o` via the ports collection but trying to run it only gets me warnings and an error message:

```
❯ /usr/local/bin/h2o -c /usr/local/etc/h2o/h2o.conf
[warning] failed to set TCP_FASTOPEN:Protocol not available
[warning] failed to set TCP_FASTOPEN:Protocol not available
[INFO] raised RLIMIT_NOFILE to 234306
failed to open pid file:/var/run/h2o.pid:Permission denied
```

After touching `/var/run/h2o.pid` manually and setting permissions to the `www` user, startup works one time. However, neither does a restart nor starting via the init script or running `/usr/local/bin/h2o --mode=daemon -c /usr/local/etc/h2o/h2o.conf`.

**Comment by utrenkner** [comment]
Strange, I run h2o on 10.3 and 11.0 without any issues.

The permissions for the pid file should look something like this:
```
-rw-r--r--  1 root  wheel      6 May 18 22:12 h2o.pid
```
You did start h2o with root privileges? Just to be sure... I always do it by invoking ``service h2o start`` (but of course, that just does what you did on the command line).

**Comment by herrbischoff** [comment]
Indeed, I executed all the mentioned operations as root. That's why I'm stumped — it really shouldn't result in those permission errors. It must be something at the point where h2o drops privileges to run as the `www` user, unless I'm completely mistaken.

**Comment by kazuho** [comment]
Due to security reasons, only the person that started h2o should have the write permission for the `h2o.pid` file. Otherwise, somebody might replace the file so that signals can be mis-redirected to another process.

**Comment by jobs-git** [comment]
so how to resolve this if I am only the owner of that server?

**Comment by jobs-git** [comment]
I am not running h2o as a service, maybe that is a problem. I removed the `pid-file` directive and its now running as usual
