### ISSUE TITLE
H2o server response to a http/2 RST_Stream

### ISSUE THREAD

**Issue by user963** [h2o/h2o#1355]
Hi,
I am using h2o server to make http2 requests to some files.
When i send an RST_STREAM to stop a stream, the server make a change after an important delay. 
If someone can help me to know the cause this delay and if it is possible to reduce it.
The  frame with blue is when the server make the change.
![aaaaaaaaaaaaaaaa](https://user-images.githubusercontent.com/29480111/27865315-6d3062be-6192-11e7-986e-ce15ae9f7052.png)

**Comment by worenga** [comment]
How many concurrent streams are active?
Can you dump your h2o configuration? Have you enabled-latency optimization?
Maybe the data is already in the OS kernel buffer at this stage.

Can you further give us detail on your setup? How much ingress traffic is there from the client?

**Comment by user963** [comment]
Thank you for your response,
-There are 2 concurrent active streams.
-The client makes requests to get files stored on the server ( client and server are running on the same machine).
-I didn't try latency-optimization
-I am using the default configuration of h2o:

# to find out the configuration commands, run: h2o --help

listen: 8080
listen:
  port: 8081
  ssl:
    certificate-file: examples/h2o/server.crt
    key-file: examples/h2o/server.key
hosts:
  "127.0.0.1.xip.io:8080":
    paths:
      /:
        file.dir: examples/doc_root
    access-log: /dev/stdout
  "alternate.127.0.0.1.xip.io:8081":
    listen:
      port: 8081
      ssl:
        certificate-file: examples/h2o/alternate.crt
        key-file: examples/h2o/alternate.key
    paths:
      /:
        file.dir: examples/doc_root.alternate
    access-log: /dev/stdout

**Comment by deweerdt** [comment]
> Maybe the data is already in the OS kernel buffer at this stage.

I agree that this explanation is likely. `latency-optimization` might help. In addition, it might be possible to advertise a small window in the `SETTINGS` frame, and send small increments in the `WINDOW_UPDATE` frames.
