### ISSUE TITLE
h2o websocket client example?

### ISSUE THREAD

**Issue by narenkn** [h2o/h2o#1374]
Hi,
  I was looking for a websocket client example, so that I don't have to reinvent the wheel!!!
-Naren.

**Comment by worenga** [comment]
Can you be more specific what this has to do with the h2o project?

**Comment by narenkn** [comment]
there is websocket-server example avaialble at 
examples/libh2o/websocket.c

So, I think there should be a websocket client example already avaialble.

**Comment by kazuho** [comment]
No. The client-side of the protocol is never implemented by us.

**Comment by unisqu** [comment]
how to run examples/libh2o/websocket.c ?
