### ISSUE TITLE
No status in OCSP response for h2o.examp1e.net

### ISSUE THREAD

**Issue by grikdotnet** [h2o/h2o#1379]
Firefox can't open h2o.examp1e.net due to the wrong OCSP response
and shows a MOZILLA_PKIX_ERROR_OCSP_RESPONSE_FOR_CERT_MISSING error

**Comment by SethArchambault** [comment]
I noticed this too, both from Firefox on an Android Device and from a Macbook Pro

![image](https://user-images.githubusercontent.com/1406558/28393153-4e123c14-6cb3-11e7-801d-8db50bc3130c.png)

**Comment by DtpEJsaYXDU4GDH8dE4MyI9VrieF0UZpPZ0K76K** [comment]
numerous security features are broken in h2o by default and the devs have yet to correct them. i would hold off on any real production usage until h2o is security hardened properly and undergoes a legitimate security review from a reputable auditing entity.

**Comment by zlm2012** [comment]
#1270 maybe related to this OCSP failure since currently h2o.examp1e.net is powered by 2.2.0-beta2. And my site powered by h2o 2.2.2 cannot reproduce this problem in both TLS 1.2 and TLS 1.3. Simply upgrading to 2.2.2 should resolve this problem @kazuho

**Comment by axelu** [comment]
running 2.3.0-DEV (built on 7/10 against openssl 1.0.2k) w/o any OCSP issues.

**Comment by kazuho** [comment]
Thank you for reporting the issue. The issue has been fixed.

This was a configuration issue on the server.

When the server certificate was replaced, the server was not restarted (by sending a HUP). That caused inconsistency between the certificate being served (the old one) and the OCSP that is being served.

**Comment by tdtgit** [comment]
![screen shot 2018-05-05 at 00 29 04](https://user-images.githubusercontent.com/4527866/39642366-c0d41aca-4ffb-11e8-9e1f-114fd79cc9dc.png)

Using latest H2O 2.2.4 and still got this error. My server was not restarted from the time all was normal. I have 2-3 sites running in same config, reverse proxy but sometime, only one got error, others don't (above screenshot).

Can you provide me a way to send you debug information to completely fix this issue?

**Comment by tdtgit** [comment]
@kazuho Ah yes, I use acmetool and now I found they have hook function so I can restart H2O. Which command I can use if I need restart H2O? I restart H2O manually by running:
```
sudo kill -TERM `cat /var/run/h2o.pid`
```
but have to run many times until OS say not found /var/run/h2o.pid. How can I archive in only one command?

**Comment by csmk** [comment]
> How can I archive in only one command?

You should use `SIGHUP` for graceful restart. See #1082 
```
sudo kill -HUP $(cat '/var/run/h2o.pid')
```
or change _foo_ for the user running H2O:
```
sudo kill -HUP $(pidof foo)
```

**Comment by tdtgit** [comment]
Super thanks, @csmk. That's first time I can feel zero downtime with h2o. For any guys who need restart h2o after acmetool renew a certificate:

1. Create a file named `h2o` at path `/usr/lib/acme/hooks/`...
2. ...with below content:
```
#!/bin/sh
sudo kill -HUP $(cat '/var/run/h2o.pid')
```
3. `chmod +x /usr/lib/acme/hooks/h2o`
4. Testing by running `/usr/bin/acmetool --xlog.severity=debug test-notify custom.example.com`

Done. The result will be:
```
[DEBUG] acme.hooks: calling hook script: /usr/lib/acme/hooks/h2o
```

**Comment by p0358** [comment]
@kazuho The issue appears to be happening again on Fx 74.0b7

**Comment by gottlike** [comment]
FYI, might be related to this (very old and still open) Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=966856
