### ISSUE TITLE
Production test of server/client from H2O fails badly

### ISSUE THREAD

**Issue by narenkn** [h2o/h2o#1380]
Hi,
  I'm evaluating H2O for production usage, but this the library is failing badly. 
  I've attached the test code here. Untar & "make" should help you build. The paths inside makefile may need fixes to point to appropriate source locations!

[fail1.tar.gz](https://github.com/h2o/h2o/files/1161213/fail1.tar.gz)

  Once the exe is created run it multiple times to find more issues. I've observed the following
1. System stuck
2. System crash

Regards,
Naren.

**Comment by kazuho** [comment]
I would appreciate it if you could be more specific about asking how to use libh2o (e.g., what should I do if I want to configure AAA as BBB).

We will not debug your program.
