### ISSUE TITLE
h2o has not passed a reputable security audit and does not provide reproducible builds

### ISSUE THREAD

**Issue by DtpEJsaYXDU4GDH8dE4MyI9VrieF0UZpPZ0K76K** [h2o/h2o#1381]
h2o has not passed a reputable security audit and does not provide reproducible builds

recommend to engage a reputable auditing entity to review the code and fuzz test for vulnerabilities in the released builds.

recommended companies might include:
* iSec Partners / NCC Group
* trailofbits

also, reproducible builds are not offered and as such the published binaries cannot really be trusted

**Comment by kazuho** [comment]
Thank you for the suggestion.

We have run an audit, but have no current plans to disclose information.
