### ISSUE TITLE
SHA256 in deps/mruby-digest

### ISSUE THREAD

**Issue by naritta** [h2o/h2o#1386]
I would like to know if it's intentional that we can't use SHA256 in deps/mruby-digest for now.
I think we can use SHA256 just by defining SHA256_DIGEST_LENGTH and defining SHA256 in md_type_md. https://github.com/h2o/h2o/blob/master/deps/mruby-digest/src/digest.c

Is there any reason for excluding SHA256 and should we use original mruby-digest(https://github.com/iij/mruby-digest) for SHA256?

**Comment by kazuho** [comment]
Thank you for raising the issue.

There is no reason to add SHA256 support. Hence #1387.

FWIW, we do not use the original version of mruby-digest since it's dependency on OpenSSL causes issues when H2O is built using the bundled version of libressl.

**Comment by naritta** [comment]
I see. Thank you for quick response!
