### ISSUE TITLE
Open file cache

### ISSUE THREAD

**Issue by gofrailo** [h2o/h2o#139]
Hi,

Do you have plans to support something line NGINX http://nginx.org/en/docs/http/ngx_http_core_module.html#open_file_cache ?

Thanks for the great project.

**Comment by kazuho** [comment]
Thank you for the suggestion.

Actually, the work is in progress (see #138, also note that it is not a open file cache, it's a shared memory cache) but I am not going to merge it until I find any benefit of using it in real-world performance.

Please let me know if you need this feature for some reason in which case I might consider raising the priority (or if you are just curious).

**Comment by gofrailo** [comment]
Hi,

I think by caching the FD like nginx saves 3-4 system calls when serving files. Performance wise do you think this would be a gain to H2O ?

**Comment by kazuho** [comment]
@gofrailo For benchmark, the answer would be yes.  For practical use, the answer would depend on the file system being used.  For HTTP servers serving files on a local disk, the bottleneck would be the network bandwidth.  OTOH if the files are on an network-based file system (e.g. nfs) the cost of file-system-related system calls would be noticeable.  In such case, not only open(2), fstat(2) but also read(2) would be slow, that is the reason why I prefer caching the content over caching only the file descriptors.
