### ISSUE TITLE
mrbconf.h tuning 

### ISSUE THREAD

**Issue by yannick** [h2o/h2o#1394]
is there a reason mrbconf.h isn't edited and e.g. 
`#define MRB_INT64` is not set?
maybe also `MRB_DISABLE_STDIO` and `MRB_ENABLE_DEBUG_HOOK`

**Comment by yannick** [comment]
@kazuho as pointed out in slack:

```
      /test:
        mruby.handler: |
          Proc.new do |env|
              [ 200, { "Content-Type" => "text", }, [ 'hello world 9223372036854775807 has class: ' + 9223372036854775807.class.to_s ]]
          end
```
results in 
```
curl localhost:8080/test
hello world 9223372036854775807 has class: Float%
```
and if i 
```
diff --git a/deps/mruby/include/mrbconf.h b/deps/mruby/include/mrbconf.h
index 4796919..3b82c4f 100644
--- a/deps/mruby/include/mrbconf.h
+++ b/deps/mruby/include/mrbconf.h
@@ -32,7 +32,7 @@
 //#define MRB_INT16

 /* add -DMRB_INT64 to use 64bit integer for mrb_int; conflict with MRB_INT16 */
-//#define MRB_INT64
+#define MRB_INT64
```
it results in 

```
curl localhost:8080/test
hello world 9223372036854775807 has class: Fixnum
```

**Comment by kazuho** [comment]
Thank you for raising the issue.

I have confirmed that we are using 32-bit ints on 64-bit machines as well (which is the default behavior of mruby).

Could you please clarify why you want changes to the default behavior of mruby? My general sense is that if the requirement sounds unspecific to h2o, then the issue should be fixed upstream.

**Comment by yannick** [comment]
fixed upstream: https://github.com/mruby/mruby/commit/f0f4a1088a270e339407a24ffe8be748f4764fc2
