### ISSUE TITLE
Feedback about one week on H2O

### ISSUE THREAD

**Issue by concatime** [h2o/h2o#1399]
Hi. I migrated from nginx to h2o. I'm quite happy with it, but I have to things that I would love see you changing:
1. Defining the port two times is redundant. Since I need both 80/443, I must define it this way:
```
'concati.me:80':
  listen:
    port: 80
```
Normally, when setting the port directly in the domain name, I don't need to define it into the `listen`.

2. Can you aloud us to use an extension in `file.mime.setdefaulttype`? I have this code:
```
file.mime.setdefaulttype: 'text/html; charset=utf-8'
file.mime.addtypes:
  'text/html; charset=utf-8': .html
```
It's not intuitive at all since I need to write two things to get the same thing done. So I would like to see it like this way:
```
file.mime.setdefaulttype: .html
file.mime.addtypes:
  'text/html; charset=utf-8': .html
```

**Comment by kazuho** [comment]
Thank you for the suggestions.

> Defining the port two times is redundant.

We cannot support the suggested approach for compatibility reasons.

Currently, we support two ways of defining a port number.

One way is to use a global-level `listen` directive. If the directive is used in such a way, then it would be applied to all the hosts __without a host-level listen directive__.

The example below shows an example using the approach, that maps both `a.com:80` and `b.com:80` to port 8080.

```yaml
listen:
  port: 8080
hosts:
  "a.com:80":
    ...
  "b.com:80":
    ...
```

The proposal changes the way this kind of configuration is handled. Therefore it is unlikely that we will be able to adopt it.

> Can you aloud us to use an extension in file.mime.setdefaulttype?

You cannot. However, you can use an YAML alias. For example, something like below is likely to meet your needs.

```yaml
file.mime.setdefaulttype: &html_mime_type 'text/html; charset=utf-8'
file.mime.addtypes:
  *html_mime_type: .html
```

**Comment by concatime** [comment]
Since you gave us a complete and concrete answer, I'm closing this. Thank you.
