### ISSUE TITLE
[QUESTION]Why h2o is faster 2x than Nginx?

### ISSUE THREAD

**Issue by xiangzhai** [h2o/h2o#14]
Nginx http://github.com/nginx/nginx/blob/master/src/event/modules/ngx_epoll_module.c and h2o http://github.com/kazuho/h2o/blob/master/lib/socket/evloop/epoll.c.h both use epoll http://man7.org/linux/man-pages/man7/epoll.7.html under Linux Kernel

Only benchmark http://github.com/kazuho/h2o#benchmark is not enough to prove that h2o is faster 2x than Nginx, isn't? I argue that you need to write a Paper or something to list 1, 2, ... n optimization compare with Nginx.

**Comment by girng** [comment]
> Also nginx probably is logging the requests, h2o isn't, that will slow down h2o abit.

you mean slow down nginx?

**Comment by proyb6** [comment]
@girng Nginx have changed a lots these 4 years

**Comment by girng** [comment]
@proyb6 i mean the logic in his sentence.  nginx would be slower since it's logging the requests, not h2o
