### ISSUE TITLE
error in expires directive value calculations

### ISSUE THREAD

**Issue by grikdotnet** [h2o/h2o#1405]
https://h2o.examp1e.net/configure/expires_directives.html

> the units recognized are: second, minute, hour, day, month, year

setting "expires: 1 day" leads to a correct "Cache-Control: max-age=86400" value (24 hours),
But "expires: 1 month" leads to "Cache-Control: max-age=108000"
108000/60/60 = 30 (hours). The value should be 2592000 (60 * 60 * 24 * 30)

**Comment by deweerdt** [comment]
Thank you for the report, @grikdotnet . I've filed https://github.com/h2o/h2o/pull/1406

**Comment by grikdotnet** [comment]
thank you for the fast fix

**Comment by deweerdt** [comment]
#1406 has now been merged
