### ISSUE TITLE
Deep water models with class balancing error

### ISSUE THREAD

**Issue by hcordobes** [h2o/h2o#1407]
When "balance classes" is selected in a Deep Water model it breaks because it tries to select a sample out of the valid range of samples. A Java error in red in the H2O flow GUI can be seen with something like this:

0 <= 403123 <= 207534

I haven't been able to find any other condition to raise this error. This does not happen with the same configuration (dataset and settings) using Deep Learning models.

H2O Build git branch 	(HEAD detached at 7c6572f64)
H2O Build git hash 	7c6572f642ec554fd89163f20a41d3b612e976f5
H2O Build git describe 	jenkins-master-3970
H2O Build project version 	3.13.0.352
H2O Build age 	1 month and 6 days
H2O Built by 	jenkins
H2O Built on 	2017-07-28 01:05:29
H2O Internal Security 	Disabled
Flow version 	0.7.2

**Comment by worenga** [comment]
This is not the h2oai machine learning repository.
You may want to go to https://github.com/h2oai/h2o-3

**Comment by hcordobes** [comment]
My fault, sorry. Closing this one here.
