### ISSUE TITLE
[proposal] Server Timing API

### ISSUE THREAD

**Issue by Jxck** [h2o/h2o#1417]
Server Timing API are under standardization process.

https://w3c.github.io/server-timing/

the point of this spec defines `Server-Timing` Header
which shows time spend on server.
(querying db, processing on app server, and total time during server side etc)

```
> GET /resource HTTP/1.1
> Host: example.com

< HTTP/1.1 200 OK
< Server-Timing: miss, db=53, app=47.2;
< Server-Timing: customView, dc;atl
< Trailer: Server-Timing
< (... snip response body ...)
< Server-Timing: total=123.4
```

in blink, [intent to development](https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/y3qwr490Fc4/boGoo41-BwAJ)
other browsers are no-signal now.

in Feedback point of view, experimental implementation of this feature in H2O helps standardization process.

**Comment by Jxck** [comment]
any updates ?

**Comment by fetus-hina** [comment]
It seems they're working on #1646

**Comment by i110** [comment]
@Jxck The feature is added at https://github.com/h2o/h2o/pull/1646.

Close.
