### ISSUE TITLE
Create libh2o NodeJS Addon to use h2o nativ with NodeJS

### ISSUE THREAD

**Issue by frank-dspeed** [h2o/h2o#1431]
It would really rock to use this nativ in nodejs projects

## Why?
There is a lot of Routing related Stuff and IO Related stuff in NodeJS Servers even none Frontend Application servers like Proxies.
NodeJS is not the Fastest in Response Time and Connection per Sec when it comes to static file serving.

## Why bundle it and not use Proxy?
because i want to do even application delivery control logic on the server its hacky when i would write always a configuration sync via NodeJS and reload the Server only to change for example response on a path.

## TODO
Create node-h2o nativ NodeJS Addon that exposes standart h2o config + application logic as JavaScript syntax.

#### Optional
- Prepare Benchmark of libuv and libh2o to check if it performs better if not there is something wrong with the already existing h2o benchmarks :)

**Comment by worenga** [comment]
I am not sure whether i understand your question correctly, but you should be able to serve NodeJS Applications using the FastCGI Handler. I am not very familiar with NodeJS but there seem to be modules that enable NodeJS over FastCGI.

**Comment by frank-dspeed** [comment]
@worenga nope we are talking about using libh2o directly in NodeJS via ABI

**Comment by jbergstroem** [comment]
@frank-dspeed but what's the benefit of embedding it? FastCGI (or http) already is a clean "separation of concerns". I see constraining embedded languages as a feature because it keeps the logic you want at web server level low. Your web server will always be a hot path, so solve problems as quickly as possible instead (lua, mruby, ..).

With that said, there's definitely something interesting embedding v8 for webassembly; but I prefer being cautious about performance gains.

**Comment by yannick** [comment]
there is nothing holding you back from integrating libh2o into nodejs, thats what libh2o is provided for. its meant as a dll that you can use. insofar the ticket is at the wrong place and you should open it at the nodejs project. 
libh2o could be a valid replacement for libuv, however it probably makes little sense.

**Comment by frank-dspeed** [comment]
@jbergstroem 
- First of all FASTCGI is not fast that would never make sense with Async IO when then we would use the normal http reverse proxy method.

@yannick benchmarking libuv vs libh2o sounds like a really good idea.
but the main point from creating bindings for usage with node was more the idea to use this with nodejs as supported language for scripting without extra round trip over reverse proxy and libuv

**Comment by jbergstroem** [comment]
> @frank-dspeed said:
> the idea to use this with nodejs as supported language for scripting without extra round trip over reverse proxy and libuv

Most of your time will be spent in IO anyway. Embedding your fully-fledged node.js app into the web server event pipeline doesn't sound like a great design decision. If you really want the extra oomph, make your content stateless and cacheable as close to edge/client as possible. 

> @frank-dspeed said:
> FASTCGI is not fast that would never make sense with Async IO

Not sure what you're talking about here. Proxying over FastCGI and HTTP is essentially the same.

**Comment by frank-dspeed** [comment]
@jbergstroem its more a full router dns stuff :) that i want to script this way we are talking about distributed systems not standart nodejs express apps :)

**Comment by yannick** [comment]
all of this can be done with mruby. if that is the right thing to do is another question. 
at some point the http parsing overhead and local network latency is irrelevant and you are ok with having a few layers. you may want to look into linkerd, traefik, istio or similar projects for  multi layered setups with a lot of traffic.

also JS is not the right language and actually trying to use all this existing piles of Node frameworks would end up in a slow drama. there would be really no value add. regarding the issue of more dynamic reloads of code that is a topic where i think h2o needs some work. one possible solution that might work is creating a small framework that reloads/evals code, this would enable certain dynamic modifications. another solution is to query redis for each call, but that obviously has a performance impact.

**Comment by deweerdt** [comment]
> Dynamic Routing based on Request Parameters in General

https://github.com/h2o/h2o/pull/1410 might help building something like this

**Comment by frank-dspeed** [comment]
@yannick ok i understand :+1: h2o is then not the right tech choice for the NodeJS Community and comparing it to HaProxy Pointed now out that HAP outperforms h2o by far thanks for pointing that out 

we will go with binding Haproxy directly to the NodeJS ABI 

little tip for your main page maybe update benchmarks ;)
