### ISSUE TITLE
Replace mruby with NodeJS or add nodejs support

### ISSUE THREAD

**Issue by frank-dspeed** [h2o/h2o#1432]
I think nodejs would be a great fit for this

**Comment by worenga** [comment]
Is this a duplicate of #1431?

**Comment by frank-dspeed** [comment]
@worenga https://hackernoon.com/n-api-and-getting-started-with-writing-c-addons-for-node-js-cf061b3eae75

**Comment by frank-dspeed** [comment]
@worenga but this issue here aims to use NodeJS directly via C and not the other way around so Replace mruby with nodejs is correct

**Comment by kazuho** [comment]
We will not be removing support for mruby (users already exist).

It would be possible to add a JavaScript handler, but I do not think that it would be easy (even if it was meaningful) to provide a JavaScript API compatible to node.js, considering the fact that the internals (including the event loop) are different between h2o (the standalone server) and node.js.

**Comment by frank-dspeed** [comment]
@kazuho yes and because they are diffrent it would be probally less effort to make libh2o work with nodejs bindings so that you can install it as a NodeJS Addon and use it

**Comment by frank-dspeed** [comment]
as no one here like replacing mruby i will close this in favor of #1431 not a braking change and
