### ISSUE TITLE
abort when limit-request-body is reached

### ISSUE THREAD

**Issue by felipewd** [h2o/h2o#1441]
Hey everybody, 

Using master c91c06c15, H2O aborts limit-request-body is reached.

Simple test:

- set limit-request-body: 4096
- H2O is set to be a reverse-proxy;

Try a simple curl with a large file:

curl -kv -F 'fileUpload=@10m' -H http://h2o-test-host/upload.cgi -v 

backtrace:

> (gdb) bt
> #0  0x00007ffff64b8a18 in raise () from /lib64/libc.so.6
> #1  0x00007ffff64ba61a in abort () from /lib64/libc.so.6
> #2  0x00007ffff64b11b7 in __assert_fail_base () from /lib64/libc.so.6
> #3  0x00007ffff64b1262 in __assert_fail () from /lib64/libc.so.6
> #4  0x000000000043d293 in do_write (_sock=_sock@entry=0x7fffdc001ae0, _bufs=_bufs@entry=0x7fffef7fce40, bufcnt=bufcnt@entry=2, 
>     cb=cb@entry=0x464340 <on_send_complete>) at h2o/lib/common/socket/evloop.c.h:257
> #5  0x000000000043ee89 in h2o_socket_write (sock=0x7fffdc001ae0, bufs=bufs@entry=0x7fffef7fce40, bufcnt=bufcnt@entry=2, 
>     cb=0x464340 <on_send_complete>) at h2o/lib/common/socket.c:640
> #6  0x000000000046451a in finalostream_send (_self=<optimized out>, req=<optimized out>, inbufs=<optimized out>, 
>     inbufcnt=<optimized out>, send_state=H2O_SEND_STATE_FINAL) at h2o/lib/http1.c:732
> #7  0x00000000004503b6 in h2o_send_inline (req=0x7fffdc001d18, body=<optimized out>, len=<optimized out>)
>     at h2o/lib/core/request.c:534
> #8  0x00000000004642e3 in create_entity_reader (entity_header=0x7fffef7fd010, conn=0x7fffdc001c40)
>     at h2o/lib/http1.c:261
> #9  handle_incoming_request (conn=0x7fffdc001c40) at h2o/lib/http1.c:441
> #10 0x000000000043d501 in read_on_ready (sock=0x7fffdc001ae0) at h2o/lib/common/socket/evloop.c.h:235
> #11 run_socket (sock=0x7fffdc001ae0) at h2o/lib/common/socket/evloop.c.h:495
> #12 0x000000000043d628 in run_pending (loop=0x7fffdc0008c0, loop=0x7fffdc0008c0)
>     at h2o/lib/common/socket/evloop.c.h:533
> #13 0x000000000043f93d in h2o_evloop_run (loop=0x7fffdc0008c0, max_wait=max_wait@entry=2147483647)
>     at h2o/lib/common/socket/evloop.c.h:578
> #14 0x00000000004c626f in run_loop (_thread_index=0x3) at h2o/src/main.c:1639
> #15 0x00007ffff72ec704 in start_thread () from /lib64/libpthread.so.0
> #16 0x00007ffff658af8d in clone () from /lib64/libc.so.6
> 
> 

This is HTTP/1.1 (not using TLS).

Curl correctly sets the content-length so H2O should be able to return a 413 error:

> POST /upload.cgi HTTP/1.1
> host: h2o-test-host
> User-Agent: curl/7.43.0
> Accept: */*
> Content-Length: 10485961
> Expect: 100-continue
> Content-Type: multipart/form-data; boundary=------------------------95204ca157054869

Please let me know if you need any additional info.

Cheers,

**Comment by kazuho** [comment]
Thank you for reporting the issue. Fixed in the PR above.
