### ISSUE TITLE
Set 'h2o.nthreads' configuration parameter failed

### ISSUE THREAD

**Issue by XuefeiHuang** [h2o/h2o#1449]
The 'H2O.configureLogging()' code line in 'H2OStarter.java' file cause static block in H2O.java file executed, so the 'PrioritizedForkJoinPool' object will be created with the 'FJPS' array initialization.

But there is a bug:  When 'PrioritizedForkJoinPool' object be created,  the value of 'ARGS.nthreads' are same as 'NUMCPUS'.  Both are initialized with'Runtime.getRuntime().availableProcessors()'. So Set 'h2o.nthreads' configuration parameter  failed at code line 'H2O.main(args)'.

H2OStarter.java------------
public static void start(String[] args, String relativeResourcePath, boolean finalizeRestRegistration) {
    long time0 = System.currentTimeMillis();
    H2O.configureLogging(); 
    H2O.registerExtensions();

    // Fire up the H2O Cluster
    H2O.main(args);     

H2O.java------------
  static {
    // Only need 1 thread for the AckAck work, as it cannot block
    FJPS[ACK_ACK_PRIORITY] = new PrioritizedForkJoinPool(ACK_ACK_PRIORITY,1);
    for( int i=MIN_HI_PRIORITY+1; i<MAX_PRIORITY; i++ )
      FJPS[i] = new PrioritizedForkJoinPool(i,4); // All CPUs, but no more for blocking purposes
    FJPS[GUI_PRIORITY] = new PrioritizedForkJoinPool(GUI_PRIORITY,2);
  }

 private static class PrioritizedForkJoinPool extends ForkJoinPool {
    final int _priority;
    private PrioritizedForkJoinPool(int p, int cap) {
      super((ARGS.nthreads <= 0) ? NUMCPUS : ARGS.nthreads, **//there is a bug.  the value of 'ARGS.nthreads' are same as 'NUMCPUS'.**
            new FJWThrFact(cap),
            null,
            p>=MIN_HI_PRIORITY /* low priority FJQs should use the default FJ settings to use LIFO order of thread private queues. */);
      _priority = p;
    }

**Comment by zlm2012** [comment]
Maybe you should go to https://github.com/h2oai/h2o-2

**Comment by concatime** [comment]
First, you are on the wrong thread.
Second, please make your code easier by using something like this:
```java
static {
	// Only need 1 thread for the AckAck work, as it cannot block
	FJPS[ACK_ACK_PRIORITY] = new PrioritizedForkJoinPool(ACK_ACK_PRIORITY,1);
	for( int i=MIN_HI_PRIORITY+1; i<MAX_PRIORITY; i++ )
	FJPS[i] = new PrioritizedForkJoinPool(i,4); // All CPUs, but no more for blocking purposes
	FJPS[GUI_PRIORITY] = new PrioritizedForkJoinPool(GUI_PRIORITY,2);
}
```
How? (Remove spaces)
> ` ` ` j a v a
actual code
` ` `

**Comment by concatime** [comment]
Please, someone close this pseudo-issue.
