### ISSUE TITLE
FYI: proposed FreeBSD port of h2o

### ISSUE THREAD

**Issue by dch** [h2o/h2o#145]
Greetings, I have prepared a port of h2o:

https://github.com/skunkwerks/freebsd-ports/tree/master/h2o

Comments & feedback welcomed, & I will keep this ticket updated as the port goes through submission to the official ports tree.

I have not set it up to install the libraries yet, nor include websocket support. If there is interest in this I welcome contributions to the port!

**Comment by dch** [comment]
Submitted to `FreeBSD-ports` https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=197519

**Comment by kazuho** [comment]
Thank you for the work!

It would be OK not to install the libraries / websocket support as the library considering the fact that the API is still unstable.

**Comment by dch** [comment]
closing this as it's been committed as `www/h2o` thanks :dart:  https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=197519

**Comment by kazuho** [comment]
@dch Wow! I am glad to hear that.  Thank you for your effort.

Looking at the tracker that you referred to, it seems like there have been some discussion on how to obtain the pid of the server.  Would implementing #152 help your case as well?

**Comment by dch** [comment]
+1 having a pidfile is a good idea, yes please! It needs to handle deleting and creating the pidfile securely, though, and support dropping privileges on startup. https://github.com/freebsd/freebsd/blob/master/usr.sbin/daemon/daemon.c should be a useful reference. The other thing one can use `daemon` for is to restart on failure.

**Comment by kazuho** [comment]
@dch Thank you for the response and the suggestion.

#152 went in before the release of 1.0.0; it is possible to use the configuration directive to let H2O emit the pid file.

However, I have not designed it to create / remove the file securely in the sense that the file is created by a superuser / deleted even if the worker process exitted abnormally, as I believe such management is not kind of task every server should handle by itself.  My understanding (and tendency) goes to relying on tools like `daemon` (as you mentioned!) to cover such requirements.

With that in mind I would appreciate if you could update the ports, if necessary.  Thank you in advance.
