### ISSUE TITLE
Dealing with '405 Not Allowed' with POST on static files

### ISSUE THREAD

**Issue by xm74** [h2o/h2o#1451]
Trying to setup autoconfiguration for client mailing software using autodiscover.xml file as standard method I found that requests comes using POST method.
> 185.30.177.40 my.sever:443 - - [13/Oct/2017:21:36:07 +0200] "POST /autodiscover/autodiscover.xml HTTP/1.1" 404 9 "https://my.server/autodiscover/autodiscover.xml" "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; Win64; x64; Trident/6.0; .NET CLR 2.0.50727; SLCC2; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3; Tablet PC 2.0; Microsoft Outlook 15.0.4481; ms-office; MSOffice 15)"

I understand why it happend but the question is there any trick to proceed 200 response  instead 405 for this kind of requests? May be using mruby or something else.

**Comment by kazuho** [comment]
One way to handle the issue would be to use the mruby handler (as you suggested) to do an internal redirect (i.e. reproxy in https://h2o.examp1e.net/configure/reproxy_directives.html) to the same URI (so that the request would be rerun using GET) or to fall through to the next handler (by returning 399), depending on the request method.

I haven't tested the code, but something like below.

```
reproxy: on
mruby.handler: |
  Proc.new do |env|
    if env["REQUEST_METHOD"] == "POST"
      [200, {"x-reproxy-url": env["PATH_INFO"]}, []]
    else
      [399, {}, []]
    end
  end
file.dir: ...
```

**Comment by xm74** [comment]
Thanks, @kazuho! I found that in my case the simplest way to do it will be PHP using.

>         paths:
             "/autodiscover/autodiscover.xml":
                redirect: &box_auto
                    url: /autodiscover/autodiscover.php
                    internal: YES
                    status: 307

And than in _autodiscover.php_ do something

> <?php
if ($_SERVER['REQUEST_METHOD'] == 'POST') {
...
} else {
        header($_SERVER['SERVER_PROTOCOL']." 405 Method Not Allowed");
}
?>
