### ISSUE TITLE
301 permanently redirect all http to https

### ISSUE THREAD

**Issue by Tintinabula** [h2o/h2o#146]
We would like to redirect all clear text HTTP requests to HTTPS.  Our site is SSL only.

If an HTTP request is made, we would "301 Moved Permanently" the request to the same URI using HTTPS. For example:

  GET http://example.com/a.html
         -> 301 response
  GET https://example.com/a.html

The nginx configuration currently looks like:

server {
  listen 127.0.0.1:80
  return 301 https://example.com$uri;
}

Does H2O have a preferred method to 301 redirect all port 80 requests?  How about a global directive "http-redirect-to-https:" with the argument "yes" ? Perhaps an option under "listen:" with the preferred domain, "https://example.com" would work? 

I am looking through the H2O code now to see if I can add the function, but I am not sure of the communities' preference. 

Thank you for your time.

**Comment by kazuho** [comment]
Thank you for the suggestion.  Sounds interesting!

> Does H2O have a preferred method to 301 redirect all port 80 requests? How about a global directive "http-redirect-to-https:" with the argument "yes" ? Perhaps an option under "listen:" with the preferred domain, "https://example.com" would work?

I like the approach, with some suggestions.

1. it would better be defined at host-level rather than within the listen directive
2. it should better be named `enforce-https`, as the directive can be extended in the future to support configuring [properties of HSTS](https://developer.mozilla.org/en-US/docs/Web/Security/HTTP_strict_transport_security#Enabling_Strict_Transport_Security)
3. the flag should be `ON` rather than `YES` for consistency with other configuration directives

Combining the three suggestions, the example would look like:

```
hosts:
    example.com:
        enforce-https: ON
```

Regarding where to implement such feature, IMO best place would be within `h2o_process_request` function, presumably right after `setup_before_processing` is being called.

**Comment by Tintinabula** [comment]
I had some time today and tested a forced http to https redirection. Code comments are welcome.

I am currently having a problem figuring out how to add the "enforce-https" option to be read from the configuration file. I was using the global directives as an example, but since the "enforce-https" is going to be a "hosts:" sub-option I am not sure how to proceed. Any pointers?

Additionally, I noticed the 301 redirects are not being logged to the " access-log:" facility. 

```
From d97e353d77f6ab29f942dd2d3fdf5c3761347608 Mon Sep 17 00:00:00 2001
From: Tintinabula
Date: Thu, 12 Feb 2015 16:41:12 -0500
Subject: [PATCH] enforce-https by redirecting http to https, test code add
 closing tags for 301 redirect html

---
 lib/core/request.c | 8 +++++++-
 1 file changed, 7 insertions(+), 1 deletion(-)

diff --git a/lib/core/request.c b/lib/core/request.c
index 02e35b8..a1d818a 100644
--- a/lib/core/request.c
+++ b/lib/core/request.c
@@ -146,6 +146,12 @@ void h2o_process_request(h2o_req_t *req)
                 h2o_send_redirect(req, 301, "Moved Permanently", pathconf->path.base, pathconf->path.len);
                 return;
             }
+            /* enforce-https by redirecting http to https */
+            if (req->scheme == &H2O_URL_SCHEME_HTTP) {
+                req->scheme = &H2O_URL_SCHEME_HTTPS;
+                h2o_send_redirect(req, 301, "Moved Permanently", req->path.base, req->path.len);
+                return;
+             }
             if (req->path_normalized.base[confpath_wo_slash] == '/') {
                 req->pathconf = pathconf;
                 break;
@@ -251,7 +257,7 @@ void h2o_send_redirect(h2o_req_t *req, int status, const char *reason, const cha
     static h2o_generator_t generator = {NULL, NULL};
     static const h2o_iovec_t body_prefix = {
         H2O_STRLIT("<!DOCTYPE html><TITLE>301 Moved Permanently</TITLE><P>The document has moved <A HREF=\"")};
-    static const h2o_iovec_t body_suffix = {H2O_STRLIT("\">here</A>")};
+    static const h2o_iovec_t body_suffix = {H2O_STRLIT("\">here</A></P></body></html>")};

     h2o_iovec_t url = h2o_concat(&req->pool, req->scheme->name, (h2o_iovec_t){H2O_STRLIT("://")}, req->authority,
                                  (h2o_iovec_t){(char*)path, path_len});
-- 
1.9.1
```

**Comment by kazuho** [comment]
Thank you for the code.

It seems that your work has revealed there are several shortcomings within H2O.

* `h2o_send_redirect` is not capable of redirecting users to a different authority (e.g. host:port); it should be fixed to accept an entire URL instead
* after reading your code, I have realized that a directive like `enforce-https` would not work in case the user is using a non-standard port number, as it cannot rewrite the authority of the URL (the fact not only limits the use-case, but also makes automated testing harder, as it means that the server would need to be launched with root privileges for testing).  Providing a `redirect` directive might be a better approach.

I am sorry to say this, but please let me rethink how we should proceed.

**Comment by kazuho** [comment]
@Tintinabula I am afraid I should better implement a handler for doing redirects myself as it requires fair amount of refactor within the existing code.  Thank you for your help!

**Comment by Tintinabula** [comment]
@kazuho  I was trying to get the enforce-https redirect working today, but after H2O upgraded to 1.0.1 my current patch no longer works. If you have the time, can you comment on the patch and if I am on the right path. 

For reference, "enforce-https" directive would redirect all http requests to https and eventually have a "hosts:" directive.

```
From 31093710ddfaf9657e6d69560646a2f0427d7a01 Mon Sep 17 00:00:00 2001
From: Tintinabula
Date: Wed, 18 Feb 2015 17:01:26 -0500
Subject: [PATCH] enforce_https testing.

---
 lib/core/request.c | 9 +++++++++
 1 file changed, 9 insertions(+)

diff --git a/lib/core/request.c b/lib/core/request.c
index 46aa159..a3aae73 100644
--- a/lib/core/request.c
+++ b/lib/core/request.c
@@ -157,6 +157,15 @@ void h2o_process_request(h2o_req_t *req)
         }
     }

+    /* enforce-https by redirecting http to https */
+    if (req->scheme == &H2O_URL_SCHEME_HTTP) {
+       req->scheme = &H2O_URL_SCHEME_HTTPS;
+       h2o_iovec_t dest =
+           h2o_concat(&req->pool, req->scheme->name, h2o_iovec_init(H2O_STRLIT("://")), req->authority, req->path_normalized);
+       h2o_send_redirect(req, 301, "Moved Permanently", dest.base, dest.len);
+       return;
+    }
+
     for (handler = req->pathconf->handlers.entries, end = handler + req->pathconf->handlers.size; handler != end; ++handler) {
         if ((*handler)->on_req(*handler, req) == 0)
             return;
-- 
1.9.1
```
