### ISSUE TITLE
reverse proxy server websocket upgrade header twice

### ISSUE THREAD

**Issue by feuerste** [h2o/h2o#1467]
I am using h2o as reverse proxy with proxy.websocket: ON in front of a Node server and socket.io.
When the first request is sent, the response header I get contains two "Upgrade: websocket" entries. Chrome also complains with "WebSocket connection to ... failed: 'Upgrade' header must not appear more than once in a response".
I guess Node already responds with Upgrade: websocket and h2o adds another one in https://github.com/h2o/h2o/blob/master/lib/core/proxy.c#L226
Could this be the reason?

**Comment by i110** [comment]
@feuerste this has been fixed by https://github.com/h2o/h2o/pull/1463. Please try latest master (or v2.2.x branch)

**Comment by feuerste** [comment]
This is great. I am using the debian packages as described in https://github.com/tatsushid/h2o-deb. Is there any chance we can get this fix soon in one of the packages?
