### ISSUE TITLE
Please tell me how to install php7, ubuntu 16.04

### ISSUE THREAD

**Issue by voiddeveloper** [h2o/h2o#1488]
I installed h2o.
but php7 is not installed.
I can't interact with the server. :-(
Please help me.

**Comment by csmk** [comment]
Top 5 relevant answer from **Google.com**!

- https://www.vultr.com/docs/how-to-install-and-configure-php-70-or-php-71-on-ubuntu-16-04
- https://www.howtoforge.com/tutorial/install-apache-with-php-and-mysql-on-ubuntu-16-04-lamp/
- https://tecadmin.net/install-php-7-on-ubuntu/
- https://www.tqhosting.com/kb/464/How-to-install-PHP-70-PHP-FPM-on-Ubuntu-1604-LTS-Xenial-Xerus.html
- http://www.ubuntugeek.com/install-apache2-with-php-7-support-in-ubuntu-16-04-server.html

**Comment by yeonsunghoon** [comment]
I really appreciate your kindness.
I hope these codes are really installed.

**Comment by csmk** [comment]
As you seems to have solved it, please close this non-h2o-related-issue.

**Comment by concatime** [comment]
Please, close this issue.
