### ISSUE TITLE
logging ssl protocol and cipher

### ISSUE THREAD

**Issue by Tintinabula** [h2o/h2o#149]
For https research and testing, the ability to log the ssl protocol and cipher to the access_log might be helpful. We use this information to determine if we can turn off older ciphers and focus on more secure variants.

For example, in Nginx we can add the logging directives $ssl_protocol $ssl_cipher to the end of the log line.

66.249.67.XX - - [12/Feb/2015:16:29:28 -0500] "GET / HTTP/1.1" 200 14 "-" "-" TLSv1.2 ECDHE-ECDSA-AES128-GCM-SHA256

I will take a look at the code and see what I can do.

**Comment by kazuho** [comment]
Sounds like a reasonable request.

As a design note, the names of the directives should match [those of Apache](http://httpd.apache.org/docs/2.4/mod/mod_ssl.html), as the access logger of H2O is designed to be compatible with their `LogFormat` directive.

**Comment by Tintinabula** [comment]
Will do. Thanks for the pointer to the correct file.

**Comment by kazuho** [comment]
part of #36
