### ISSUE TITLE
Why is h2o so fast?

### ISSUE THREAD

**Issue by voiddeveloper** [h2o/h2o#1497]
I am learning why h2o is fast.
1. What does "Unlike most parsers, it is stateless and does not allocate memory by itself. All it does is accept pointer to buffer and the output structure, and setups the pointers in the latter to point at the necessary portions of the buffer." mean?

When I read ppt or read git's "read me" it says "fast" because it is "Unlike most parsers, it is stateless and does not allocate memory by itself. All it does is accept pointer to buffer and the output structure, and setups the pointers in the latter to point at the necessary portions of the buffer."
I do not understand what it means. I would be grateful if you explain in detail.

I would really appreciate it if you let me know.

**Comment by sudarsha** [comment]
my seige benchmark results on an Uplcoud 2GB instance using Lan connections
-----------------------------------------------------------------------------------------------------------

Command -- siege -v -d1 -c250 -i -f siege.txt

siege.txt has 65 urls (all cached, and served by the server itself)
------------

h2o
------
Transactions:			       71847 hits
Availability:			       99.98 %
Elapsed time:			      180.39 secs
Data transferred:	     3519.58 MB
Response time:		        0.61 secs
Transaction rate:	      398.29 trans/sec
Throughput:		       19.51 MB/sec
Concurrency:		      241.77
Successful transactions:       71846
Failed transactions:	          12
Longest transaction:	        4.39
Shortest transaction:	        0.00

nginx
---------

Nginx

Transactions:		        9909 hits
Availability:		       99.77 %
Elapsed time:		       34.35 secs
Data transferred:	      455.19 MB
Response time:		        0.84 secs
Transaction rate:	      288.47 trans/sec
Throughput:		       13.25 MB/sec
Concurrency:		      242.80
Successful transactions:        9905
Failed transactions:	          23
Longest transaction:	        8.84
Shortest transaction:	        0.00

Caddy

Transactions:		       12145 hits
Availability:		       99.44 %
Elapsed time:		       35.07 secs
Data transferred:	      635.66 MB
Response time:		        0.69 secs
Transaction rate:	      346.31 trans/sec
Throughput:		       18.13 MB/sec
Concurrency:		      239.72
Successful transactions:       11813
Failed transactions:	          69
Longest transaction:	        1.97
Shortest transaction:	        0.00

**Comment by deweerdt** [comment]
> When I read ppt or read git's "read me" it says "fast" because it is "Unlike most parsers, it is stateless and does not allocate memory by itself. All it does is accept pointer to buffer and the output structure, and setups the pointers in the latter to point at the necessary portions of the buffer."
> I do not understand what it means. I would be grateful if you explain in detail.

That means that when H2O receives a request, the HTTP parser itself, doesn't allocate any memory besides to the one necessary to receive the request. The HTTP/1 parser that H2O uses is picohttpparser, it has its own repository: https://github.com/h2o/picohttpparser . The source is small enough, and it has small tests https://github.com/h2o/picohttpparser/blob/master/test.c that demonstrate its use.

**Comment by xm74** [comment]
@sudarsha These are the results for HTTP/2  ?

**Comment by csmk** [comment]
@xm74 seems not, because [_siege_](https://github.com/JoeDog/siege) doesn't support HTTP/2 yet.

**Comment by sudarsha** [comment]
Siege doesn't support it. h2load has, but I haven't got around to configuring it.

**Comment by yeonsunghoon** [comment]
@deweerdt 
Thanks to this, I became a chance to understand a little more.
Thank you very much.
I have a question.
I know that "picoparser" is the role of parsing http messages
Is there a store?
In ppt, it is referred to as a buffer. What buffer is the buffer?
Is it a buffer on the web server? Is it a buffer in picoparser?

And "stateless" means speed?
Please explain in detail.
