### ISSUE TITLE
Brotli 1.0

### ISSUE THREAD

**Issue by laugere** [h2o/h2o#1509]
Hi,

If I don't make mistake, the source code of Brotli which is bundled with H2O is v0.3. Version 1.0 is available since September (1.0.1 now). So maybe it can be interesting to update to the 1.0 code, which is certainly mature. (I understand that 0.6 also added some compression enhancement).

I hope I am not saying something wrong, if so, please accept my apologizes. 

Regards,

**Comment by csmk** [comment]
More or less a duplicate of https://github.com/h2o/h2o/issues/1167

**Comment by laugere** [comment]
Oh, sorry !
