### ISSUE TITLE
error-log and log rotation (on FreeBSD)

### ISSUE THREAD

**Issue by utrenkner** [h2o/h2o#1510]
Every night, my error and access logs are automatically rotated and h2o is reloaded. This frees the access log but not the error log. Thus until I restart the server, I do not get anything written into the error log.

Is there a recommended way for how to deal with log rotation? Does it really require a full restart? Or else could the error log be freed through a reload just like the access log (feature request)?

**Comment by xm74** [comment]
Hmm. I my case all works as it should.

```
root@beta:/home/xm # uname -v
FreeBSD 11.1-RELEASE-p4 #0: Tue Nov 14 06:12:40 UTC 2017     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC
root@beta:/home/xm # ll /var/log/h2o/
total 1989
-rw-r--r--  1 www  www  2768050 24 нояб. 00:17 h2o-access.log
-rw-r--r--  1 www  www   358956 20 нояб. 00:00 h2o-access.log.0.bz2
-rw-r--r--  1 www  www   306110 13 нояб. 00:00 h2o-access.log.1.bz2
-rw-r--r--  1 www  www   370706  6 нояб. 00:00 h2o-access.log.2.bz2
-rw-r--r--  1 www  www   374905 30 окт.  00:00 h2o-access.log.3.bz2
-rw-r--r--  1 www  www    97486 23 нояб. 21:02 h2o-error.log
-rw-r--r--  1 www  www     9964 20 нояб. 00:00 h2o-error.log.0.bz2
-rw-r--r--  1 www  www     6273 13 нояб. 00:00 h2o-error.log.1.bz2
-rw-r--r--  1 www  www     8731  6 нояб. 00:00 h2o-error.log.2.bz2
-rw-r--r--  1 www  www    11173 30 окт.  00:00 h2o-error.log.3.bz2
root@beta:/home/xm # grep h2o /usr/local/etc/newsyslog.conf.d/beta.peek.local
/var/log/h2o/*.log www:www                      644     4       *       $W1D0   GJ /var/run/h2o.pid
```

**Comment by utrenkner** [comment]
@xm74 Thank you, I tried (again) the way you do it, but it does not work on any of my servers (neither FreeBSD nor HardenedBSD). I changed permission fourth and back (I originally had root:www on the log files and therefore did not use www:www in newsyslog.conf) - always with the same result: newsyslog rotates the log files, but then h2o cannot write to the error log anymore. 

Both, a reload or the signal to /var/run/h2o.pid via newsyslog do free the access log, but never the error log. I have to restart the h2o server to get error logging working again.

Anyone else experiencing this on FreeBSD (specifically in FreeBSD jails)?

**Comment by xm74** [comment]
Hmm. Very strange issue.
Probably you need to send SIGUSR1 (30) signal to H2O daemon to force to close the file descriptors.
`*.log www:www                      644     4       *       $W1D0   GJ `/var/run/h2o.pid 30``

**Comment by utrenkner** [comment]
I tried it in FreeBSD and HardenedBSD jails - but this did not work either. The 30 signal even prevented the access log from being written (which worked without this signal).

Any other having this problem on FreeBSD? @dch @Tintinabula perhaps?

**Comment by yannick** [comment]
@xm74  how do you restart/reload h2o ?

i recently looked into the code and as far as i remember this is a bug and error.log is never re-opened, since its opened early in main.c and the master keeps track of it.
could be wrong information,but i for sure had the same problem that rename + SIGHUP would not create a new file

**Comment by xm74** [comment]
@yannick by standard way
```
# service h2o restart
```
Log rotation record in newsyslog.conf
```
/var/log/h2o/*.log www:www                      644     4       *       $W1D0   GJ /var/run/h2o.pid
```

**Comment by kazuho** [comment]
The file specified in `error-log` is never reopened once the server starts running.

One way of changing the file to which error log is being emitted without fully restarting the server is to use pipe, e.g. by using rotatelogs as can be found in https://h2o.examp1e.net/configure/base_directives.html#error-log.

The rationale behind current design are:
* we want to open error-log before dropping privileges, so that error-log could be owned by root (or any other user, if pipe is being used)
* we want to avoid error handling when we fail to open a new error log file upon rotation (IIRC Apache had a long-standing bug here)

**Comment by utrenkner** [comment]
Thank you @kazuho for the explanation. Which - as always - makes a lot of sense!!!

For my fellow FreeBSD users:
The ``rotatelogs`` utility is available as part of the Apache webserver port ([www/apache24](https://www.freshports.org/www/apache24/)); and here is its [man-page](https://www.freebsd.org/cgi/man.cgi?query=rotatelogs&apropos=0&sektion=0&manpath=FreeBSD+Ports+11.1&arch=default&format=html), including example confs.

I now have this in my h2o.conf:
``error-log: "| /usr/local/sbin/rotatelogs -l /var/log/h2o/h2o-error_%y%m%d.log 86400"`` which creates error logs such as this ``/var/log/h2o/h2o-error_171208.log``. Very nice.

**Comment by utrenkner** [comment]
@kazuho Just a thought: Would it make sense to include the rotatelogs utility with h2o? It seems that this is almost an essential tool to make h2o error logging useful. I was a bit hesitant to install the complete Apache 2.4 web server package just to have this little tool.

**Comment by kazuho** [comment]
@utrenkner I ask this out of curiosity, but in FreeBSD isn't there any standard way of logging messages emitted by server processes to stdout / stderr?

My understanding is that tools like systemd provide such feature.

Personally I use daemontools to and run `h2o -m master` while keeping `error-log` to the default value (i.e. `stderr`). When invoked with `-m master`, h2o will emit errors to stderr, which will be logged and rotated by daemontools.

**Comment by xm74** [comment]
@kazuho in FreeBSD exist `daemon` https://www.freebsd.org/cgi/man.cgi?query=daemon&sektion=8
Standard daemonizing script from ports use H2P own parameters `-m daemon -c ${h2o_config}` to invoke.

**Comment by dch** [comment]
`daemon(8)` supports capturing stdout/stderr of processes and sending them to e.g. syslog from 11.1R onwards. As 10.x is still supported in the ports, we don't do that directly.

Today's update includes an example config which imo takes care of this:

```yaml
pid-file: /var/run/h2o.pid
# log normal access to file
access-log: /var/log/h2o/access.log
# send errors to syslog
error-log:  "| logger -i -p daemon.err -t h2o"
```

@utrenkner I'll close this as I think we have it covered, but perhaps you might feel like sending a small PR to the docs including a couple of the tricks you and others have mentioned in this thread?

https://github.com/h2o/h2o/blob/master/doc/configure/base_directives.html

**Comment by utrenkner** [comment]
@kazuho I asked my friends at the German bsdforen.de, how they would log such a service. And there actually is a very elegant way, which does not depend on any third party tools such as rotatelog: It uses logger and the syslog.

Let [logger](https://www.freebsd.org/cgi/man.cgi?query=logger&apropos=0&sektion=0&manpath=FreeBSD+11.1-RELEASE+and+Ports&arch=default&format=html) send messages into the syslog, e.g.:
```echo "foo" | logger -t h2o -p local0.err```

Then add to [syslog.conf](https://www.freebsd.org/cgi/man.cgi?query=syslog.conf&apropos=0&sektion=0&manpath=FreeBSD+11.1-RELEASE+and+Ports&arch=default&format=html) something like
```!h2o
*.err                                   /var/log/h2o/h2o-error.log
!-h20```

Once the file is touches and syslogd restarted, all error messages tagged h2o should appear in the specified error log file. And that one could be rotated using the standard FreeBSD way via [newsyslog.conf](https://www.freebsd.org/cgi/man.cgi?query=newsyslog.conf&apropos=0&sektion=0&manpath=FreeBSD+11.1-RELEASE+and+Ports&arch=default&format=html).

Many thanks to KobRheTilla for [this suggestion](https://www.bsdforen.de/threads/dienste-loggen-die-nach-stdout-bzw-stderr-ausgeben.33963/#post-296884)!

I will give this approach a try in the coming days. I really like that it uses only tools from FreeBSD's base system.

**Comment by proyb6** [comment]
My small concern what if the H2O was not log at any point, how do you make sure it’s log without missing the important timing?
