### ISSUE TITLE
H2O fastcgi creates zombie process in FreeBSD

### ISSUE THREAD

**Issue by xm74** [h2o/h2o#1512]
I found that H2O fastcgi generates zombie process in FreeBSD.

```
root@beta:~ # uname -v
FreeBSD 11.1-RELEASE-p4 #0: Tue Nov 14 06:12:40 UTC 2017     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC
root@beta:~ # service h2o start
Starting h2o.
start_server (pid:2384) starting now...
root@beta:~ # ps ajx | grep -w Z
root     31474 27377  4505  4505    0 Z     -      0:00,00 <defunct>
root     35953 93373 29476 73645    2 S+    0      0:00,00 grep -w Z
root@beta:~ # ps auxww | grep 27377
root     27377   0,0  0,2   27492    6472  -  I    23:09             0:00,03 /usr/local/bin/perl -x /usr/local/share/h2o/kill-on-close --rm /tmp/h2o.fcgisock.BzrKST -- /usr/local/share/h2o/setuidgid www /bin/sh -c exec /usr/local/share/h2o/fastcgi-cgi
root     24391   0,0  0,1   14864    2524  0  S+   23:10             0:00,00 grep 27377
```

Is it normal behavior?
Seems it may have relation to issue #1371

**Comment by kazuho** [comment]
> Is it normal behavior?

No.

PID 27377 is invoking setuidgid which in turn invokes sh which in turn invokes fastcgi-cgi. fastcgi-cgi is a daemon process that should not die.

If the only child process that you can find for 27377 is the zombie process, it is most likely that either of the invoked process is failing. Do you see anything in the error log?

**Comment by xm74** [comment]
Here is only records in error log (except OCSP)

> root@beta:/home/xm # cat /var/log/h2o/h2o-error.log
>...
> starting new worker 83317
> exec: perl: not found
> [INFO] raised RLIMIT_NOFILE to 116910
> ...

**Comment by dch** [comment]
@xm74 is this a build from source or using ports? If the latter I'll get it fixed downstream too

**Comment by kazuho** [comment]
@dch Assuming that the ports version is being used, does it reliy on the `H2O_PERL` environment variable? If that is the case, merger of #1518 should fix the issue.

**Comment by xm74** [comment]
@dch  from sources in ports.

**Comment by dch** [comment]
@kazuho yes the ports do:

```
# defaults
: ${h2o_enable:=NO}
: ${h2o_config:=%%PREFIX%%/etc/${name}/${name}.conf}
: ${h2o_perl:=%%LOCALBASE%%/bin/perl}

# daemon
pidfile=`grep pid-file ${h2o_config} | cut -d' ' -f2`
h2o_env="H2O_PERL=${h2o_perl}"
command="%%PREFIX%%/bin/${name}"
command_args="-m daemon -c ${h2o_config}"
procname="%%LOCALBASE%%/bin/perl"
```

closing as this will land in next ports release of 2.2.4.
