### ISSUE TITLE
2 Quick Questions on libh2o

### ISSUE THREAD

**Issue by GuacheSuede** [h2o/h2o#1517]
is there a way to serve static files via libh20 without using config ?
what does h2o_memis function do ?

**Comment by yannick** [comment]
you can likely mostly copy the actual handler h2o itself uses for this. see file.c: https://github.com/h2o/h2o/blob/e8ff48a9812373775c938dde27bf486113bd0aca/lib/handler/file.c

memis compares memory see:
```
/**
 * tests if target chunk (target_len bytes long) is equal to test chunk (test_len bytes long)
 */
static int h2o_memis(const void *target, size_t target_len, const void *test, size_t test_len);
```
https://github.com/h2o/h2o/blob/e8ff48a9812373775c938dde27bf486113bd0aca/include/h2o/memory.h#L281

**Comment by GuacheSuede** [comment]
@yannick apologies i don't understand. Would you happen to mean this method ? https://github.com/h2o/h2o/blob/e8ff48a9812373775c938dde27bf486113bd0aca/lib/handler/file.c#L325

**Comment by yannick** [comment]
@GuacheSuede  no, you shod register the handlers similar to what is shown in the simple.c examples. 
so register 
https://github.com/h2o/h2o/blob/e8ff48a9812373775c938dde27bf486113bd0aca/lib/handler/file.c#L730 
and the other methods following there.

see https://github.com/h2o/h2o/blob/2886d79a2abbc99fbc3a2c1929b1e7510d00d2d4/examples/libh2o/simple.c#L38 for examples with different handlers

**Comment by GuacheSuede** [comment]
@yannick I see, Thanks Yannick, will go try it out and see how it goes.
