### ISSUE TITLE
[FAQ] How to achieve same throughput with streaming and non-streaming

### ISSUE THREAD

**Issue by objd** [h2o/h2o#1530]
I'm trying to implement streaming upload with h2o as a web server, and I have an implementation that works, but when I enable streaming on the handler, it gets really slower. 

I have read through lib/http2/connection.c, and what I've understood is that `write_req_non_streaming(void *, h2o_iovec_t, int)` is just a `req.write_req.cb` that buffers the stream into memory. 

By replacing my request's `req.write_req.cb` with a custom callback that does nothing with the data, I tought I would achieve similar performances as the non streaming alternative. However, when I upload a 1G file in localhost, it gets uploaded in 3.5s without streaming and in ~100s with streaming enabled.

Could it be the compilation flags? I tried enabling `-O3` to no use. I've debugged through `write_req_non_streaming` to see if it did anything special, and it seems to me that it only copies data from the stream's buffer to the request's entity buffer. There must be something I have done that corrupts the http2 state machine.

I've included a minimal example that shows my problem.

```bash
# Usage
wget https://github.com/h2o/h2o/files/1544777/main.tar.gz
tar -zxvf main.tar.gz
gcc main.c -lh2o -luv -lssl -lcrypto -lpthread -o main
dd if=/dev/zero of=test bs=1G count=1
./main &
nghttp -d test -nv http://localhost:8080
```
[main.tar.gz](https://github.com/h2o/h2o/files/1544777/main.tar.gz)

**Comment by sturcotte06** [comment]
Anybody had time to check?

**Comment by kazuho** [comment]
The amount of data that can be sent is a product of bandwidth and delay (know as "BDP").

Before the merger of #1559, the bandwidth has been limited to 64KB. So you might see slow upload speed depending on how you delay the call to `proceed_req`.

**Comment by objd** [comment]
I just confirmed this did solve the issue.
