### ISSUE TITLE
Is H2O brotli support reverse proxy?

### ISSUE THREAD

**Issue by tdtgit** [h2o/h2o#1541]
My websites running H2O reverse proxy, serve content from another backend. H2O config have the line that enable brotli:

```
compress: ON
compress: [ gzip, br ]
```

Checked with KeyCDN Tools still says my website support brotli but from Google Chrome, it sill says content-encoding: gzip in Development Tool. How can I figure out?

P/s: My backend send gzip-ed content to H2O.

**Comment by kazuho** [comment]
> Is H2O brotli support reverse proxy?

Yes.

> P/s: My backend send gzip-ed content to H2O.

Glad you mentioned that. The compress handler can only compress (or decompress) the response. In other words, you need to serve the uncompressed content to take advantage of the compress handler to compress responses.

**Comment by tdtgit** [comment]
Brilliant! Now my website served by br encoding. Thank you again @kazuho 

![screen shot 2017-12-14 at 14 37 58](https://user-images.githubusercontent.com/4527866/33980690-8b19cba2-e0dc-11e7-8114-5a9a96b1c41f.png)

**Comment by tdtgit** [comment]
One more question. Can we set the level of brotli compression? Try settings in [this post](http://blog.kazuhooku.com/2016/03/h2o-http2-server-goes-20-adding-support.html) but not success.

**Comment by deweerdt** [comment]
From https://h2o.examp1e.net/configure/compress_directives.html#compress, emphasis mine:

> If the argument is ON, both brotli and gzip compression are enabled. If the argument is OFF, on-the-fly compression is disabled. If the argument is a sequence, the elements are the list of compression algorithms to be enabled. **If the argument is a mapping, each key specifies the compression algorithm to be enabled, and the values specify the quality of the algorithms.**

**Comment by tdtgit** [comment]
Is this correct?

```
compress: 
  gzip: 6
  br: 4
```

Don't know why but few hours ago I always got error when config like that instead: `compress: [gzip, br]`. Now everything is ok.

Thanks for support.

**Comment by deweerdt** [comment]
> Is this correct?

yes, that looks good.
