### ISSUE TITLE
2.3 does not return an Internal Server Error when mruby handler returns an invalid response

### ISSUE THREAD

**Issue by kazuho** [h2o/h2o#1575]
In versions up to 2.2.x, the mruby handler has returned an Internal Server Error when an mruby handler  returns an invalid response (see the example below). However, we do not see a response in the master branch.
```
mruby.handler: |
  Proc.new do |env|
    nil
  end
```

@i110 Could this be a regression?

**Comment by i110** [comment]
@kazuho Yes, it's regression caused by https://github.com/h2o/h2o/pull/1173. Fixed at #1578
