### ISSUE TITLE
Option to set the group

### ISSUE THREAD

**Issue by concatime** [h2o/h2o#1594]
Hi. I would really love to have an option to set only the group. For instance, I want to be able to set group to `www-data`, but let h2o to pick automatically pick `nobody` as user.
> H2O now setuids to nobody if launched as root and if the user directive is not used.

[Source](//github.com/h2o/h2o/issues/77#issuecomment-74210605).
This way, I don't have to create a custom user `h2o` with `www-data` as the primary group.
Thank you bro ;)

**Comment by kazuho** [comment]
Thank you for the suggestion. Unfortunately, I am against the idea.

The best current practice is of running daemons is to run every one of them with distinct user IDs, to avoid one daemon influencing another. Using `nobody` for multiple purposes is an old practice.

In your case, the fact that you have a group named `www-data` seems to imply that you want to have access control specific to H2O (or a group of processes that handle HTTP). Setting `nobody` as the UID for such process contradicts with the motive.
