### ISSUE TITLE
FreeBSD, failed to obtain sysconf(_SC_GETPW_R_SIZE_MAX)

### ISSUE THREAD

**Issue by Tintinabula** [h2o/h2o#160]
H2O fails to start on FreeBSD 10.1-p5 because H2O can not change to an unprivileged user. The source code compiles on FreeBSD 10.1-p5 without error.

$:  freebsd-version 
10.1-RELEASE-p5

$: grep daemon /etc/passwd 
daemon:*:1:1:Owner of many system processes:/root:/usr/sbin/nologin

$: grep user h2o.conf
user: daemon

$: ./h2o -t -c h2o.conf
[OCSP Stapling] ...messages...
failed to obtain sysconf(_SC_GETPW_R_SIZE_MAX): No such file or directory
[h2o.conf:19] in command user, user:daemon does not exist

A discussion on a Redhat mailing list mentions PATH MAX might not be portable.

FreeBSD and sysconf(_SC_GETPW_R_SIZE_MAX)
https://www.redhat.com/archives/libvir-list/2011-May/msg01013.html

**Comment by kazuho** [comment]
@Tintinabula Thank you for noticing the issue.

Reading the [POSIX man page of getpwnam](http://pubs.opengroup.org/onlinepubs/9699919799/functions/getpwnam.html), quote:

> A call to sysconf(_SC_GETPW_R_SIZE_MAX) returns either -1 without changing errno or an initial value suggested for the size of this buffer.
> 
> [ERANGE] Insufficient storage was supplied via buffer and bufsize to contain the data to be referenced by the resulting passwd structure.

it seems that the best way would be to:

* call `getpwnam_r` repeatedly until it stops returning `ERANGE`, while expotentially increasing the size of buffer being passed (i.e. 1,024 bytes -> 2,048 bytes -> 4,096 bytes, ...).
* do not use `sysconf(_SC_GETPW_R_SIZE_MAX)` as there is no guarantee that it would succeed

**Comment by kazuho** [comment]
Oops.  It seems that we cannot skip calling `sysconf(_SC_GETPW_R_SIZE_MAX)`.

The man page of OS X states that:
> The maximum required bufsize can be obtained by passing the _SC_GETPW_R_SIZE_MAX constant to the sysconf(3) call.

**Comment by kazuho** [comment]
@Tintinabula I would appreciate it if you could confirm that the problem has been resolved on FreeBSD.

**Comment by Tintinabula** [comment]
@kazuho  I can confirm H2O will run on FreeBSD 10.1-p5 (latest patches) as the user specified in the config file.  H2O runs without error when I requested a few web pages as well.

$:  sockstat -l
USER     COMMAND    PID     FD PROTO  LOCAL ADDRESS  FOREIGN ADDRESS      
daemon   h2o                11023 4    tcp6        *:8080                      *:*
daemon   h2o                11023 5    tcp4        *:8080                      *:*
daemon   h2o                11023 6    tcp6        *:8443                      *:*
daemon   h2o                11023 7    tcp4        *:8443                      *:*

**Comment by kazuho** [comment]
:+1: Thanks a lot!!!
