### ISSUE TITLE
Firefox and server push?

### ISSUE THREAD

**Issue by utrenkner** [h2o/h2o#1603]
Sorry, this is a bit OT, but I really cannot find any information on this, anywhere: For months, current Firefox releases do not seem to support server push anymore. Patrick Meenan suggested that [he thought it was temporarily disabled](https://www.webpagetest.org/forums/showthread.php?tid=15122&pid=30251#pid30251) by the developers. But 5 months later, nothing has changed.

Does anyone here know anything about the fate of server push on Firefox (over here in Germany, Firefox still is one of the top browsers used... so it is important to us). Or where to ask at Mozilla (their forums, mailing lists and bug trackers are so granular that I never know where to post my problems).

**Comment by TheDecryptor** [comment]
It's working fine for me in 57, but the dev tools have no awareness of pushed resources and it leads to some rather buggy behavior (Like pushed resources never showing up even though they've obviously been loaded)

They can also appear at the very end of the resources list, or appear with no metadata (Status code, headers, body, timeline, etc.). The only reliable way I've found is the presence of the "x-http2-push" header.

**Comment by utrenkner** [comment]
In my FF57, I do not see the x-http2-push header. But I can see it working in Chrome/Chromium.

Have a look at this [webpagetest.org result](http://www.webpagetest.org/result/180112_AB_511a847a552ecff25d60c6ac856eed99/1/details/#waterfall_view_step1): FF claims that the resources immediately following the initial HTML are pushed, but the waterfall shows that this was not honored (resources are requested clearly after HTML was in). This [looks totally different in Chrome](http://www.webpagetest.org/result/180112_2C_29fc5a19e8e75d80ea6fb0b11f75b98e/1/details/#waterfall_view_step1), where JS and CSS are in _before_ the HTML download has finished.

While looking for test tools checking for server push, I noticed that some tools do not even see HTTP/2 enabled on our server. E.g. testing https://www.solarserver.de/ for server push on https://http2-push.io/ results in ``Error: The HTTP/2 protocol was not selected``.

But other tools and even FF do "see" HTTP/2 and I have ``http1-upgrade-to-http2: ON`` in my config. Earlier versions of FF had no problem with our config and received the pushed resources before the HTML.

Anyone seeing this strange behavior with h2o / Firefox, too?

**Comment by utrenkner** [comment]
The FF behavior seems to be somewhat unpredictable. See these two tests for https://h2o.examp1e.net/
- [obviously with push](http://www.webpagetest.org/result/180112_FR_4aac826cd8ae84be717d837bafb2fbad/1/details/#waterfall_view_step1)
- [apparently without push](http://www.webpagetest.org/result/180112_N0_604becd03e6cdec7bb0563d62e1186da/1/details/#waterfall_view_step1)

**Comment by kazuho** [comment]
FWIW, h2o only pushes a URL at most once per each h2 connection, since it is fairly safe to assume that a client connected to a server has a resource that has been delivered using the same connection stored in its cache. I am not sure if that is related to the issue though.

**Comment by utrenkner** [comment]
No, it really seems to be a problem of Firefox. Webpagetest.org can show both, first-view and repeat-view of a page. And one can see the HTTP headers for each resource: On first-view, the casper cookie is not yet set and all static content is downloaded for the first time. It really seems that FF disabled server push with version 56. 

I had hoped others here knew more about this... I am closing this issue now.

**Comment by utrenkner** [comment]
PS: I just found that @deweerdt has [answered my question over on Stackoverflow](https://stackoverflow.com/questions/48278265/firefox-and-http-2-server-push?noredirect=1#comment83572750_48278265): Server push is foreseen to come back to FF with version 58.

Thanks!
