### ISSUE TITLE
autoh2o.py : ignored columns set is overwritten with None. Consequence: 'weights_column' not used

### ISSUE THREAD

**Issue by johndelarue** [h2o/h2o#1608]
The weights_column in automl is not used and throws an error due to ignored_columns being overwritten by None.  The error is found in:
h2o/automl/autoh2o.py:
            ignored_columns = set(names) - {y} - set(x)
            if fold_column is not None: ignored_columns = ignored_columns.remove(fold_column)
            if weights_column is not None: ignored_columns = ignored_columns.remove(weights_column)
            if ignored_columns is not None:
                input_spec['ignored_columns'] = list(ignored_columns)

Possible solution:
           ignored_columns = set(names) - {y} - set(x)
            if fold_column is not None:  ignored_columns.remove(fold_column)
            if weights_column is not None: ignored_columns.remove(weights_column)
            if ignored_columns is not None:
                input_spec['ignored_columns'] = list(ignored_columns)

**Comment by kazuho** [comment]
Wrong repository?
