### ISSUE TITLE
resources leak when h2o is used as a library

### ISSUE THREAD

**Issue by chenbd** [h2o/h2o#1609]
When dynamic server loop created/quits, some resources not released.
eg:
evloop's fd.
memory cached in perthread h2o_mem_recycle_t.
multithread queue destroy.

**Comment by kazuho** [comment]
Could you please elaborate why you want to restart a loop?

In H2O, the configuration is kept independent to the loop. Therefore, users can reconfigure the application without switching to a new loop.

**Comment by chenbd** [comment]
`libh2o-evloop` is used as a library in our project.
i wrapper a few interfaces of libh2o-evloop like `server_start()`, `server_stop()`.
in `server_start()`, threads are created as server loop.
in server loop thread, evloop is created.

so when `server_stop()` is called by other module, the call is blocked by join server loop thread.
i want all resources allcated in server loop thread  be released before server loop thread quit.
` graceful restart` is not needed in our business logic.

**Comment by kazuho** [comment]
Thank you for the answer.

I would argue that a server cannot be stopped instantly. There could be responses in-flight, or requests in-flight. So graceful shutdown (which is often part of graceful restart) is mandatory.

> in server loop thread, evloop is created.

As stated, you should not implement that way. You should keep the event loop always alive, adding a listener when the server is started (and removing the listener when the server is stopped).

**Comment by chenbd** [comment]
>I would argue that a server cannot be stopped instantly. There could be responses in-flight, or requests in-flight. So graceful shutdown (which is often part of graceful restart) is mandatory.

the server loop thread can close listening socket and wait all client sockets closed before exit.
so all request/response should be processed. right?

>As stated, you should not implement that way. You should keep the event loop always alive, adding a listener when the server is started (and removing the listener when the server is stopped).

i will check this way.

anyway, just a few interface added, the user can choose how the library be used, right?

**Comment by kazuho** [comment]
> the server loop thread can close listening socket and wait all client sockets closed before exit.
so all pending request/response should be processed. right?

Correct.

> anyway, just a few public/private interface added, the user can choose how the library be used, right?

I disagree. The factors we need to consider are: i) if it helps the users write good code ii) how big the maintenance cost is. In this case, i is questionable since having the proposed interface would lead to users implementing incorrect shutdown procedure.

**Comment by chenbd** [comment]
>I disagree. The factors we need to consider are: i) if it helps the users write good code ii) how big the maintenance cost is. In this case, i is questionable since having the proposed interface would lead to users implementing incorrect shutdown procedure.

Ok, about `incorrect shutdown procedure`, so would you please suggest the `correct shutdown procedure `?
currently i create hostconf/pathconf/req handler/listening socket in `server_start()`, just like what we already have done in `src/main.c` and start server loop thread.

i thought about `reuse event loop`.
if i reuse event loop from `h2o_evloop_create()`, the server thread must **not** quit.
and in server thread's main loop, some logic must be added which need synchronized  when other module call `server_stop()` and call `server_start()` again. eg: listening socket close/open.
this seems not simpler than just release all resources and quit server thread and start again.

would you please give your suggestions about this use case?
thanks.

**Comment by kazuho** [comment]
> would you please give your suggestions about this use case?

One way is to reuse an existing event loop for newer generations of connections as explained in https://github.com/h2o/h2o/issues/1609#issuecomment-357843566.

The other way is to stop a thread after all the connections have been gracefully closed. `src/main.c` does that (with the exception that the entire process is terminated). It might be well worth to track the behavior starting from the `on_sigterm` function.

Regardless of the approach (or regardless of shutting down the connections gracefully or not), you need to wake up a event loop running at a different thread so that it could shut down. IMO that is the most difficult part.

**Comment by chenbd** [comment]
thanks for you answer.

>The other way is to stop a thread after all the connections have been gracefully closed. src/main.c does that (with the exception that the entire process is terminated). It might be well worth to track the behavior starting from the on_sigterm function.

> Regardless of the approach (or regardless of shutting down the connections gracefully or not), you need to wake up a event loop running at a different thread so that it could shut down. IMO that is the most difficult part.

this is exactly what i have done. the entire process is not terminated.
the `server loop` thread can receive event from other thread, wait all connections closed and release resources.

what i want here is just release **all** resources as i talked about in this topic.
what i preferred is h2o provide interface and let user do it when needed.

but the current state of libh2o seems not well fulfilled this requirement.
if we want to improve this, what's your suggestion?
i can  adjust the PR according to your suggestion.

**Comment by kazuho** [comment]
> what i want here is just release **all** resources as i talked about in this topic.

Am I correct in assuming that the only resources that leak are the memory allocations tied to thread-local variables? If that is the case, my suggestion would be to add a destructor function that releases them as we discuss in https://github.com/h2o/h2o/pull/1610#issuecomment-358505623.

**Comment by chenbd** [comment]
test for http1 and websocket, the answer is yes.
http2 not been tested.

I'm happy with your suggestion and will address it.
