### ISSUE TITLE
ld error in "examples/libh2o/simple.c" on ubuntu 14.04 

### ISSUE THREAD

**Issue by chenbd** [h2o/h2o#1611]
examples/libh2o/simple.c:197: undefined reference to `SSL_CTX_set_ecdh_auto'
collect2: error: ld returned 1 exit status

**Comment by CorryO** [comment]
looks like known issue with openssl
https://github.com/openssl/openssl/issues/1437

**Comment by chenbd** [comment]
`apt-cache policy openssl` gives the following output:

```
openssl:
  Installed: 1.0.1f-1ubuntu2.23
  Candidate: 1.0.1f-1ubuntu2.23
  Version table:
 *** 1.0.1f-1ubuntu2.23 0
        500 http://mirrors.aliyun.com/ubuntu/ trusty-updates/main amd64 Packages
        500 http://mirrors.aliyun.com/ubuntu/ trusty-security/main amd64 Packages
        100 /var/lib/dpkg/status
     1.0.1f-1ubuntu2 0
        500 http://mirrors.aliyun.com/ubuntu/ trusty/main amd64 Package
```

**Comment by CorryO** [comment]
6 days ago there was significant commit for simple.c
which introduced this line (and a lot of other changes)
"SSL_CTX_set_ecdh_auto(accept_ctx.ssl_ctx, 1);"
https://github.com/h2o/h2o/commit/7f5f2ea1e384dbd1e430b67607c0ae8f5180b574

Maybe you can try to run the most recent version simple.c before this commit?
The code will be less secure, but it could help confirming that the update requires a follow up.
Maybe @Varbin can add to this topic.

**Comment by Varbin** [comment]
An ifdef might be required to check that the auto function is really available (like in the main executable).

**Comment by CorryO** [comment]
@Varbin 
Ok so I assume that this would be enough?
/*snippet from main.c*/
#ifdef SSL_CTX_set_ecdh_auto
    SSL_CTX_set_ecdh_auto(ssl_ctx, 1);
#endif

Or is a similar version of the else-part also required?
/*snippet from main.c*/
#ifdef SSL_CTX_set_ecdh_auto
    SSL_CTX_set_ecdh_auto(ssl_ctx, 1);
#else
    int nid = NID_X9_62_prime256v1;
    EC_KEY *key = EC_KEY_new_by_curve_name(nid);
    if (key == NULL) {
        fprintf(stderr, "Failed to create curve \"%s\"\n", OBJ_nid2sn(nid));
        return;
    }
    SSL_CTX_set_tmp_ecdh(ssl_ctx, key);
    EC_KEY_free(key);
#endif

@chenbd 
The commit before the related change is
git checkout 0cbb91b63e931e26f26cd8b11618ce823dba0a75
I'll try this commit by myself to see if this issue "unsupported http2 protocol" https://github.com/h2o/h2o/issues/1616 started to exist after current latest commit of simple.c being https://github.com/h2o/h2o/commit/7f5f2ea1e384dbd1e430b67607c0ae8f5180b574

**Comment by Varbin** [comment]
The second part is to setup a  single curve if the auto function is not defined - if the auto function might be not defined in a lower version it is required. As OpenSSL < 1.1.0 should always define `SSL_CTX_set_ecdh_auto` the `else` part should not be required.

**Comment by Varbin** [comment]
@CorryO But shouldn't a compat macro be defined in OpenSSL 1.1.0 (https://github.com/openssl/openssl/commit/2ecb9f2d18614fb7b7b42830a358b7163ed43221)? The `ifdef` check should still be used.

@chenbd h2o usually requires Openssl 1.0.2+

**Comment by CorryO** [comment]
@varbin yes it looks like

**Comment by kazuho** [comment]
Thank you for your help.

@CorryO's fix has been merged in the commit above.
