### ISSUE TITLE
"H2O_HTTP1_CALLBACKS missing request_shutdown" cause server loop can not quit immediately

### ISSUE THREAD

**Issue by chenbd** [h2o/h2o#1612]
when server loop quits, if `http1_is_persistent` is true, the server loop cant not quit immediately and must wait 'http1.req_timeout`, the connection will be closed only when timeout reachs.

guess this is not the user's want, specially when used as a library.

**Comment by kazuho** [comment]
Please refer to #1609 #1613 for related discussion.
