### ISSUE TITLE
Redirect to subfolders with MRuby

### ISSUE THREAD

**Issue by proyb6** [h2o/h2o#1642]
I have a use case which will need to serve different images (Webp or JPEG)

On index.html, MRuby will look up header and found webp is exist, it will serve index.html in /www-webp subfolder or /www-jpeg subfolder if none were found. Is it feasible in H2O or MRuby? I'll rather try not to code in PHP or dynamic scripting language to maximise the performance.

**Comment by i110** [comment]
@proyb6 
After https://github.com/h2o/h2o/pull/1217 gets merged, you can tweak the request path like the following:

```ruby
hosts:
  "example.com":
    paths:
      /:
        - mruby.handler: |
            proc {|env|
              env['PATH_INFO'] = if webp_found?
                '/www-webp' + env['PATH_INFO']
              else
                '/www-jpeg' + env['PATH_INFO']
              end
              H2O.next.call(env)
            }
        - file.dir: /path/to/your/root
```

Of cause you can try that branch now if you checkout it and build.

**Comment by proyb6** [comment]
@i110 Thanks, will these retain the original URL https://www.example.com and not showing ```https://www.example.com/www-web/```?

What does ```H2O.next.call(env)``` do?

**Comment by utrenkner** [comment]
@proyb6 I think you could also adapt my cache scripts, especially the older one for the now deprecated Wordfence Phalcon cache. Have a particular look at [lines 88-109](https://github.com/utrenkner/wfcache-mruby/blob/master/wfcache.rb#L88-L109).

It uses the reproxy-directive to tell h2o to actually deliver a different file based on e.g. the browser's acceptance of gz compression (as indicated in the HTTP header). This happens completely transparently to the user. If I did not add a cache-hit header, there would be no trace of which file was actually delivered.

**Comment by proyb6** [comment]
@i110 This works as expected! Can this branch be use in production?

@kazuho Any plans to merge #1217 into master branch?

@utrenkner I'm new to reproxy-directive and docs is insufficient for beginner. How does it works if I could instruct H2O to looks for HTML and images in subfolders?

**Comment by proyb6** [comment]
This lose the ability to "push" (was not pushed) and only deliver images as requested by web content if I'm prefer to serve images from a ```common``` aka share folder instead of having to create multiple common folder in subfolders.

```
   paths:
     /common:
       file.dir: /var/h2o/www/common/

   paths:
     /:
      - mruby.handler: |
          Proc.new do |env|
            push_paths = []
            if /webp/.match(env["HTTP_ACCEPT"])
              push_paths << ["/common/logo.png", "image",""]
              push_paths << ["/img/slide1.webp", "image",""]
            end
            [399, push_paths.empty? ? {} : {"link" => push_paths.map{|p| "<#{p[0]}>; rel=preload; as=#{p[1]} #{p[2]}"}.join("\n")}, []]

            env['PATH_INFO'] = '/www-webp' + env['PATH_INFO']
            H2O.next.call(env)
          end
      - file.dir: /var/h2o/www
```

**Comment by proyb6** [comment]
@utrenkner I have found your 307 reproxy works great for me.
