### ISSUE TITLE
MRuby version

### ISSUE THREAD

**Issue by proyb6** [h2o/h2o#1645]
What is the current MRuby version and what is the requirements to update new MRuby?

**Comment by i110** [comment]
@proyb6 current mruby version is https://github.com/mruby/mruby/commit/3acaa44. There're no specific requirements to update to new version, but we have to watch the details of the changes.
Recently mruby 1.4 was released but there are no release note yet, so I'm waiting it to be published

**Comment by proyb6** [comment]
@i110 Thanks, I see the latest fix for this issue https://github.com/mruby/mruby/issues/3860

**Comment by proyb6** [comment]
MEuby 1.4.1 is scheduled to release on April 2018.

**Comment by proyb6** [comment]
It’s also useful to have an upgrade guide for MRuby for early testing so we won’t have to delay longer to resolve future bugs.

**Comment by i110** [comment]
@proyb6 Please refer https://github.com/h2o/h2o/wiki/Importing-third-party-code. After that build h2o again.

**Comment by proyb6** [comment]
@i110 thanks, there is a broken link in the wiki to:

https://github.com/h2o/h2o/tree/master/misc/dump-github-reposistory.pl

**Comment by i110** [comment]
Thank you for reporting. fixed.

**Comment by proyb6** [comment]
@i110 Although, I have tried to import MRuby 1.4 and compile new build, it appear the H2O display blank screen. I wonder if you have tried with latest MRuby?
