### ISSUE TITLE
MRuby script compile to MRI

### ISSUE THREAD

**Issue by proyb6** [h2o/h2o#1652]
Is MRuby script running in interpreter?

Is it feasible to compile MRuby script to gain performance advantage and faster execution?

**Comment by i110** [comment]
@proyb6 You can compile .rb files into .mrb in advance, but otherwise h2o (and `require` method) compiles mruby scripts at startup, so I don't think you can gain performance improvements so much. Do you have any performance issues?

**Comment by proyb6** [comment]
I was looking at chart comparing Nginx native vs ngx_mruby

**Comment by proyb6** [comment]
Is mrb still be request and load at every requests by H2O or call mrb from memory?

**Comment by i110** [comment]
from memory.

**Comment by proyb6** [comment]
Is there a directive to cache rb code similar to Nginx?

location /hello {
    mruby_content_handler /path/to/hello.rb cache;
}

**Comment by i110** [comment]
caching compiled result is default behavior in h2o.

**Comment by proyb6** [comment]
Thanks!

**Comment by proyb6** [comment]
I'm not sure how does it load in H2O.conf?

```
      "/test2":
        mruby.handler-file: /var/h2o/www/hello.mrb
```

mrbc hello.rb created mrb file.

```
Proc.new do |env|
  push_paths = []
  if /jpg/.match(env["HTTP_ACCEPT"])
    push_paths << ["/test.jpg", "image",""]
  end
    [399, push_paths.empty? ? {} : {"link" => push_paths.map{|p| "<#{p[0]}>; rel=preload; as=#{p[1]} #{p[2]}"}.join("\n")}, []] 
end
```

My initial test shown HTTP 500 error.

**Comment by i110** [comment]
what error message did you get in stderr?

**Comment by proyb6** [comment]
mruby raised: /var/h2o/www/hello.mrb:1: uninitialized constant RITE0003 (NameError)

**Comment by proyb6** [comment]
@i110

Thanks for looking into it, to further looking for more of what is possible, I might have the wrong impression that MRuby version is a limited edition in H2O or those extensions like MRuby_pg found on MRuby website are 100% compatibles?
