### ISSUE TITLE
Quick Question: Libh2o Path

### ISSUE THREAD

**Issue by GuacheSuede** [h2o/h2o#1656]
How would one be able to put in libh2o handler such that path is `/blog/post/{id}` ?

**Comment by yannick** [comment]
you would need a library such as https://github.com/c9s/r3

**Comment by GuacheSuede** [comment]
@yannick Yes :), that was what i was looking at, however i was wondering how would one go about integrating it into the path handler ?
`    pathconf = register_handler(hostconf, "/post-test", post_test);`
from https://github.com/h2o/h2o/blob/master/examples/libh2o/simple.c#L239

**Comment by GuacheSuede** [comment]
I see, Thanks Yannick for the help.
Just a last question, do you see performance drops in mruby vs c ?

**Comment by GuacheSuede** [comment]
@yannick Alright Thanks for your help so far
