### ISSUE TITLE
Gzip compression to use Zopfil?

### ISSUE THREAD

**Issue by proyb6** [h2o/h2o#1657]
We know Zopfil gave better compression than GZip and may impact performance for large uncompressed files. Is it feasible to include an option to compress with Zopfil?

It work well with precompressed file with Zopfil.

**Comment by kazuho** [comment]
Zopfli is too slow for on-the-fly compression.

If you want to serve files compressed by Zopfli, you should compress them manually and let the server choose them (see `file.send-compressed`).
