### ISSUE TITLE
Support SCT extension for Expect-CT

### ISSUE THREAD

**Issue by Jxck** [h2o/h2o#1659]
I wanna use Expect-CT, but this requires adding SCT timestamp to `signed_certificate_timestamp`.
so please accept signed_certificate_timestamp in h2o.conf and using that in tls-handshake.

- https://tools.ietf.org/html/rfc6962
- https://www.certificate-transparency.org/what-is-ct

**Comment by lenovouser** [comment]
Duplicate of #448

**Comment by Jxck** [comment]
sorry

**Comment by lenovouser** [comment]
@Jxck no worries 😃  - just wanted to point you to the right issue
