### ISSUE TITLE
preloads.rb requires should be local

### ISSUE THREAD

**Issue by yannick** [h2o/h2o#1660]
when including files via `mruby.handler-file` and the files have filenames already used in `share/h2o/mruby/preloads.rb` it creates errors or even segfaults. 

e.g. you can't do `mruby.handler-file: acl.rb`

this should be fixed or receive a big fat warning  in the docs. 

EDIT: worse, even just having a file laying in the same directory as h2o.conf  named that way will make things fail

**Comment by kazuho** [comment]
Thank you for reporting the issue.

Can you post a reproducible case? I am not sure if it is an issue with `mruby.handler-file` or `require`, since IIUC all they do is just load the source file and pass to mruby.

**Comment by i110** [comment]
@yannick Thank you for finding and reporting this problem! https://github.com/h2o/h2o/pull/1662 will fix the issue.
