### ISSUE TITLE
Passing return value from MRuby to the page tempalte

### ISSUE THREAD

**Issue by proyb6** [h2o/h2o#1661]
Is it possible to perform like a template engine like that MRuby could return value from H2O?

**Comment by yannick** [comment]
yes.
you could e.g. use https://github.com/pbosetti/mruby-merb/blob/master/mrblib/merb.rb or compile in a mruby gem.

**Comment by proyb6** [comment]
Thanks, it’s would be useful to add this into Wkii as a guide to help H2O gaining popularity?

**Comment by yannick** [comment]
not sure, usually that is done in your backend. 
what is your use case?

**Comment by proyb6** [comment]
I’m currently building HTML static content and want to set “active” on certain navigation links in the current page using MRuby to detect the current PATH_INFO. Useful for those without JavaScript enabled. There are more features and try to rely on H2O as much as possible to improve performance or running on embedded device.

I have, PHP, Swift and Nodejs with different template engine as a backend, bad for Developers experience.

**Comment by proyb6** [comment]
Or the simplest would be good to inject a sting into the HTML files at particular lines is even better
