### ISSUE TITLE
NamedError with MRuby

### ISSUE THREAD

**Issue by proyb6** [h2o/h2o#1674]
I have came across someone repo running on H2O v1.6 with the code like this:

‘’’’
class JsonApi
  def initialize
    @storage = Hiredis.new
    @storage['foo'] = 'bar'
  end

  def call(env)
    body = JSON.generate({foo: @storage['foo']})

    [
      200,
      {'Content-Type'   => 'application/json',
       'Content-Length' => body.size},
       [body]
    ]
  end
end

JsonApi.new

‘’’

I got:
mruby raised: /var/h2o/json_api.rb:3: uninitialized constant JsonApi::Hiredis (NameError)

Is class method can be used or could directly consume Redis APIs as seen in the H2O test suite.

**Comment by i110** [comment]
Please latest master. I believe https://github.com/h2o/h2o/pull/1173 fixed the namespace issue

**Comment by proyb6** [comment]
Im using H2O 2.2.4 last night, could you test on your end with my code?

**Comment by proyb6** [comment]
Will test tonight, I wish this patch could be release soon.

**Comment by proyb6** [comment]
@i110 Latest master is 2.2.4? I have tested on 2.2.4 last night.

**Comment by i110** [comment]
No, clone from github.

**Comment by proyb6** [comment]
Noted, will recline from

git clone https://github.com/h2o/h2o.git

**Comment by proyb6** [comment]
@i110 Recompile with latest H2O source and based on this files and configuration for your reference.

https://github.com/jodosha/mruby-rack-json-api/tree/master/app
https://github.com/jodosha/mruby-rack-json-api/blob/master/conf/h2o.conf

```
h2o server (pid:16767) is ready to serve requests
mruby raised: app/json_api.rb:3: uninitialized constant JsonApi::Hiredis (NameError)
```

```/hardcoded``` route is working except it append a trailing backslash to ```www.example.com/hardcoded/```

**Comment by i110** [comment]
You're using mruby-hiredis? I guess that that mrbgem is not properly installed. Please re-check your https://github.com/h2o/h2o/blob/master/misc/mruby_config.rb so that the modules you need are all listed.

**Comment by proyb6** [comment]
I have hiredis in deps folder installed by default and it has compiled, are there any extra configuration?

```
brotli     hiredis  libyrmcds                   mruby-digest  mruby-errno      mruby-input-stream  mruby-pack     picohttpparser  ssl-conservatory
cloexec    klib     mruby                       mruby-dir     mruby-file-stat  mruby-io            mruby-require  picotest        yaml
golombset  libgkc   mruby-class-new-fiber-safe  mruby-env     mruby-iijson     mruby-onig-regexp   neverbleed     picotls         yoml
```

**Comment by proyb6** [comment]
I'm not sure if I'm suppose to test by running ```ruby mruby_config.rb``` or ```mruby mruby_config.rb``` which both also have the same NamedError. On Ubuntu server using MRuby 1.2 that come with the distribution.

**Comment by i110** [comment]
@proyb6 `deps/hiredis` is c library. You need to import mruby-hiredis (mruby binding of hiredis) or whatever mruby libraries you want to use, in `deps` directory, by yourself.

**Comment by proyb6** [comment]
I see it can be rather confuse, I think c libraries could have a prefix like c-* to differentiate from MRuby libraries.

Will try tonight.

**Comment by proyb6** [comment]
I've compile with the MRuby-redis and tried MRuby-hiredis, assume I need to specify ```require``` with absolute path to the file when the author's original source code doesn't have it?

```
require "/home/testmruby/h2o/deps/mruby-hiredis/mrblib/hiredis.rb"

class Mr
  def initialize
    @storage = Hiredis.new
    @storage['foo'] = 'bar'
  end

  def call(env)
    body = JSON.generate({foo: @storage['foo']})

    [
      200,
      {'Content-Type'   => 'application/json',
       'Content-Length' => body.size},
       [body]
    ]
  end
end

Mr.new
```

and got an error, sorry if this is MRuby specific.

``mruby raised: /.../h2o/deps/mruby-hiredis/mrblib/hiredis.rb:15: undefined method 'call' for #<Hiredis:0x269d590> (NoMethodError)
```

**Comment by proyb6** [comment]
@i110 Solved: After trying using the author starter kit with master branch, Redis is working as expected. I'll have to troubleshoot why adding ```git clone ...``` even with the script for adding 3rd parties dependencies provided by H2O into deps don't work in my own setup.
