### ISSUE TITLE
H2O::Redis API

### ISSUE THREAD

**Issue by proyb6** [h2o/h2o#1679]
I seen in slide 45 and I can't read Japanese without translation, Google has lost in translation as well.
https://www.slideshare.net/ichitonagata/h2o-x-mruby-72949986#!

How do you access H2O::Redis which raised an error or pending for https://github.com/h2o/h2o/pull/1152? While I had succeed with MRuby-Hiredis deps.

```mruby raised: /var/h2o/www/app/mr.rb:1: uninitialized constant H2O::Redis (NameError)```

**Comment by i110** [comment]
That PR will be merged shortly. If you cannot wait it, please try it by checkouting that branch.

**Comment by i110** [comment]
@proyb6 FYI: https://github.com/h2o/h2o/pull/1152 gets merged
