### ISSUE TITLE
H2O MRuby deps has no mruby executable file?

### ISSUE THREAD

**Issue by proyb6** [h2o/h2o#1681]
I realise there is no ```mruby``` executable file in H2O MRuby bin which one of the 3rd parties deps tried to run and failed.

/home/test/h2o/mruby/host/bin/
```
mirb  mrbc  mruby-config  mruby-strip
```

CMake
```
CMakeFiles/mruby.dir/build.make
CMakeFiles/mruby:
        cd /home/test/h2o/deps/mruby && MRUBY_TOOLCHAIN=gcc MRUBY_CONFIG=/home/test/h2o/misc/mruby_config.rb MRUBY_BUILD_DIR=/home/test/h2o/mruby MRUBY_ADDITIONAL_CONFIG=
...
```

I have read H2O Install page point 3 at the footer notes mentioned ```mkmf``` which it's not found despite installed ruby-dev which I think is no longer in latest ruby dev package?

**Comment by yannick** [comment]
@proyb6 can you post your cmake config and operating system version?

e.g. on macOS i do:

```
brew install openssl@1.1
mkdir h2o-installdir
H2O_INSTALLDIR=$(greadlink -f h2o-installdir)
git clone https://github.com/h2o/h2o.git
mkdir h2o/build
cd h2o/build
cmake -DWITH_MRUBY=ON -LAHT -DCMAKE_BUILD_TYPE=Release -DOPENSSL_ROOT_DIR=/usr/local/Cellar/openssl@1.1/1.1.0g -DCMAKE_INSTALL_PREFIX=$H2O_INSTALLDIR ..
```

also note that the binaries in `./deps/mruby/bin/` are not super useful,as they do not run the h2o eventloop ( see https://github.com/h2o/h2o/issues/1669 ). so you might be better of to have your own mruby installation in a separate dir to test mruby stuff that does not use h2o specific things. if you want to test h2o specific things you need to run them as a handler from the h2o binary.

**Comment by proyb6** [comment]
Sorry, I’m on mobile device, I’m following the exact commands in H2O install page.

sudo cmake -DWITH_BUNDLED_SSL=on .
sudo make
sudo make install

I haven’t modified any script.

**Comment by proyb6** [comment]
Does H2O compiles with release if I don’t set “Release”?
I’m assume we need LAHT if it’s necessary, it should be include on H2O page.

-LAHT -DCMAKE_BUILD_TYPE=Release

**Comment by yannick** [comment]
Neither is needed. Dont use bundled ssl, its depreciated.

**Comment by proyb6** [comment]
@yannick Sorry, I missed your question on OS, I'm running on Ubuntu 16.04 Server on VPS server.

**Comment by proyb6** [comment]
I found it's some missing source packages require to compile and add -I### of those libraries like -lMagick++-6.Q16 -lMagickCore-6.Q16 to CMakeFiles/h2o.dir/link.txt

It's a bit of hassle, can these parameter be pass during cmake?
