### ISSUE TITLE
Set max-age for files 

### ISSUE THREAD

**Issue by proyb6** [h2o/h2o#1691]
In a scenario, some assets has been "pushed" to client's web browser. When I tried to run GTMetrix
(https://gtmetrix.com) and it indicates I should leverage browser caching with 1 hour expiry age.

How do I set header for pushed assets with max-age?

```
          Proc.new do |env|
            push_paths = []
            push_paths << ["/images/logo.svg", "image",""]
            [399, push_paths.empty? ? {} : {"link" => push_paths.map{|p| "<#{p[0]}>; rel=preload; as=#{p[1]} #{p[2]}"}.join("\n")}, []]
          end
```

**Comment by axelu** [comment]
You could do something like this:
```
Proc.new do |env|
    headers = {}
    if /\.svg\z/.match(env["PATH_INFO"])
        headers["cache-control"] = "max-age=3600"
    end
    push_paths = []
    push_paths << ["/images/logo.svg", "image",""]
    push_paths.empty? ? {} : {headers["link"] => push_paths.map{|p| "<#{p[0]}>; rel=preload; as=#{p[1]} #{p[2]}"}.join("\n")
    [399, headers, []]
end
```
It will add the cache-control header of 1hr to all requests that end in .svg.

On my test site I have something similar and you can see that the cache-control header is delivered as part of the server push:

...
[  0.283] recv PUSH_PROMISE frame <length=52, flags=0x04, stream_id=13>
          ; END_HEADERS
          (padlen=0, promised_stream_id=2)
...
[  0.283] recv (stream_id=2) cache-control: max-age=31536000
...
[  0.284] recv (stream_id=2) x-http2-push: pushed
[  0.284] recv HEADERS frame <length=431, flags=0x04, stream_id=2>
          ; END_HEADERS
          (padlen=0)
          ; First push response header
...

**Comment by proyb6** [comment]
Didn't know I could write that way, but I couldn't solve the Google Pagespeed which still advice I should leverage browser cache even with your code.

**Comment by axelu** [comment]
I checked my site w/ gtmetrix and Google Pagespeed and it is not complaining about the pushed resource in regards to browser caching, but in my case it complains using browser caching for another resource (funny enough, its complaining about browser caching for GA script).  Are you sure it is complaining about your pushed resource? Did you expand it in Google Page speed to see exactly which resources it is complaining about? Did you check your returns with like nghttp client, like $ nghttp -nsv https://example.com? The latter will show you the headers it sent as part of the push - see my example.

**Comment by proyb6** [comment]
Sure, i have modified the code from .svg to .jpg and run nghttp:
```
          ; First push response header
[  0.074] recv (stream_id=13) :method: GET
[  0.074] recv (stream_id=13) :scheme: https
[  0.074] recv (stream_id=13) :authority: www.##############:9000
[  0.074] recv (stream_id=13) :path: /images/slide1.jpg
[  0.074] recv (stream_id=13) accept: */*
[  0.074] recv (stream_id=13) accept-encoding: gzip, deflate
[  0.074] recv (stream_id=13) user-agent: nghttp2/1.29.0
[  0.074] recv PUSH_PROMISE frame <length=28, flags=0x04, stream_id=13>
          ; END_HEADERS
          (padlen=0, promised_stream_id=6)
[  0.074] recv (stream_id=6) :status: 200
[  0.074] recv (stream_id=6) date: Mon, 12 Mar 2018 03:19:11 GMT
[  0.074] recv (stream_id=6) content-type: image/jpeg
[  0.074] recv (stream_id=6) last-modified: Sat, 27 Jan 2018 07:49:42 GMT
[  0.074] recv (stream_id=6) vary: accept-encoding
[  0.074] recv (stream_id=6) accept-ranges: bytes
[  0.074] recv (stream_id=6) strict-transport-security: max-age=15768000
[  0.074] recv (stream_id=6) referrer-policy: no-referrer
[  0.074] recv (stream_id=6) x-content-type-options: nosniff
[  0.074] recv (stream_id=6) cache-control: max-age=3600, public
[  0.074] recv (stream_id=6) x-frame-options: deny
[  0.074] recv (stream_id=6) x-xss-protection: 1; mode=block
[  0.074] recv (stream_id=6) x-http2-push: pushed
[  0.074] recv (stream_id=6) content-length: 41028
[  0.074] recv HEADERS frame <length=44, flags=0x04, stream_id=6>
          ; END_HEADERS
          (padlen=0)
```

**Comment by proyb6** [comment]
The ```/``` path in H2O.conf for serving HTML
The ```/images``` route in H2O.conf contains the pushed and max-age

**Comment by axelu** [comment]
So it shows the cache-control header being delivered as part of the push for your pushed resource.  Is Google Page speed still complaining about your pushed resource in regards to browser caching?

**Comment by utrenkner** [comment]
Maybe you could post the relevant parts of your h2o.conf, so that we get a better idea, of how things work together.  Like @axelu I do not see any problems with mixing push and browser caching, neither on webpagetest.org nor on GTmetrix.

Apart from this: In your original question you indicate cache times of 1h. Could it be that Google just thinks this is too short? ``We recommend a minimum cache time of one week and preferably up to one year for static assets, or assets that change infrequently. `` ([full recommendation here](https://developers.google.com/speed/docs/insights/LeverageBrowserCaching)).

**Comment by proyb6** [comment]
Sure, @utrenkner I tried the 307 reproxy you mentioned previous on ```/``` route.

```
      "/images":
        file.dir: /var/h2o/www/img

      "/testpage":
        mruby.handler: |
          Proc.new do |env|
            headers = {}
            if /\.jpg\z/.match(env["PATH_INFO"])
                headers["cache-control"] = "max-age=13600"
            end
            if /\.css\z/.match(env["PATH_INFO"])
                headers["cache-control"] = "max-age=13600"
            end
            push_paths = []
            push_paths << ["/css/t.css", "style",""]
            push_paths << ["/images/slide.jpg", "image",""]
            push_paths.empty? ? {} : {headers["link"] => push_paths.map{|p| "<#{p[0]}>; rel=preload; as=#{p[1]} #{p[2]}"}.join("\n")}
            [399, headers, []]
          end
        file.dir: /var/h2o/www/testpage

      "/":     
        mruby.handler: |
          proc {|env|
            [307, {"x-reproxy-url" => "https://www.###:9000/testpage/" + env["PATH_INFO"]}, []]
          }
        file.dir: /var/h2o/www

```

**Comment by proyb6** [comment]
To make it clear example, I found one will push and the other configuration with header will not push:

Will push css asset:
```
      "/p":
        mruby.handler: |
          Proc.new do |env|
            push_paths = []
            push_paths << ["/css/t.css", "style",""]
            [399, push_paths.empty? ? {} : {"link" => push_paths.map{|p| "<#{p[0]}>; rel=preload; as=#{p[1]} #{p[2]}"}.join("\n")}, []]
          end
        file.file: /var/h2o/www/testpage/p.html

```

Will not push css asset:
```
      "/p":
        mruby.handler: |
          Proc.new do |env|
            headers = {}
            if /\.css\z/.match(env["PATH_INFO"])
                headers["cache-control"] = "max-age=13600"
            end
            push_paths = []
            push_paths << ["/css/t.css", "style",""]
            push_paths.empty? ? {} : {headers["link"] => push_paths.map{|p| "<#{p[0]}>; rel=preload; as=#{p[1]} #{p[2]}"}.join("\n")}
            [399, headers, []]
          end
        file.file: /var/h2o/www/testpage/p.html
```

Will not push css asset as well:
```
      "/p":
        mruby.handler: |
          Proc.new do |env|
            headers = {}
            headers["cache-control"] = "max-age=13600"
            push_paths = []
            push_paths << ["/css/t.css", "style",""]
            push_paths.empty? ? {} : {headers["link"] => push_paths.map{|p| "<#{p[0]}>; rel=preload; as=#{p[1]} #{p[2]}"}.join("\n")}
            [399, headers, []]
          end
        file.file: /var/h2o/www/testpage/p.html

```

**Comment by utrenkner** [comment]
Thank you for the config.

What you are doing: You set the cache-control header for resources under ``/testpage``. But you want to add it to resources under ``/images``. It does not matter, from where the push is initiated, but where the resource actually resided.

You have to add the cache-control parts to the config of path ``/images``. That should do the trick.

**Comment by utrenkner** [comment]
The second example suffers from a similar problem: When should the source be triggered? When ``/p.html`` is requested. Then ``/p.html``should be delivered and certain stylesheets pushed along with it. Thus you need to apply the push-configuration to the path ``"/p.html"`` (or to ``"/p.html"`` and there match for the ``p.html`` file to apply the push directive.

**Comment by proyb6** [comment]
@utrenkner Finally, thanks! Yes, that's apply on ```/images``` is indeed did the trick!
