### ISSUE TITLE
Is H2O::TCPSocket implement?

### ISSUE THREAD

**Issue by proyb6** [h2o/h2o#1701]
I have been reading one of Kazuho's slides which some code seem to be implemented?
```
      "/nb":
       mruby.handler: |
          proc {|env|
            s = H2O::TCPSocket.connect(example.com, 80)
            s.write(["GET / HTTP/1.1", "Host: 127.0.0.1", "Connection: close", "\r\n"].join("\r\n"))
            c = s.read
            [200, {}, [c]]
          }
```

I had found an interesting slides 53 (h2oxmruby-170308163718) and perhaps confuse words to me. @i110 What does ```クソアプリ``` mean in English?

**Comment by i110** [comment]
@proyb6 Sorry for my belated response. It's node my slide and it mentioned https://github.com/h2o/h2o/pull/1686

> What does クソアプリ mean in English?

An app for the birds :D
