### ISSUE TITLE
add headers

### ISSUE THREAD

**Issue by lifeofguenter** [h2o/h2o#172]
would be cool to get some support for custom headers like:

* Expires
* Cache-Control
* Pragma

Also is something like gzipping planned? Or is that not anymore done with HTTP2?

**Comment by kazuho** [comment]
@lifeofguenter Thank you for the suggestion.

At the moment, H2O supports adding `Cache-Control` header through the expire handler (see [Result of `h2o --help` (version 1.0.0)](https://gist.github.com/kazuho/f15b79211ea76f1bf6e5#file-gistfile1-txt-L89)).

Is your case that you would want to add headers to prevent the client from caching content that are served statically (i.e. not through the proxy module of H2O)?  I am positive on introducing a generic configuration directive for adding headers, I would like to understand why you would want to add the headers you mentioned.

> Also is something like gzipping planned? Or is that not anymore done with HTTP2?

H2O is capable of sending `.gz` files in place of the non-compressed versions.  Please search for `.gz` within the list of directives (linked above).  We might add support for on-the-fly compression (relates to #139).

**Comment by lifeofguenter** [comment]
thanks @kazuho for the guidance! I do not know why I was not able to figure that out by myself - sorry.

This is all perfect - pragma is http/1.0 - so not really important anymore.
