### ISSUE TITLE
Issue with certification name mismatch

### ISSUE THREAD

**Issue by proyb6** [h2o/h2o#1729]
I have a strange issue with SSL certs generated by LetsEncrypt. Clear cache still persist.

When I keep reload the page, it will appear normal and sometime it will appear ```certificate name mismatch```

Trace the error log that load index.html content in www
```[lib/core/proxy.c] in request:/www/:certificate name mismatch```

On Ubuntu 16.04 and OpenSSL 1.1.0H latest, the content is static page serving direct from H2O file.dir, not proxy but I have enabled proxy for other URL routes.

**Comment by proyb6** [comment]
Closed, sorry, it's the problem with redirect using IP address that cause false alarm.

**Comment by cbrassel** [comment]
Sorry to re-open this topic, but I have juste done a fresh installation of h2o for testing and I have the same random error message : [lib/core/proxy.c] in request:/:certificate name mismatch
# h2o -v
h2o version 2.2.4
OpenSSL: OpenSSL 1.1.0g  2 Nov 2017
mruby: YES
Ubuntu 18.04.1 LTS

cat /etc/h2o/h2o.conf
server-name: "h2o (Debian)"
user: debian-h2o
access-log: "|rotatelogs -l -f -L /var/log/h2o/access.log -p /usr/share/h2o/compress_logs /var/log/h2o/access.log.%Y-%m-%d 86400"
error-log: "|rotatelogs -l -f -L /var/log/h2o/error.log -p /usr/share/h2o/compress_logs /var/log/h2o/error.log.%Y-%m-%d 86400"
pid-file: /run/h2o.pid

listen:
  host: 172.18.0.95
  port: 443
  ssl:
    key-file: /etc/ssl/wildcard/privkey.pem
    certificate-file: /etc/ssl/wildcard/h2o.pem

hosts:
  default:
    paths:
      "/":
        proxy.reverse.url: https://172.18.0.51/
        proxy.preserve-host: ON    # to not rewrite the incoming host:port
