### ISSUE TITLE
H2O.ai == H2O ?

### ISSUE THREAD

**Issue by simseyoung** [h2o/h2o#1736]
Is H2O and H2O.ai the same web server? Can I use H2O.ai as a web server? I am confused. Please let me know.

**Comment by csmk** [comment]
> Can I use H2O.ai as a web server?

Not at all. They are unrelated projects.

https://github.com/h2oai != https://github.com/h2o

**Comment by proyb6** [comment]
Nope, AI is for machines learning, This repo is for web server like  Nginx
