### ISSUE TITLE
LOG file lose write access

### ISSUE THREAD

**Issue by proyb6** [h2o/h2o#1742]
I found if I edit /var/log/h2o_access.log and /var/log/h2o_error.log and save the changes, reload the website, it does not append new entries to the log file anymore until I have rerun H2O. I believe it shouldn't lose the write access to the log file?

See my latest question below.

**Comment by utrenkner** [comment]
There is a good reason for this, as @kazuho [explained here](https://github.com/h2o/h2o/issues/1510#issuecomment-350140654).

**Comment by proyb6** [comment]
Do H2O support USR1 signal which is use to reopen log file? Nginx has this implemented.

**Comment by csmk** [comment]
I think you should use `SIGHUP`, see #1082 for more info. Something like [this](https://github.com/gentoo/gentoo/blob/master/www-servers/h2o/files/h2o.logrotate#L6).
