### ISSUE TITLE
Cast column int to real

### ISSUE THREAD

**Issue by dangchienhsgs** [h2o/h2o#1752]
I have 2 similar dataframes,  one has a column name X with type int, the other has column name X with type real. I can not concat or rbind it because Error: "h2o.exceptions.H2OValueError: Column names and types must match for rbind() to work"

How to deal with it ?

**Comment by csmk** [comment]
> How to deal with it ?

This repository is for the HTTP server. This might be the project you're looking for: https://github.com/h2oai/h2o-3
