### ISSUE TITLE
Redirecting wildcard HTTP requests to HTTPS

### ISSUE THREAD

**Issue by injust** [h2o/h2o#1760]
My H2O configuration listens to `*.domain.tld:80` and `*.domain.tld:443`.
Besides setting up a redirect for each subdomain, is it possible to redirect all HTTP requests to their HTTPS equivalents, while preserving the subdomain? Currently, it seems that H2O only supports redirects to an absolute URL.

I'm migrating a configuration from nginx, in which you can do something like this:
```
server {
	listen 80;
	server_name *.domain.tld;
	return 308 https://$host$request_uri;
}
```

**Comment by proyb6** [comment]
It's possible to redirect, I just saw a useful tip in Qiita.

https://www.vultr.com/docs/install-the-h2o-web-server-on-centos-7

https://qiita.com/oppara/items/4685c6d116ef2e16f6f5

**Comment by injust** [comment]
But that redirects `http://*.oppara.tv` to `https://oppara.tv`, stripping away the subdomain. Unless I'm incorrectly interpreting the configuration?

**Comment by proyb6** [comment]
You can apply reproxy and use mruby to redirect which is similar to HTTP 308.
https://h2o.examp1e.net/configure/reproxy_directives.html

```
    mruby.handler: |
        Proc.new do |env|
          if /..hostname.../.match(env["HTTP_HOST"])
          [307, {"x-reproxy-url" => env["HTTP_HOST"]}, []]
          elsif /..hostname.../.match(env["HTTP_HOST"])
          [307, {"x-reproxy-url" => env["HTTP_HOST"]}, []]
          end
        end
```

You will still need to define each absolute path:
```
"subdomain1.domain.tld:80":
...
"subdomain1.domain.tld:443":
...
```

**Comment by injust** [comment]
What if I have a wildcard configuration that I want to support? Is that not possible with H2O?
That seems like a major disappointment.

**Comment by injust** [comment]
cc @kazuho
Is lack of wildcard redirects intended by design? It's disappointing that I have to do this in mruby, because nginx makes this awfully simple.

Right now I'm doing something like:
```ruby
hosts:
    "*.domain.tld:80":
        paths:
            /:
                mruby.handler: |
                    Proc.new do |env|
                        [308, {'Location' => "https://#{env['HTTP_HOST']}#{env['PATH_INFO']}#{'?' unless env['QUERY_STRING'].empty?}#{env['QUERY_STRING']}"}, []]
                    end
```

**Comment by ksaltik** [comment]
In nginx 
server {
	listen 80;
	server_name *.domain.tld;
	return 308 https://$host$request_uri;
}

İn H2o 
hosts:
    "*.domain.tld:80":
        paths:
            /:
                mruby.handler: |
                    Proc.new do |env|
                        [308, {'Location' => "https://#{env['HTTP_HOST']}#{env['PATH_INFO']}#{'?' unless env['QUERY_STRING'].empty?}#{env['QUERY_STRING']}"}, []]
                    end

I wonder what is the performance impact of those scripts in configuration files in every request will this ruby scripts will handled......

H2o web server tries to save Ruby.....Ok maybe you are Japanese but software don't have nationality and every one tries to make things simple. Even nginx release the nginx unit to simplify things.....

H2o server is good to use for special cases.......Not for popular CMS CRM e-commerce systems.....It is an advanced thing for advanced people......

**Comment by dch** [comment]
@ksaltik I've amended your 4 comments on recent issues to focus on the technical aspects of the project. Please keep this in mind for future contributions.

**Comment by paulmenzel** [comment]
I am having the same issue. Any suggestions, if the solution is the recommended way to do this in h2o?

**Comment by i110** [comment]
I hope https://github.com/h2o/h2o/pull/2186 will be of some help.
