### ISSUE TITLE
Avoid Wget from mirror all website resources in H2O

### ISSUE THREAD

**Issue by proyb6** [h2o/h2o#1762]
Beside H2O, I wonder if you have a strategy to prevent wget from download all of my sites and assets?

**Comment by csmk** [comment]
Using [ACL](https://h2o.examp1e.net/configure/access_control.html) to match the user-agent:

```
paths:
  "/":
    mruby.handler: |
      acl {
        allow { addr == "127.0.0.1" }
        deny { user_agent.match(/wget/i) && ! addr.start_with?("192.168.") }
      }
    file.dir: /path/to/doc_root
```

Or using the "[DoS Detector](https://h2o.examp1e.net/configure/dos_detection.html)". IMO, matching the user-agent isn't very effective, so I recommend that you stick with the second option.

**Comment by proyb6** [comment]
@csmk I think the DoS detector could work in complement with ACL. Thanks.
