### ISSUE TITLE
Why doesn't h20 forwards Early hint headers to client (bowser)

### ISSUE THREAD

**Issue by rohanpujaris** [h2o/h2o#1771]
When h20 is used as a reverse proxy with puma and puma send 103 early hint response, why isn't it forwarder to client(browser)

I am not sure if this is the right place for this question. This issues can be closed, if it isn't.

**Comment by i110** [comment]
Just recently https://github.com/h2o/h2o/pull/1727 gets merged, you can forward 103 from upstream. In the default behavior, h2o forward 103 responses only to http2 clients, but not to http1 clients. If you like to do that for h1 too, do the following:

```
send-informational: all
```

**Comment by rohanpujaris** [comment]
Thanks for the information @i110.
