### ISSUE TITLE
Out of range in H2O Master

### ISSUE THREAD

**Issue by proyb6** [h2o/h2o#1830]
I use @volyrique configuration and benchmark to find an out of range error.

```
https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Ruby/h2o_mruby/h2o.conf

wrk -t 1 -c  100 -d 5 http://abcdefg.com:8011/plaintext
```

```
Error appear twice:
[h2o_mruby] in request:/plaintext:mruby raised: RuntimeError: status returned from rack app is out of range```

Might be applicable to master branch?

**Comment by proyb6** [comment]
Sorry, to add more details if this may help

Ubuntu 16.04 with latest patches
1 core CPU
1 GB memory

**Comment by i110** [comment]
After some trial and error, I succeeded in reproducing that bug. I'm not sure the root cause of this, but I guess it's from mruby GC's bug. I'll continue to pursue the issue and keep you updated.

**Comment by proyb6** [comment]
@i110 Sorry, I have realised I read the Changes file wrongly assume it's H2O 2.3 Beta-1 after git clone, it's exactly from Master branch (d890ee7cd01e5a3e4287d77c9e1743aa9dfeaa28) and glad you found the issue.
