### ISSUE TITLE
file.send-gzip - Automatic or manual compression?

### ISSUE THREAD

**Issue by Matviy** [h2o/h2o#184]
I manually compress my static files (index.html -> index.gz) and serve the saved .gz versions. The current --help says:

file.send-gzip: [ghp]
whether or not to send .gz variants if possible (ON or OFF, default: OFF) 

Which makes it sound like h2o will search for a manually compressed .gz version of the requested file in the requested file's directory. This would be perfect for what i need, but i suspect that this isn't  how it works, and h2o is just automatically compressing requested files.

Am I correct? How does this work?

EDIT: I'm checking the source and it seems like it is actually searching for a .gz variant, which is a great feature. Most webservers required rewriterules to get this working, and manually setting content-encoding headers.

I was confused for a bit because my file was index.gz while h2o was searching for index.html.gz, but i got it working now.

Great!

**Comment by kazuho** [comment]
:+1:
