### ISSUE TITLE
mruby plans

### ISSUE THREAD

**Issue by schmurfy** [h2o/h2o#1881]
(This is not an issue but I don't know where to ask)

What are the plans for mruby, one thing I would like to use h2o for is an api server which means it would need to:
- query a database (mysql, postgresql, redis)
- possibly query another http server

Are there any plan/will to add a network api to the embedded mruby, I have not checked too much at h2o internals but there are two options I see:
- using the internal h2o event loop if there is one for mruby too
- spawn the mruby handlers in a forked process and use some kind of channel between the h2o core and the handlers

I could also contribute to go into this direction but I need to know what you currently want to do with h2o, for me mruby in h2o is currently more a nice toy than anything else, as is I don't really have much use fo it.

**Comment by utrenkner** [comment]
>     * query a database (mysql, postgresql, redis)
Support for (Hi)Redis is already built in, see this issue thread #1152 
 
>     * possibly query another http server
You can use h2o's http_request call for this. The [documentation](https://h2o.examp1e.net/configure/mruby.html) says
```
Starting from version 1.7, a HTTP client API is provided. HTTP requests issued through the API will be handled asynchronously; the client does not block the event loop of the HTTP server. 
```

**Comment by schmurfy** [comment]
nice !
sorry I missed that but that is great news :)
