### ISSUE TITLE
How to identify reproxy-request?

### ISSUE THREAD

**Issue by utrenkner** [h2o/h2o#1889]
I use the [reproxy directive](https://h2o.examp1e.net/configure/reproxy_directives.html) to deliver cached (static) files.

However, I would like to block direct GET-access to the cached files. Files should only be delivered through reproxy. Is there an easy way to identify requests that came through reproxy? The env looks exactly the same as when directly GET'ing the file. One option would be to add a secret QUERY_STRING to the reproxy request and check for its existence. 

Is there a better (more direct, more elegant) solution?

**Comment by myfreeweb** [comment]
Relies on knowing the configured max delegations (default 5):

```ruby
            lambda do |env|
              if env["h2o.remaining_delegations"] == 5
                return [401, {}, ["Where do you think you're going??"]]
              end
              return [399, {}, []]
            end
```

but it would be great if there was a way to just mark a path as reproxy-only (internal) without mruby :)

**Comment by utrenkner** [comment]
This is a nice way of solving the problem. Thanks, @myfreeweb !
