### ISSUE TITLE
complie failed, error undefined reference to `h2o_timer_link'

### ISSUE THREAD

**Issue by owhao** [h2o/h2o#1897]
Makefile:
`PROGNAME   = http1client

OBJFILES   = deps/h2o/examples/libh2o/http1client.c
INCFILES   =

CFLAGS_GEN = -Wall -funsigned-char -g -ggdb \
             -I/usr/local/include/ \
             -I/opt/local/include/ \
             -I/usr/local/opt/openssl/include/ \
             -DH2O_USE_LIBUV=1 \
             $(CFLAGS)

CFLAGS_DBG = -DDEBUG=1 \
             $(CFLAGS_GEN)

CFLAGS_OPT =  -O3 -Wno-format $(CFLAGS_GEN)

LDFLAGS   += -L/usr/local/lib/ \
             -L/opt/local/lib/ \
             -L/usr/local/opt/openssl/lib/

LIBS      += -lh2o-evloop -luv -lz -lssl -lcrypto -lpthread

all: $(PROGNAME)

$(PROGNAME): $(OBJFILES) $(INCFILES)
	$(CC) $(LDFLAGS) -o $(PROGNAME) \
        $(CFLAGS_OPT) $(OBJFILES) $(LIBS)
	@echo
	@echo "release complied."
	@echo

debug: $(OBJFILES) $(INCFILES)
	$(CC) $(LDFLAGS) -o $(PROGNAME) \
        $(CFLAGS_DBG) $(OBJFILES) $(LIBS)
	@echo
	@echo "debug complied."
	@echo

clean:
	rm -f $(PROGNAME) *.exe *.o *~ a.out core core.[1-9][0-9]* *.stackdump
	rm -rf $(PROGNAME).dSYM`

make output:
`cc -L/usr/local/lib/ -L/opt/local/lib/ -L/usr/local/opt/openssl/lib/ -o http1client \
        -O3 -Wno-format -Wall -funsigned-char -g -ggdb -I/usr/local/include/ -I/opt/local/include/ -I/usr/local/opt/openssl/include/ -DH2O_USE_LIBUV=1  deps/h2o/examples/libh2o/http1client.c -lh2o-evloop -luv -lz -lssl -lcrypto -lpthread
deps/h2o/examples/libh2o/http1client.c: In function ‘start_request’:
deps/h2o/examples/libh2o/http1client.c:75:9: warning: ‘TLSv1_client_method’ is deprecated [-Wdeprecated-declarations]
         SSL_CTX *ssl_ctx = SSL_CTX_new(TLSv1_client_method());
         ^~~~~~~
In file included from /usr/include/openssl/ct.h:13:0,
                 from /usr/include/openssl/ssl.h:61,
                 from /usr/local/include/h2o.h:38,
                 from deps/h2o/examples/libh2o/http1client.c:25:
/usr/include/openssl/ssl.h:1626:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_client_method(void)) /* TLSv1.0 */
 ^
/tmp/ccpgZIht.o: In function `on_connect':
/deps/h2o/examples/libh2o/http1client.c:202: undefined reference to `h2o_timer_link'
/tmp/ccpgZIht.o: In function `timeout_cb':
/deps/h2o/examples/libh2o/http1client.c:154: undefined reference to `h2o_timer_unlink'
/tmp/ccpgZIht.o: In function `proceed_request':
/deps/h2o/examples/libh2o/http1client.c:169: undefined reference to `h2o_timer_link'
collect2: error: ld returned 1 exit status
Makefile:27: recipe for target 'http1client' failed
make: *** [http1client] Error 1`

why? could you give me some help?

**Comment by kazuho** [comment]
> LIBS += -lh2o-evloop -luv -lz -lssl -lcrypto -lpthread

libh2o-evloop is the one that uses evloop - our own event loop.

You have `H2O_USE_LIBUV` and `-libuv` set, therefore I assume that you are trying to use libh2o with libuv. If that is the case, you should use libh2o (without the `-evloop` suffix).

**Comment by owhao** [comment]
> > LIBS += -lh2o-evloop -luv -lz -lssl -lcrypto -lpthread
> 
> libh2o-evloop is the one that uses evloop - our own event loop.
> 
> You have `H2O_USE_LIBUV` and `-libuv` set, therefore I assume that you are trying to use libh2o with libuv. If that is the case, you should use libh2o (without the `-evloop` suffix).

Than you, I solved my problem.
```
cmake .
make libh2o
```
Makefiles
```
LIBS += -lh2o -luv -lz -lssl -lcrypto -lpthread
```
