### ISSUE TITLE
h2o mangling location header when acting as reverse proxy

### ISSUE THREAD

**Issue by Lukasa** [h2o/h2o#190]
[http2bin.org](https://http2bin.org/) is a Python HTTP/1.1 webapp running behind a h2o reverse proxy. This all works really well, except weirdly for the location header. This can be observed by hitting this URL: `https://http2bin.org/cookies/set?k1=v1&k2=v2`. This returns a location header that is total garbage. That's a little unexpected, because the same code running on `httpbin.org` generates the correct response.

I can get more detail out of the code later today when I have access to the server that's running, but I wanted to raise this issue now.

**Comment by tatsuhiro-t** [comment]
FYI, https://nghttp2.org/httpbin running same code and works fine with that URI.

**Comment by kazuho** [comment]
@Lukasa Thank you for reporting the issue, and thank you for running http2bin.org!

I think I have fixed the issue in the commit above.  Would you mind testing?  I was unable to write a reliable test (as this involves a timing issue).

The case was that H2O was not creating a copy of the location header if it contained relative URI even though it should.

**Comment by Lukasa** [comment]
I'd love to test. Note that I probably won't be able to for about 24 hours, for boring reasons to do with my day job, but I'll report back when I know.

As to whether the relative URI use is intentional: yes, it is. As you point out, many webapps have been doing this for a long time. The python requests library (which I'm a core developer of) has had support for relative redirects since 2011, so we've believed it to be important for at least four years.

Interop testing with http2bin.org is highly encouraged, as well as testing with nghttp2.org/httpbin. The more people fronting up httpbin the better, frankly. =)

**Comment by Lukasa** [comment]
Oh, and it's my pleasure to run http2bin.org! Thankyou for your thanks. =)

**Comment by Lukasa** [comment]
That *appears* to work. http2bin is running revision 93d87443f8ee34768fbf89504d8ffd93aac4ead7 of h2o and I've not yet seen the location header be incorrectly rendered. I'd like to see @tatsuhiro-t try on his end as well, given that he found it first.

However, I tentatively think this is working acceptably.

**Comment by kazuho** [comment]
@Lukasa Thank you for checking,and thanks to @tatsuhiro-t for nociting the issue.

FYI the reason why corrupt header seemed to always become `Location: ref="/coo` is as follows as I believe:

1. upstream server sends all headers in a single packet
2. the reverse proxy module of H2O reads the headers into buffer and handles them, but does not duplicate the value of the `Location` header
3. http1client (part of H2O) returns the memory allocated for the buffer to the associated memory pool
4. meanwhile the server sends the response body
5. reverse proxy module allocates memory for the input buffer (which is reused from the memory pool), and reads the body into itr
6. reverse proxy modules issues a send request (by calling `h2o_send`) to the protocol handler
7. the protocol handler flattens the response (at this time, the pointer to the `Location` header points to somewhere within the response body sent by the upstream server, and in this case, it was part of `<a href="/cookies">` within the HTML)

> As to whether the relative URI use is intentional: yes, it is. As you point out, many webapps have been doing this for a long time. The python requests library (which I'm a core developer of) has had support for relative redirects since 2011, so we've believed it to be important for at least four years.

Understood.  Thank you for the explanation.

**Comment by tatsuhiro-t** [comment]
I confirm that it works fine now.

**Comment by Lukasa** [comment]
Let's call this fixed then. Thanks @kazuho!

**Comment by kazuho** [comment]
@tatsuhiro-t Thank you for finding the bug and for the confirmation!
