### ISSUE TITLE
Example for maximum performance of hello world via http protocol

### ISSUE THREAD

**Issue by jobs-git** [h2o/h2o#1900]
What is an example code for a simple hello world via http protocol

**Comment by volyrique** [comment]
The `plaintext()` handler function [here](https://github.com/TechEmpower/FrameworkBenchmarks/blob/dd81534722b68fa04286c1584b3f7a6f2ac71752/frameworks/C/h2o/src/request_handler.c#L79) does the job (full disclosure - I implemented it). It is mostly self-contained (well, it needs `libh2o` obviously), and the few other functions it depends on should be in the same file. Finally, you can look at the existing [simple example](https://github.com/h2o/h2o/blob/master/examples/libh2o/simple.c) to understand how to set up a listener.

**Comment by jobs-git** [comment]
Yes, thanks for implementing it! I forgot to close this while I was studying your code. I found a bottleneck while trying to send a larger plaintext, I noticed that as the payload increases the number of `request/s` decreases even on localhost. My suspicion was an absence of `zero-copy send` implementation in libh2o, but I am not exactly sure.
