### ISSUE TITLE
[question] confusion on "0\r\n" in `on_send_request`.

### ISSUE THREAD

**Issue by meritozh** [h2o/h2o#1920]
Code is:

https://github.com/h2o/h2o/blob/0189d67c3d8ba87abdc69d610b1879a9ce51811f/lib/common/http1client.c#L389

`\r\n` is EOL, but what is `0`? Or it is a typo?

**Comment by zlm2012** [comment]
It should mean that it is the end of the chunked body.

FYI https://tools.ietf.org/html/rfc7230#section-4.1 See the `last-chunk` part.

**Comment by meritozh** [comment]
Thx, learned new knowledge
