### ISSUE TITLE
[question] How to understand h2o_httpclient_connection_pool_t?

### ISSUE THREAD

**Issue by meritozh** [h2o/h2o#1926]
`h2o_httpclient_connection_pool_t` has member `sockpool` and `http2.conns`.

For HTTP/1.x, logic about reusing underlying socket is in `h2o_socketpool_connect`, the `_shared.sockets`. But for HTTP/2, reusing connection is just `connpool->http2.conns.next` in `h2o_httpclient_connect`? The question is:

1. Why it just access the first meaningful element of `http2.conns`? No loop?
2. `http2.conns` represent several HTTP/2 streams on one underlying socket? But how it know the `http2.conns.next` can be reuse for current new come-in request (I mean it needn't check url/host) when I call `h2o_httpclient_connect`?
3. For many HTTP request, I must malloc httpclient for each request? The socketpool can be shared because I can initialize it by `h2o_socketpool_init_global`. Can I reuse `connpool`? If can, how?
4. What's the best way to manage many HTTP requests? I don't want malloc many objects for each request.

Thank you.

**Comment by chenbd** [comment]
I'm not quit understand http2, about your question, `http2.conns` is the list head of all `h2o_httpclient__h2_conn_t` which contains underlying `sock`. so `http2.conns.next` is the first `h2o_httpclient__h2_conn_t` in the list.

> For many HTTP request, I must malloc httpclient for each request? The socketpool can be shared because I can initialize it by h2o_socketpool_init_global. Can I reuse connpool? If can, how?

`httclient` is managed by libh2o, you should **NOT** malloc for it. guess connpool is only used by http2

> What's the best way to manage many HTTP requests? I don't want malloc many objects for each request.

you are talking about httpclient?

**Comment by i110** [comment]
> Why it just access the first meaningful element of http2.conns? No loop?

`connpool->http2.conns` is sorted linked list in ascending order of the number of active (in-flight) streams.

> http2.conns represent several HTTP/2 streams on one underlying socket? But how it know the http2.conns.next can be reuse for current new come-in request (I mean it needn't check url/host) when I call h2o_httpclient_connect?

http2.conns represent several HTTP/2 **connections**. `h2o_httpclient_connection_pool_t` is dedicated for one host/port/is_ssl triplet, so we can reuse it.

> For many HTTP request, I must malloc httpclient for each request?

Currently, yes.

> The socketpool can be shared because I can initialize it by h2o_socketpool_init_global. Can I reuse connpool? If can, how?

yes you can reuse `h2o_httpclient_connection_pool_t` by passing the connpool you want to reuse to 
 `h2o_httpclient_connect`.

> What's the best way to manage many HTTP requests? I don't want malloc many objects for each request.

Actually is it your bottleneck? I think we can rewrite our code to avoid allocations per each request (or at least use `h2o_mem_pool` for faster allocation), but before doing that I want to ensure that it's a real problem.

> Seems I cannot use libh2o as a generic HTTP client directly, because it is designed for h2o's reverse proxy functionality.

Why did you feel so?

**Comment by meritozh** [comment]
@i110 Thanks for your reply.

> http2.conns represent several HTTP/2 connections. h2o_httpclient_connection_pool_t is dedicated for one host/port/is_ssl triplet, so we can reuse it.

So many streams transfer on one HTTP/2 connection. Where is the "dedicated" code? Sorry, I don't find it.

> yes you can reuse h2o_httpclient_connection_pool_t by passing the connpool you want to reuse to
h2o_httpclient_connect.

If I reuse this, I need call `lookup_target` on connpool?

> Actually is it your bottleneck? I think we can rewrite our code to avoid allocations per each request (or at least use h2o_mem_pool for faster allocation), but before doing that I want to ensure that it's a real problem.

It's not my bottleneck, I just want it run faster.

> Why did you feel so?

If my understanding is right, the http client in h2o is designed for one single request.

In my case, I want do:

1. initialize all configs. start run event loop.
2. requests come in.
3. send requests.
4. handle respective responses.

The "client" in my case is a more generic concept, it is a manager. So I need wrap an additional layer, to manage event loop and req/res.

`h2o_httpclient_t` is "The endpoint that initiates an HTTP/2 connection. Clients send HTTP requests and receive HTTP responses." (copy from HTTP/2 specification).

So my true question is how to make the `h2o_httpclient_connection_pool_t` become more generic one, not be attached to `h2o_httpclient_t`.

Thanks again!

**Comment by i110** [comment]
> The "client" in my case is a more generic concept, it is a manager. So I need wrap an additional layer, to manage event loop and req/res.

I thinks it's a problem of wording. Please regard `h2o_httpclient_t` as `h2o_httprequest_t` or somethink like that and write your own multiple req/res manager. The only thing you're wondering is the httpclient allocation per each request I think, but I'm guessing it might not be a problem in ordinal systems. Anyway how about trying at first?

> So my true question is how to make the h2o_httpclient_connection_pool_t become more generic one, not be attached to h2o_httpclient_t.

`h2o_httpclient_connection_pool_t` is designed to be used with h2o_httpclient_t. You can use connpool without httpclient, but I don't think it's meaningful because almost all of it's functionalities are in httpclient imprementations. It's a mere wrapper struct that conveys some informations used by httpclient.

**Comment by meritozh** [comment]
@i110 Thanks again. I have tried, and it works as I expected. Close this issue.
