### ISSUE TITLE
Add header for Key Pinning

### ISSUE THREAD

**Issue by evmuc** [h2o/h2o#194]
Is it possible to add a configuration option for adding headers releated to public key pinning?
https://developer.mozilla.org/en-US/docs/Web/Security/Public_Key_Pinning

Also Strict Transport Security (HSTS) header would be perfect

**Comment by kazuho** [comment]
@evmuc 
> Is it possible to add a configuration option for adding headers releated to public key pinning?

Unfortunately not.  Please wait until #196 gets done.

**Comment by kazuho** [comment]
With the merger of PR #204 it is now possible to add any headers to the response.  For example, PKS header can be added by:

```
header.add 'Public-Key-Pins: pin-sha256="cUPcTAZWKaASuYWhhneDttWpY3oBAkE3h2+soZS7sWs="; pin-sha256="M8HztCzM3elUxkcjR2S5P4hhyBNf6lHkmjAHKhpGPWE="; max-age=5184000; includeSubdomains; report-uri="https://www.example.net/hpkp-report"
```

**Comment by evmuc** [comment]
works perfectly ... very cool job
