### ISSUE TITLE
libh2o simple example for doing async using evloop

### ISSUE THREAD

**Issue by jobs-git** [h2o/h2o#1954]

**Comment by volyrique** [comment]
It's not clear what you are asking for because the existing [simple example](https://github.com/h2o/h2o/blob/master/examples/libh2o/simple.c) is already working asynchronously.

**Comment by jobs-git** [comment]
i was expecting for `await`, I guess that was already built within evloop. Anyhow, I noticed that as payload increases libh2o `response/s` decreases even in localhost, does it not implement zero-copy send?

**Comment by volyrique** [comment]
Again, not sure what you mean by `await` - if you refer to [the async/await pattern](https://en.wikipedia.org/wiki/Async/await), generally speaking, it has no relevance to C.

I am not qualified to answer your second question, but bandwidth is always limited (even on localhost), so the behaviour you are describing seems to be the most natural thing to me.

**Comment by jobs-git** [comment]
I see, I will just look into it further. Thank you for clarifying things up! This can now be closed
