### ISSUE TITLE
Missing zero copy libh2o implementation

### ISSUE THREAD

**Issue by jobs-git** [h2o/h2o#1959]
When there is a 1MB data in libh2o the server performance  drops by about 15x. This is also in conjunction w/ high cpu usage indicating that data is being parsed by the cpu byte by byte instead of taking advantage of direct memory access.

I check h2o source and it appears that it uses a `non zero copy send` which means that h2o server might also be affected.

These are some discussions about zero copy

zero copy mmap ring buffer
http://yusufonlinux.blogspot.com/2010/11/data-link-access-and-zero-copy.html

zero copy send
https://lwn.net/Articles/726917/

zero copy recv
https://lwn.net/Articles/752188/

netmap
http://info.iet.unipi.it/~luigi/netmap/

splice
http://man7.org/linux/man-pages/man2/splice.2.html

@kazuho

**Comment by dch** [comment]
dupe https://github.com/h2o/h2o/issues/1950
