### ISSUE TITLE
mruby, how to send static file for all apple-touch-icon queries?

### ISSUE THREAD

**Issue by Tintinabula** [h2o/h2o#1964]
What is the proper mruby syntax to send the same static file to queries for apple-touch-icon* ?

For example, when a client asks for "/apple-touch-icon-precomposed.png" the server would send the static file "/apple-touch-icon.png" instead. This is not a redirection, but a substitution.

I tried the following syntax, but I believe the return line is wrong as a client receives the string "apple-touch-icon.png" instead of the file for apple-touch-icon* queries.

```
mruby.handler: |
    lambda do |env|
       if /\A(\/apple-touch-icon[\w\-]+\.png)\z/.match?(env["PATH_INFO"])
          return [200, {'content-type' => 'image/png'}, ["apple-touch-icon.png"]]
       end
       [399, {}, []]
    end
```

**Comment by TheDecryptor** [comment]
200 tells h2o that it's a normal response with a text body (As you've found), what you want to do instead is an internal redirect (Code 307), and set the custom `x-reproxy-url` header to the path of the file (relative to the site root) you want to serve.

```ruby
    lambda do |env|
        if /\A(\/apple-touch-icon[\w\-]+\.png)\z/.match?(env["PATH_INFO"])
            return [307, {"x-reproxy-url" => "/apple-touch-icon-base.png"}, []]
        end
        [399, {}, []]
    end
```

Something like that, I don't know regex enough to know if that'll match the base filename, so I changed it just in case.

**Comment by Tintinabula** [comment]
Excellent. Thank you very much.
