### ISSUE TITLE
mruby, how to check if the client Accept: header is defined?

### ISSUE THREAD

**Issue by Tintinabula** [h2o/h2o#1967]
Question: What is the recommended mruby function to check if the client side Accept header is defined ?

Purpose: The site provides server push support for clients who support the webp image format. The following mruby handler works correctly to push the "site_image.webp" to a client who includes the string "webp" in their client Accept: header. For clients who do not support webp, server push is ignored as designed.

```
mruby.handler: |
     Proc.new do |env|
        push_paths = []
        if (/(\/|\.html)\z/.match?(env["PATH_INFO"]) && env["HTTP_ACCEPT"].include?("webp"))
            push_paths << ["/site_image\.webp", "image"]
        end
        [399, push_paths.empty? ? {} : {"link" => push_paths.map{|p| "<#{p[0]}>; rel=preload; as=#{p[1]}"}.join("\n")}, []]
end
```

Problem: For older clients who do not define an Accept: header at all,  h2o will return a "500 Server Error" as the above mruby handler faults on the .include? check. What should happen is server push is ignored as if the client did not support webp.

Any suggestions how to check if the client Accept: header is defined?

I do not believe "defined?(env["HTTP_ACCEPT"])" works with mruby. I also tried "const_defined?(env["HTTP_ACCEPT"])" but I may have the syntax incorrect. 

Thanks for you time.

**Comment by utrenkner** [comment]
If I remember correctly I used something like this successfully:
```
if env["HTTP_COOKIE"]
  if env["HTTP_COOKIE"].match("SOMETHING")
    ...
  end
end
```
Have you tried this?

**Comment by Tintinabula** [comment]
Yes, adding an if statement for env["HTTP_ACCEPT"] solved the problem. Seems I was making the issue more complicated than it needed to be. Thanks again.

```
mruby.handler: |
  Proc.new do |env|
    push_paths = []
    if env["HTTP_ACCEPT"]
      if (/(\/|\.html)\z/.match?(env["PATH_INFO"]) && env["HTTP_ACCEPT"].include?("webp"))
        push_paths << ["/site_image\.webp", "image"]
      end
    end
    [399, push_paths.empty? ? {} : {"link" => push_paths.map{|p| "<#{p[0]}>; rel=preload; as=# p[1]}"}.join("\n")}, []]
  end
```

**Comment by utrenkner** [comment]
I am glad, _I_ could help _you_. Your site has helped me several times already... And I am glad to see you switched it back to h2o. So we can hope for more valuable tips on h2o there.
