### ISSUE TITLE
Error executing h2o - libyaml-0.so.2

### ISSUE THREAD

**Issue by theobarberbany** [h2o/h2o#198]
Hey, 

So I've tried reinstalling libyaml a bunch of times (from the instructions here http://pyyaml.org/wiki/LibYAML) and am still getting this error. The install/make of libyaml does not fail.

    h2o: error while loading shared libraries: libyaml-0.so.2: cannot open shared object file: No such file or directory

is the specific error, below is my install process.

root@theo:~/H2O# git clone https://github.com/h2o/h2o.git
Cloning into 'h2o'...
remote: Counting objects: 8555, done.
remote: Compressing objects: 100% (99/99), done.
remote: Total 8555 (delta 43), reused 0 (delta 0), pack-reused 8455
Receiving objects: 100% (8555/8555), 2.92 MiB | 825 KiB/s, done.
Resolving deltas: 100% (5590/5590), done.
root@theo:~/H2O# cd h2o/
root@theo:~/H2O/h2o# ls
Changes  cmake	CMakeLists.txt	deps  examples	h2o.xcodeproj  include	lib  LICENSE  misc  README.md  share  src  t
root@theo:~/H2O/h2o# cmake -DCMAKE_INSTALL_PREFIX=/usr/local .
-- The C compiler identification is GNU 4.7.2
-- The CXX compiler identification is GNU 4.7.2
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found.
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.1e")
-- Found LIBUV: /usr/local/lib/libuv.so
-- Found LIBYAML: /usr/local/lib/libyaml.so
-- Found WSLAY: /usr/local/lib/libwslay.so
-- Configuring done
-- Generating done
-- Build files have been written to: /root/H2O/h2o
root@theo:~/H2O/h2o# make
Scanning dependencies of target h2o
[  0%] Building C object CMakeFiles/h2o.dir/deps/picohttpparser/picohttpparser.c.o
[  2%] Building C object CMakeFiles/h2o.dir/lib/common/memory.c.o
[  4%] Building C object CMakeFiles/h2o.dir/lib/common/multithread.c.o
[  4%] Building C object CMakeFiles/h2o.dir/lib/common/http1client.c.o
[  6%] Building C object CMakeFiles/h2o.dir/lib/common/serverutil.c.o
[  8%] Building C object CMakeFiles/h2o.dir/lib/common/socket.c.o
[  8%] Building C object CMakeFiles/h2o.dir/lib/common/socketpool.c.o
[ 10%] Building C object CMakeFiles/h2o.dir/lib/common/string.c.o
[ 12%] Building C object CMakeFiles/h2o.dir/lib/common/time.c.o
[ 12%] Building C object CMakeFiles/h2o.dir/lib/common/timeout.c.o
[ 14%] Building C object CMakeFiles/h2o.dir/lib/common/url.c.o
[ 17%] Building C object CMakeFiles/h2o.dir/lib/core/config.c.o
[ 17%] Building C object CMakeFiles/h2o.dir/lib/core/configurator.c.o
[ 19%] Building C object CMakeFiles/h2o.dir/lib/core/context.c.o
[ 19%] Building C object CMakeFiles/h2o.dir/lib/core/headers.c.o
[ 21%] Building C object CMakeFiles/h2o.dir/lib/core/request.c.o
[ 23%] Building C object CMakeFiles/h2o.dir/lib/core/token.c.o
[ 23%] Building C object CMakeFiles/h2o.dir/lib/core/util.c.o
[ 25%] Building C object CMakeFiles/h2o.dir/lib/handler/access_log.c.o
[ 27%] Building C object CMakeFiles/h2o.dir/lib/handler/chunked.c.o
[ 27%] Building C object CMakeFiles/h2o.dir/lib/handler/expires.c.o
[ 29%] Building C object CMakeFiles/h2o.dir/lib/handler/file.c.o
[ 31%] Building C object CMakeFiles/h2o.dir/lib/handler/mimemap.c.o
[ 31%] Building C object CMakeFiles/h2o.dir/lib/handler/proxy.c.o
[ 34%] Building C object CMakeFiles/h2o.dir/lib/handler/redirect.c.o
[ 36%] Building C object CMakeFiles/h2o.dir/lib/handler/configurator/access_log.c.o
[ 36%] Building C object CMakeFiles/h2o.dir/lib/handler/configurator/expires.c.o
[ 38%] Building C object CMakeFiles/h2o.dir/lib/handler/configurator/file.c.o
[ 40%] Building C object CMakeFiles/h2o.dir/lib/handler/configurator/proxy.c.o
[ 40%] Building C object CMakeFiles/h2o.dir/lib/handler/configurator/redirect.c.o
[ 42%] Building C object CMakeFiles/h2o.dir/lib/http1.c.o
[ 44%] Building C object CMakeFiles/h2o.dir/lib/http2/connection.c.o
[ 44%] Building C object CMakeFiles/h2o.dir/lib/http2/frame.c.o
[ 46%] Building C object CMakeFiles/h2o.dir/lib/http2/hpack.c.o
[ 46%] Building C object CMakeFiles/h2o.dir/lib/http2/scheduler.c.o
[ 48%] Building C object CMakeFiles/h2o.dir/lib/http2/stream.c.o
[ 51%] Building C object CMakeFiles/h2o.dir/src/main.c.o
Linking C executable h2o
[ 51%] Built target h2o
Scanning dependencies of target libh2o
[ 51%] Building C object CMakeFiles/libh2o.dir/deps/picohttpparser/picohttpparser.c.o
[ 53%] Building C object CMakeFiles/libh2o.dir/lib/common/memory.c.o
[ 55%] Building C object CMakeFiles/libh2o.dir/lib/common/multithread.c.o
[ 55%] Building C object CMakeFiles/libh2o.dir/lib/common/http1client.c.o
[ 57%] Building C object CMakeFiles/libh2o.dir/lib/common/serverutil.c.o
[ 59%] Building C object CMakeFiles/libh2o.dir/lib/common/socket.c.o
[ 59%] Building C object CMakeFiles/libh2o.dir/lib/common/socketpool.c.o
[ 61%] Building C object CMakeFiles/libh2o.dir/lib/common/string.c.o
[ 63%] Building C object CMakeFiles/libh2o.dir/lib/common/time.c.o
[ 63%] Building C object CMakeFiles/libh2o.dir/lib/common/timeout.c.o
[ 65%] Building C object CMakeFiles/libh2o.dir/lib/common/url.c.o
[ 68%] Building C object CMakeFiles/libh2o.dir/lib/core/config.c.o
[ 68%] Building C object CMakeFiles/libh2o.dir/lib/core/configurator.c.o
[ 70%] Building C object CMakeFiles/libh2o.dir/lib/core/context.c.o
[ 72%] Building C object CMakeFiles/libh2o.dir/lib/core/headers.c.o
[ 72%] Building C object CMakeFiles/libh2o.dir/lib/core/request.c.o
[ 74%] Building C object CMakeFiles/libh2o.dir/lib/core/token.c.o
[ 74%] Building C object CMakeFiles/libh2o.dir/lib/core/util.c.o
[ 76%] Building C object CMakeFiles/libh2o.dir/lib/handler/access_log.c.o
[ 78%] Building C object CMakeFiles/libh2o.dir/lib/handler/chunked.c.o
[ 78%] Building C object CMakeFiles/libh2o.dir/lib/handler/expires.c.o
[ 80%] Building C object CMakeFiles/libh2o.dir/lib/handler/file.c.o
[ 82%] Building C object CMakeFiles/libh2o.dir/lib/handler/mimemap.c.o
[ 82%] Building C object CMakeFiles/libh2o.dir/lib/handler/proxy.c.o
[ 85%] Building C object CMakeFiles/libh2o.dir/lib/handler/redirect.c.o
[ 87%] Building C object CMakeFiles/libh2o.dir/lib/handler/configurator/access_log.c.o
[ 87%] Building C object CMakeFiles/libh2o.dir/lib/handler/configurator/expires.c.o
[ 89%] Building C object CMakeFiles/libh2o.dir/lib/handler/configurator/file.c.o
[ 91%] Building C object CMakeFiles/libh2o.dir/lib/handler/configurator/proxy.c.o
[ 91%] Building C object CMakeFiles/libh2o.dir/lib/handler/configurator/redirect.c.o
[ 93%] Building C object CMakeFiles/libh2o.dir/lib/http1.c.o
[ 95%] Building C object CMakeFiles/libh2o.dir/lib/http2/connection.c.o
[ 95%] Building C object CMakeFiles/libh2o.dir/lib/http2/frame.c.o
[ 97%] Building C object CMakeFiles/libh2o.dir/lib/http2/hpack.c.o
[100%] Building C object CMakeFiles/libh2o.dir/lib/http2/scheduler.c.o
[100%] Building C object CMakeFiles/libh2o.dir/lib/http2/stream.c.o
Linking C static library libh2o.a
[100%] Built target libh2o
root@theo:~/H2O/h2o# sudo make install
[ 51%] Built target h2o
[100%] Built target libh2o
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/bin/h2o
-- Removed runtime path from "/usr/local/bin/h2o"
-- Installing: /usr/local/lib/libh2o.a
-- Installing: /usr/local/include
-- Installing: /usr/local/include/h2o.h
-- Installing: /usr/local/include/h2o
-- Installing: /usr/local/include/h2o/http2.h
-- Installing: /usr/local/include/h2o/time_.h
-- Installing: /usr/local/include/h2o/linklist.h
-- Installing: /usr/local/include/h2o/multithread.h
-- Installing: /usr/local/include/h2o/socket
-- Installing: /usr/local/include/h2o/socket/evloop.h
-- Installing: /usr/local/include/h2o/socket/uv-binding.h
-- Installing: /usr/local/include/h2o/socket.h
-- Installing: /usr/local/include/h2o/http2_scheduler.h
-- Installing: /usr/local/include/h2o/token.h
-- Installing: /usr/local/include/h2o/string_.h
-- Installing: /usr/local/include/h2o/websocket.h
-- Installing: /usr/local/include/h2o/url.h
-- Installing: /usr/local/include/h2o/memory.h
-- Installing: /usr/local/include/h2o/http1.h
-- Installing: /usr/local/include/h2o/serverutil.h
 -- Installing: /usr/local/include/h2o/configurator.h
-- Installing: /usr/local/include/h2o/http2_internal.h
-- Installing: /usr/local/include/h2o/socketpool.h
-- Installing: /usr/local/include/h2o/version.h
-- Installing: /usr/local/include/h2o/http1client.h
-- Installing: /usr/local/include/h2o/timeout.h
-- Installing: /usr/local/share/h2o/fetch-ocsp-response
root@theo:~/H2O/h2o# h2o -c examples/h2o/h2o.conf
h2o: error while loading shared libraries: libyaml-0.so.2: cannot open shared object file: No such file or     directory

**Comment by kazuho** [comment]
Seems like that the shared libraries installed under `/usr/local/lib` are not recognized by the runtime linker.

There are several ways to let them get used; reading http://stackoverflow.com/a/17892806/3269811 might help.

**Comment by theobarberbany** [comment]
Thanks! Useful link!

    export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib" 

running the above command was what fixed it for me. (for reference)

**Comment by kazuho** [comment]
We will no longer have this kind of issue; libyaml is now bundled and statically linked to H2O (#248).
