### ISSUE TITLE
Proper way to stop H2O

### ISSUE THREAD

**Issue by Ys88** [h2o/h2o#1991]
Hi,

I was wondering what is the right/clean/proper way to stop H2O server? Is it just sending a sigterm ?

Thank you.

**Comment by jobs-git** [comment]
I think ctrl+c is just fine. I have need seen long term effect so far.

**Comment by meritozh** [comment]
https://github.com/h2o/h2o/blob/531ca3027729b84f4250838884f5bbdb73c7bed0/src/main.c#L1517-L1530

`ctrl-c` is just fine.

**Comment by Ys88** [comment]
Thank you!
