### ISSUE TITLE
Profile-guided optimization ?

### ISSUE THREAD

**Issue by Ys88** [h2o/h2o#1994]
Hi,

Sorry if the question is silly, but, is it possible to build H2O with Profile-guided optimization ?

Regards,

**Comment by meritozh** [comment]
PGO is a compiler feature, and yes, you can.

**Comment by Ys88** [comment]
Thank you @meritozh for your answer. 

By any chance, do you know how to do it?

I tried this:

`env CXXFLAGS='-march=native -fprofile-dir=/src/h2o/pgo -fprofile-generate=/src/h2o/pgo' cmake -DWITH_MRUBY=on
make`

After installing, stopping/starting H2O, accessing a page, stopping H2O, I was expecting files to be written into the /src/h2o/pgo folder. But nothing happens.

**Comment by meritozh** [comment]
Use `CMAKE_C_FLAGS` flags, its **c**, not **c++**. h2o use cmake, so you should modify _CMakeLists.txt_, use cmake builtin variables to override default behavior. And remember, cleanup all cmake generated files first.

**Comment by kazuho** [comment]
What @meritozh says. Though IIRC you do not need to modify CMakeLists.txt. The CMakeLists.txt of H2O inherits environment variable `CMAKE_C_FLAGS` when being set (see https://github.com/h2o/h2o/blob/master/CMakeLists.txt#L206).

**Comment by Ys88** [comment]
Thank you @meritozh and @kazuho !
