### ISSUE TITLE
How to disable keep-alive?

### ISSUE THREAD

**Issue by jobs-git** [h2o/h2o#1995]
How do I set keep-alive to off?
For example, the following sets the status, reason and content type, however, how do we do it for disabling keepalive?
```c
  req->res.status = 200;
  req->res.reason = "OK";
  h2o_add_header(&req->pool, &req->res.headers, H2O_TOKEN_CONTENT_TYPE, NULL, H2O_STRLIT("text/plain"));
```

**Comment by meritozh** [comment]
https://github.com/h2o/h2o/blob/330e23eb1ceaf458f7a0772c56c6cb2862cc4175/lib/common/http1client.c#L308-L315

Attention, you are trying to modify HTTP protocol defined behavior.
