### ISSUE TITLE
High cpu usage & low performance on reverse proxy

### ISSUE THREAD

**Issue by jobs-git** [h2o/h2o#1999]
How do we improve reverse proxy performance of h2o server?

I use that h2o techempower code sample that can do 60k req/s as an upstream. But the h2o server can only do about 17k req/s and it already consumes large amount of cpu.

Below is the configuration file:

```bash

user: my-user
hosts:
  "h2otest.com":
    listen:
      host: 127.0.0.1
      port: 80
    paths:
        /:
          proxy.reverse.url: http://127.0.0.2:8080/
access-log: /dev/null
error-log: /dev/null
max-connections: 1024
tcp-fastopen: 4096
num-threads: 1
http2-reprioritize-blocking-assets: ON # performance tuning option
```

**Comment by dch** [comment]
I'd look at re-doing this with more than 1 thread and not doing the asset reprioritisation - as there's no details on what the techempower code is doing we cannot see if the asset unblocking causes significant work. Re-open if required.

**Comment by jobs-git** [comment]
the same h2o techempower code only does in 1 thread only. If in proxy, we should at least get almost 30k reqest/second
