### ISSUE TITLE
FastCGI protocol 

### ISSUE THREAD

**Issue by esa60816081** [h2o/h2o#200]
Hi guys,

Thanks for this nice server. It's really fast but misses fastCGI protocol which is one of the main protocols these days.
Mist of big companies use it like facebook and wikipedia if am not mistaken.

Please support it

**Comment by kazuho** [comment]
FYI, for anyone interested in writing FastCGI support, [lib/handler/proxy.c of H2O version 1.0.1](https://github.com/h2o/h2o/blob/v1.0.1/lib/handler/proxy.c) would be a good place to look at.  It would be possible to implement a FastCGI handler by replacing the calls to http1client with something equivalent.

note: in HEAD, the HTTP proxy implementation has been moved out from the proxy handler (#197)

**Comment by swinghu** [comment]
I will have a try writing FastCGi support this module.

**Comment by kazuho** [comment]
@swinghu :+1:

**Comment by swinghu** [comment]
Is there anything more I can reference？@kazuho

**Comment by kazuho** [comment]
@swinghu There would be couple of ways to start, but reading `examples/libh2o/socket-client.c` might be a good first-step.  It is a simple TCP client program written above libh2o that sends a hard-coded chunk of data and prints the response.

If you are going to at first write a somewhat-working standalone FastCGI client, and then integrate it has a request handler of H2O, then copying and extending socket-client.c would be a good idea (please let me know if you are going to take a different approach).

At the very beginning of implementing a protocol client, you can go on with a hard-coded request.  In other words, the first thing you need to write is a FastCGI response handler.

To handle a FastCGI response, you would need to parse the header-list and body contained in the `FCGI_STDOUT` record.  To parse the header-list, I would suggest using `phr_parse_headers` function in picohttpparser.  The interface provided by the function is similar to `phr_parse_response`; reading the functions of [lib/common/http1client.c](https://github.com/h2o/h2o/blob/v1.0.1/lib/common/http1client.c) (specifically `on_head`) might help.

**Comment by swinghu** [comment]
thks

**Comment by kazuho** [comment]
@swinghu How is it going on?  Recently there has been a discussion in my company to raise the priority of this issue, and I would like to know the status.

**Comment by kazuho** [comment]
In #346 fastcgi support has been merged to master.

**Comment by szepeviktor** [comment]
Thank.
