### ISSUE TITLE
HTTP/2 Priority implementation

### ISSUE THREAD

**Issue by DaanDeMeyer** [h2o/h2o#2002]
I was wondering how HTTP/2 priority information is used in h2o to put data from streams on the connection send buffer. 

From what I've discovered, the `do_emit_writereq` function calls `h2o_http2_scheduler_run` with the `emit_writereq_of_openref` callback to put data from streams onto the connection send buffer. The callback seems to be called on each stream in order of descending priority. The callback calls `h2o_http2_stream_send_pending_data` which calls `send_data_push` or `send_data_pull`. Both these function then call `calc_max_payload_size` to calculate the maximum amount of data a stream can put onto the connection send buffer. 

However, as far as I can see, the `calc_max_payload_size` function only takes into account the flow control windows of the connection and stream, the send buffer leftover capacity and in some cases the leftover congestion window. 

Disregarding flow control, does this mean that the first sibling in a set of sibling streams is allowed to fill the entire connection send buffer regardless of the weights assigned to each sibling? Wouldn't this interfere with the working of priorities where the available connection buffer space (or congestion window) should be divided among sibling streams according to their weight? If a sibling is allowed to fill the entire connection send buffer, are priorities between siblings implemented somewhere else in h2o?

**Comment by kazuho** [comment]
> Disregarding flow control, does this mean that the first sibling in a set of sibling streams is allowed to fill the entire connection send buffer regardless of the weights assigned to each sibling? Wouldn't this interfere with the working of priorities where the available connection buffer space (or congestion window) should be divided among sibling streams according to their weight?

The question is what the "unit" of QoS is. In case of a network device, the unit is a packet. In case of H2O, the unit is the amount of data you can write in one invocation of `send_data_pull` / `send_data_push`. Every time the server is notified of additional room to send data (via `epoll`), a different stream is being emitted (see how `h2o_http2_scheduler_run` invokes `queue_pop` and `queue_set`). It is by no means a fair queuing in strict sense, but my assume is that it would be sufficient for HTTP/2.

That said, it was my surprise to see that `calc_max_payload_size` did not cap the return value to no greater than 16KB. I had always assumed that was the case. So it could be the case that we have an issue in practice.

**Comment by DaanDeMeyer** [comment]
I just checked again and it seems `calc_max_payload_size` does cap the return value to `peer_settings.max_frame_size`, which the HTTP/2 spec defaults to 16Kb so it does seem each invocation of `send_data_pull` and `send_data_push` is capped to 16Kb. This prevents a single stream from filling the entire send buffer so I was wrong in my first post.

I also found these two links which further explain the priority tree implementation used in h2o and other HTTP/2 servers:
- <https://www.mew.org/~kazu/material/2015-http2-priority2.pdf>
- <https://www.mew.org/~kazu/doc/paper/http2-haskell-2016.pdf>
