### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by meritozh** [h2o/h2o#2004]
I'm using macOS, installed h2o by `brew install h2o` which installed h2o@2.2.5.

And I find it even not install _httpclient.h_. I cannot use libh2o unless I build h2o from source code.

**Comment by dch** [comment]
Regarding h2o brew recipe's lack of libh2o, it's not unusual to leave off unusual/uncommon options from recipes - I'm sure they'd take a PR altering that if you provide one.

Regarding releases, we have this underway - more news soon.
