### ISSUE TITLE
HTTP Authentication

### ISSUE THREAD

**Issue by kazuho** [h2o/h2o#203]
At the moment, H2O lacks support for HTTP Authentication.

**Comment by kazuho** [comment]
Although it is not difficult to support very basic style of HTTP authentication (e.g. basic authentication using `.htpasswd` file), we would anyways need to provide a way to define _custom_ authentication handlers.

OTOH, [the _authorizer_ application type of FastCGI](http://www.fastcgi.com/drupal/node/6?q=node/22#S6.3) is a protocol that is well-documented / is actually used for such purpose.

Thus, it might be a good idea to support it as part of #200, #147.

**Comment by swinghu** [comment]
:+1:

**Comment by webhtb** [comment]
Hi, how can i protect my site like apache htpasswordd style? Bottom is am apache example, i need the h20 alternative, thanks!

AuthType Basic
AuthName "Restricted Zone"
AuthBasicProvider file
AuthUserFile /var/www/.htpasswd
Require user myproject

**Comment by kazuho** [comment]
FYI the feature has been merged to master in the PR above.

https://github.com/h2o/h2o/pull/624#issuecomment-165454959 contains an example showing how it can be used.
