### ISSUE TITLE
Client seems not handle http1.1 Keep-Alive semantic.

### ISSUE THREAD

**Issue by CodeLife2012** [h2o/h2o#2049]
`Keep-Alive: timeout=15, max=100 `

Can't find anywhere handle timeout or max in response?

**Comment by kazuho** [comment]
The keep-alive header field was an experiment of HTTP/1.0 and never made it to HTTP/1.1.

**Comment by CodeLife2012** [comment]
@kazuho Sorry for my mistake.  So `destroy_expired_locked` is just a local keep alive timeout?

**Comment by CodeLife2012** [comment]
close it
