### ISSUE TITLE
Pospone QUIC (HTTP3) - hardware usage is too high!

### ISSUE THREAD

**Issue by jobs-git** [h2o/h2o#2060]
As investigated by Google, though there are advantages, HTTP3 consumes 2x that of TLS/TCP. This will result utilizing twice more hardware to serve the same TLS/TCP. 

Here is the Google Research
http://delivery.acm.org/10.1145/3100000/3098842/p183-Langley.pdf

**Comment by kazuho** [comment]
HTTP/3 will be an optional feature of H2O, you are not enforced to using that, if you consider the CPU cost to bee to high.

**Comment by jobs-git** [comment]
Thank you, that's relieving.
