### ISSUE TITLE
Implement DPDK

### ISSUE THREAD

**Issue by jobs-git** [h2o/h2o#2072]
With DPDK network performance can increase by about 3x.

https://www.dpdk.org/

**Comment by rock59** [comment]
It's not as easy as it seems. DPDK does not provide a TCP/IP Stack and h2o needs a TCP/IP Stack. There are some open source TCP/IP Stack for DPDK : F-Stack, dpdk-ans, OpenFastPath (OFP)

F-Stack can't be used in multithreaded servers so h2o can not use F-Stack

dpdk-ans can be used in multithreaded servers . it's free but not open source

OFP performs well with UDP but not TCP   

Another big limitation is that DPDK only works with special network card models

**Comment by jobs-git** [comment]
That is interesting.

For multi thread, dpdk-ans is open source https://github.com/ansyun/dpdk-ans with BSD License

OFP with be good for the upcoming QUIC/HTTP3 since its UDP

If F-stack is used, then it would be non-thread safe or there might be an alternative approach to multi thread.

And I doubt a really special card is needed, on Intel supported card includes e1000, that is a very old way back 2002(? i cant get much further back since archives were for much newer than e1000, e1000 is a much older card), even mine is supported and its already phased out!

**Comment by jobs-git** [comment]
That is interesting.

For multi thread, dpdk-ans is open source https://github.com/ansyun/dpdk-ans with BSD License

OFP would be good for the upcoming QUIC/HTTP3 since its UDP

If F-stack is used, then it would be non-thread safe or there might be an alternative approach to multi thread.

And I doubt a really special card is needed, on Intel supported card includes e1000, that is a very old way back 2002(? i cant get much further back since archives were for much newer than e1000, e1000 is a much older card), even mine is supported and its already phased out!

**Comment by rock59** [comment]
dpdk-ans is not open source. only compiled static libs are available.

F-stack is not thread safe since F-stack team removes all thread related codes from freebsd tcp/ip stack for eliminating lock contention and improve performance. We used it to develop a pub/sub multi process server and we are satisfied with it. Extracted socket abstraction from h2o evloop was used in our project . Thanks to h2o team

However I recommend to stick with standard kernels. DPDK shines well when you need to process raw packets and develop routers , load balancers , software switches not application servers that consume cpu cycles

**Comment by jobs-git** [comment]
Yhea, I just noticed it, dpdk-ans libs are closed, i dont like that either.

OpenFastPath has TCP now! https://openfastpath.org/index.php/faq/ so that might be a good thing.

**Comment by kazuho** [comment]
Thank you for opening the issue.

I appreciate the suggestion. I would also mention that we'd be looking into some kind of kernel-bypass mechanism as a way to optimize QUIC traffic.

OTOH, we are not interested in working on doing kernel bypass and using a userspace TCP stack at a moment. It's not that important for a HTTP/2 server compared to the cost that we need to pay for not only for developing but for debugging, and maintaining the capability.

Therefore, I am going to close the issue. I would be happy to see somebody working on integrating a userspace TCP stack using kernel bypass to H2O, but as stated, please understand that having such work merged to H2O might not be easy.

**Comment by jobs-git** [comment]
Thank you for considering kernel-bypass mechanism, I was looking forward to that.
