### ISSUE TITLE
How to serve Flask(Python) app on h2o?

### ISSUE THREAD

**Issue by ozturkoktay** [h2o/h2o#2075]
I'm trying to serve Flask app on h2o but I didn't do it. I tried with WSGI but It didn't work.

Any help?

**Comment by jobs-git** [comment]
Is your Flask app running as a backend server?

**Comment by ozturkoktay** [comment]
Yes, I write my code with Flask framework and I'm working on a local machine. But as you know Flask is slow. 

By the way, I'm making a request test, because of that I need h2o. How can I do that?

**Comment by jobs-git** [comment]
use h2o http1client its on the source

**Comment by ozturkoktay** [comment]
Can you explain How can I do that? I didn't solve it.

**Comment by jobs-git** [comment]
compile http1client in your desired outcome that send request to you app

**Comment by ozturkoktay** [comment]
I don't think you understand me. I can serve php file and can make request. I can't serve Flask application. There is no configuration for Flask.

**Comment by proyb6** [comment]
This solution may still applicable, uWSGI?

https://github.com/h2o/h2o/issues/1023
