### ISSUE TITLE
h2o.import_hive_tabel() doesn't work with big tables

### ISSUE THREAD

**Issue by manojs123** [h2o/h2o#2095]
Hello, 

I'm very new to h2o, and when I try to read a table in hive using h2o.import_hive_table(), it gives me below error. I have increased my Memory but it still keep failing. It works fine with small tables, but if the table is greater than 2GB it's failing. I have work around by reading data stored in HDFS. 

in .h2o.doSafeREST(h2oRestApiVersion = h2oRestApiVersion, urlSuffix = urlSuffix,  : 
  Unexpected CURL error: couldn't connect to host

Can you please let me know how to make import_hive_table() to work ?

Thanks,
Manoj

**Comment by rock59** [comment]
You are in the wrong repo.
https://github.com/h2oai/h2o-3
