### ISSUE TITLE
Query: How to read value from request URL and query param

### ISSUE THREAD

**Issue by buro1983** [h2o/h2o#2109]
I am not able to find any example to read a value from the request URL and query param.
e.g.
   ```/v1/store/123?full=true```

Here I want to read value 123 from URI and value of 'full' query param. So my questions are,
1. How do I register path ```/v1/store/<id>``` as id is a variable here? 
Another idea is that register only "/v1/store/" and then iterate through the URL  to validate URL and value. Is there any better idea?

2. How do I read query param and corresponding value from URL? 

3. Which config param indicates server side HTTP/1 connection timeout in h2o_globalconf_t. If it is not there then how to set server side connection timeout. If client sent a request with client side request timeout and is taking long time to process then connection will get stuck there for long time. If there is any premature connection close from client side then server side connection goes into clise_wait state. I want server to set server side connection time out to 60s, How do I achieve that?

Thanks.

**Comment by utrenkner** [comment]
I do not quite understand your first question. Do you pass the value of <id> to e.g. a PHP script? Then you could capture the path segment similarly to how I did it [here](https://github.com/utrenkner/wfcache-mruby/blob/master/wfcache.rb#L100-L101).

For the second question: The query string is stored in ``env['QUERY_STRING']``. If you know what value you are looking for and only need to check if that is true/false, you can do something like 
```if /preview\=true/.match(env['QUERY_STRING'])```,
which I use to check if we are delivering a WordPress preview page... If you need to capture the result you would have use regular expression to parse the query string (similar to the example above).

**Comment by buro1983** [comment]
Hi utrenkner, thanks for the info and the example. It will be a great help for me. 
My first question was to read resource id from URL. Suppose you want to get/post some employee info whose id is 123, if id 123 is part of URL then how do I read it. If there is any library function to read it or I have to parse URL and read the value from predefined position. 

Do you have any idea about Q3? how to set connection timeout on server side.

**Comment by utrenkner** [comment]
Concerning 1: I still don't understand how you want to use the captured id. In my experience, routing is most often done in the application itself (in Ruby, PHP, Node.js). Typical frameworks let you break down a URL in segments which are mapped to e.g. controllers etc. If you really want to do it in the web server, I think there is no way around mruby and a way similar to the one I have taken in [wfcache-mruby](https://github.com/utrenkner/wfcache-mruby/blob/master/wfcache.rb#L100-L101). Then you have the variable value in mruby... and then? What is it that you want to do with it?

Concerning 3: I think you are looking for the [http1-request-timeout](https://h2o.examp1e.net/configure/http1_directives.html#http1-request-timeout).

**Comment by buro1983** [comment]
@utrenkner thanks for your response. Your response answer my queries. I am closing this ticket.
