### ISSUE TITLE
Cmake: Could NOT find OpenSSL

### ISSUE THREAD

**Issue by aafanasyev** [h2o/h2o#213]
Hi everyone

I just followed the https://github.com/h2o/h2o/blob/master/README.md#installation topic, but I stacked at point: 
```
cmake -DCMAKE_INSTALL_PREFIX=/usr/local .

```

I am constantly getting this error:
```
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_LIBRARIES
  OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-2.8/Modules/FindOpenSSL.cmake:313 (find_package_handle_standard_args)
  CMakeLists.txt:8 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!
See also "/root/h2o/CMakeFiles/CMakeOutput.log".
See also "/root/h2o/CMakeFiles/CMakeError.log".

```

My installation steps on a clean Ubuntu 14.04.02:

```
root@RP-01:~# apt-get install locate git perl python cmake libyaml-0-2 build-essential -y
root@RP-01:~# git clonehttps://github.com/openssl/openssl.git
root@RP-01:~# git clone https://github.com/h2o/h2o.git

root@RP-01:~# apt-get remove openssl libssl-dev
root@RP-01:~# cd openssl/
root@RP-01:~/openssl# ./config
root@RP-01:~/openssl# make
root@RP-01:~/openssl# make test
root@RP-01:~/openssl# make install
root@RP-01:~# /usr/local/ssl/bin/openssl version
OpenSSL 1.1.0-dev xx XXX xxxx

# Looks like ssl is ok! I have no errors here.
```

According error mentioned above I found this topic:
http://stackoverflow.com/questions/16248775/cmake-not-able-to-find-openssl

And I tried:
```
cmake -DOPENSSL_ROOT_DIR=/usr/local/ssl -DOPENSSL_LIBRARIES=/usr/local/ssl/lib
```

However, I am getting the same error.  How can I solve it?

Thank you for your help.

Andre

**Comment by swinghu** [comment]
I meet this problem ,then I follow 
cmake -DOPENSSL_ROOT_DIR=/usr/local/ssl -DOPENSSL_LIBRARIES=/usr/local/ssl/lib
then the error gone

**Comment by aafanasyev** [comment]
By me error still exist. Even I try it like this:
```
root@RP-01:~/h2o# cmake -DOPENSSL_ROOT_DIR=/usr/local/ssl -DOPENSSL_LIBRARIES=/usr/local/ssl/lib cmake -DCMAKE_INSTALL_PREFIX=/usr/local .
```

**Comment by kazuho** [comment]
Would you mind trying: `cmake -DCMAKE_INCLUDE_PATH=/usr/local/ssl/include -DCMAKE_LIBRARY_PATH=/usr/local/ssl/lib`?

**Comment by aafanasyev** [comment]
Hi hank you! Looks like your proposal will work. However I got now some different error:

```
cmake -DCMAKE_INCLUDE_PATH=/usr/local/ssl/include -DCMAKE_LIBRARY_PATH=/usr/local/ssl/lib
CMake Error at /usr/share/cmake-2.8/Modules/FindOpenSSL.cmake:278 (list):
  list GET given empty list
Call Stack (most recent call first):
  CMakeLists.txt:8 (FIND_PACKAGE)


CMake Error at /usr/share/cmake-2.8/Modules/FindOpenSSL.cmake:279 (list):
  list GET given empty list
Call Stack (most recent call first):
  CMakeLists.txt:8 (FIND_PACKAGE)


CMake Error at /usr/share/cmake-2.8/Modules/FindOpenSSL.cmake:281 (list):
  list GET given empty list
Call Stack (most recent call first):
  CMakeLists.txt:8 (FIND_PACKAGE)


CMake Error at /usr/share/cmake-2.8/Modules/FindOpenSSL.cmake:283 (list):
  list GET given empty list
Call Stack (most recent call first):
  CMakeLists.txt:8 (FIND_PACKAGE)


-- Found OpenSSL: /usr/local/ssl/lib/libssl.a;/usr/local/ssl/lib/libcrypto.a (found version ".0.0`") 
-- Could NOT find LIBUV (missing:  LIBUV_LIBRARIES LIBUV_INCLUDE_DIR) 
-- Could NOT find LIBYAML (missing:  LIBYAML_LIBRARIES LIBYAML_INCLUDE_DIR) 
-- Could NOT find WSLAY (missing:  WSLAY_LIBRARIES WSLAY_INCLUDE_DIR) 
-- Configuring incomplete, errors occurred!
See also "/root/h2o/CMakeFiles/CMakeOutput.log".
See also "/root/h2o/CMakeFiles/CMakeError.log".
```

**Comment by aafanasyev** [comment]
OK I have some achievements in my installation journey. I believe later it can be used as a installation tutorial. ;)

All I am testing is on a XEN virtual guest Ubuntu Server 14.04.2 LTS.
```bash
root@RP-01:~/h2o# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty
```
Steps I took:

**Comment by kazuho** [comment]
@aafanasyev Sorry I have accidentally closed the issue.  Please reopen the issue if the problem still persists.

**Comment by kishorenc** [comment]
@kazuho - Is OpenSSL required even when I am building with `cmake -DWITH_BUNDLED_SSL=on`? That seems to be so, because I get the same `Could NOT find OpenSSL` error.

**Comment by kazuho** [comment]
@kishorenc 
> Is OpenSSL required even when I am building with `cmake -DWITH_BUNDLED_SSL=on`?

No.
Could you please post the enter output?

**Comment by kishorenc** [comment]
Sure:

```
$ cmake -DWITH_BUNDLED_SSL=on .
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE)
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing:  OPENSSL_LIBRARIES OPENSSL_INCLUDE_DIR)
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-2.8/Modules/FindZLIB.cmake:85 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:46 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!
```

**Comment by kishorenc** [comment]
Sorry for the false alarm. I realize that it's actually complaining about ZLIB and not OpenSSL. All good now.

**Comment by Grace5921** [comment]
lol

**Comment by qianxi2017** [comment]
> OK I have some achievements in my installation journey. Required packages (not sure if libyaml-dev 0.1.4 libuv-dev 0.10.22 right versions)
> 
> ```shell
> apt-get install locate git cmake build-essential checkinstall autoconf pkg-config libtool python-sphinx libcunit1-dev nettle-dev libyaml-dev libuv-dev -y
> ```
> 
> I believe later I can produce a ubuntu installation tutorial. ;) However, I have still the pretty same error:
> 
> ```shell
> root@RP-01:~/h2o# cmake -DCMAKE_INSTALL_PREFIX=/usr/local .
> CMake Error at /usr/share/cmake-2.8/Modules/FindOpenSSL.cmake:278 (list):
>   list GET given empty list
> Call Stack (most recent call first):
>   CMakeLists.txt:8 (FIND_PACKAGE)
> 
> 
> CMake Error at /usr/share/cmake-2.8/Modules/FindOpenSSL.cmake:279 (list):
>   list GET given empty list
> Call Stack (most recent call first):
>   CMakeLists.txt:8 (FIND_PACKAGE)
> 
> 
> CMake Error at /usr/share/cmake-2.8/Modules/FindOpenSSL.cmake:281 (list):
>   list GET given empty list
> Call Stack (most recent call first):
>   CMakeLists.txt:8 (FIND_PACKAGE)
> 
> 
> CMake Error at /usr/share/cmake-2.8/Modules/FindOpenSSL.cmake:283 (list):
>   list GET given empty list
> Call Stack (most recent call first):
>   CMakeLists.txt:8 (FIND_PACKAGE)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/root/h2o/CMakeFiles/CMakeOutput.log".
> See also "/root/h2o/CMakeFiles/CMakeError.log".
> ```
> 
> @kazuho Thank you for your proposal but I have it now like this:
> 
> ```shell
> root@RP-01:~/h2o# cmake -DCMAKE_INCLUDE_PATH=/usr/local/ssl/include -DCMAKE_LIBRARY_PATH=/usr/local/ssl/lib
> CMake Error at /usr/share/cmake-2.8/Modules/FindOpenSSL.cmake:278 (list):
>   list GET given empty list
> Call Stack (most recent call first):
>   CMakeLists.txt:8 (FIND_PACKAGE)
> 
> 
> CMake Error at /usr/share/cmake-2.8/Modules/FindOpenSSL.cmake:279 (list):
>   list GET given empty list
> Call Stack (most recent call first):
>   CMakeLists.txt:8 (FIND_PACKAGE)
> 
> 
> CMake Error at /usr/share/cmake-2.8/Modules/FindOpenSSL.cmake:281 (list):
>   list GET given empty list
> Call Stack (most recent call first):
>   CMakeLists.txt:8 (FIND_PACKAGE)
> 
> 
> CMake Error at /usr/share/cmake-2.8/Modules/FindOpenSSL.cmake:283 (list):
>   list GET given empty list
> Call Stack (most recent call first):
>   CMakeLists.txt:8 (FIND_PACKAGE)
> 
> 
> -- Found OpenSSL: /usr/local/ssl/lib/libssl.a;/usr/local/ssl/lib/libcrypto.a (found version ".0.0`") 
> -- Found LIBUV: /usr/lib/x86_64-linux-gnu/libuv.so  
> -- Found LIBYAML: /usr/lib/x86_64-linux-gnu/libyaml.so  
> -- Found WSLAY: /usr/local/lib/libwslay.so  
> -- Configuring incomplete, errors occurred!
> See also "/root/h2o/CMakeFiles/CMakeOutput.log".
> See also "/root/h2o/CMakeFiles/CMakeError.log".
> ```

I run into this problem, too. And with some searching the internet, I find this issue.
Finally, I find the reason why cmake cannot successfully decide openssl version.
In /usr/share/cmake-2.8/Modules/FindOpenSSL.cmake:278 this file, it use regexp to match the openssl version using:
`REGEX "^#define[\t ]+OPENSSL_VERSION_NUMBER[\t ]+0x([0-9a-fA-F])+.*")`
BUT in openssl/opensslv.h, it defines version as:
`# define OPENSSL_VERSION_NUMBER  0x101000bfL`
Do you notice the magic here?
Yes, the space between # and define is the reason why it cannot decide openssl version correctly. And by removing the space in opensslv.h, the configure process can now succeed.
change to:
`#define OPENSSL_VERSION_NUMBER  0x101000bfL`

**Comment by pinyue007** [comment]
cmake -D_OPENSSL_VERSION=x.y.z is good for me.

**Comment by mainguyenanhvu** [comment]
I used plan B in this link:
https://askubuntu.com/questions/355565/how-do-i-install-the-latest-version-of-cmake-from-the-command-line

and fix openssl in this link:
https://stackoverflow.com/questions/3016956/how-do-i-install-the-openssl-libraries-on-ubuntu
