### ISSUE TITLE
Unregister file.custom-handler

### ISSUE THREAD

**Issue by utrenkner** [h2o/h2o#2136]
I have globally registered a [file.custom-handler](https://h2o.examp1e.net/configure/file_directives.html#file.custom-handler) for ``.php`` files - just like in the example.

Now, I want to unregister this handler for a specific directory. In this directory, ``.php`` files should never be handled by php-fpm. What is the recommended way of doing this?

**Comment by kazuho** [comment]
`file.custom-handler` is a MIME mapping.

You can override that (or any other mapping of extensions) for a narrower scope by using `file.mime.addtypes` or other directives that sets the mapping.

**Comment by utrenkner** [comment]
Thank you for the explanation.
