### ISSUE TITLE
Stripping cookies from response header?

### ISSUE THREAD

**Issue by utrenkner** [h2o/h2o#2139]
Does anybody here have an idea, how one could strip cookies from the response header via mruby? The only solutions I could think of go along the way that @i110 [outlined here](https://github.com/h2o/h2o/issues/1863#issuecomment-428800567). But this would mean, that I would have to capture/reuse every response and tweak the header before sending it to the user. Is there anything more straight-forward?

Background: 
Today, the European Court of Justice ruled, that [users _always_ have to give their explicit consent before a cookie may be set in their browser](https://www.forbes.com/sites/emmawoollacott/2019/10/01/pre-checked-cookie-consent-invalid-eu-court-rules/#26ce14712049). A German law allowed for some ambiguity so far. For me the most elegant solution would be the webserver striping cookies from the response header unless a certain consent-cookie was present.

**Comment by 19h** [comment]
mruby in h2o is following the Rack specification, which means that you could technically use Rack-related implementations of your use-case.

Example: https://github.com/icoretech/rack-strip-cookies/blob/master/lib/rack/strip-cookies.rb#L22

**Comment by utrenkner** [comment]
Yes, but usually we we work with _incoming requests_ that we tweak. I can imagine how this strip-cookie code is used to strip cookies from an incoming request that is then passed to .e.g php-fpm.

But I would need the other end: Code that manipulates the response from php-fpm before delivering it to the user. This is possible, but not quite so straight-forward. See the first link in my original post.

I was wondering if anyone has a working example of how this would look like.

**Comment by i110** [comment]
I'm not sure if I understand what you want to do, but the example @19h pasted seems to me it meets your requirements. The example removes cookie-related headers from both of the request and response headers.

writing minimum example:
```
mruby-handler: |
  proc {|env|
    status, headers, body = H2O.next.call(env)
    headers.delete('Set-Cookie') # Be careful you should be case-insensitive here! This is just an example.
    [status, headers, body]
  }
```
The above example `Set-Cookie` header from the **response** headers.

**Comment by utrenkner** [comment]
Stupid me! Of course, you are right, @19h and @i110! Thank you also for the strip-cookie-code, which looks very useful!

Sorry for my temporary confusion.
