### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by sleepycodernotes** [h2o/h2o#2146]
`start_server (pid:65) starting now...

fcntl(F_SETFD, 0) failed:Invalid argument at /usr/share/h2o/start_server line 8.`

can someone help me with it? Trying to run it on windows 10 wsl debian

**Comment by msmshazan** [comment]
same issue with windows 10 wsl ubuntu

**Comment by syohex** [comment]
https://github.com/kazuho/p5-Server-Starter/pull/53
