### ISSUE TITLE
FreeBSD 12, Assertion failed error

### ISSUE THREAD

**Issue by Tintinabula** [h2o/h2o#2149]
On FreeBSD 12, the h2o server faulted with an "Assertion failed" error. I am not sure what triggered the error as the public traffic "looked" normal. Just thought I would report the problem.

```
#  cat /var/log/h2o_error.log 
h2o server (pid:67605) is ready to serve requests with 4 threads
Assertion failed: (h2o_timer_is_linked(&conn->_timeout_entry)), function update_idle_timeout, file /tmp/h2o/lib/http2/connection.c, line 159.
received fatal signal 6
h2o server (pid:59835) is ready to serve requests with 4 threads

# h2o -v
h2o version 2.3.0-DEV@2efb98da
OpenSSL: OpenSSL 1.1.1a-freebsd  20 Nov 2018
mruby: YES

#  freebsd-version 
12.0-RELEASE-p10
```

Thanks for your time.

**Comment by kazuho** [comment]
Thank you for sharing the information. I agree that we need to look into this issue.

**Comment by utrenkner** [comment]
I see these failed assertions, too. Several times per day. This is with h2o-2.3.0-beta2 on HardenedBSD 12 (essentially like FreeBSD 12).

```
Nov 14 23:38:16 web3 h2o[3069]: Assertion failed: (h2o_timer_is_linked(&conn->_timeout_entry)), function update_idle_timeout, file /wrkdirs/usr/ports/www/h2o-devel/work/h2o-2.3.0-beta2/lib/http2/connection.c, line 158.
Nov 14 23:38:16 web3 h2o[3069]: received fatal signal 6
Nov 14 23:38:16 web3 h2o[3069]: [22644] 0x39cfc6a1aea <???> at /usr/local/bin/h2o
Nov 14 23:38:16 web3 h2o[3069]: [22644] 0x4cb69b143f5 <_pthread_sigmask+0x535> at /lib/libthr.so.3
Nov 14 23:38:16 web3 h2o[3069]: worker 22644 died unexpectedly with status:6, restarting
```

**Comment by utrenkner** [comment]
Just wanted to let you know the good news: After updating my servers to @dch 's latest h2o port for FreeBSD, these frequent exits have disappeared. This is true for both, my FreeBSD 13.0-RELEASE server, and my HardenedBSD 12.3-STABLE server.

The fix must have been introduced into h2o master between 11 June 2021 ([#96bf0ef](https://github.com/h2o/h2o/commit/96bf0ef)) and 31 January 2022 ([#a68cabae](https://github.com/h2o/h2o/commit/a68cabae)).

Many thanks to whoever fixed this issue! And to @dch for the updated www/h2o-devel port.

**Comment by cwyang** [comment]
@i110 san fixed the issue https://github.com/h2o/h2o/pull/2844

Best regards,
Chul-Woong
