### ISSUE TITLE
Two Questions - Ubuntu Support & Benchmark

### ISSUE THREAD

**Issue by blueray453** [h2o/h2o#2154]
1. Is h2o compatible with ubuntu? Why there is nothing about ubuntu in https://h2o.examp1e.net/install.html

2. I checked the performance of h2o in -https://http2benchmark.org/results/benchmark-apache-caddy-h2o-litespeed-nginx-digitalocean.html

It is quiet impressive. However I did not understand why it performed very well in `h2load - 1knogzip.jpg` but not in `h2load - 1kstatic.html`. I mean it performs well with small jpg but not with small html. Why?

**Comment by tdtgit** [comment]
1. Using h2o on Ubuntu 18.04 LTS. No issues at all but you will missing some dependencies when building if I recall correctly.

**Comment by proyb6** [comment]
2. Just my quick thought, perhaps, caching in lsws and nginx are more efficient but Nginx is ideally battle tested if reliability is more important. If you need the performance, serving HTML through SO_REUSEPORT is easier but I have yet to benchmark in Go language now.
