### ISSUE TITLE
Why h2o_headers_t is vector instead of hash data structure

### ISSUE THREAD

**Issue by suddas** [h2o/h2o#2159]
I am new in this community as well as in http. I was exploring some http library to reuse in our product. I am impressed by h2o performance. I have very limited knowledge in this area.

I have one quick question related to performance.  Why "h2o_headers_t" is a "Vector" instead of "Hash". Is "h2_find_header" less likely to be called in general case? Because in our use case we like to write a handler which will call this function 4-5 times in every  request.

**Comment by kazuho** [comment]
Several reasons:
* the ordering of the header field has meanings in HTTP
* a HTTP message typically contains about 10 header fields, so using a hash does not really give you benefits
* insertion and iteration tend to be slower when using hashes
* we use tokens for well-known header names, therefore the comparison is extremely fast (address comparison) to an extent that doing O(N) search does not matter

**Comment by suddas** [comment]
Thanks
