### ISSUE TITLE
Can "paths" vector inside h2o_pathconf_t be a "B-tree"

### ISSUE THREAD

**Issue by suddas** [h2o/h2o#2160]
In general use case how many dynamic handlers are registered? Does to make sense making this table "B-tree"?

Same question is also for "Virtual host". Does it make sense changing the vector implementation of virtual host to a Hash?

**Comment by kazuho** [comment]
I'd assume that most deployments do not define that much of paths or hosts to warrant the necessity of a tree.

That said, I am happy to review a PR that incorporates a simple tree implementation that runs as fast as the vector that we use now when the number of entries is small.

However, I tend to assume that it is going to be a difficult task, as you need to retain things like the longest match rules for paths (as well as trailing `/`), mapping of wildcard domains (i.e. hosts with `*`).

**Comment by suddas** [comment]
Thanks for your quick response.. If required, I will raise a PR
