### ISSUE TITLE
Make check error: Can't locate t/Util.pm in @INC

### ISSUE THREAD

**Issue by jobs-git** [h2o/h2o#2167]
as the title says, I get this error when doing `make check` the folder and the file was present though, so I dont know where the problem is

**Comment by kazuho** [comment]
Thank you for reporting the problem. The issue was fixed in #1443, but has not been backported to v2.2.x.

**Comment by jobs-git** [comment]
thank you, that means my copy is probably too old, I know it would be hard to maintain old versions so will be updating my copy and close this.
