### ISSUE TITLE
Question about implementing a reactor pattern with h2o

### ISSUE THREAD

**Issue by 0ctopus13prime** [h2o/h2o#2173]
Hello, expert!

I'm wondering if h2o provide a callback interface or something.
I refered [example](https://github.com/h2o/h2o/blob/master/examples/libh2o/simple.c) several times, still confusing.

Can I dispatch `h2o_socket_t` to another thread in `on_accept` method?
Purpose is to make two divided layers have each different responsibility in my application server.
Front threads only accept incoming requests, worker threads process a dispatched request from the front thread and send a result back to a socket.
After dispatching, front thread go back to accept another incoming requests.

How to achieve this using h2o library?

Thank you in advance.

**Comment by i110** [comment]
> Can I dispatch h2o_socket_t to another thread in on_accept method?

I haven't tried yet, but I think you can. The only difficulty is, `h2o_socket_t` is bound to an event loop (in libuv case, `uv_loop_t`), so unlike the above example I suppose you have to create h2o_socket_t with the eventloop that the worker thread owns, instead of the lister thread's one.

**Comment by 0ctopus13prime** [comment]
@i110 
Thank you for replying!
It's seems to some tweeks need here to do that,
I made a prototype for that, but the restriction that `h2o_socket_t` bounded within a `uv_loop_t` make multi threads compete each other, cause a conflict each other.
It appears that two different threads made a simultaneous access to an unsynchronized buffer variable which leads the prototype application crash

I think once the thread accepted an request, then it must be resolved within the current thread context, as related variables are in an unprotected zone that might cause unexpected behavior when it comes to multi thread processing.

But, nevertheless, I really appreciate your comment!

Thank you!
