### ISSUE TITLE
h2o-httpclient: received signal SIGABRT, Aborted

### ISSUE THREAD

**Issue by chenbd** [h2o/h2o#2180]
Test with `h2o-httpclient -2 100 -t 10 https://h2o.examp1e.net/`

The following error:
`lib/common/http2client.c:767: close_connection_now: Assertion !h2o_timer_is_linked(&conn->output.defer_timeout)' failed.`

`close_connection_now` is called  when some error case( eg: io timeout).
Should this assert be removed?

**Comment by i110** [comment]
@chenbd Thank you for reporting this. You're right. I filed https://github.com/h2o/h2o/pull/2185
