### ISSUE TITLE
How is H2O buffering FCGI response ?

### ISSUE THREAD

**Issue by OscarWater** [h2o/h2o#2191]
Hello, 

I was wondering if H2O is buffering the response received from a Fast CGI process. And if so, it is possible to disable it? 

I am looking for something similar to the "fastcgi_buffering off;" option, available with nginx: https://nginx.org/en/docs/http/ngx_http_fastcgi_module.html#fastcgi_buffering

Thank you !

**Comment by kazuho** [comment]
H2O streams the response to the client, as it receives it from the application.

**Comment by OscarWater** [comment]
Okay thank you very much !
