### ISSUE TITLE
How should I configure h2o for http2?

### ISSUE THREAD

**Issue by danielvj** [h2o/h2o#220]
I have this conf file but i dont know why the server never works using HTTP2.

listen: 8080
max-connections: 10240
http1-request-timeout: 10
limit-request-body: 536870912
http1-upgrade-to-http2: ON
http2-idle-timeout: 10
http2-max-concurrent-requests-per-connection: 16
num-threads: 2
user: daniel
listen:
  port: 8081
  ssl:
    certificate-file: examples/h2o/server.crt
    key-file: examples/h2o/server.key
hosts:
  "127.0.0.1.xip.io:8080":
    paths:
      /:
        file.dir: examples/doc_root
    access-log: /dev/stdout
  "127.0.0.1.xip.io:8081":
    listen:
      port: 8081
      ssl:
        certificate-file: examples/h2o/alternate.crt
        key-file: examples/h2o/alternate.key
    paths:
      /:
        file.dir: examples/doc_root.alternate
    access-log: /dev/stdout

Furthermore i get errors:

h2o server (pid:8269) is ready to serve requests
fetch-ocsp-response (using OpenSSL 1.0.2 22 Jan 2015)
fetch-ocsp-response (using OpenSSL 1.0.2 22 Jan 2015)
failed to extract ocsp URI from examples/h2o/alternate.crt
[OCSP Stapling] disabled for certificate file:examples/h2o/alternate.crt
failed to extract ocsp URI from examples/h2o/alternate.crt
[OCSP Stapling] disabled for certificate file:examples/h2o/alternate.crt
fetch-ocsp-response (using OpenSSL 1.0.2 22 Jan 2015)
fetch-ocsp-response (using OpenSSL 1.0.2 22 Jan 2015)
failed to extract ocsp URI from examples/h2o/server.crt
failed to extract ocsp URI from examples/h2o/server.crt

Thankyou

**Comment by kazuho** [comment]
@danielvj 
> I have this conf file but i dont know why the server never works using HTTP2.

How did you check the behavior?  Since the web browsers that support HTTP/2 limit the use to HTTPS only, you would need to access the server using HTTPS.

> Furthermore i get errors:
> 
> h2o server (pid:8269) is ready to serve requests
> (snip)

Please ignore them.  They are not errors, they are only informative output.

**Comment by danielvj** [comment]
I have checked using wireshark(beta version) and I decrypt the packages using the SSLKEYLOGFILE environment variable. 

The conf file is ok?

**Comment by kazuho** [comment]
@danielvj Sorry I think I have missed one thing. Whether the web browsers would be possible to use HTTP/2 depends on the version of OpenSSL that H2O is linking to.

An TLS extension called ALPN is used by the web browsers to select HTTP/2.  However, the extension has only been supported by the newest version OpenSSL (version 1.0.2).  If you are using an older version of OpenSSL, then the web browsers may not be able to communicate using HTTP/2 (note: some web browsers also use NPN for selecting HTTP/2; which was supported in IIRC OpenSSL 1.0.1).
