### ISSUE TITLE
Question - C/C++ Documentation, API Reference, Usage Example For each feature 

### ISSUE THREAD

**Issue by mohsenomidi** [h2o/h2o#2229]
Hi, 

I am interested in your library (libh2o) and and want to use it in C/C++, I search for 1 day and I can not find any useful manual to cover all ability and base functionality such as multi-threading, http2, message processing, MIME parsing, complex file serving and so on..  just found the simple document 
[A warm welcome to libh2o](https://powerdns.org/libh2o/#http/2specificfeatures)

I am not application user, I mean h2o as web-server, I want to use it as library 
for now i can add it to my sample C++ code, and compile it and have a very basic functionality, but need more, to use advanced feature, multi-threading & so on.

would you please help me in this regard,

**Comment by mohsenomidi** [comment]
Hi everybody...
I would like to hear something about the h2o library, help, manual, guid or references, and will be great for anyone wants to use it...

Would you please make a comment, if know something about it...

**Comment by i110** [comment]
There's no user-friendly manual other than the one you pasted, as far as I know. Using libh2o requires you to be more or less familiar with the internal implementation, if you want to know the details.

**Comment by mohsenomidi** [comment]
@i110 Thanks for your reply

It seems the main project goal is only for the http server, not using it as a library.

It will be great if support it as a library because the many other people can use it in their applications therefore many people can be a potential volunteer to improve it and will add many functionalities that only happens if the developers involve to using it.

The main capability can be writing a C++ wrapper for it to be able to using it in modern C++ application.

For example h2o router I mean in (h2o_config_register_path) function there is no parameter to be able send the non static member function of class to it as a callback, and if you want to pass the static function there is no void* parameter to send the callback function parameters

In these cases need to be a documentation, design papers and good community support for the library users.

Maybe this offer can be study by the project owner @kazuho 

As respects nobody interested in this topic and for cleanup the issue list i will close this issue.

Best Regards
