### ISSUE TITLE
Possible Bug

### ISSUE THREAD

**Issue by BrandonRCopeland** [h2o/h2o#2241]
Hey folks, my code that's been in production for  several months is now breaking when I call h2o_context(sc). I'm wondering if there is a new bug that go introduced somehow.  Can you check this out?  Again, this code is unchanged and was running successfully in production until yesterday 1/28/20 when it started crashing at the h2o_context(sc) call.

![image](https://user-images.githubusercontent.com/44583531/73397114-9f665480-4297-11ea-9ae4-6ebbec020a50.png)

**Comment by i110** [comment]
If you are doing something related AI, you should go and report to https://github.com/h2oai. This repository is for HTTP2 Web Server, not for AI stuff.

**Comment by BrandonRCopeland** [comment]
Thanks.  I didn't realize I posted in the wrong repo.  Move to h2o.ai.
