### ISSUE TITLE
libh2o - Call back function arguments 

### ISSUE THREAD

**Issue by mohsenomidi** [h2o/h2o#2247]
Dear Contributors  & Project Owners

I hope you are doing well.

With all due respect I want to ask the feasibility of adding the new option to libh2o library.
Is there possible to add a prototype as (void * ) as the last variable in function `h2o_config_register_path` for callbacks to send an argument to the callback functions? it is completely transparent for the libh2o, It just for the library users who want to set callback , this argument can be provide for It, and at the execution time, the libh2o just send it to callback function. 

This is the way that the callback functions can be have arguments, it is extremely useful for library users to be able to set variable for call back functions and also with this option the C++ users can use their objects inside the callbacks. 

I will be appreciate to check this option.

Best Regards,

**Comment by kazuho** [comment]
Thank you for the suggestion.

I am not sure if that is necessary. The proper way of setting up a handler is by first calling `h2o_config_register_path`, then calling `h2o_create_handler` that takes the registered path as the argument.

If you want to associate information to the handler, what you should be doing is to "subclass" h2o_handler_t, and use `h2o_create_handler` to allocate memory that is enough to hold that subclass.

As an example, please refer to https://github.com/h2o/h2o/blob/master/lib/handler/status.c#L33-L36, https://github.com/h2o/h2o/blob/master/lib/handler/status.c#L264.

**Comment by kazuho** [comment]
See also: https://github.com/h2o/h2o/wiki/Coding-Style#context-passing-and-subclassing

**Comment by mohsenomidi** [comment]
Dear @kazuho Thanks for reply and flag these useful information 👍 

I am sorry for my late reply, i was in vacation, now I am reading your comments and will try to make some tests, it seems it will cover the requirements. give me some time to write an example and test it, for now I'll leave this issue opened if I need some more assistance will reply here. 

Just one more question, is it possible to add the example as PR in library for helping others in this section or maybe the other parts. 

I can provide this if you agree.

Regards.

**Comment by mohsenomidi** [comment]
@kazuho i test the solution and it works perfect.

Can I submit the PR for this question, as an example?
It will be a great help for library users.
