### ISSUE TITLE
When compiling for c++ segfault because different empty struct size

### ISSUE THREAD

**Issue by mingodad** [h2o/h2o#225]
Again trying to compile h2o main.c renamed to main.cpp and after adjusting the more strict type cast requirements needed by c++ I was getting segfaults and after a while decided to compile with clang 3.5 and noticed a warning that g++ was not giving:

"warning: empty struct has size 0 in C, size 1 in C++"

I solved it by adding on include/h2o/socket/evloop.h a dummy field to allow be compiled/run by c++:

struct st_h2o_timeout_backend_properties_t {
    char *dummy_for_cpp;
};

**Comment by kazuho** [comment]
Thank you!!!
