### ISSUE TITLE
CONTENT_TYPE retained in H2O.next but not in H2O.reprocess?

### ISSUE THREAD

**Issue by utrenkner** [h2o/h2o#2255]
I just noticed a subtle but important difference in how `H2O.next` and `H2O.reprocess` handle `env`, and I wonder whether or not this is intended:

The next handler called via `H2O.next` receives the `env` with `CONTENT_TYPE`. The call issued by `H2O.reprocess` does not contain the original `CONTENT_TYPE` (or any CONTENT_TYPE for that matter).

In a WordPress backend and using `H2O.reprocess` I receive only status codes of 400 for calls to `/wp-admin/admin-ajax.php`. This is because `"CONTENT_TYPE"=>"application/x-www-form-urlencoded; charset=UTF-8"` is dropped from the request (env). And I do not know of any way to re-enter it.

Using `H2O.next`, the original `CONTENT_TYPE` of the request is retained and I get the proper 200 answer.

For some more background: I was playing around with @i110 's [patch that solved my problems](https://github.com/h2o/h2o/issues/2234#issuecomment-582492313) with `H2O.next` and `H2O.reprocess`.

**Comment by i110** [comment]
Thank you for reporting: this helped me a lot. Fixed in https://github.com/h2o/h2o/pull/2256
