### ISSUE TITLE
h2o predict contributions are inconsistent between R and Python

### ISSUE THREAD

**Issue by zvaen** [h2o/h2o#2288]
Dear h2o-development team and each h2o-contributor,

thanks for creating such a powerful tool to make Machine Learning that easy. 
I ran into an issue with the predict contributions function (which are an implementation of the SHAP Values as far as I understood) in R and Python. 
To clarify my issue, here is the situation:
If I am doing a Random Forest on numerical predictors and a factorial target variable on an highly imbalanced dataset then the Bias Term of the output of predict contributions is negative in R which should not happen, as Random Forests outputs probabilities (if I am not mistaken on this point of view). If I am doing the exact same steps in Python then the Bias Term is not negative which is fine according to the theoretical properties of SHAP values (and I am aware of the issue that I do have a highly imbalanced dataset).  
How is that discrepancy possible,and assuming everything is correct - how is the Bias Term determined in such a case? 

Kind regards and thanks for your attention (codes are attached for reproducibility).
[SHAP_Python_R_Examples.zip](https://github.com/h2o/h2o/files/4294656/SHAP_Python_R_Examples.zip)

**Comment by fetus-hina** [comment]
Unfortunately, this is not a machine-learning related project.
Probably you should visit to: https://github.com/h2oai/h2o-3
