### ISSUE TITLE
header.append proper usage ?

### ISSUE THREAD

**Issue by centminmod** [h2o/h2o#229]
What's the proper syntax and placement for header.append ?

I tried it in my h2o.conf and get this error

    failed to parse configuration file:/usr/local/h2o/h2o.conf:line 27:
    mapping values are not allowed in this context
    new worker 27188 seems to have failed to start, exit status:19968

my h2o.conf

    hosts:
      "0.0.0.0:8080":
        paths:
          /:
            file.dir: /usr/local/nginx/html
            header.append: Server: 'on centminmod.com'
        access-log: /usr/local/h2o/logs/access.log

looking to append to existing Server header for my Centmin Mod integration https://github.com/centminmod/h2o_installer

so it looks like this

    Server: h2o/1.1.1 on centminmod.com

**Comment by kazuho** [comment]
You need to quote the header line (as it contains `:` which has a special meaning in YAML), i.e. `header.append: "Server: on centiminmod.com"`.

**Comment by centminmod** [comment]
thanks @kazuho tried that and get this message on start up and after first page reload on SSL domain it gives 'web page not available' and message below about **headers.c:92: rewrite_headers: Assertion `!"FIXME"' failed**

    h2o: /svr-setup/h2o-1.1.1/lib/handler/headers.c:92: rewrite_headers: Assertion `!"FIXME"' failed.
    worker 28710 died unexpectedly with status:6, restarting
    
    starting new worker 28725
    [INFO] raised RLIMIT_NOFILE to 262144
    h2o server (pid:28725) is ready to serve requests
    fetch-ocsp-response (using OpenSSL 1.0.1e-fips 11 Feb 2013)
    fetch-ocsp-response (using OpenSSL 1.0.1e-fips 11 Feb 2013)
    sending OCSP request to http://ocsp.comodoca.com
    --issuer option was not used, and failed to extract issuer certificate from the certificate
    [OCSP Stapling] disabled for certificate file:/usr/local/h2o/centminmod.com.crt
    /usr/local/h2o/centminmod.com-unified.crt: good
            This Update: Mar 16 00:18:54 2015 GMT
            Next Update: Mar 20 00:18:54 2015 GMT
    verifying the response signature
    verify OK (used: -VAfile /tmp/B0LVHZLW01/issuer.crt)
    [OCSP Stapling] successfully updated the response for certificate file:/usr/local/h2o/centminmod.com-unified.crt

**Comment by kazuho** [comment]
@centminmod I am sorry but I was not able reproduce the crash / the most probable reason for seeing the assertion failure on that line is due to internal memory corruption.

Would you mind rebuilding H2O?  If the problem persists, would you mind sending me your entire configuration (i.e. all the HTML, images and configuration files excluding the server-certificate and the private key).  Looking at #231 I believe the number of files needed for reproducing the issue is quite small.

**Comment by centminmod** [comment]
@kazuho here's the h2o.conf file at https://gist.github.com/centminmod/db18853abfd5aaf12617

and contents of /usr/local/nginx/html is located at https://github.com/centminmod/centminmod/tree/123.08centos7beta02/htdocs/default - it's the default index.html and cmlogo.png that I tested with which is the default Nginx test start page for my Centmin Mod project

This test server I am using is an OpenVZ VPS in virtualised environment so wonder if that is a factor ?

**Comment by centminmod** [comment]
Also tried compiling h2o and same exact error/symptoms

CentOS 6.6 64bit
1GB RAM OpenVZ VPS

    rm -rf CMakeCache.txt                        
    
    cmake -DCMAKE_INSTALL_PREFIX=/usr/local .
    -- Looking for include file pthread.h
    -- Looking for include file pthread.h - found
    -- Looking for pthread_create
    -- Looking for pthread_create - not found
    -- Looking for pthread_create in pthreads
    -- Looking for pthread_create in pthreads - not found
    -- Looking for pthread_create in pthread
    -- Looking for pthread_create in pthread - found
    -- Found Threads: TRUE  
    -- Found OpenSSL: /usr/lib64/libssl.so;/usr/lib64/libcrypto.so (found version "1.0.1e") 
    -- Could NOT find LIBUV (missing:  LIBUV_LIBRARIES LIBUV_INCLUDE_DIR) 
    -- Found LIBYAML: /usr/lib64/libyaml.so  
    -- Could NOT find WSLAY (missing:  WSLAY_LIBRARIES WSLAY_INCLUDE_DIR) 
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /svr-setup/h2o-1.1.1
    
    make -j4
    Scanning dependencies of target h2o
    Linking C executable h2o
    [100%] Built target h2o
    
    make install
    [100%] Built target h2o
    Linking C executable CMakeFiles/CMakeRelink.dir/h2o
    Install the project...
    -- Install configuration: ""
    -- Installing: /usr/local/bin/h2o
    -- Up-to-date: /usr/local/share/h2o/fetch-ocsp-response

**Comment by kazuho** [comment]
@centminmod Thank you for the test data :+1: 

Using them I was possible to reproduce the issue and fix the bug in the above commit.

**Comment by centminmod** [comment]
You're welcome @kazuho 

so if you can't append to Server header, can we use `header.set:` to replace it ?

    header.set: "Server: h2o/1.1.1 on centiminmod.com"

**Comment by kazuho** [comment]
No.  The `headers.*` directives cannot be used for mangling the `server` header.

**Comment by centminmod** [comment]
ok guess I must not touche server header and use something else :)
