### ISSUE TITLE
cipher-suite order not being observed ?

### ISSUE THREAD

**Issue by centminmod** [h2o/h2o#230]
Just installed h2o 1.1.1 to play with it and setup SSL host with cipher-suite prefer specified. But using [cipherscan](https://github.com/jvehent/cipherscan) it reports a different order to that which I specified via cipher-suite line ?

Example H2O SSL config

    listen:
      host: 0.0.0.0
      port: 8081
      ssl:
        certificate-file: /usr/local/h2o/centminmod.com-unified.crt
        key-file: /usr/local/h2o/centminmod.com.key
        minimum-version: TLSv1
        cipher-suite: ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA:!CAMELLIA

check https SSL on port 8081 for H20 server using [cipherscan](https://github.com/jvehent/cipherscan) and order of ciphers aren't correct ?

    ./cipherscan XXX.centminmod.com:8081        
    ..............
    Target: XXX.centminmod.com:8081
    
    prio  ciphersuite                  protocols              pfs_keysize
    1     ECDHE-RSA-AES256-GCM-SHA384  TLSv1.2                ECDH,P-256,256bits
    2     ECDHE-RSA-AES256-SHA384      TLSv1.2                ECDH,P-256,256bits
    3     ECDHE-RSA-AES256-SHA         TLSv1,TLSv1.1,TLSv1.2  ECDH,P-256,256bits
    4     AES256-GCM-SHA384            TLSv1.2
    5     AES256-SHA256                TLSv1.2
    6     AES256-SHA                   TLSv1,TLSv1.1,TLSv1.2
    7     ECDHE-RSA-AES128-GCM-SHA256  TLSv1.2                ECDH,P-256,256bits
    8     ECDHE-RSA-AES128-SHA256      TLSv1.2                ECDH,P-256,256bits
    9     ECDHE-RSA-AES128-SHA         TLSv1,TLSv1.1,TLSv1.2  ECDH,P-256,256bits
    10    AES128-GCM-SHA256            TLSv1.2
    11    AES128-SHA256                TLSv1.2
    12    AES128-SHA                   TLSv1,TLSv1.1,TLSv1.2
    13    DES-CBC3-SHA                 TLSv1,TLSv1.1,TLSv1.2
    
    Certificate: trusted, 2048 bit, sha256WithRSAEncryption signature
    TLS ticket lifetime hint: 300
    OCSP stapling: supported
    Client side cipher ordering

compared to Centmin Mod Nginx SPDY SSL setup with OpenSSL 1.0.2 chacha20_poly1305 cipher patched on [https://community.centminmod.com](https://community.centminmod.com) the order of ciphers is correct for my cipher preferences.

    ./cipherscan community.centminmod.com:443       
    ........
    Target: community.centminmod.com:443
    
    prio  ciphersuite                  protocols              pfs_keysize
    1     ECDHE-RSA-CHACHA20-POLY1305  TLSv1.2                ECDH,P-256,256bits
    2     ECDHE-RSA-AES256-GCM-SHA384  TLSv1.2                ECDH,P-256,256bits
    3     ECDHE-RSA-AES256-SHA384      TLSv1.2                ECDH,P-256,256bits
    4     ECDHE-RSA-AES256-SHA         TLSv1,TLSv1.1,TLSv1.2  ECDH,P-256,256bits
    5     DHE-RSA-AES256-GCM-SHA384    TLSv1.2                DH,4096bits
    6     DHE-RSA-AES256-SHA256        TLSv1.2                DH,4096bits
    7     DHE-RSA-AES256-SHA           TLSv1,TLSv1.1,TLSv1.2  DH,4096bits
    
    Certificate: trusted, 2048 bit, sha256WithRSAEncryption signature
    TLS ticket lifetime hint: 43200
    OCSP stapling: supported
    Server side cipher ordering

**Comment by kazuho** [comment]
@centminmod 
> Just installed h2o 1.1.1 to play with it and setup SSL host with cipher-suite prefer specified. But using cipherscan it reports a different order to that which I specified via cipher-suite line ?

As can be found on the last line of the output of cipherscan for H2O, the ciphersuite is selected by the client-side preference.  In other words, the output of cipherscan in case for client-side cipher ordering does not indicate the preference order.

We could add a configuration option to select the cipher-suite using the server-side preference if that is necessary.

**Comment by centminmod** [comment]
oh I see, thanks for clarification :)

Trying to find a tool for checking the cipher-suite preference as ssllabs doesn't support tests on ports other than 443

**Comment by kazuho** [comment]
@centminmod
> would be nice to specific cipher-suite for server-side preference too :)

The PR above has added a new property named `cipher-preference`.  By adding a line like `cipher-preference: server` into the `ssl:` section, the server will use the server-side list for choosing the ciphersuite.

> Trying to find a tool for checking the cipher-suite preference as ssllabs doesn't support tests on ports other than 443

That's might be a hard question, since IIRC RFC 5246 only states that the server should choose one cipher-suite from the list provided by the client (the provided list is ordered by client-side preference).

It would be possible to write a tool for checking the preference order of a TLS implementation that is _known to prefer_ the server-side list (e.g. cipherscan).  OTOH there is no such preference in case the server is implemented or configured to prefer the client-side list.  Or a server implementation may use complicated algorithm for selecting the cipher-suite.

**Comment by centminmod** [comment]
cheers @kazuho
