### ISSUE TITLE
Reverse Proxy Error

### ISSUE THREAD

**Issue by varsbhat** [h2o/h2o#2304]
Hey, I have installed [writefreely](https://writefreely.org/start) and wanted to reverse proxy it behind h2o. I have done it , but there are errors. whenever,i try to open `http://<url>/me/posts/` , i get error saying `connection refused` . nginx works correctly.

Steps to reproduce the bug:
1) install writefreely.
2) goto <url>/me/posts/ (or go to editor>> click my posts)
3) out of 5 times, you will get `connection refused` error atleast 3 times.

Thanks.

**Comment by yrashk** [comment]
I am running into a similar situation, more often on underpowered VMs.
