### ISSUE TITLE
build error 2.3.0_beta2

### ISSUE THREAD

**Issue by axelu** [h2o/h2o#2312]
getting built error on v2.3.0-beta2

...
Don't know how to rake /path/to/h2o/deps/mruby-io/src/file.c
...
Don't know how to rake /path/to/h2o/deps/mruby-pack/src/pack.c

This path /path/to/h2o/deps/mruby-io and mruby-pack is referenced in the corresponding .d files in /path/to/h2o/mruby/host/mrbgems/mruby-<module>/src/<filename>.d

It appears mruby-io and mruby-pack was in prior versions in fact located directly under /deps, but is now in /deps/mruby/mrbgems/.  I simply copied them to the expected path and repeated make to get over the error, but that cannot be the solution.  I maybe missing a clean up step or configure step.

**Comment by syohex** [comment]
I cannot reproduce on both macOS 10.15 and Ubuntu 20.04 by following commands. I suppose your build environment corrupts. Please clean up your build environment and retry to build

```
git clone https://github.com/h2o/h2o
cd h2o
git checkout v2.3.0-beta2
mkdir build
cd build
cmake ..
make
```

IMHO you might want to show your environment, build commands etc for maintainers when you report such build error

**Comment by axelu** [comment]
@syohex You are correct.  A fresh clone and checkout of v2.3.0-beta2 does **not** exhibit the issue. But if you simply switch to an older version tag, you get the issue and vice versa also, so in case you started initially with a clone and checkout of anything other than v2.3.0-beta2, built it and then switch to v2.3.0-beta2.  So take your above command syntax as-is and then do next:
```make clean
cd ..
git checkout v2.3.0-beta1
cd build
cmake ..
make
```
You will get the error.  So manually deleting the mruby dir in build dir in between builds will also address this build error, or of course deleting the entire build dir in between builds will address the issue. Like I initially said, I missed a clean step, in this case blowing away the build dir or simply using a fresh clone.  However, I think the better option (real fix) would be to have 'make clean' truly remove all build artifacts so that simply switching between any branch including v2.3.0-beta2 without manually cleaning the build dir is possible.

**Comment by axelu** [comment]
Closing the issue due to a) a workaround being available and b) a fix done in above referenced pull/merge request #2313.
