### ISSUE TITLE
How does one specificy static OpenSSL 1.0.2 version in h2o ?

### ISSUE THREAD

**Issue by centminmod** [h2o/h2o#235]
I asked at https://github.com/h2o/h2o/issues/85 but that was with h2o 0.9.0. 

h20 1.1.1 now supports OpenSSL 1.0.2 static compile ? if so how does one install and compile h2o with such ?

thanks

**Comment by kazuho** [comment]
The situation has not changed since 0.9.0.

note: In 1.2 we might start bundling libressl.

**Comment by centminmod** [comment]
oh so still can not compile static OpenSSL yet

could of sworn i read about it somewhere :)

**Comment by kazuho** [comment]
> oh so still can not compile static OpenSSL yet

Well you can, since the very early days.  As stated in #85 if you build a openssl with `--enable-static --disable-shared` and then use that openssl when building H2O, then the openssl library would get statically linked.  Generally speaking that is how `ld` works.

**Comment by centminmod** [comment]
Oh must of read it wrongly. Thanks @kazuho
