### ISSUE TITLE
[h2olog] use original header files

### ISSUE THREAD

**Issue by kazuho** [h2o/h2o#2365]
At the moment, h2olog uses the following approach:
* define copies of certain structs (e.g., `quicly_conn_t`) in h2olog/quic.h
* dump all those struct members

As it is difficult and error-prone to have structs defined in two places, we need to change h2olog to use the header files that we use for building h2o, and in the source code of h2olog (or maybe in the doc-comment of *-probes.d), designate the fields that have to be logged.

**Comment by kazuho** [comment]
To achieve the goal, we might include `quicly.h`, etc., in generated-quic.cc (i.e. the source file generated during the build process, which in turn gets compiled every time `h2olog` is being invoked). The downside of this approach is that it requires hacks, as some header files that `quicly.h` depends on (e.g., `netinet/in.h`) cannot be included when building eBPF code. The other problem is that it creates a *runtime* dependency on quicly.h.

Considering these downsides, it might actually be a better idea to generate *during the build time* a list of (offset, type) of struct members that we need to log. When generating generated-quic.cc, we could also generate C++ code that logs offsets and types of the struct fields that h2olog needs to have access to. To give an example, a code like below can be used to generate pair of `#define` macros that designate the offset and the type of the fields (e.g., `offsetof_quicly_rtt_t_latest`, `typeof_quicly_rtt_t_latest`). Then, we could use these macros in generated-quic.cc.

```
#include <stddef.h>
#include <cstdio>
#include "quicly.h"

#define RESOLVE(name, type, field) resolve(name, &((type *)NULL)->field)

#define DEFINE_RESOLVE_FUNC(type) \
static void resolve(const char *name, const type *p) \
{ \
    printf("#define offsetof_%s %zd\n", name, (const char *)p - (const char *)NULL); \
    printf("#define typeof_%s %s\n", name, "uint32_t"); \
}

DEFINE_RESOLVE_FUNC(uint32_t);
DEFINE_RESOLVE_FUNC(uint64_t);

int main(int argc, char **argv)
{
    // add the struct fields that we need to have access to
    RESOLVE("quicly_rtt_t_latest", quicly_rtt_t, latest);
    return 0;
}
```

**Comment by janaiyengar** [comment]
I like this idea, @kazuho, thank you for helping me understand this. Despite being a bit complex, I think this is robust to all future changes to the code, which I really like.

**Comment by kazuho** [comment]
Heh.

```
% pahole build/default/h2o
...
struct _st_quicly_conn_public_t {
        quicly_context_t *         ctx;                  /*     0     8 */
        quicly_state_t             state;                /*     8     4 */

        /* XXX 4 bytes hole, try to pack */
...
struct st_quicly_stats_t {
        struct {
                uint64_t           received;             /*     0     8 */
                uint64_t           decryption_failed;    /*     8     8 */
                uint64_t           sent;                 /*    16     8 */
                uint64_t           lost;                 /*    24     8 */
                uint64_t           lost_time_threshold;  /*    32     8 */
                uint64_t           ack_received;         /*    40     8 */
                uint64_t           late_acked;           /*    48     8 */
        } num_packets;                                   /*     0    56 */
        struct {
                uint64_t           received;             /*    56     8 */
                /* --- cacheline 1 boundary (64 bytes) --- */
                uint64_t           sent;                 /*    64     8 */
        } num_bytes;                                     /*    56    16 */
        uint32_t                   num_ptos;             /*    72     4 */
        quicly_rtt_t               rtt;                  /*    76    16 */

        /* XXX 4 bytes hole, try to pack */

        quicly_cc_t                cc;                   /*    96    48 */

        /* size: 144, cachelines: 3, members: 5 */
        /* sum members: 140, holes: 1, sum holes: 4 */
        /* last cacheline: 16 bytes */
};
...
```
