### ISSUE TITLE
h2load benchmark errors on h2o = no supported protocol was negotiated

### ISSUE THREAD

**Issue by centminmod** [h2o/h2o#237]
@kazuho hopefully you have some insights as to whether this is a h2load issue or h2o issue ? I borrowed your config for nghttp2 install from your blog and altered it for my CentOS 6.6 64bit install :)

* You can see [install steps I did for nghttp2 here](https://github.com/centminmod/h2o_installer/blob/master/nghttp2/nghttp2_install.sh).
* [h2o installation method](https://github.com/centminmod/h2o_installer/blob/master/h2o_installer.sh) for integration into my Centmin Mod LEMP stack base environment

I am getting error when benchmarking with h2load against h2o server with https on port 8081

    [DEBUG] no supported protocol was negotiated, expected: h2-14, spdy/2, spdy/3, spdy/3.1

nghttp2 was installed with SPDYLAY support but seems this error related to no SPDYLAY https://github.com/tatsuhiro-t/nghttp2/blob/master/src/h2load.cc#L88-L90 ?

h2o version

    /usr/local/bin/h2o -v
    h2o version 1.1.1

h2load version

    /usr/local/http2-15/bin/h2load --version
    h2load nghttp2/0.7.8-DEV

h2load test with https on port 8081

    /usr/local/http2-15/bin/h2load -p h2c-14 -c 10 -m 10 -n 100 -v https://MYHOST.centminmod.com:8081
    starting benchmark...
    spawning thread #0: 10 concurrent clients, 100 total requests
    Protocol: TLSv1.2
    Cipher: ECDHE-RSA-AES128-GCM-SHA256
    Server Temp Key: ECDH P-256 256 bits
    [DEBUG] no supported protocol was negotiated, expected: h2-14, spdy/2, spdy/3, spdy/3.1
    [DEBUG] no supported protocol was negotiated, expected: h2-14, spdy/2, spdy/3, spdy/3.1
    [DEBUG] no supported protocol was negotiated, expected: h2-14, spdy/2, spdy/3, spdy/3.1
    [DEBUG] no supported protocol was negotiated, expected: h2-14, spdy/2, spdy/3, spdy/3.1
    [DEBUG] no supported protocol was negotiated, expected: h2-14, spdy/2, spdy/3, spdy/3.1
    [DEBUG] no supported protocol was negotiated, expected: h2-14, spdy/2, spdy/3, spdy/3.1
    [DEBUG] no supported protocol was negotiated, expected: h2-14, spdy/2, spdy/3, spdy/3.1
    [DEBUG] no supported protocol was negotiated, expected: h2-14, spdy/2, spdy/3, spdy/3.1
    [DEBUG] no supported protocol was negotiated, expected: h2-14, spdy/2, spdy/3, spdy/3.1
    [DEBUG] no supported protocol was negotiated, expected: h2-14, spdy/2, spdy/3, spdy/3.1
    
    finished in 13.58ms, 0 req/s, 0B/s
    requests: 100 total, 0 started, 100 done, 0 succeeded, 100 failed, 100 errored
    status codes: 0 2xx, 0 3xx, 0 4xx, 0 5xx
    traffic: 0 bytes total, 0 bytes headers, 0 bytes data
                         min         max         mean         sd        +/- sd
    time for request:        0us         0us         0us         0us     0.00%

cipherscan output

    ./cipherscan MYHOST.centminmod.com:8081         
    ..............
    Target: MYHOST.centminmod.com:8081
    
    prio  ciphersuite                  protocols              pfs_keysize
    1     ECDHE-RSA-AES256-GCM-SHA384  TLSv1.2                ECDH,P-256,256bits
    2     ECDHE-RSA-AES256-SHA384      TLSv1.2                ECDH,P-256,256bits
    3     ECDHE-RSA-AES256-SHA         TLSv1,TLSv1.1,TLSv1.2  ECDH,P-256,256bits
    4     AES256-GCM-SHA384            TLSv1.2
    5     AES256-SHA256                TLSv1.2
    6     AES256-SHA                   TLSv1,TLSv1.1,TLSv1.2
    7     ECDHE-RSA-AES128-GCM-SHA256  TLSv1.2                ECDH,P-256,256bits
    8     ECDHE-RSA-AES128-SHA256      TLSv1.2                ECDH,P-256,256bits
    9     ECDHE-RSA-AES128-SHA         TLSv1,TLSv1.1,TLSv1.2  ECDH,P-256,256bits
    10    AES128-GCM-SHA256            TLSv1.2
    11    AES128-SHA256                TLSv1.2
    12    AES128-SHA                   TLSv1,TLSv1.1,TLSv1.2
    13    DES-CBC3-SHA                 TLSv1,TLSv1.1,TLSv1.2
    
    Certificate: trusted, 2048 bit, sha256WithRSAEncryption signature
    TLS ticket lifetime hint: 300
    OCSP stapling: supported
    Client side cipher ordering

**Comment by centminmod** [comment]
but if i test h2o on http non-https port 8080 it works ??

    /usr/local/http2-15/bin/h2load -p h2c-14 -c 10 -m 10 -n 100 -v http://MYHOST.centminmod.com:8080
    starting benchmark...
    spawning thread #0: 10 concurrent clients, 100 total requests
    progress: 10% done
    progress: 20% done
    progress: 30% done
    progress: 40% done
    progress: 50% done
    progress: 60% done
    progress: 70% done
    progress: 80% done
    progress: 90% done
    progress: 100% done
    
    finished in 2.02ms, 49627 req/s, 181.56MB/s
    requests: 100 total, 100 started, 100 done, 100 succeeded, 0 failed, 0 errored
    status codes: 100 2xx, 0 3xx, 0 4xx, 0 5xx
    traffic: 383610 bytes total, 1350 bytes headers, 380100 bytes data
                         min         max         mean         sd        +/- sd
    time for request:      434us       941us       734us       189us    74.00%

**Comment by centminmod** [comment]
current h2o.conf config file https://gist.github.com/centminmod/db18853abfd5aaf12617

**Comment by kazuho** [comment]
@centminmod There are several ways for a client to identify if peer is capable of communicating using HTTP/2.  The spec. _requires_ all the implementations to support a TLS extension called ALPN for the purpose (supported in OpenSSL 1.0.2 and above).  Implementations _might_ support another extension called NPN (supported in OpenSSL 1.0.1 and above).  Or implementations _might_ skip the protocol negotiation and just expect that peers support HTTP/2.

The error message of `h2load` you are seeing looks like that h2load is performing some kind of negotiation (which fails).

In such case, I would suggest using the `openssl` command line tool to identify whether the server is capable of negotiating the protocol using the two methods.

* to check if the peer supports NPN, set `-nextprotoneg h2-14` as an argument to the `openssl s_client` tool, and look for `Next protocol: (1) h2-14` in the output
* to check if the peer supposts ALPN, set `-alpn h2-14` as an argument, and look for `ALPN protocol: h2-14` in the output

note: `h2-14` is the identifier for HTTP/2 draft 14; which is supported by H2O and also by h2load looking at the error message.

If the server does not support ALPN nor NPN, it means that you have failed to build H2O with the appropriate version of openssl.
If you can confirm that the server you are running does support both ALPN and NPN, then it would be likely that you have failed to build h2load with the correct version of openssl.

FYI. the full output of `openssl s_client` used for testing the negotiation methods (against google.com) can be found [here](https://gist.github.com/kazuho/34bbd04dcc4382fce615) and [here](https://gist.github.com/kazuho/b26845bb3ad94e47226c).

**Comment by kazuho** [comment]
PS. `-p h2c-14` might be the cause of the issue.  The identifier of the protocol used over TLS is `h2` (not `h2c`); the draft-14 edition should be specified as `-p h2-14`.

>  `/usr/local/http2-15/bin/h2load -p h2c-14 -c 10 -m 10 -n 100 -v https://MYHOST.centminmod.com:8081`

**Comment by centminmod** [comment]
doh didn't notice I added a 'c' but tried without and get

    /usr/local/http2-15/bin/h2load -p h2-14 -c10 -m10 -n100 -v https://MYHOST.centminmod.com:8081
    -p: unsupported protocol h2-14
    
    /usr/local/http2-15/bin/h2load -p h2 -c10 -m10 -n100 -v https://MYHOST.centminmod.com:8081   
    -p: unsupported protocol h2

But I guess the problem is h2load needs OpenSSL 1.0.2 as opposed to OpenSSL 1.0.1 that CentOS 6.x uses. H2O was built with same system OpenSSL 1.0.1 base version that h2load was done with.

for `openssl s_client -alpn h2-14`     

    openssl s_client -alpn h2-14 -host MYHOST.centminmod.com -port 8081
    unknown option -alpn
    usage: s_client args

for `openssl s_client -nextprotoneg h2-14`

    openssl s_client -nextprotoneg h2-14 -host MYHOST.centminmod.com -port 8081

    Protocols advertised by server: h2, h2-16, h2-14

    No client certificate CA names sent
    Server Temp Key: ECDH, prime256v1, 256 bits
    ---
    SSL handshake has read 5002 bytes and written 444 bytes
    ---
    New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
    Server public key is 2048 bit
    Secure Renegotiation IS supported
    Compression: NONE
    Expansion: NONE
    Next protocol: (1) h2-14
    SSL-Session:
        Protocol  : TLSv1.2
        Cipher    : ECDHE-RSA-AES256-GCM-SHA384        

thanks so much for the clarification

**Comment by centminmod** [comment]
tried h2o 1.1.1 with static openssl 1.0.2 but it keeps reporting openssl 1.0.1e even though it's openssl 1.0.2 ? maybe related to this issue ?

    -- Found OpenSSL: /opt/h2o_openssl/lib/libssl.a;/opt/h2o_openssl/lib/libcrypto.a (found version "1.0.1e") 

full output

    h2o-1.1.1]# rm -rf CMakeCache.txt
    
    h2o-1.1.1]# cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_INCLUDE_PATH="/opt/h2o_openssl/include" -DCMAKE_LIBRARY_PATH="/opt/h2o_openssl/lib" .
    -- Looking for include file pthread.h
    -- Looking for include file pthread.h - found
    -- Looking for pthread_create
    -- Looking for pthread_create - not found
    -- Looking for pthread_create in pthreads
    -- Looking for pthread_create in pthreads - not found
    -- Looking for pthread_create in pthread
    -- Looking for pthread_create in pthread - found
    -- Found Threads: TRUE  
    -- Found OpenSSL: /opt/h2o_openssl/lib/libssl.a;/opt/h2o_openssl/lib/libcrypto.a (found version "1.0.1e") 
    -- Could NOT find LIBUV (missing:  LIBUV_LIBRARIES LIBUV_INCLUDE_DIR) 
    -- Found LIBYAML: /usr/lib64/libyaml.so  
    -- Could NOT find WSLAY (missing:  WSLAY_LIBRARIES WSLAY_INCLUDE_DIR) 
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /svr-setup/h2o-1.1.1

pretty sure it's openssl 1.0.2
    
    h2o-1.1.1]# /opt/h2o_openssl/bin/openssl version
    OpenSSL 1.0.2 22 Jan 2015 

compiled with

    STATICLIBSSL=/opt/h2o_openssl
    ./config --prefix=${STATICLIBSSL} --openssldir=${STATICLIBSSL}/ssl no-shared enable-ec_nistp_64_gcc_128

**Comment by kazuho** [comment]
@centminmod I am not sure why cmake says '1.0.1', but looking at the response of `openssl s_client -alpn` it is evident that the server is capable of speaking `h2-14`.

> ```
> /usr/local/http2-15/bin/h2load -p h2-14 -c10 -m10 -n100 -v https://MYHOST.centminmod.com:8081        
> -p: unsupported protocol h2-14
> ```

Looking at `--help` it seems that `-p` is only intended for non-HTTPS connections.  Sorry for the confusion.

So the case seems like that your installation of h2load is not working well for some reason.  If the benchmark tool does not work with no `-p` option, it might be better to ask @tatsuhiro-t for help.

**Comment by centminmod** [comment]
just caught your reply, yeah looks like it could be h2load related so will ask @tatsuhiro-t :)

    /usr/local/http2-15/bin/h2load -c10 -m10 -n100 -v https://MYHOST.centminmod.com:8081         
    starting benchmark...
    spawning thread #0: 10 concurrent clients, 100 total requests
    
    finished in 530us, 0 req/s, 0B/s
    requests: 100 total, 0 started, 100 done, 0 succeeded, 100 failed, 100 errored
    status codes: 0 2xx, 0 3xx, 0 4xx, 0 5xx
    traffic: 0 bytes total, 0 bytes headers, 0 bytes data
                         min         max         mean         sd        +/- sd
    time for request:        0us         0us         0us         0us     0.00%

**Comment by centminmod** [comment]
okay seems with h2load concurrenty of 1 or 2, the test runs and get 100 succeeded requests

if i set concurrenty in h2load to 10, get 100 failed requests

    /usr/local/http2-15/bin/h2load -c1 -m10 -n100 -v https://MYHOST.centminmod.com:8081                 
    starting benchmark...
    spawning thread #0: 1 concurrent clients, 100 total requests
    Protocol: TLSv1.2
    Cipher: ECDHE-RSA-AES128-GCM-SHA256
    Server Temp Key: ECDH P-256 256 bits
    progress: 10% done
    progress: 20% done
    progress: 30% done
    progress: 40% done
    progress: 50% done
    progress: 60% done
    progress: 70% done
    progress: 80% done
    progress: 90% done
    progress: 100% done
    
    finished in 6.65ms, 15028 req/s, 54.84MB/s
    requests: 100 total, 100 started, 100 done, 100 succeeded, 0 failed, 0 errored
    status codes: 100 2xx, 0 3xx, 0 4xx, 0 5xx
    traffic: 382638 bytes total, 675 bytes headers, 380100 bytes data
                         min         max         mean         sd        +/- sd
    time for request:      121us       781us       275us        85us    85.00%
    
    /usr/local/http2-15/bin/h2load -c2 -m10 -n100 -v https://MYHOST.centminmod.com:8081 
    starting benchmark...
    spawning thread #0: 2 concurrent clients, 100 total requests
    Protocol: TLSv1.2
    Cipher: ECDHE-RSA-AES128-GCM-SHA256
    Server Temp Key: ECDH P-256 256 bits
    progress: 10% done
    progress: 20% done
    progress: 30% done
    progress: 40% done
    progress: 50% done
    progress: 60% done
    progress: 70% done
    progress: 80% done
    progress: 90% done
    progress: 100% done
    
    finished in 7.27ms, 13747 req/s, 50.18MB/s
    requests: 100 total, 100 started, 100 done, 100 succeeded, 0 failed, 0 errored
    status codes: 100 2xx, 0 3xx, 0 4xx, 0 5xx
    traffic: 382722 bytes total, 750 bytes headers, 380100 bytes data
                         min         max         mean         sd        +/- sd
    time for request:      406us       757us       566us       100us    57.00%
    
    /usr/local/http2-15/bin/h2load -c10 -m10 -n100 -v https://MYHOST.centminmod.com:8081 
    starting benchmark...
    spawning thread #0: 10 concurrent clients, 100 total requests
    Protocol: TLSv1.2
    Cipher: ECDHE-RSA-AES128-GCM-SHA256
    Server Temp Key: ECDH P-256 256 bits
    
    finished in 10.11ms, 0 req/s, 0B/s
    requests: 100 total, 10 started, 100 done, 0 succeeded, 100 failed, 100 errored
    status codes: 0 2xx, 0 3xx, 0 4xx, 0 5xx
    traffic: 0 bytes total, 0 bytes headers, 0 bytes data
                         min         max         mean         sd        +/- sd
    time for request:        0us         0us         0us         0us     0.00%

**Comment by kazuho** [comment]
> ```
> h2o: md_rand.c:327: ssleay_rand_add: Assertion `md_c[1] == md_count[1]' failed.
> Aborted
> ```
> seems h2load concurrency greater than >3 gives the error

I would suggest looking into OpenSSL.  The assertion is surrounded by `#if !defined(OPENSSL_THREADS) && !defined(OPENSSL_SYS_WIN32)` which apparently means that the OpenSSL library linked to H2O was not configured with support for threads enabled.  My understanding is thread support is enabled by default for OpenSSL, but anyways I think you should rebuild the library with appropriate options.

**Comment by centminmod** [comment]
woohoo ! mystery solved I assumed threads was enabled by default but looks like needed `enable-threads` to be specifically set when compiling openssl 1.0.2 statically on CentOS 6.6 !

h2load concurrency at 10 succeeded !


    /usr/local/http2-15/bin/h2load -c10 -m10 -n100 -v https://MYHOST.centminmod.com:8081 
    starting benchmark...
    spawning thread #0: 10 concurrent clients, 100 total requests
    Protocol: TLSv1.2
    Cipher: ECDHE-RSA-AES128-GCM-SHA256
    Server Temp Key: ECDH P-256 256 bits
    progress: 10% done
    progress: 20% done
    progress: 30% done
    progress: 40% done
    progress: 50% done
    progress: 60% done
    progress: 70% done
    progress: 80% done
    progress: 90% done
    progress: 100% done
    
    finished in 13.17ms, 7593 req/s, 27.78MB/s
    requests: 100 total, 100 started, 100 done, 100 succeeded, 0 failed, 0 errored
    status codes: 100 2xx, 0 3xx, 0 4xx, 0 5xx
    traffic: 383610 bytes total, 1350 bytes headers, 380100 bytes data
                         min         max         mean         sd        +/- sd
    time for request:      325us      1.82ms      1.27ms       461us    70.00%

h2load at 100 concurrency succeed !
    
    /usr/local/http2-15/bin/h2load -c100 -m10 -n100 -v https://MYHOST.centminmod.com:8081
    starting benchmark...
    spawning thread #0: 100 concurrent clients, 100 total requests
    Protocol: TLSv1.2
    Cipher: ECDHE-RSA-AES128-GCM-SHA256
    Server Temp Key: ECDH P-256 256 bits
    progress: 10% done
    progress: 20% done
    progress: 30% done
    progress: 40% done
    progress: 50% done
    progress: 60% done
    progress: 70% done
    progress: 80% done
    progress: 90% done
    progress: 100% done
    
    finished in 80.93ms, 1235 req/s, 4.64MB/s
    requests: 100 total, 100 started, 100 done, 100 succeeded, 0 failed, 0 errored
    status codes: 100 2xx, 0 3xx, 0 4xx, 0 5xx
    traffic: 393600 bytes total, 8100 bytes headers, 380100 bytes data
                         min         max         mean         sd        +/- sd
    time for request:     2.82ms     23.53ms     10.77ms      3.51ms    82.00%    

thanks @kazuho :+1: 

now to learn more about the finer points of using h2load :)

**Comment by kazuho** [comment]
:+1:
