### ISSUE TITLE
The site https://h2o.examp1e.net/ certificate is expried

### ISSUE THREAD

**Issue by gcnyin** [h2o/h2o#2435]
<img width="409" alt="Screen Shot 2020-08-26 at 19 54 52" src="https://user-images.githubusercontent.com/53973962/91300632-31a2ec80-e7d6-11ea-97b6-97d511674551.png">

**Comment by kazuho** [comment]
Thank you for the remainder. We have a new server instance that (of course) does automatic renewal of certificates, but I haven't moved the data there...
