### ISSUE TITLE
h2o proxy error = node must be a MAPPING

### ISSUE THREAD

**Issue by centminmod** [h2o/h2o#246]
Trying to setup reverse proxy where backend is centminmod.com on port 80 and getting error

    [/usr/local/h2o/h2o.conf:88] node must be a MAPPING

line 88 of my h2o.conf is

     proxy.reverse.url: http://centminmod.com:80/

any guidance is much appreciated :)

**Comment by kazuho** [comment]
@centminmod Sorry for keeping you waiting!

> ```
> [/usr/local/h2o/h2o.conf:88] node must be a MAPPING
> ```

Seems like an error reported by the YAML parser; does it get fixed if you quote the URL using ```""```?

However, I do not see such issue on my side, which means that if it the case then it is likely due to the differences bet. the libyaml versions we use.

Therefore I would suggest you to resolve #251 first; now that libyaml is bundled to H2O (merged to master #248), we would not have such issues from now on.

**Comment by kazuho** [comment]
BTW, I saw your benchmark via Twitter.  Awesome work!

**Comment by centminmod** [comment]
yeah will sort out segfaults in h2o first

and you're welcome - h2o benchmarking is fun :)

**Comment by kazuho** [comment]
@centminmod are you still having this issue?

**Comment by centminmod** [comment]
no i don't get that error in 1st post but the proxy for `h2oproxy1.centminmod.com:8083` isn't proxying content from my set backend `proxy.reverse.url: http://centminmod.com:80/` ?

    "h2oproxy1.centminmod.com:8083":
      listen:
        host: 0.0.0.0
        port: 8083
        ssl:
          certificate-file: /usr/local/h2o/centminmod.com-unified.crt
          key-file: /usr/local/h2o/centminmod.com.key
          minimum-version: TLSv1
          cipher-suite: ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-RSA-AES128-GCM-SHA256$
          dh-file: /usr/local/nginx/conf/ssl/centminmod_rsa/dhparam4096.pem
          cipher-preference: server
      header.add: "SSL Host: 8083"
      paths:
        /:
          file.dir: /home/nginx/domains/h2ohttp2.centminmod.com/public
          proxy.reverse.url: http://centminmod.com:80/
      access-log: /usr/local/h2o/logs/access-alternate.log

**Comment by centminmod** [comment]
nevermind it works, once i remove `file.dir: /home/nginx/domains/h2ohttp2.centminmod.com/public` :)

**Comment by kazuho** [comment]
Thank you for checking!  Glad to hear that it's solved.

Maybe there should be a restriction that forbids multiple handlers (e.g. `file.dir` and `proxy.reverse.url`) being defined against a single path.

**Comment by centminmod** [comment]
or maybe have a proxy on/off variable in host, if proxy on it ignores all handlers at path level i.e. file.* and only looks for proxy.* ones ? if proxy off, then it ignores all proxy.* handlers

**Comment by kazuho** [comment]
That's a good point!

Actually, at the source code level handlers can be delegated.  That was the intention when writing the code.  However it seems that we do not usually need such feature (as a default).
