### ISSUE TITLE
Is python mojo prediction supposed to be slower?

### ISSUE THREAD

**Issue by rich-staackmann** [h2o/h2o#2466]
I have an H2O python application that I recently converted to containers for kubernetes. As part of the conversion I started saving MOJO files when training and using MOJO prediction in the python flask api running on the container. However, I have seen a massive performance drop when doing this. I've searched around a lot and haven't been able to find much on the issue. Part of me wonders if I am simply using the wrong pattern for mojo prediction. I wanted to predict without running H2O on the container, to keep the container simpler. So I use the mojo_predict_pandas method.

However, I don't really see anyone else use this method when I search the internet. Most people load the mojo into the H2O server and then call it for predictions. Is this the more correct way, should I be running h2o in my api container? Is the mojo_predict_pandas method not suited for fast performance?

 Below I have included a snippet of the code from my flask api.

```
gbmModelPredict = h2o.mojo_predict_pandas(predictionParams, gbmModel)
ubModelPredict = h2o.mojo_predict_pandas(predictionParams, ubModel)
lbModelPredict = h2o.mojo_predict_pandas(predictionParams, lbModel)
```

**Comment by syohex** [comment]
h2oai repository is https://github.com/h2oai/h2o-3 . Here is HTTP server repository.

**Comment by rich-staackmann** [comment]
My bad, thank you.
