### ISSUE TITLE
Code duplication found using pmd

### ISSUE THREAD

**Issue by mingodad** [h2o/h2o#249]
Hello !

Using http://pmd.sourceforge.net/pmd-4.3.0/cpd.html over h2o sources it reports the following:

Found a 17 line (149 tokens) duplication in the following files: 
Starting at line 37 of /home/mingo/dev/c/web-servers/h2o-dad/lib/handler/file/templates.c.h
Starting at line 53 of /home/mingo/dev/c/web-servers/h2o-dad/lib/handler/file/templates.c.h

        h2o_iovec_t _s = (h2o_iovec_init(H2O_STRLIT("<!DOCTYPE html>\n<TITLE>Index of ")));
        if (_s.len != 0 && _s.base[_s.len - 1] == '\n')
            --_s.len;
        h2o_buffer_reserve(&_, _s.len);
        memcpy(_->bytes + _->size, _s.base, _s.len);
        _->size += _s.len;
    }
    {
        h2o_iovec_t _s = (path_normalized_escaped);
        if (_s.len != 0 && _s.base[_s.len - 1] == '\n')
            --_s.len;
        h2o_buffer_reserve(&_, _s.len);
        memcpy(_->bytes + _->size, _s.base, _s.len);
        _->size += _s.len;
    }
    {
        h2o_iovec_t _s = (h2o_iovec_init(H2O_STRLIT("</TITLE>\n<H2>Index of ")));
=====================================================================
Found a 17 line (149 tokens) duplication in the following files: 
Starting at line 83 of /home/mingo/dev/c/web-servers/h2o-dad/lib/handler/file/templates.c.h
Starting at line 99 of /home/mingo/dev/c/web-servers/h2o-dad/lib/handler/file/templates.c.h

            h2o_iovec_t _s = (h2o_iovec_init(H2O_STRLIT("<LI><A HREF=\"")));
            if (_s.len != 0 && _s.base[_s.len - 1] == '\n')
                --_s.len;
            h2o_buffer_reserve(&_, _s.len);
            memcpy(_->bytes + _->size, _s.base, _s.len);
            _->size += _s.len;
        }
        {
            h2o_iovec_t _s = (fn_escaped);
            if (_s.len != 0 && _s.base[_s.len - 1] == '\n')
                --_s.len;
            h2o_buffer_reserve(&_, _s.len);
            memcpy(_->bytes + _->size, _s.base, _s.len);
            _->size += _s.len;
        }
        {
            h2o_iovec_t _s = (h2o_iovec_init(H2O_STRLIT("\">")));
=====================================================================
Found a 9 line (75 tokens) duplication in the following files: 
Starting at line 45 of /home/mingo/dev/c/web-servers/h2o-dad/lib/handler/file/templates.c.h
Starting at line 61 of /home/mingo/dev/c/web-servers/h2o-dad/lib/handler/file/templates.c.h
Starting at line 91 of /home/mingo/dev/c/web-servers/h2o-dad/lib/handler/file/templates.c.h
Starting at line 107 of /home/mingo/dev/c/web-servers/h2o-dad/lib/handler/file/templates.c.h

        h2o_iovec_t _s = (path_normalized_escaped);
        if (_s.len != 0 && _s.base[_s.len - 1] == '\n')
            --_s.len;
        h2o_buffer_reserve(&_, _s.len);
        memcpy(_->bytes + _->size, _s.base, _s.len);
        _->size += _s.len;
    }
    {
        h2o_iovec_t _s = (h2o_iovec_init(H2O_STRLIT("</TITLE>\n<H2>Index of ")));

**Comment by mingodad** [comment]
If we run over the deps folder there is also some duplications on klib.

**Comment by kazuho** [comment]
Thank you for noticing the issue.

lib/handler/file/templates.c.h is an automatically generated file (from lib/handler/file/_templates.c.h by misc/regen-all.sh), so code duplication is not a problem.
klib is an external project and we should ignore reports under the directory as well.
