### ISSUE TITLE
[libh2o][libuv] Corruptions due to faulty timer handling

### ISSUE THREAD

**Issue by cbay** [h2o/h2o#2511]
I've run into random bugs (segmentation faults, assertion errors) when using libh2o with libuv. During investigation, I've noticed that simply running `examples/libh2o/simple.c` generates those crashes, which means there's likely a bug inside libh2o.

On my computer, setting `#define USE_HTTPS 0` (rather than 1) in `simple.c` helps trigger the bug, for some reason. Here's what I get when running `examples-simple-libuv` and launching many requests at it (using `ab` in my case):

```
[...]
127.0.0.1 - - [17/Dec/2020:12:51:26 +0100] "GET / HTTP/1.0" 200 177 "-" "ApacheBench/2.3"
127.0.0.1 - - [17/Dec/2020:12:51:26 +0100] "GET / HTTP/1.0" 200 177 "-" "ApacheBench/2.3"
examples-simple-libuv: /home/cbay/h2o/lib/common/memory.c:96: h2o_mem_alloc_recycle: Assertion `chunk != NULL' failed.
```

This is reproductible at every run, typically after a few hundreds requests were served.

In gdb:

```
#0  0x00007ffff7810615 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff77f9862 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff77f9747 in __assert_fail_base.cold () from /usr/lib/libc.so.6
#3  0x00007ffff7808bf6 in __assert_fail () from /usr/lib/libc.so.6
#4  0x000055555556f360 in h2o_mem_alloc_recycle (allocator=0x5555556770a0, sz=93824992348827) at /home/cbay/h2o/lib/common/memory.c:96
#5  0x000055555556f93b in h2o_buffer_try_reserve (_inbuf=0x555555677160, min_guarantee=93824992348791) at /home/cbay/h2o/lib/common/memory.c:256
#6  0x0000555555570a45 in alloc_inbuf (buf=0x555555677160, _vec=0x7fffffffadd0) at /home/cbay/h2o/lib/common/socket/uv-binding.c.h:42
#7  0x0000555555570aad in alloc_inbuf_tcp (handle=0x555555677050, suggested_size=65536, buf=0x7fffffffadd0) at /home/cbay/h2o/lib/common/socket/uv-binding.c.h:54
#8  0x00007ffff7f64a3c in ?? () from /usr/lib/libuv.so.1
#9  0x00007ffff7f657f8 in ?? () from /usr/lib/libuv.so.1
#10 0x00007ffff7f6b7e4 in uv.io_poll () from /usr/lib/libuv.so.1
#11 0x00007ffff7f5a4e7 in uv_run () from /usr/lib/libuv.so.1
#12 0x000055555556ef68 in main (argc=1, argv=0x7fffffffe5f8) at /home/cbay/h2o/examples/libh2o/simple.c:280
```

We have a corrupted `h2o_buffer_t` object. When using [rr](https://rr-project.org/) to find out what corrupts it, it tells me that's libuv, in `uv__finish_close`, line `QUEUE_REMOVE(&handle->handle_queue)`. There are some occasional variations, but libuv seemed the culprit.

After more investigation and debugging, I've found that the timer handling in `uv-binding.c.h` seems wrong.

`h2o_timer_link` calls `uv_timer_start`, but `h2o_timer_unlink` never calls `uv_close` (calling `uv_timer_stop` doesn't free the handle). Which means that libuv keeps references to an object that will get freed at some point, with its memory reused, hence the corruption.

One could think that calling `uv_close` in `h2o_timer_unlink` would be enough, but it wouldn't work. libuv [keeps references](http://docs.libuv.org/en/v1.x/handle.html#c.uv_close) to the object until the `uv_close` callback is called, which typically means at the next loop run. Unfortunately, libh2o frees memory before, for instance in `http1.c`, `close_connection`: `free` is called immediately after calling `h2o_timer_unlink`. There's no way to [free objects immediately](https://github.com/libuv/libuv/issues/1536) using libuv.

That's why I ended up allocating `uv_timer_t` objects on the heap instead. The incoming pull request fixes the issue for me.

These crashes was reproduced on several systems (Arch Linux, Debian Buster), with several libuv versions (1.40, 1.24), on h2o master and 2.3.0-beta2. The evloop version works properly.

**Comment by kazuho** [comment]
Thank you for reporting the issue, and thank you very much for the great analysis. Makes perfect sense. I'm running CI with the proposed changes. PR #2512 to be merged once the CI successfully concludes (as expected).
