### ISSUE TITLE
How to Proxy from mruby handler ?

### ISSUE THREAD

**Issue by Jxck** [h2o/h2o#2523]
Hi team.

In amp sxg usecase, I need to forward request to backend server (amppkger) based on request headers (not a path).

- https://github.com/ampproject/amppackager#productionizing

What I need to do is something like...

```ruby
# proxy.rb
Proc.new do |env|
  amp_cache_transform = env["HTTP_AMP_CACHE_TRANSFORM"]
  if amp_cache_transform
    # proxy to http://127.0.0.1:8080/
  end
  [399, {}, []]
end
```

```
"example.com:443":
  paths:
    "/": 
      mruby.handler-file: proxy.rb
```

How can I make this happen ?

**Comment by kazuho** [comment]
There are two solutions; either use the reproxy handler or use the HTTP client available in our mruby handler. Both solutions are explained in https://h2o.examp1e.net/configure/mruby.html.

**Comment by Jxck** [comment]
Ah, I assumed that reproxy is only for same domain (as example mentioned). but it works for server running on the other ports too.
Thanks for your help !
