### ISSUE TITLE
how to use LIBRESSL ?

### ISSUE THREAD

**Issue by centminmod** [h2o/h2o#253]
Noticed latest alpha has added LIBRESSL bundle but how do yo use ?

I tried

    cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DUSE_BUNDLED_SSL=ON .

but get this warning

    CMake Warning:
      Manually-specified variables were not used by the project:
    
        USE_BUNDLED_SSL

CentOS 6.6 32bit OS

**Comment by kazuho** [comment]
Name of the configuration variable is `WITH_BUNDLED_SSL`, not `USE_BUNDLED_SSL`.

**Comment by centminmod** [comment]
ah ha ! thanks @kazuho
