### ISSUE TITLE
[CI] Remaining issues wrt GitHub Actions

### ISSUE THREAD

**Issue by kazuho** [h2o/h2o#2532]
Thanks to @gfx and others, I am very happy to see our new CI process on GitHub Actions is running smoothly.

We still the following minor issues though:
* Occasional failure in t/40max-connections.t. To be fixed by PR #2531.
* Cannot restart the failed flavor. With Travis CI, it is possible to rerun the flavor that failed. With GitHub Actions using the current workflow definition, the only option is to rerun all.
* No "no output" timeout. Travis CI automatically terminates when there is no output for 10 minutes. GitHub Actions does not have the same feature and the CI process runs forever.

Note: the list above calls out issues exclusively; it intentionally excludes outstanding PRs that I consider as improvements (e.g., #2520, #2529).

**Comment by gfx** [comment]
> No "no output" timeout. Travis CI automatically terminates when there is no output for 10 minutes. GitHub Actions does not have the same feature and the CI process runs forever.

We can set a timeout for each step. I think 60min is a conservative but appropriate value since most of the builds are done in 40min.

**Comment by kazuho** [comment]
@gfx Re timeout, 60 minutes SGTM! Thank you.

**Comment by kazuho** [comment]
Re restarting failed flavor, chatted with @gfx elsewhere, agreed that we would look into splitting the YAML files once it becomes painful, and https://github.community/t/ability-to-rerun-just-a-single-job-in-a-workflow/17234 remains unresolved.

**Comment by kazuho** [comment]
Closing.

Out of the three issues being pointed out, the first issue has been addressed by #2531, second issue by #2535. As discussed above, we will revisit the third issue when it becomes painful.
