### ISSUE TITLE
Even more mime types ?

### ISSUE THREAD

**Issue by centminmod** [h2o/h2o#254]
I see you added webp, but why not add more ? i ran into problem with favicon .ico prompting for download on h2o

here's nginx's supported mime types

    text/html                             html htm shtml;
    text/css                              css;
    text/xml                              xml;
    image/gif                             gif;
    image/jpeg                            jpeg jpg;
    application/x-javascript              js;
    application/atom+xml                  atom;
    application/rss+xml                   rss;
    text/mathml                           mml;
    text/plain                            txt;
    text/vnd.sun.j2me.app-descriptor      jad;
    text/vnd.wap.wml                      wml;
    text/x-component                      htc;
    image/png                             png;
    image/tiff                            tif tiff;
    image/vnd.wap.wbmp                    wbmp;
    image/x-icon                          ico;
    image/x-jng                           jng;
    image/x-ms-bmp                        bmp;
    image/svg+xml                         svg svgz;
    image/webp                            webp;
    application/java-archive              jar war ear;
    application/mac-binhex40              hqx;
    application/msword                    doc;
    application/pdf                       pdf;
    application/postscript                ps eps ai;
    application/rtf                       rtf;
    application/vnd.ms-excel              xls;
    application/vnd.ms-powerpoint         ppt;
    application/vnd.wap.wmlc              wmlc;
    application/vnd.google-earth.kml+xml  kml;
    application/vnd.google-earth.kmz      kmz;
    application/x-7z-compressed           7z;
    application/x-cocoa                   cco;
    application/x-java-archive-diff       jardiff;
    application/x-java-jnlp-file          jnlp;
    application/x-makeself                run;
    application/x-perl                    pl pm;
    application/x-pilot                   prc pdb;
    application/x-rar-compressed          rar;
    application/x-redhat-package-manager  rpm;
    application/x-sea                     sea;
    application/x-shockwave-flash         swf;
    application/x-stuffit                 sit;
    application/x-tcl                     tcl tk;
    application/x-x509-ca-cert            der pem crt;
    application/x-xpinstall               xpi;
    application/xhtml+xml                 xhtml;
    application/zip                       zip;
    application/octet-stream              bin exe dll;
    application/octet-stream              deb;
    application/octet-stream              dmg;
 
    application/octet-stream              iso img;
    application/octet-stream              msi msp msm;
    audio/midi                            mid midi kar;
    audio/mpeg                            mp3;
    audio/ogg                             ogg;
    audio/x-m4a                           m4a;
    audio/x-realaudio                     ra;
    video/3gpp                            3gpp 3gp;
    video/mp4                             mp4;
    video/mpeg                            mpeg mpg;
    video/quicktime                       mov;
    video/webm                            webm;
    video/x-flv                           flv;
    video/x-m4v                           m4v;
    video/x-mng                           mng;
    video/x-ms-asf                        asx asf;
    video/x-ms-wmv                        wmv;
    video/x-msvideo                       avi;
    application/vnd.ms-fontobject           eot;
    application/x-font-ttf                  ttf;
    font/opentype                           ott;
    application/font-woff                   woff;

**Comment by centminmod** [comment]
oh i just added this yesterday as i switched my font/fontawesome from woff to woff2 for smaller sized files too

    application/font-woff2                   woff2;

**Comment by kazuho** [comment]
@centminmod Would you mind providing a link to the source of the information so that we could track the changes in the future?

**Comment by centminmod** [comment]
you mean https://github.com/h2o/h2o/pull/250 or http://trac.nginx.org/nginx/browser/nginx/conf/mime.types (2nd link is missing some mime types compared to above list as I added those myself)

these are additional ones I added to nginx's mime.types

    application/vnd.ms-fontobject           eot;
    application/x-font-ttf                  ttf;
    font/opentype                           ott;
    application/font-woff                   woff;
    application/font-woff2                  woff2;

**Comment by kazuho** [comment]
@centminmod Hi, sorry to be late; the default list of mime types is going to get updated in #280 (which at the moment is equivalent to that of nginx; thank you for the link).

> ```
> application/vnd.ms-fontobject           eot;
> application/x-font-ttf                  ttf;
> font/opentype                           ott;
> application/font-woff                   woff;
> application/font-woff2                  woff2;
> ```

Regarding these entries being proposed, some of the mime-types used here do not appear in http://www.iana.org/assignments/media-types/media-types.xhtml.  Please update the list so that it would be compatible with the registered ones being registered.

**Comment by centminmod** [comment]
thanks @kazuho will do

updated my h2o test server works wonderfully :+1:
