### ISSUE TITLE
h2o HTTP/2 vs nginx SPDY/3.1 vs openlitespeed HTTP/2

### ISSUE THREAD

**Issue by centminmod** [h2o/h2o#255]
Round 2 comparisons for you @kazuho https://community.centminmod.com/threads/http-2-h2o-vs-openlitespeed-vs-nginx-spdy-3-1.2564/ :)

**Comment by centminmod** [comment]
summarized in one nice webpagetest.org pageload speed chart for https://h2ohttp2.centminmod.com:8081/webpagetests1.html

![WPT Tests](https://h2ohttp2.centminmod.com:8081/wptcharts/wpt.png)

**Comment by kazuho** [comment]
Closing the issue (as IMO it is not actually a problem nor a FAQ).  Thank you for benchmark, I really appreciate that.
