### ISSUE TITLE
multiple host name resolution on http vs https ?

### ISSUE THREAD

**Issue by centminmod** [h2o/h2o#256]
For my next tests I want to see difference between SPDY/3.1 vs HTTP/2 for multiple hostname multiplexing in HTTP/2 but having trouble setting up http on port 8080 to resolve multiple hostnames ? Seems https on port 8081 does it automatically without me needing to configure anything ?

So HTTP/2 on h2o port 8081 already works for

* https://h2ohttp2.centminmod.com:8081
* https://h2ohttp2b.centminmod.com:8081
* https://h2ohttp2c.centminmod.com:8081

But for http h2o on port 8080 it doesn't work ?

* https://h2ohttp2.centminmod.com:8080
* https://h2ohttp2b.centminmod.com:8080
* https://h2ohttp2c.centminmod.com:8080

what needs changing in my h2o.conf for it to work for http on port 8080 ? my h2o.conf is like https://gist.github.com/centminmod/d985f92ee549021e926e

on Nginx is was easy

    server_name h2ohttp2.centminmod.com h2ohttp2b.centminmod.com h2ohttp2c.centminmod.com;

**Comment by kazuho** [comment]
Each element of the `hosts` section are bound to the `listen` directives within the element, and to the `listen` directives at the global level.

So if you want to bind port 8080 to hosts: `h2ohttp2:8080`, `h2ohttp2b:8080`, `h2ohttp2c:8080`, the configuration file should look like:

```
hosts:
  "h2ohttp2:8080":
    listen: 8080
    ...
  "h2ohttp2b:8080":
    listen: 8080
    ...
  "h2ohttp2c:8080":
    listen: 8080
    ...
```

**Comment by centminmod** [comment]
i see but from this config https://gist.github.com/centminmod/d985f92ee549021e926e why did 8081 work with multiple host names but not 8080 as both 8080 and 8081 have listen at global level ?

**Comment by centminmod** [comment]
okay this is the current working revised h2o.conf https://gist.github.com/centminmod/63afbb999ef4d8f079bf/affdf83f2bf82658c9c12bbfbfe752d48031f44d

still get seg faults signal 11 on start up if i add any headers to any of the additional hosts though

**Comment by kazuho** [comment]
@centminmod Has this issue been resolved?  I am getting confused.

I understand that you are still suffering from signal 11 issues on your 32-bit platform, but I think it would be appropriate to handle the case on the issue dedicated to the topic (#251).

**Comment by centminmod** [comment]
yup multiple hostnames works as per your suggestion :)

**Comment by kazuho** [comment]
Great!
