### ISSUE TITLE
update FreeBSD www/h2o-devel port to a recent git commit

### ISSUE THREAD

**Issue by dch** [h2o/h2o#2586]
I'd like to update the very old `2.3.0-beta2` FreeBSD port to a git snapshot on a regular basis. As I don't have email addresses for a number of the FreeBSD users here, I'm hijacking the issue to get some feedback if this would work for you. You're welcome to email me dch@FreeBSD.org privately for next time.

@devnexen @utrenkner @tintinabula  @UlasSAYGINIM @csjperon any thoughts?

**Comment by devnexen** [comment]
It is delicate balance, waiting next tag/release or a particular commit. Another more or less similar example is jemalloc which misses the 13.0 release train https://github.com/jemalloc/jemalloc/issues/2030#issuecomment-783789742

**Comment by utrenkner** [comment]
Sorry for the late reply: I would love to get a hand on more up-to-date versions of H2O. As you know, I am using my own back-port of a [bug fix](https://github.com/h2o/h2o/pull/2254) that was merged to master more than a year ago. Being able to get proper packages with modern H2O versions would be fantastic.

Many thanks in advance for your work!

**Comment by xm74** [comment]
> I'd like to update the very old 2.3.0-beta2 FreeBSD port to a git snapshot on a regular basis

That would be great. I have multiple instances of H2O-devel in production, so I could take part in testing the updated port.

**Comment by UlasSAYGINIM** [comment]
can you also look for dragonflybsd version too? if it is not too much :) because as far as i remember, it copies from freebsd generally. 
but also it will need special care maybe , because of previous bug about dragonflybsd.

after update i can test it. i have no production server for it. but why not if it is updated regularly.

**Comment by UlasSAYGINIM** [comment]
i am talking about his issue, if someone solve that issue too. that would be fantastic news!

https://github.com/kazuho/picohash/issues/2

**Comment by dch** [comment]
I've made some progress on this already; is that enough for people to test out?

https://git.sr.ht/~dch/ports/commit/95b0efa86ef3d7c1c63bee7f671aa5caba0ad5ba
https://git.sr.ht/~dch/ports/commit/95b0efa86ef3d7c1c63bee7f671aa5caba0ad5ba.patch

If you need pre-built packages, I can probably arrange that.

**Comment by utrenkner** [comment]
Thank you, @dch !!! I'll give it a try, this week.

**Comment by utrenkner** [comment]
After a successful test, one new h2o-devel is already running in production. No problems so far, logs are showing normal behaviour.

For the record: This is on HardenedBSD 12.2-STABLE:
```
# h2o -v
h2o version 2.3.0-DEV
OpenSSL: OpenSSL 1.1.1k-freebsd  25 Mar 2021
mruby: YES
```

Will upgrade the next jail(s), soon.

**Comment by utrenkner** [comment]
BTW: Does anyone here have a config for how to enable HTTP/3? Found some lines of older config, but did not manage to get HTTP/3 working (did not have much time to investigate further).

**Comment by utrenkner** [comment]
Hi @dch , some further feedback: I upgraded two more production instances to your new port (one, again, on HardenedBSD 12.2-STABLE and one on FreeBSD 13.0-RELEASE). Nothing unusual happened - everything works as before. 

So: Good work - many thanks, again!

**Comment by hfujita** [comment]
> BTW: Does anyone here have a config for how to enable HTTP/3? Found some lines of older config, but did not manage to get HTTP/3 working (did not have much time to investigate further).

Maybe you could try this out? I think this would be a minimal config to make it work.
```
listen:
  type: quic
  port: 8443
  ssl:
    key-file: examples/h2o/server.key
    certificate-file: examples/h2o/server.crt

hosts:
  default:
    paths:
      /:
        file.dir: /examples/doc_root
```

**Comment by xm74** [comment]
How I did this

```
listen:
    port: 80
listen:
    port: 443
    ssl: &default_ssl
        cipher-preference: server
        min-version: TLSv1.2
        dh-file: /etc/ssl/dhparams.pem
        certificate-file: /usr/local/etc/letsencrypt/live/xxx/fullchain.cur.pem
        key-file: /usr/local/etc/letsencrypt/live/xxx/privkey.cur.pem
listen:
    port: 443
    ssl: *default_ssl
    type: quic

header.add: "alt-svc: h3-29=\":443\"; ma=600"

**Comment by utrenkner** [comment]
@hfujita and @xm74 Thanks, I hope to find the time to play with HTTP/3, soon!

@dch I just noticed your updated h2o-devel port in the FreeBSD ports tree. Many thanks. I hope it was still in time for the Q3-quarterly branch so that I can go back to using the official packages.

**Comment by dch** [comment]
yes it should be in quarterly again
