### ISSUE TITLE
h2o opportunistic encryption and PHP

### ISSUE THREAD

**Issue by centminmod** [h2o/h2o#262]
As h2o doesn't support PHP yet (would love to have PHP-FPM support), would opportunistic encryption still work for PHP requests if I had Nginx + PHP-FPM site on port 80 and setup AltSvc h2 header on h2o port 8081. Unauthenticated encrypted PHP data from http port 80 to port 8081 would just pass onto PHP-FPM service running on port 9000 (PHP-FPM) and back ? Or would h2o need to work with PHP-FPM as well first for OE ?

**Comment by kazuho** [comment]
When working as a reverse proxy H2O rewrites only the headers that are required to be treated as such by the HTTP RFC.

In other words, I do not see any issues in such a configuration, since AltSvc headers are not defined _within_ the HTTP specification.

**Comment by centminmod** [comment]
cheers @kazuho
