### ISSUE TITLE
H2O.next.call(env) does not seem to send request body for method POST

### ISSUE THREAD

**Issue by utrenkner** [h2o/h2o#2686]
I have had problems with ``H2O.next.call(env)`` for years and always tried to avoid it. Now, I tried again and to me it seems that the content of POST is not transmitted. I can capture GET content but never POST content. Is this intended behaviour? It makes ``H2O.next.call(env)`` completely useless to me.

Note: I use the "latest" beta release, 2.3.0-beta2.

**Comment by utrenkner** [comment]
Further tests: ``H2O.reprocess.call(env)`` suffers from the same problem - no POST content transmitted...

Thus, it looks like a bug in ``call(env)`` to me. Has this been fixed already in current code (after 2.3.0-beta2)?

**Comment by utrenkner** [comment]
Has anyone looked into this likely bug?

It makes it impossible to e.g. [strip cookies from the response](https://github.com/h2o/h2o/issues/2139#issuecomment-537762729) as suggested by @i110 . H2O.next.call(env) works only for GET requests.

**Comment by i110** [comment]
@utrenkner Thank you for raising this (and sorry for missing this issue). Would you mind sharing reproducible configuration of that bug?

**Comment by i110** [comment]
I just tried the latest master with the following conf

```
hosts:
  "127.0.0.1:8080":
    paths:
      /:
        mruby.handler: |
          proc {|env|
            resp = H2O.next.call(env)
            resp[1]['x-foo'] = 'FOO'
            resp
          }
        proxy.reverse.url: http://127.0.0.1:9000
```

with spawning the upstream by
```
echo -n 'HTTP/1.1 200 OK\r\n\r\n' | nc -l 9000
```

and issued the request to h2o by `curl -sv -X POST --data-binary "FOOBAR" http://0:8080`, then the upstream logged the request body correctly
```
POST / HTTP/1.1
host: 127.0.0.1:9000
connection: keep-alive
content-length: 6
accept: */*
user-agent: curl/7.64.1
content-type: application/x-www-form-urlencoded
x-forwarded-proto: http
x-forwarded-for: 127.0.0.1
via: 1.1 0:8080

FOOBAR
```

Does this work for you?

**Comment by utrenkner** [comment]
Thank you for your reply, @i110 

I tested your configuration on two different systems, but don't get the POST-content - the response is identical to yours, except for a missing content-type and the POST-content itself.

```
POST / HTTP/1.1
host: 127.0.0.1:9000
connection: keep-alive
content-length: 6
accept: */*
user-agent: curl/7.75.0
x-forwarded-proto: http
x-forwarded-for: 127.0.0.1
via: 1.1 0:8080
```

I also changed the setup and answered the request to http://127.0.0.1:9000 with this PHP-file (dumping the content of $_GET, $_POST and $_SERVER):
```
<?php
echo "GET:\n";
var_dump($_GET);
echo "POST:\n";
var_dump($_POST);
echo "SERVER:\n";
var_dump($_SERVER);

```

I then made this call ``curl -sv -X POST --data-binary "FOOBAR" "http://0:8080/?test=123"``, and was able to capture the GET-variable, but not the POST-content:

```
GET:
array(1) {
  ["test"]=>
  string(3) "123"
}
POST:
array(0) {
}
SERVER:
array(27) {
  ["HOME"]=>
  string(12) "/nonexistent"
  ["USER"]=>
  string(3) "www"
  ["HTTP_VIA"]=>
  string(10) "1.1 0:8080"
  ["HTTP_X_FORWARDED_FOR"]=>
  string(8) "10.0.0.7"
  ["HTTP_X_FORWARDED_PROTO"]=>
  string(4) "http"
  ["HTTP_USER_AGENT"]=>
  string(11) "curl/7.75.0"
  ["HTTP_ACCEPT"]=>
  string(3) "*/*"
  ["HTTP_CONNECTION"]=>
  string(10) "keep-alive"
  ["SERVER_SOFTWARE"]=>
  string(15) "h2o/2.3.0-beta2"
  ["SERVER_PROTOCOL"]=>
  string(8) "HTTP/1.1"
  ["SERVER_NAME"]=>
  string(9) "127.0.0.1"
  ["SERVER_PORT"]=>
  string(4) "9000"
  ["SERVER_ADDR"]=>
  string(9) "127.0.0.1"
  ["REQUEST_URI"]=>
  string(10) "/?test=123"
  ["HTTP_HOST"]=>
  string(14) "127.0.0.1:9000"
  ["REQUEST_METHOD"]=>
  string(4) "POST"
  ["TZ"]=>
  string(13) "Europe/Berlin"
  ["REMOTE_PORT"]=>
  string(5) "54718"
  ["REMOTE_ADDR"]=>
  string(9) "127.0.0.1"
  ["QUERY_STRING"]=>
  string(8) "test=123"
  ["SCRIPT_NAME"]=>
  string(1) "/"
  ["SCRIPT_FILENAME"]=>
  string(28) "/usr/local/www/data/post.php"
  ["CONTENT_LENGTH"]=>
  string(1) "6"
  ["FCGI_ROLE"]=>
  string(9) "RESPONDER"
  ["PHP_SELF"]=>
  string(1) "/"
  ["REQUEST_TIME_FLOAT"]=>
  float(1622457093.1145)
  ["REQUEST_TIME"]=>
  int(1622457093)
}
```

Again, this is using the latest Beta-Release (h2o/2.3.0-beta2). As you show that it works for you with the latest master, I will have to give that a try (but I don't have the time right now... I probably come back tomorrow with the results).

**Comment by utrenkner** [comment]
Sorry, @i110, while testing different versions, I noticed that all my problems with POST and ``H2O.next.call(env)`` were due to my "backport" of your #2254! I would like to apologize for my wrong alarm and for taking your time.

I hope that there will be a new official release in the not so distant future... Then we could all benefit from the great improvements of the last 2 years.
