### ISSUE TITLE
h2o proxy to backend laggy / slow ?

### ISSUE THREAD

**Issue by centminmod** [h2o/h2o#274]
I setup 

* h2o proxy at https://h2oproxy1.centminmod.com:8083 
* backend at http://centmin.sh:7111 

**Problem**

It seems accessing the proxy server there's some lag ? especially if you do a page reload in Chrome 41 or Opera 28. Access the backend directly is fast.

**Background**

Proxy server is located in San Francisco and Backend is in Freemont, California with 2-5ms ping RTT

**h2o.conf**

my used [h2o.conf](https://bitbucket.org/snippets/eva2000/jKxA/revisions/47a77ed44cd5e0c6b64d7c5d1ae4d9c26d9b1bb3)

**Comment by retsaot** [comment]
Try with "proxy.timeout.keepalive: 0". H2O doesn't seem to play nice with keep-alive.

**Comment by kazuho** [comment]
ToDo: we need to figure out how to implement test for this case using Starlet (Starlet precautionally closes the connection even if `--max-keepalive-reqs` is used in case the length of the content is not known or is not equal to that being actually emitted).

**Comment by kazuho** [comment]
Thank you for noticing the issue.  The cause has been fixed in #276 and merged to master.

As @retsaot commented (thanks to him/her), it was actually an issue specific to persistent connections.  I hope that with this being fixed there would be no more issues in using persistent connections against upstream servers.

If you find anything well, please report back.  Thank you in advance.

**Comment by centminmod** [comment]
cheers, just updated and works fine on page reloads now :)

**Comment by centminmod** [comment]
ok spoke too soon on manual page reloads got the following errors on the page itself

    connection timed out

and

    ai_family not supported

**Comment by whatvn** [comment]
the response header looks odd
```
content-encoding:gzip
content-type:text/html; charset=utf-8
date:Wed, 08 Apr 2015 03:11:43 GMT
etag:W/"552065b7-57d"
expires:Thu, 09 Apr 2015 03:11:43 GMT
last-modified:Sat, 04 Apr 2015 22:29:11 GMT
powered-by:h2o on centminmod.com
server:h2o/1.1.2-alpha1
ssl host:8083
status:200
vary:Accept-Encoding
```
what is `ssl host` header in this case? if you use port to identify backend host, it's ok. but should be changed to ssl-host instead. 


@kazuho : when examine that page, I noticed that there's 2 different etag header sent from h2o: 
If I sent request with `pragma:no-cache`, etag is: `W/"552065b7-57d"`, but request with:
```
if-modified-since:Sat, 04 Apr 2015 22:29:11 GMT
if-none-match:W/"552065b7-57d"
```
Return etag from h2o is: `"552065b7-57d"` 

this seems to be an error when producing etag buffer

**Comment by centminmod** [comment]
thanks @whatvn i fixed my ssl-host header on my h2o.conf :)

**Comment by whatvn** [comment]
Edit: different etag not because of pragma or cache-control header, it's because of accept-encoding header: 
```
Hungs-MacBook-Air:NetBeansProjects hungnguyen$ curl -I 'https://h2oproxy1.centminmod.com:8083/' -H 'accept-encoding: gzip, deflate, sdch'
HTTP/1.1 200 OK
Date: Wed, 08 Apr 2015 07:32:50 GMT
Server: h2o/1.1.2-alpha1
Connection: keep-alive
content-type: text/html; charset=utf-8
last-modified: Sat, 04 Apr 2015 22:29:11 GMT
vary: Accept-Encoding
etag: W/"552065b7-57d"
expires: Thu, 09 Apr 2015 07:32:50 GMT
content-encoding: gzip
powered-by: h2o on centminmod.com
ssl-host: 8083

Hungs-MacBook-Air:NetBeansProjects hungnguyen$
Hungs-MacBook-Air:NetBeansProjects hungnguyen$ curl -I 'https://h2oproxy1.centminmod.com:8083/'
HTTP/1.1 200 OK
Date: Wed, 08 Apr 2015 07:33:05 GMT
Server: h2o/1.1.2-alpha1
Connection: keep-alive
Content-Length: 1405
content-type: text/html; charset=utf-8
last-modified: Sat, 04 Apr 2015 22:29:11 GMT
vary: Accept-Encoding
etag: "552065b7-57d"
expires: Thu, 09 Apr 2015 07:33:05 GMT
accept-ranges: bytes
powered-by: h2o on centminmod.com
ssl-host: 8083
```

**Comment by kazuho** [comment]
@whatvn Thank you for pointing that out!

@centminmod 
> ```
> [lib/core/proxy.c] in request:/:connection timeout
> [lib/core/proxy.c] in request:/:ai_family not supported
> ```

Is the error reproducible?

The first error indicates that the server failed to connect to upstream (by timeout).  The second is an error returned by `getaddrinfo`, a function used to resolve the address of the upstream server before the server tries to establish a new connection.  So it means that there was a connection timeout for a request, and then subsequently a name resolution failure.  It should also be noted that the second error is something that you would not see often; considering the fact that H2O passes `AF_UNSPEC` (which means _any_ protocol) as the argument.

Considering the facts, the most likely cause of the issue is IMO in the network or the host.  For example, did you reconfigure the network while running H2O?

**Comment by centminmod** [comment]
no network reconfiguration.. but i haven't had the error since that first time :)

so probably a network issue ?

**Comment by whatvn** [comment]
@centminmod is your backend using h2o or another webserver?

**Comment by centminmod** [comment]
@whatvn backend is using Nginx 1.7 http non-https

**Comment by whatvn** [comment]
well, maybe the etag issue cause by nginx (the backend) not h2o. Do you think so?

**Comment by centminmod** [comment]
not sure

from proxy h2o
    curl -I https://h2oproxy1.centminmod.com:8083
    HTTP/1.1 200 OK
    Date: Wed, 08 Apr 2015 10:10:49 GMT
    Server: h2o/1.1.2-alpha1
    Connection: keep-alive
    Content-Length: 1405
    content-type: text/html; charset=utf-8
    last-modified: Sat, 04 Apr 2015 22:29:11 GMT
    vary: Accept-Encoding
    etag: "552065b7-57d"
    expires: Thu, 09 Apr 2015 10:10:49 GMT
    accept-ranges: bytes
    powered-by: h2o on centminmod.com
    ssl-host: 8083

from backend nginx    
    curl -I http://centmin.sh:7111               
    HTTP/1.1 200 OK
    Server: nginx centminmod
    Date: Wed, 08 Apr 2015 10:11:03 GMT
    Content-Type: text/html; charset=utf-8
    Content-Length: 1405
    Last-Modified: Sat, 04 Apr 2015 22:29:11 GMT
    Connection: keep-alive
    Vary: Accept-Encoding
    ETag: "552065b7-57d"
    Expires: Thu, 09 Apr 2015 10:11:03 GMT
    Cache-Control: max-age=86400
    Cache-Control: public, must-revalidate, proxy-revalidate
    Accept-Ranges: bytes

**Comment by whatvn** [comment]
what happen if you run: 
```
curl -I 'http://centmin.sh:7111'  -H 'accept-encoding: gzip, deflate, sdch'
```

**Comment by whatvn** [comment]
well, I test it myself. The problem is etag module you're using with nginx, strange!. 
```
Hungs-MacBook-Air:~ hungnguyen$ curl -I 'http://centmin.sh:7111'  -H 'accept-encoding: gzip, deflate, sdch'
HTTP/1.1 200 OK
Server: nginx centminmod
Date: Wed, 08 Apr 2015 12:08:02 GMT
Content-Type: text/html; charset=utf-8
Last-Modified: Sat, 04 Apr 2015 22:29:11 GMT
Connection: keep-alive
Vary: Accept-Encoding
ETag: W/"552065b7-57d"
Expires: Thu, 09 Apr 2015 12:08:02 GMT
Cache-Control: max-age=86400
Cache-Control: public, must-revalidate, proxy-revalidate
Content-Encoding: gzip
```
