### ISSUE TITLE
proxy persistent upstream: occassional 502 I/O error (head)

### ISSUE THREAD

**Issue by devlearner** [h2o/h2o#281]
Hi kazuho,

Thanks for the great h2o !

Recently I'm trying to debug occassional (periodic) 502 errors with `I/O error (head)` when using h2o as reverse proxy (with persistent connections) to a backend server.

When it happens, the console (h2o) logs:
`[lib/core/proxy.c] in request:/text.txt:I/O error (head)`
and it gives a 502 response with `I/O error (head)` 

Interestingly, the error only happens once in a while, and a subsequent retry gives a normal 200 response again.

Trying to figure out what's wrong, I set up a test setup as below:

client --->  h2o (proxy) -----> h2o (backend)

(I used h2o as a webserver for the backend, but I think other webservers will do)

the backend listens at 10.0.100.2:80 (a loopback interface); the h2o proxy will connect to the backend from a random port on 10.0.100.2.

After studying some wireshark dumps for a while, I seem to narrow down the culprit to the h2o proxy on its persistent connections to the upstream part.

[of course, the below is just my deduction; but just for now... ]

Consider a partial wireshark dump below (which shows an upstream connection between the h2o proxy and the backend):
![test62pcap-3bcrop](https://cloud.githubusercontent.com/assets/10971704/7118414/aab6e5dc-e231-11e4-90b8-f9792fa45902.png)

the h2o proxy (from port 18921) connects to the backend at port 80.
to fulfill the request for `GET /text.txt HTTP/1.1`, h2o proxy connects to the backend and relays the client's request, the backend replies with a 200 response plus a reply body. 

In the test conf file of the h2o proxy, there are the following lines:
```
        proxy.timeout.io: 60000
        proxy.timeout.keepalive: 600000
```
which denote a 1min i/o timeout and 10mins keep-alive timeout when connecting to the backend.

By default, the webserver's keep-alive timeout is just 10s. 

After serving the last request, the backend initiates a connection close [`764, t=121.681500`].

I'm not very familiar with TCP; some googling finds an introduction on [TCP Connection Close] (http://www.freesoft.org/CIE/Course/Section4/11.htm) as below:

>     　　TCP A                                                TCP B
>     the backend (80)                                the h2o proxy (18921) ... in our case
>   
>     1.  ESTABLISHED                                          ESTABLISHED
>   
>     2.  (Close)
>         FIN-WAIT-1  --> <SEQ=100><ACK=300><CTL=FIN,ACK>  --> CLOSE-WAIT
>   
>     3.  FIN-WAIT-2  <-- <SEQ=300><ACK=101><CTL=ACK>      <-- CLOSE-WAIT
>   
>     4.                                                       (Close)
>         TIME-WAIT   <-- <SEQ=300><ACK=101><CTL=FIN,ACK>  <-- LAST-ACK
>   
>     5.  TIME-WAIT   --> <SEQ=101><ACK=301><CTL=ACK>      --> CLOSED
>   
>     6.  (2 MSL)
>         CLOSED                                                      
>   
>                            Normal Close Sequence
>   
>                                  Figure 13.

In the screenshot dumps above, it seems that we see stage 2-3:
```
764  121.681500   80->18921 [FIN, ACK]
765  121.681500   18921->80 [ACK]
```
(remember that at this point in time, the webserver, on its timeout (10s), is trying to close the connection from h2o proxy; however, it is still within the `proxy.timeout.keepalive` (10mins) to the h2o proxy)

the closing process seems to stall at stage 3 of the closing sequence

[it's just my speculation] it seems that the h2o proxy does not recognize that the backend is closing one of its persistent upstream connections (due to the backend's own timeout) (and subsequently the h2o proxy does not finish the proper teardown, and remove this connection from the backend pool), as we see, subsequently:
```
831  125.630500   18921->80 GET /text.txt HTTP/1.1
```
the h2o proxy is trying to use this persistent connection to fulfill the next request from client some 4 secs later.

since the h2o proxy is reaching the webserver via a connection already in the process of closing down to the webserver, the backend thus respond with an RST:
```
831  125.630500   80->18921 [RST, ACK]
```
failing to reach the backend, the h2o proxy thus respond with a 502 to the client: `I/O error (head)`
and it shows in the console log:
`[lib/core/proxy.c] in request:/text.txt:I/O error (head)`

Speculation:
It seems like when persistent connections to backend is lost (or closed by the backend), the h2o proxy (sometimes) does not correctly remove it from its upstream pool (and finishes the proper teardown), so that (under certain circumstances) requests could erroneously reuse a persistent connection that should be closed to communicate with the backend, thus resulting in a 502.

[of course it's just a guess --- sometimes it's tricky to troubleshoot occasional but recurring errors like this ;) ]

p.s. dump of another persistent upstream connection that shows the RST
![test62pcap-4bcrop](https://cloud.githubusercontent.com/assets/10971704/7119920/0dd8b2c6-e23c-11e4-94fd-2ad09b52d166.png)

a persistent connection towards the end of the dump session that shows the entire closing sequence (2-5):
![test62pcap-5b](https://cloud.githubusercontent.com/assets/10971704/7119951/47aef35c-e23c-11e4-936c-c24a499d379a.png)

[sorry that the raw wireshark dumps seem a bit messy and may require a bit clean-up; but do let me know if that's useful so that I could upload the pcap file here ;) ]

any thoughts and helps appreciated !! :)

thanks

**Comment by kazuho** [comment]
@devlearner Thank you for reporting the issue.

> It seems like when persistent connections to backend is lost (or closed by the backend), the h2o proxy (sometimes) does not correctly remove it from its upstream pool (and finishes the proper teardown), so that (under certain circumstances) requests could erroneously reuse a persistent connection that should be closed to communicate with the backend, thus resulting in a 502.

Your assumption is correct.

The proxy module should better check if the socket is closed by peer before reusing the socket.

That said, __you should always configure the value of `proxy.timeout.keepalive` to something smaller than the keep-alive seconds of the upstream server__ (in case of H2O the value is `http1-request-timeout`).  This is because there is an inherent race condition bet. when the upstream server sends FIN and when the client recognizes the packet.  If the client sends a new request _after_ the server sent FIN _but before_ the client received it, then the server would inevitably send RST.

This is a design issue of HTTP/1.1 (addressed by HTTP/2).  We could possibly add an workaround by extending the protocol, but such a fix would not work well with all the HTTP servers.

**Comment by devlearner** [comment]
Thanks @kazuho for the reply :)
>you should always configure the value of  proxy.timeout.keepalive  to something smaller than the keep-alive seconds of the upstream server (in case of H2O the value is  http1-request-timeout )

Thanks for the suggestion! (I actually thought by mistake I should do it the other way round ;) )

Back to the issue, I was wondering, if there's anything could be done on h2o's part ;)
I was asking this because, I've tried using several http softwares, both http1 and http2 ones, and honestly this is the first time I ran into such an issue...

I was thinking like: from the captures, h2o did immediately respond to the backend with an `ACK` on receiving the first `FIN, ACK`
but somehow, there seems to be a delay in h2o closing the backend connection by sending its own `FIN, ACK` and removing it from its backend pool

could we remove the backend connection from the pool immediately upon seeing `FIN, ACK` from backend so that h2o won't be reusing this connection again by chance?

> This is because there is an inherent race condition bet. when the upstream server sends FIN and when the client recognizes the packet. If the client sends a new request after the server sent FIN but before the client received it, then the server would inevitably send RST.

in my humble opinion, I think in this case how the backend (upstream server) reacts does not affect the 'real' client; I'll take the `client` as the h2o proxy server here in this text ;)

really hope that we could do something to address this issue :)

**Comment by kazuho** [comment]
@devlearner 
> I was thinking like: from the captures, h2o did immediately respond to the backend with an ACK on receiving the first FIN, ACK

That is the task of the network stack of the OS, no H2O.

> could we remove the backend connection from the pool immediately upon seeing FIN, ACK from backend so that h2o won't be reusing this connection again by chance?

Yes, we can assert that a `FIN` (or `RST`) packet has _not_ arrived from peer by calling `read()` against the socket and by checking that the return value is `-1` with `errno` set to `EWOULDBLOCK` (or `EAGAIN`).  That should better be done before reusing the socket.

However, as I stated, if the client (e.g. H2O acting as the proxy) sends a request _before_ its network stack receives a `FIN`, and if the server (e.g. H2O acting as the content server) receives the request _after_ sending `FIN`, nothing can be done on the server-side to process the request (the only choices for the server is to either send `RST` (as is done now), or to send `ACK` to swallow the request).

That said, the other aspect (other than how TCP connections work) is to consider if a request could be resent by the downstream H2O server.

HTTP/1.1 (RFC 7230 et.al.) permits to resend requests that are known to be idempotent, and we could potentially do it (but that may cause the admins to report requests being duplicated).  We could possibly also provide an option to enable resends for all types of request as an option disable by default.

**Comment by devlearner** [comment]
@kazuho Thanks for the explanation!

>That is the task of the network stack of the OS, no H2O.

(Sorry that I was not very advanced with TCP stuff :) thanks for sheding the light! )

> That is why I stated that the timeout of the proxy should be set to a smaller value than that of the content server upstream; and the issue gets basically resolved by configuring as such.

Seems the way to go! will try that in my setup.

Many thanks! ;)

**Comment by devlearner** [comment]
Fixed the timeouts in my setup, and the periodic 502s are gone. Thanks for the tip!

**Comment by devlearner** [comment]
The above PR (with 1.7.0) largely solves the issue. Can be considered close. 
Thanks kazuho for the PR!
