### ISSUE TITLE
using the wrapper function

### ISSUE THREAD

**Issue by ihsinme** [h2o/h2o#2842]
I think this is a wrapper function created for just such places.
https://github.com/h2o/h2o/blob/94c7448b78bb840564b7a78b18e251237c8edd0b/deps/picotls/lib/openssl.c#L170

I think this is quite simple and safer than calling `RAND_bytes` directly
https://github.com/h2o/h2o/blob/94c7448b78bb840564b7a78b18e251237c8edd0b/deps/neverbleed/neverbleed.c#L1505

**Comment by ihsinme** [comment]
friendly ping

**Comment by kazuho** [comment]
Thank you for the suggestion. Neverbleed is actually a subproject of h2o that can be found https://github.com/h2o/neverbleed.

Neverbleed is designed to _not_ depend on OpenSSL, but not on h2o or picotls. Therefore, it makes sense to use RAND_bytes directly rather than using the picotls wrapper.
