### ISSUE TITLE
ETag for original / alternative representation

### ISSUE THREAD

**Issue by Jxck** [h2o/h2o#2896]
for same-file and different content-encoding, h2o adding same etag.

![Screen Shot 2021-12-03 at 1 45 13](https://user-images.githubusercontent.com/322289/144465732-f0ba168d-5799-4f90-8690-5a281421934b.png)

In this case, gziped / plain response could use different ETag.
https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#rfc.section.8.8.3.3

This can cause interoperability problems, especially with caches. It's know bug for a long in apache too.
https://bz.apache.org/bugzilla/show_bug.cgi?id=39727

for the point of view from validation, `If-Non-Match` uses weak validation for entity tag.
so changing etag value between gzip / plain completely seems too much and less efficiency. 
https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#rfc.section.13.1.2

How about adding `W/` for alternative representation (e.g. gzip, br, zstd) and strong tag for original ?

```http
plain: `6030af49-cd`
gzip: `W/6030af49-cd`
```

**Comment by u5surf** [comment]
Hi, @Jxck 
Indeed, weak etag has been supported by nginx as far as I know.

I've tried to modify weaken etag when server can be responded compressed contents.

Not have Accept-Encoding
```
 curl -v -H"Host:myhost.example.com" http://localhost:8080/foobar.txt 
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /foobar.txt HTTP/1.1
> Host:myhost.example.com
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Connection: keep-alive
< Content-Length: 7
< Server: h2o/2.3.0-DEV@13fb66ac2
< date: Wed, 22 Dec 2021 10:24:53 GMT
< content-type: text/plain
< last-modified: Wed, 22 Dec 2021 10:23:46 GMT
< etag: "61c2fcb2-7"
< accept-ranges: bytes
< 
foobar
* Connection #0 to host localhost left intact
```
Accept-Encoding : gzip
```
curl -v -H"Accept-Encoding: gzip" -H"Host:myhost.example.com" http://localhost:8080/foobar.txt
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /foobar.txt HTTP/1.1
> Host:myhost.example.com
> User-Agent: curl/7.58.0
> Accept: */*
> Accept-Encoding: gzip
> 
< HTTP/1.1 200 OK
< Connection: keep-alive
< Server: h2o/2.3.0-DEV@13fb66ac2
< date: Wed, 22 Dec 2021 10:42:28 GMT
< content-type: text/plain
< last-modified: Wed, 22 Dec 2021 10:23:46 GMT
< etag: W/"61c2fcb2-7"
< accept-ranges: none
< content-encoding: gzip
< vary: accept-encoding
< transfer-encoding: chunked
< 
Warning: Binary output can mess up your terminal. Use "--output -" to tell 
Warning: curl to output it to your terminal anyway, or consider "--output 
Warning: <FILE>" to save to a file.
* Failed writing body (0 != 27)
* Failed writing data
* stopped the pause stream!
* Closing connection 0
```

It can resolve this issue that it would be applying  the quite easy patch of compress.c. 
But I'm not sure whether should we apply that, cause I'm not a maintainer.
If you looks good, Can I work on this issue?

**Comment by Jxck** [comment]
@u5surf Thanks. Yes, that's the behavior I expected.
