### ISSUE TITLE
create backend using poll for the embedded event loop

### ISSUE THREAD

**Issue by kazuho** [h2o/h2o#291]
The embedded event loop of H2O (used by the standalone server) has three backends: `epoll`, `kqueue`, and `select`.

As discussed in #287, the select-based backend (intended for testing) has some inevitable issues (the number of file-descriptors that can be used is limited by the _design_ of `select`).

In other words, the standalone server of H2O does not work correctly on systems that do not support `epoll` or `kqueue`.

Considering that such operating systems exist (e.g. cygwin, Solaris, etc.) we should better create a `poll`-based backend.

**Comment by devlearner** [comment]
:thumbsup:

**Comment by kazuho** [comment]
done in #385
