### ISSUE TITLE
build fails on freebsd

### ISSUE THREAD

**Issue by rock59** [h2o/h2o#2944]
EAI_NODATA  and EAI_ADDRFAMILY used in hostinfo.c were deprecated. 

Tested on both freebsd 12 and 13

https://lists.freebsd.org/pipermail/freebsd-ports/2003-October/005757.html

https://patchwork.kernel.org/project/qemu-devel/patch/1456414292-55363-1-git-send-email-emaste@freebsd.org/

**Comment by utrenkner** [comment]
Which code version of h2o did you use?

@dch just updated [www/h2o-devel](https://www.freshports.org/www/h2o-devel/) to a 31 January snapshot. I can confirm it builds without problems on FreeBSD 13 and HardenedBSD 12 (essentially like FreeBSD 12.3-STABLE). And I believe @dch successfully tested it on FreeBSD 14.

**Comment by rock59** [comment]
@dch 

latest commit
33f4626c6d5d654b683373a0322d25ca44cf8ed6

gcc 10.3.0
cmake 3.22.1
OpenSSL 1.1.1k-freebsd

freebsd runs inside vmware vm on Windows

I placed EAI_NODATA and EAI_ADDRFAMILY inside #ifdef and h2o builds without problems

static const char *hostinfo_error_from_gai_error(int ret)
{
    switch (ret) {
    case EAI_NONAME:
        return h2o_hostinfo_error_nxdomain;
#ifdef EAI_NODATA    
	case EAI_NODATA:
        return h2o_hostinfo_error_nodata;
#endif		
    case EAI_FAIL:
        return h2o_hostinfo_error_refused;
    case EAI_AGAIN:
        return h2o_hostinfo_error_servfail;
#ifdef EAI_ADDRFAMILY	
    case EAI_ADDRFAMILY:
        return h2o_hostinfo_error_gai_addrfamily;
#endif    
	case EAI_BADFLAGS:
        return h2o_hostinfo_error_gai_badflags;
    case EAI_FAMILY:
        return h2o_hostinfo_error_gai_family;
    case EAI_MEMORY:
        return h2o_hostinfo_error_gai_memory;
    case EAI_SERVICE:
        return h2o_hostinfo_error_gai_service;
    case EAI_SOCKTYPE:
        return h2o_hostinfo_error_gai_socktype;
    case EAI_SYSTEM:
        return h2o_hostinfo_error_gai_system;
    default:
        return h2o_hostinfo_error_gai_other;
    }
}

![error](https://user-images.githubusercontent.com/1836483/153157489-17f8ad3c-f134-49c7-8325-d578196594fd.jpg)

**Comment by utrenkner** [comment]
@rock59 Just noticed now, that the www/h2o-devel was updated yesterday to a snapshot just 3 commits before the one you tried to build. Maybe try to build that port and see if it builds (which it should).

**Comment by utrenkner** [comment]
I confirm the failure to build (the www/h2o-devel port of yesterday) for FreeBSD 12.2 and HardenedBSD 12.3. Same error as @rock59 reported.

I successfully built the new port on FreeBSD 13.0.

**Comment by dch** [comment]
1d1da0742211a27030c089edbdba9de9d6fca631 is the last h2o commit that builds on FreeBSD (13 + CURRENT amd64) here.

In my defence I got COVID last week, so everything's a bit hazy still...

this is what I have locally for h2o:

```diff
commit 49cb80e401dbc12b4b5c4ce4831a8f7b82c406cd
Author: Dave Cottlehuber <dch@FreeBSD.org>
Date:   Wed Feb 9 17:17:07 2022 +0000

    www/h2o-devel: revert to 20220207 snapshot

diff --git www/h2o-devel/Makefile www/h2o-devel/Makefile
index 6917f9a73ac9..fed239c07f07 100644
--- www/h2o-devel/Makefile
+++ www/h2o-devel/Makefile
@@ -2,7 +2,7 @@
 
 PORTNAME=	h2o
 DISTVERSIONPREFIX=	v
-DISTVERSION=	2.3.0-dev.20220208
+DISTVERSION=	2.3.0-dev.20220207
 CATEGORIES=	www
 PKGNAMESUFFIX=	-devel
 
@@ -22,7 +22,7 @@ USES=		cmake:noninja compiler:c11 cpe perl5 shebangfix ssl pkgconfig
 CPE_VENDOR=	dena
 USE_GITHUB=	yes
 USE_LDCONFIG=	yes
-GH_TAGNAME=	34a5ac2
+GH_TAGNAME=	1d1da07
 
 CONFLICTS=	h2o
 
diff --git www/h2o-devel/distinfo www/h2o-devel/distinfo
index 22237520938f..aa33ba0a7720 100644
--- www/h2o-devel/distinfo
+++ www/h2o-devel/distinfo
@@ -1,3 +1,3 @@
-TIMESTAMP = 1644311187
-SHA256 (h2o-h2o-v2.3.0-dev.20220208-34a5ac2_GH0.tar.gz) = 516f0deef27c6c09c261902b788ac01e387f6cdb556d3b5fd278a7d3f01a1fbc
-SIZE (h2o-h2o-v2.3.0-dev.20220208-34a5ac2_GH0.tar.gz) = 30112859
+TIMESTAMP = 1644426680
+SHA256 (h2o-h2o-v2.3.0-dev.20220207-1d1da07_GH0.tar.gz) = 94724f64ea1fc274056fc48f5cfb94b271ad6b6122ce45651d4de31a62c6768a
+SIZE (h2o-h2o-v2.3.0-dev.20220207-1d1da07_GH0.tar.gz) = 30095034
```

I would like to get h2o upstream fixed, and then update port accordingly.

**Comment by dch** [comment]
@rock59 I see you have a temp patch here, I'll look into this after dinner. thanks!!

**Comment by utrenkner** [comment]
Sorry to hear about your COVID infection, @dch . Please, take care of yourself. Don't work on ports now, if you don't feel well!!!

As for the build: I have to correct myself... yesterday's port version did NOT build on FreeBSD 13. 

I just tried the latest patch that reverts to a 7 February snapshot:
- FreeBSD 13: OK
- FreeBSD 12.2: OK
- HardenedBSD 12.3: OK

**Comment by dch** [comment]
So this was annoying. the patch we just committed and merged in fixes the original issue, but subsequent commits which are incorporated in merges inbetween the original issue and the merge to master, break this.

@rock59 great sleuthing, I'm checking your patches (twice!) and will commit them. What attribution do you want in the commit?

**Comment by rock59** [comment]
@dch Sorry to hear about your COVID infection and I hope you get over your illness quite soon.
I am working on my proxy server using a modified version of libh2o and unfortunately I dont have enough time to send pull request or share the modifications. You are free to use the patches as you wish.

**Comment by kazuho** [comment]
Opened #2945 that should address this issue. @dch I hope your quick recovery!

**Comment by dch** [comment]
brilliant! thanks.
