### ISSUE TITLE
haproxy (frontend) => h2o (backend) | using http2 protocol results in 502 or 503 errors

### ISSUE THREAD

**Issue by trendymail** [h2o/h2o#2954]
Hello!

First of all, many many thanks for this awesome tool. :)

Not sure if this is related to h2o** but, when using the latest version (master.zip), HAProxy no longer "talks" correctly to h2o when h2 is enabled.

**using an old version of h2o is okay (for instance : Commits on Aug 10, 2021 => https://github.com/h2o/h2o/commits/master?after=99ca04dd42fd2c32019b381d91e974c53586dd85+419&branch=master)

# haproxy.cfg (simplified)
backend hap30-h2o10
  mode http
  server hap30-www10 HOST.DOMAIN.TLD:443 init-addr libc maxconn 256 ssl verify none alpn h2

I am unable to compile h2olog (so I have no clue about what is going on.

=> /usr/local/src/h2o-master/src/h2olog/h2olog.cc:352:33: error: 'DEBUG_BTF' is not a member of 'ebpf'
      BCC_FLAG(bcc_flags, DEBUG_BTF)

HAProxy version is 2.5.4 and h2o was compiled with master.zip (yesterday).

Could you help me sending you more useful info in order to understand the issue?

Have a great day!

**Comment by trendymail** [comment]
Hello!

Please, could you delete this issue or mark it as "bogus".

No more info: I didn't search, sorry for the "noise".

Have a great day!

**Comment by kazuho** [comment]
:+1:
