### ISSUE TITLE
use h2o as httpserver, handle request but client close suddenly

### ISSUE THREAD

**Issue by charlescao92** [h2o/h2o#2965]
https://github.com/h2o/h2o/issues/1894
so sory that i can't got it honestly. i have read dnsdist-1.7.0, but can' help.
can you  explain that, 
du->self = reinterpret_cast<DOHUnit**>(h2o_mem_alloc_shared(&req->pool, sizeof(*self), on_generator_dispose));
where to release it ,when client close util get reponse??

**Comment by CharlesCao9211** [comment]
can you give me a example ? i read the httpclient.c/proxy.c, but don't know how to use it to the httpserver..

**Comment by CharlesCao9211** [comment]
i know you suggest use  h2o_mem_alloc_shared , but i don' know  when client close, where  release it ?
