### ISSUE TITLE
h2o_socket_write: Assertion `ret == sz' failed.

### ISSUE THREAD

**Issue by Roze** [h2o/h2o#297]
Couple times in day while running h2o (1.2.0) in proxy mode we end up with:

h2o: /data/install/h2o-1.2.0/lib/common/socket.c:343: h2o_socket_write: Assertion `ret == sz' failed.
worker 18607 died unexpectedly with status:6, restarting
starting new worker 26157

**Comment by kazuho** [comment]
Thank you for reporting the issue.

In the commit above, I have made a temporary change to the codebase hoping that the error log would help us determine the cause of the issue.

Would you mind upgrading H2O and see what is emitted to the error log?  Thank you in advance.

**Comment by Roze** [comment]
Applied the patch. Will post when the error shows up.

**Comment by Roze** [comment]
SSL_write failed; IN 27, OUT -1, ERROR 1

**Comment by kazuho** [comment]
@Roze Thank you running with the updated version.

The error (OUT=-1, ERROR 1) indicates that `SSL_ERROR_SSL` is returned by OpenSSL, meaning that something has gone wrong within the SSL library.

I have updated the master branch to log more details if such error is returned; would you mind running the updated version once again?  Hopefully it would help us find the cause.

Also, I would appreciate it if you could give me the details of your environment; i.e. the operating system, whether 32-bit or 64-bit, compiler version, OpenSSL version (or if you are using the embedded libressl), etc.

**Comment by Roze** [comment]
openSUSE 12.2 64bit
cmake version 2.8.8
gcc version 4.7.1

I'm using the embedded libressl (-DWITH_BUNDLED_SSL=on) but the system has OpenSSL 1.0.1g-fips 7 Apr 2014

Applied the patch will post when the next error appears.

**Comment by Roze** [comment]
SSL_write(3) failed; IN 36, OUT -1
result of SSL_get_error is 1
140030957840128:error:060C1064:digital envelope routines:AEAD_CHACHA20_POLY1305_OPEN:bad decrypt:evp/e_chacha20poly1305.c:204:
140030957840128:error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac:s3_pkt.c:467:
140030957840128:error:1409F07F:SSL routines:SSL3_WRITE_PENDING:bad write retry:s3_pkt.c:781:

**Comment by Roze** [comment]
Got also a bit different:

SSL_write(3) failed; IN 29, OUT -1
result of SSL_get_error is 1
140031077300160:error:1409F07F:SSL routines:SSL3_WRITE_PENDING:bad write retry:s3_pkt.c:781:

**Comment by kazuho** [comment]
Thank you for the logs.

I am not sure why you are receiving corrupt TLS packets, but that might explain the cause of the issue.  When receiving a corrupt packet, LibreSSL (or OpenSSL) tries to send an _alert_ packet, and looking at their source code that might be triggering the error you are seeing.

I will try to reproduce the issue by artificially creating corrupt TLS packets.
