### ISSUE TITLE
Allow preserving `server` HTTP header through the reverse proxy

### ISSUE THREAD

**Issue by LoganDark** [h2o/h2o#3009]
Currently, h2o has three modes when it comes to the `server` header:

- Clobber it completely with h2o's brand and version
- Clobber it completely with a user-provided string (via the top-level `server-name` configuration directive)
- Forbid it completely and even remove it from the backend response (by setting the top-level `send-server-name` configuration directive to `OFF`)

I think there should really be a fourth mode :

- Do not touch the `server` header at all

**Comment by u5surf** [comment]
Hi, @LoganDark 
`send-server-name: preserve ` might help you want to do. It could not find anywhere in the document, but the implementation and tests(t/50servername.t) can confirm the existence.
