### ISSUE TITLE
error 403 when h2o is overloaded

### ISSUE THREAD

**Issue by Tintinabula** [h2o/h2o#301]
Using h2load we overload H2O during stress testing and H2O sometimes sends back error 403, Access Forbidden. Should H2O send back an error 503 Service Unavailable instead?

The following is a stress test run:

```
./h2load -t 16 -m 16 -c 1000 -n 10000000 -v https://10.10.10.10/test.txt
starting benchmark...
Protocol: TLSv1.2
Cipher: ECDHE-RSA-AES256-GCM-SHA384
finished in 23.07s, 433452 req/s, 291.29MB/s
requests: 10000000 total, 10000000 started, 10000000 done, 5218188 succeeded, 4781812 failed, 0 errored
status codes: 5218188 2xx, 0 3xx, 4781812 4xx, 0 5xx
traffic: 7046735817 bytes total, 110910185 bytes headers, 6755789632 bytes data
                     min         max         mean         sd        +/- sd
time for request:      187us    703.77ms     29.37ms     20.13ms    80.61%
```

At the same time h2load is running we manually run curl to check the responses. The following shows two error 403's and a 200 for the same file.

```
$ curl -kI https://10.10.10.10/test.txt
HTTP/1.1 403 Access Forbidden
Date: Fri, 01 May 2015 18:52:38 GMT
Server: h2o/1.2.1-alpha1
Connection: keep-alive
Content-Length: 16
content-type: text/plain; charset=utf-8

$ curl -kI https://10.10.10.10/test.txt
HTTP/1.1 403 Access Forbidden
Date: Fri, 01 May 2015 18:52:39 GMT
Server: h2o/1.2.1-alpha1
Connection: keep-alive
Content-Length: 16
content-type: text/plain; charset=utf-8

$curl -kI https://10.10.10.10/test.txt
HTTP/1.1 200 OK
Date: Fri, 01 May 2015 18:52:39 GMT
Server: h2o/1.2.1-alpha1
Connection: keep-alive
Content-Length: 1280
content-type: text/plain
last-modified: Thu, 23 Apr 2015 15:49:39 GMT
etag: "55391493-500"
vary: accept-encoding
```

The concern is when Googlebot receives an error 403 it will de-index the page since the error tells the bot it does not have permission to access the resource and to never try again. 

According to W3 (http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html)

Error 403 says "The server understood the request, but is refusing to fulfill it. Authorization will not help and the request SHOULD NOT be repeated." 

Error 503 says, "The server is currently unable to handle the request due to a temporary overloading or maintenance of the server. The implication is that this is a temporary condition which will be alleviated after some delay. If known, the length of the delay MAY be indicated in a Retry-After header."

BTW, the addition of a default "Retry-After: 10" header on an error 503 _might_ help clients and bots which would otherwise never connect again.

The current state of the Retry-After header
http://stackoverflow.com/questions/3764075/retry-after-http-response-header-does-it-affect-anything/23863426#23863426

**Comment by retsaot** [comment]
H2O only sends 403 when [open(2) fails](https://github.com/h2o/h2o/blob/acfe971b8c2b7b45cc907c28d82063cda4b01ba8/lib/handler/file.c#L349). Maybe you are out of file descriptors?
```
--- lib/handler/file.c
+++ lib/handler/file.c
@@ -349,8 +349,10 @@
     /* failed to open */
     if (errno == ENOENT) {
         h2o_send_error(req, 404, "File Not Found", "file not found", 0);
+    } else if (errno == EACCES) {
+        h2o_send_error(req, 403, "Access Forbidden", "access forbidden", 0);
     } else {
-        h2o_send_error(req, 403, "Access Forbidden", "access forbidden", 0);
+        perror("open");
     }
     return 0;
```
Use the patch above and see what is emitted to the error log.

**Comment by Tintinabula** [comment]
@retsaot , the error log showed "open: Too many open files" when the patch was applied. The open file limit was 4096 files. We increased the open file limit to 100000 and the errors subsided.

```
./h2load -t 16 -m 16 -c 1000 -n 10000000 -v https://10.10.10.10/test.txt
Protocol: TLSv1.2
Cipher: ECDHE-RSA-AES256-GCM-SHA384
finished in 34.61s, 288951 req/s, 359.64MB/s
requests: 10000000 total, 10000000 started, 10000000 done, 10000000 succeeded, 0 failed, 0 errored
status codes: 10000000 2xx, 0 3xx, 0 4xx, 0 5xx
traffic: 13050887093 bytes total, 70851093 bytes headers, 12800000000 bytes data
                     min         max         mean         sd        +/- sd
time for request:      224us    787.16ms     49.02ms     32.14ms    80.78%
```

What were your thoughts on sending an error 503 instead on a 403? When H2O gets overloaded (DoS) and Googlebot tries to connect it may receive a 403 and de-list the website's pages.

**Comment by kazuho** [comment]
@Tintinabula thank you for reporting the issue; @retsaot thank you for providing a patch to resolve issue.

I agree that this is not a bug, but I do see the point that it would be better to send 503 response when h2o fails to open a file due to overload (e.g. too many files open).
