### ISSUE TITLE
how do i use the examples/h2o

### ISSUE THREAD

**Issue by yzcaijie0818** [h2o/h2o#305]
book@book-desktop:~/Desktop/h2o-master/examples$ /usr/local/bin/h2o -c h2o/h2o.conf 
[h2o/h2o.conf:7] in command listen, failed to load certificate file:examples/h2o/server.crt

3078280992:error:02001002:system library:fopen:No such file or directory:bio/bss_file.c:255:fopen('examples/h2o/server.crt', 'r')
3078280992:error:20074002:BIO routines:FILE_CTRL:system lib:bio/bss_file.c:257:
3078280992:error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:727:

**Comment by pokeyrule** [comment]
I think you need to run the server from ~/Desktop/h2o-master.  I believe the crt path is relative to this dir.  Ie

cd ~/Desktop/h2o-master/examples
/usr/local/bin/h2o -c examples/h2o/h2o.conf

**Comment by kazuho** [comment]
@pokey :+1:

**Comment by yzcaijie0818** [comment]
book@book-desktop:~/Desktop/h2o-master$ h2o -c h2o/h2o.conf 
could not open configuration file:h2o/h2o.conf:Not a directory

book@book-desktop:~/Desktop/h2o-master$ h2o -c examples/h2o/h2o.conf 
[INFO] raised RLIMIT_NOFILE to 1024
h2o server (pid:3338) is ready to serve requests
fetch-ocsp-response (using OpenSSL 1.0.2a 19 Mar 2015)
fetch-ocsp-response (using OpenSSL 1.0.2a 19 Mar 2015)
failed to extract ocsp URI from examples/h2o/alternate.crt
[OCSP Stapling] disabled for certificate file:examples/h2o/alternate.crt
failed to extract ocsp URI from examples/h2o/server.crt
[OCSP Stapling] disabled for certificate file:examples/h2o/server.crt

**Comment by yzcaijie0818** [comment]
book@book-desktop:~/Desktop/h2o-master$ /usr/local/bin/h2o -c examples/h2o/h2o.conf
[INFO] raised RLIMIT_NOFILE to 1024
h2o server (pid:3389) is ready to serve requests
fetch-ocsp-response (using OpenSSL 1.0.2a 19 Mar 2015)
failed to extract ocsp URI from examples/h2o/server.crt
[OCSP Stapling] disabled for certificate file:examples/h2o/server.crt
fetch-ocsp-response (using OpenSSL 1.0.2a 19 Mar 2015)
failed to extract ocsp URI from examples/h2o/alternate.crt
[OCSP Stapling] disabled for certificate file:examples/h2o/alternate.crt
