### ISSUE TITLE
Why not use mempool for st_h2o_http1client_private_t?

### ISSUE THREAD

**Issue by pokey** [h2o/h2o#306]
Why do we have

```c
struct st_h2o_http1client_private_t *client = h2o_mem_alloc(sizeof(*client));
```

instead of

```c
struct st_h2o_http1client_private_t *client = h2o_mem_alloc_pool(pool, sizeof(*client));
```

at https://github.com/h2o/h2o/blob/master/lib/common/http1client.c#L410?

**Comment by kazuho** [comment]
Thank you for the suggestion.

While doing so is certainly possible, I doubt if it would have any practical impact on performance considering the fact that the object is allocated only once per HTTP request, and that issuing an HTTP request is a somewhat heavy operation involving multiple numbers of syscalls.

After all, in #307 I have removed all the references to `pool` from the HTTP/1 client implementation considering the fact that enforcing the user of the client implementation to always specify a pool is not a good idea.
