### ISSUE TITLE
the example h2o  :  failed to extract ocsp URI from examples/h2o/server.crt

### ISSUE THREAD

**Issue by yzcaijie0818** [h2o/h2o#308]
book@book-desktop:~/Desktop/h2o-master$ h2o -c examples/h2o/h2o.conf 
[INFO] raised RLIMIT_NOFILE to 1024
h2o server (pid:2575) is ready to serve requests
fetch-ocsp-response (using OpenSSL 1.0.2a 19 Mar 2015)
fetch-ocsp-response (using OpenSSL 1.0.2a 19 Mar 2015)
failed to extract ocsp URI from examples/h2o/server.crt
[OCSP Stapling] disabled for certificate file:examples/h2o/server.crt
failed to extract ocsp URI from examples/h2o/alternate.crt
[OCSP Stapling] disabled for certificate file:examples/h2o/alternate.crt

**Comment by kazuho** [comment]
> ```
> failed to extract ocsp URI from examples/h2o/server.crt
> [OCSP Stapling] disabled for certificate file:examples/h2o/server.crt
> ```

It is not a bug but an informational message.  As the second line suggests, OCSP stapling automatically gets enabled (or disabled) if OCSP URI exists in the certificate (or not).

**Comment by yzcaijie0818** [comment]
thanks for your patient explanation

**Comment by ilmalalifriansyah** [comment]
Hello Mr. Kazuho,
I've same problem with Mr.  yzcaijie0818

But it stuck there. not any proccess anymore. I think it's a while, so I leave it with sleep. But after I wake up, it still like that. None says it's done. So I choose to Ctrl+C. 

I try again and again just like that. I can't continue to the configure section.

Thank you very much for your attention.

**Comment by kazuho** [comment]
@ilmalalifriansyah Would you mind providing your configuration file so that I can look into? (or please let me know if you are using examples/h2o/h2o.conf)

I would appreciate it if you could provide other details of your environment (OS, CPU architecture (32bit or 64bit), build configuration of H2O, ...).

**Comment by ilmalalifriansyah** [comment]
Mr. @kazuho 

Absolutely,
My environment:
OS : 14.04, 64-bit

Maybe I can give my screenshot. I just follow the instruction in Install section
% /usr/local/bin/h2o -c examples/h2o/h2o.conf

![screenshot from 2015-05-20 09 11 39](https://cloud.githubusercontent.com/assets/7435712/7718912/e614ef44-fee1-11e4-9d02-f78448574d1d.png)

But It never done. the cursor just in there.

Are this okay? So I can through to the Configure section.

I'm sorry before, I'm new in ubuntu and http/2

I really appreciate you're answer.

**Comment by kazuho** [comment]
@ilmalalifriansyah 

The log looks OK.  The server should be running.  Would you mind trying to access the server by using a web browser or some kind of command-line HTTP client (e.g. curl)?

Please note that unless you use the `-m daemon` option, the server does not gets detached from the console.

**Comment by ilmalalifriansyah** [comment]
Mr. @kazuho

Sure, I think access the server is fine.

So I think now go to the Configure section

Thank you very much for your attention.

Really appreciate it.

**Comment by kazuho** [comment]
:+1:
