### ISSUE TITLE
Build failed with -Werror=format

### ISSUE THREAD

**Issue by msmhrt** [h2o/h2o#3105]
Description:
After commit [cd14742f2](https://github.com/h2o/h2o/commit/cd14742f21c6afc87b76033e76620f86e113f719) h2o can not build

Expected Behavior:
Can build

Output of `make`:
full version is https://gist.github.com/msmhrt/8e1b63d1fb21b85f5c37c4a1553b1018

~~~
...
[  3%] Building C object CMakeFiles/h2o.dir/lib/common/url.c.o
/home/msmhrt/repository/h2o/lib/common/url.c: In function ‘h2o_url_init_with_hostport’:
/home/msmhrt/repository/h2o/lib/common/url.c:430:39: error: ‘%u’ directive writing between 1 and 10 bytes into a region of si
ze 6 [-Werror=format-overflow=]
         int port_len = sprintf(_port, "%" PRIu16, port);
                                       ^~~
/home/msmhrt/repository/h2o/lib/common/url.c:430:40: note: format string is defined here
         int port_len = sprintf(_port, "%" PRIu16, port);
/home/msmhrt/repository/h2o/lib/common/url.c:430:39: note: directive argument in the range [0, 2147483647]
         int port_len = sprintf(_port, "%" PRIu16, port);
                                       ^~~
In file included from /usr/include/stdio.h:862:0,
                 from /home/msmhrt/repository/h2o/include/h2o/memory.h:31,
                 from /home/msmhrt/repository/h2o/lib/common/url.c:26:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:33:10: note: ‘__builtin___sprintf_chk’ output between 2 and 11 bytes into a desti
nation of size 6
   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       __bos (__s), __fmt, __va_arg_pack ());
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/msmhrt/repository/h2o/lib/common/url.c: At top level:
cc1: warning: unrecognized command line option ‘-Wno-nullability-completeness’
cc1: some warnings being treated as errors
CMakeFiles/h2o.dir/build.make:1603: recipe for target 'CMakeFiles/h2o.dir/lib/common/url.c.o' failed
make[2]: *** [CMakeFiles/h2o.dir/lib/common/url.c.o] Error 1
CMakeFiles/Makefile2:883: recipe for target 'CMakeFiles/h2o.dir/all' failed
make[1]: *** [CMakeFiles/h2o.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
msmhrt@ashrose:~/repository/h2o/build$
~~~

**Comment by msmhrt** [comment]
For me this issue occured with Ubuntu 18.04.6 LTS and gcc 7.5.0

-----
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic
$ gcc --version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by gfx** [comment]
Or, I propose another fix: https://github.com/h2o/h2o/pull/3106

**Comment by msmhrt** [comment]
I have confirmed that the build is successful on https://github.com/h2o/h2o/pull/3106/commits/48e8ee83baf06a3592547d2475f6996bec45d070 with GCC-7.5.0 on Ubuntu 18.04.

**Comment by msmhrt** [comment]
I have confirmed that the build is successful on https://github.com/h2o/h2o/commit/7e9977136b90b22f4a0607b89b93bdc50bbdf952 with GCC-7.5.0 on Ubuntu 18.04.

thx!

**Comment by msmhrt** [comment]
BTW, Does CI test not use GCC at all? Because of too long test time?

**Comment by trendymail** [comment]
Hello!

Build is successful with commit [7e99771](https://github.com/h2o/h2o/commit/7e9977136b90b22f4a0607b89b93bdc50bbdf952) with gcc version 8.3.0 on Debian 10 (Buster).

Many thanks for investigating.

**Comment by kazuho** [comment]
Thank you!
