### ISSUE TITLE
Empty paths key results in invalid HTTP proxy request

### ISSUE THREAD

**Issue by funkybob** [h2o/h2o#3110]
With a config like:
```
hosts:
  default:
    paths:
      "":
        proxy.reverse.url:...
```

Making a request to `http://localhost` will result in an invalid HTTP request like: `GET  HTTP/1.1` where it should be `GET / HTTP/1.1`

**Comment by kazuho** [comment]
It seems to me that this issue was fixed in https://github.com/h2o/h2o/pull/1506 in 2017.

**Comment by funkybob** [comment]
That looks like it would have caught this case.
Shame it's not in any released version.

Thanks for the prompt reply!
