### ISSUE TITLE
Folding of set-cookie headers against RFC 6265 recommendation

### ISSUE THREAD

**Issue by utrenkner** [h2o/h2o#3120]
In my quest to filter out (unnecessary) cookies, I came across a problem: It seems that `H2O.next.call()` folds several ``set-cookie`` headers into one, thus breaking how most browsers expect ``set-cookie`` headers.

[RFC 6265](https://httpwg.org/specs/rfc6265.html#overview) explicitly discourages this behaviour:
`Origin servers SHOULD NOT fold multiple Set-Cookie header fields into a single header field. The usual mechanism for folding HTTP headers fields (i.e., as defined in [RFC2616](https://httpwg.org/specs/rfc6265.html#RFC2616) might change the semantics of the Set-Cookie header field because the %x2C (",") character is used by Set-Cookie in a way that conflicts with such folding.`

And this is exactly what I encountered: In one situation the WordPress application sends four different set-cookie headers, which are folded into one; the individual cookies are separated by commas. However, the `expires` attribute also contains a legitimate comma (e.g. ``expires=Sat, 01-Oct-2022 06:59:47 GMT``). In any case, Firefox and Chrome both ignore the complete set-cookie header. I have not tested other browsers.

Would it be possible to change the behaviour `H2O.next.call()` to keeping separate `set-cookie` headers?

**Comment by kazuho** [comment]
@utrenkner Thank you for reporting the issue. We think we have fixed the problem in #3185, but please let us know if the issue persists.

**Comment by utrenkner** [comment]
@kazuho Many thanks! I'll give it a try, next week and will report back.
