### ISSUE TITLE
"group_by" extremely slow

### ISSUE THREAD

**Issue by mayer79** [h2o/h2o#3140]
I am working on an algorithm (in R) that needs column sums, grouped by a discrete column.

On my laptop, H2O is about 400 times slower than base R:

```r

library(ggplot2)
library(h2o)

h2o.init()

to_ord <- c("color", "cut", "clarity")

dia <- diamonds
dia[to_ord] <- lapply(dia[to_ord], factor, ordered = FALSE)

dia_h2o <- as.h2o(dia)

microbenchmark::microbenchmark(
  h2o = h2o.group_by(dia_h2o, by = "color", sum("carat"), sum("price"), sum("x")),
  base = rowsum(diamonds[, c("carat", "price", "x")], diamonds[["color"]]),
  times = 5
)

Unit: milliseconds
 expr       min        lq       mean    median        uq       max neval
  h2o 1389.0963 1414.3779 1413.93288 1415.7277 1420.9661 1429.4964     5
 base    1.2686    3.0424    3.39526    3.0733    4.0959    5.4961     5
```

Is there any way to speed up grouped sums? In my use-case, it is a show-stopper, unfortunately.

**Comment by syohex** [comment]
I suppose you should file your issue at https://github.com/h2oai/h2o-3

**Comment by mayer79** [comment]
Oh, my bad. Thanks for pointing this out. I don't know where to file the bug (they seem to keep their issues on jira), so I will simply close this issue and forget the problem.
