### ISSUE TITLE
proceed_handshake: Assertion `sock->ssl->input.encrypted->size == 0' failed

### ISSUE THREAD

**Issue by Roze** [h2o/h2o#316]
Then recently had a few restarts with this:

h2o: /data/install/h2o-1.2.0/lib/common/socket.c:475: proceed_handshake: Assertion `sock->ssl->input.encrypted->size == 0' failed.
worker 32418 died unexpectedly with status:6, restarting

	Program terminated with signal 6, Aborted.
	#0  0x00007ffabc415d25 in raise () from /lib64/libc.so.6

	(gdb) bt full
	#0  0x00007ffabc415d25 in raise () from /lib64/libc.so.6
	No symbol table info available.
	#1  0x00007ffabc4171a8 in abort () from /lib64/libc.so.6
	No symbol table info available.
	#2  0x00007ffabc40ec22 in __assert_fail_base () from /lib64/libc.so.6
	No symbol table info available.
	#3  0x00007ffabc40ecd2 in __assert_fail () from /lib64/libc.so.6
	No symbol table info available.
	#4  0x0000000000447e45 in proceed_handshake (sock=0x7ffab018adb0, status=0) at /data/install/h2o-1.2.0/lib/common/socket.c:475
			ret = 0
			__PRETTY_FUNCTION__ = "proceed_handshake"
	#5  0x0000000000446dc6 in read_on_ready (sock=0x7ffab018adb0) at /data/install/h2o-1.2.0/lib/common/socket/evloop.c.h:228
			status = <optimized out>
			prev_bytes_read = 0
	#6  run_socket (sock=0x7ffab018adb0) at /data/install/h2o-1.2.0/lib/common/socket/evloop.c.h:466
	No locals.
	#7  run_pending (loop=0x7ffab00008c0) at /data/install/h2o-1.2.0/lib/common/socket/evloop.c.h:477
			sock = 0x7ffab018adb0
	#8  0x000000000044795c in h2o_evloop_run (loop=0x7ffab00008c0) at /data/install/h2o-1.2.0/lib/common/socket/evloop.c.h:490
			node = <optimized out>
			__PRETTY_FUNCTION__ = "h2o_evloop_run"
	#9  0x0000000000473a02 in run_loop (_thread_index=0x3) at /data/install/h2o-1.2.0/src/main.c:1205
			thread_index = 3
			listeners = 0x7ffaba3a3da0
			i = <optimized out>
	#10 0x00007ffabcb99e0e in start_thread () from /lib64/libpthread.so.0
	No symbol table info available.
	#11 0x00007ffabc4c52cd in clone () from /lib64/libc.so.6
	No symbol table info available.

**Comment by kazuho** [comment]
Thank you for noticing the issue!

I haven't reproduced the issue, but I expect the above commit to have fixed the problem.  Please reopen the issue if the problem persists.
