### ISSUE TITLE
Again C99 build error on FreeBSD

### ISSUE THREAD

**Issue by utrenkner** [h2o/h2o#3189]
On Friday, I wanted to test the new fix for "handling of headers appearing more than once" (#3185). However, I could not get over a C99 error on FreeBSD 13.1-RELEASE-p5, which looks similar to earlier problems (#2933 , #2944). I tried further today, but without luck:

```
/home/uwe/test/h2o/deps/neverbleed/neverbleed.c:1302:11: error: implicit declaration of function 'pthread_setaffinity_np' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    ret = pthread_setaffinity_np(pthread_self(), sizeof(NEVERBLEED_CPU_SET_T), &cpuset);
          ^
```
Does anyone know how to work around this?

**Comment by utrenkner** [comment]
@dch @kazuho You solved similar problems, in the past. May I kindly ask you to have a look at this issue? Maybe it can be fixed rather easily, based on your previous solutions?

**Comment by utrenkner** [comment]
@dch @kazuho I am not a developer, but to me it looks as if the [solution used in main.c](https://github.com/h2o/h2o/pull/2942/files#diff-e0cf5b28d9b6b600f0af2bc78e8fd30ec675fd731a5da86f0c4283ffc0e40176) could be adapted for neverbleed.c.

**Comment by kazuho** [comment]
Hey sorry for the delay, I think the issue has been addressed now, with #3220 incorporating https://github.com/h2o/neverbleed/pull/56.

**Comment by dch** [comment]
awesome! shall I just bump the port to the next master version?

**Comment by utrenkner** [comment]
@dch That would be great! I managed to modify the current version of www/h2o-devel for the latest commit 43cf4e6. I successfully built the package from this version. I'll send you my patch directly, because GH somehow does not let me attach it here.

**Comment by kazuho** [comment]
Hey sorry for the inconvenience.

As you may have noticed, we have a vulnerability fix that has to be merged; please see https://github.com/h2o/h2o/security/advisories/GHSA-p5hj-phwj-hrvx.

@dch I would appreciate it if you could pick that up as well.

FWIW regarding the release model, I am sorry that we are failing to make releases, I had recently started my work to transition to a new model; please see https://github.com/h2o/h2o/issues/3230.
