### ISSUE TITLE
Arch Linux AUR package

### ISSUE THREAD

**Issue by Alir3z4** [h2o/h2o#32]
Hello,

I just created a pkg for archlinux aur:

https://aur.archlinux.org/packages/h2o-git/

On Arch Linux `h20` with `libh2o` can be installed with:

```
$ yaourt -S h2o-git
```

Since there's no version available it will install the latest from master branch.

**Comment by toddpi314** [comment]
Thanks for this @Alir3z4

**Comment by toddpi314** [comment]
Looks like this package is no longer live: https://aur.archlinux.org/packages/h2o-git/

Any news on creating an Arch dist long term?
