### ISSUE TITLE
FastCGI incorrectly encode size 127 in name-value pairs

### ISSUE THREAD

**Issue by diogin** [h2o/h2o#3204]
https://github.com/h2o/h2o/blob/04835cb502d661035b4908ea555b227fa7160942/lib/handler/fastcgi.c#L156

According to FastCGI specification (https://fastcgi-archives.github.io/FastCGI_Specification.html ):
"Lengths of 127 bytes and less can be encoded in one byte, while longer lengths are always encoded in four bytes"

The condition should be: (len <= 127).

**Comment by kazuho** [comment]
@diogin Thank you for spotting the issue, @fengve thank you for the fix.

Though I do not think this is a bug, considering that the specification says "_can_ be encoded in one byte" implying that they can be sent in four bytes, I agree that we should not be using 4-byte encoding for 127.
