### ISSUE TITLE
http1client#update_read_state may have a difficult-to-stop erroneous invariant

### ISSUE THREAD

**Issue by yrashk** [h2o/h2o#3225]
If the configuration `max_buffer_size` for  in the context is (erroneously?) set to 0, the following condition will be true:

```c
(*client->super.buf)->size >= client->super.ctx->max_buffer_size)
```

To the best of my observation (I had proxying sporadically hang in my use of libh2o) and reading of the code  `update_read_state` code, it'll just stop reading from that socket.

Perhaps we can insert an assertion somewhere to ensure `max_buffer_size` is not zero? At the very least, it may help people like myself spend less time figuring out what happened.

**Comment by kazuho** [comment]
Thank you for raising the issue. Your suggestion is totally reasonable, adopted in #3226.
