### ISSUE TITLE
I find a bug

### ISSUE THREAD

**Issue by shibochan** [h2o/h2o#323]
In h2o/deps/yoml/yoml.h line121-122
`
if ((n = yoml_find_anchor(node->data.mapping.elements[i].key, name)) != NULL
           || (n = yoml_find_anchor(node->data.mapping.elements[i].key, name)) != NULL)
`
I think it should be
`
if ((n = yoml_find_anchor(node->data.mapping.elements[i].key, name)) != NULL
           || (n = yoml_find_anchor(node->data.mapping.elements[i].value, name)) != NULL)
`

**Comment by kazuho** [comment]
Thank you for noticing the issue!
