### ISSUE TITLE
Custom h2o_fatal

### ISSUE THREAD

**Issue by yrashk** [h2o/h2o#3244]
When using H2O as a library, having it fail with `abort` is rather impractical in cases where (some) error recovery is possible. In my case, I integrate it with a much bigger application that should (ideally) not crash.

I wonder if you'd be open to allowing for h2o_fatal customization? I can submit a PR.

For example, we can make the inclusion of `h2o_fatal` implementation optional (configurable through CMake options/defines?) or allow for a globally configurable callback (since it's not in the way of the fast path, extra check there wouldn't hurt?), making it possible to use one regardless of the build-time configuration.

I am happy to iterate on the design of this feature.

P.S. I also see there are a few places where `h2o_fatal` could have been used but wasn't. May be I can address this as well?

**Comment by kazuho** [comment]
Thank you for raising the problem.

`h2o_fatal` is a macro that can be overridden; see include/h2o/memory.h. It is wrapped by `#ifndef`. I think you can pass something like `-DCMAKE_C_FLAGS="-Dh2o_fatal(x)=your_own(x)"` to replace the implementation. Or are you looking for something else?

> P.S. I also see there are a few places where `h2o_fatal` could have been used but wasn't. May be I can address this as well?

I would appreciate that. There are few places where we call `fprintf()` and `abort()`. They should be replaced by `h2o_fatal`.

**Comment by yrashk** [comment]
I will send a PR replacing `fprintf` and `abort` with `h2o_fatal` where appropriate.

As for passing h2o_fatal with a flag has two problems:

* Defining a function-like macros using command line is not guaranteed to work across different C compiler (though this works for GCC and clang). They are not supported by CMake: https://cmake.org/cmake/help/latest/prop_dir/COMPILE_DEFINITIONS.html ("Function-style definitions are not supported.")
* This makes it impossible to define/change the fatal handler in runtime, which may be desirable.

Considering that h2o_fatal is not in the fast execution path, perhaps it would be best to make it possible to configure it in runtime by setting a global variable to a custom function that would be set to `h2o__fatal` by default. Would you be open to this?
