### ISSUE TITLE
Website design improvisation

### ISSUE THREAD

**Issue by shivajivarma** [h2o/h2o#325]
I believe it would be great if website (https://h2o.github.io/index.html) design is improvised using any of open source html framework works like bootstrap, boilerplate etc.

**Comment by kazuho** [comment]
Thank you for the suggestion.

I understand the merits of using popular frameworks, and am not against migrating to such frameworks if it is as maintainable for me as the current approach.

If you could come up with a example (maybe by rewriting one or two pages and snippets) I will review it.

**Comment by shivajivarma** [comment]
Yes sure. I can do that.

**Comment by shivajivarma** [comment]
Hi Kazuho, I have made home page ready, have a look at it and let me know.... http://shivajivarma.com/h2o-website/

**Comment by k0nsl** [comment]
That looks very decent, Mr. Venkata.
-k0nsl

Shivaji Varma Pusapati Venkata skrev den 6/6/2015 1:26 PM:
>
> Hi Kazuho, I have made home page ready, have a look at it and let me
> know.... http://shivajivarma.com/h2o-website/
>
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/h2o/h2o/issues/325#issuecomment-109568199>.
>
>
>
>
>
>
>
>
>
>
>
>


-- 
This e-mail message may contain confidential or legally privileged
information and is intended only for the use of the intended
recipient(s). Any unauthorized disclosure, dissemination, distribution,
copying or the taking of any action in reliance on the information
herein is prohibited.

**Comment by kazuho** [comment]
@shivajivarma Thank you for your work!  It looks great.

Would you mind changing index.html to use some kind of wrapper to generate the notes and references to them?

The original source does that (by calling `$ctx->{note}`; see https://github.com/h2o/h2o/blob/master/srcdoc/index.mt#L20), and I would like to have same kind of feature.  Without such, it would be hard to maintain the numbers of the notes (and the links).

Such feature is also essential for generating the docs of configuration directives.  `$ctx->{directive}` is a function that builds the HTML element describing a configuration directive, taking the following arguments, which returns a closure to which the detailed description should be sent:
* name: name of the directive
* levels: array of levels (in string)
* default: the default value
* desc: summary of the description

https://github.com/h2o/h2o/blob/master/srcdoc/configure/http2_directives.mt (and https://github.com/h2o/h2o/blob/master/doc/configure/http2_directives.html which is the output) are good examples to understand how the function works.

Would you please also consider how we should implement such features on Jekyll?

**Comment by shivajivarma** [comment]
@kazuho : These can be implemented. Let me create a sample page.

**Comment by shivajivarma** [comment]
@kazuho : I have developed an alternative solution for 'notes' feature using jQuery.

Old code:
```scala
<?= $note->("also supports draft 14 and 16 for compatibility") ?>
```
New code:
```html
<sup note='also supports draft 14 and 16 for compatibility'/>
```

see code: https://github.com/shivajivarma/h2o-website/blob/gh-pages/index.html#L19
output: http://shivajivarma.com/h2o-website/

**Comment by shivajivarma** [comment]
@kazuho : In jekyll using `layout` and `site variables` you can modify page title, metadata and page structure. 

By default jekyll will generate page in same directive as the source page is defined.
Example:
Source page: /docs/test.html
Generated page: /docs/test/index.html

But you can still customize the directive by using `permalink` variable.
```YAML
---
layout: default
permalink: /custom/test.html
---
```

**Comment by shivajivarma** [comment]
@kazuho: I'm developing `directive` feature using jekyll. Code is not yet fully complete. You can have a look at partial implementation.

Directive snippet:
https://github.com/shivajivarma/h2o-website/blob/gh-pages/_includes/directive.html

Page:
https://github.com/shivajivarma/h2o-website/blob/gh-pages/func.html

Output:
http://shivajivarma.com/h2o-website/func/index.html

**Comment by kazuho** [comment]
Thank you for the code!

It looks neat and seems like I can maintain it :-)

Do you have any suggestions for:

> Would you mind changing index.html to use some kind of wrapper to generate the notes and references to them?
> The original source does that (by calling `$ctx->{note}`; see https://github.com/h2o/h2o/blob/master/srcdoc/index.mt#L20), and I would like to have same kind of feature. Without such, it would be hard to maintain the numbers of the notes (and the links).

**Comment by shivajivarma** [comment]
@kazuho : Hi, looks like i have already provided my solution in before comment. Ref: https://github.com/h2o/h2o/issues/325#issuecomment-110661169
