### ISSUE TITLE
Automl Sparkling Water Actual modelling steps: []

### ISSUE THREAD

**Issue by ssefick** [h2o/h2o#3251]
On a local spark cluster running sparkling water there is no problem fitting on a subset.

On emr I am receiving the messeage that no actual steps are being pased to automl.

This is a new problem. Any help wold be appreciated.

**Comment by u5surf** [comment]
@ssefick 
I wonder if you are misconscious the issue of something h2oai's peripheral suites for example this one.

https://github.com/h2oai/sparkling-water

This `h2o` is just http server is different completely from `h2oai`

**Comment by ssefick** [comment]
Thank you for the reply. It happens that s3a is used instead of s3 for the
checkpoints dir.

Stephen Sefick

**Comment by u5surf** [comment]
@ssefick 
I don't see that the issue is relevant to this repository.

**Comment by ssefick** [comment]
It is not. I didn't figure this out until 2 days ago. Please close issue.

Stephen Sefick
