### ISSUE TITLE
[Question] Clarification on HTTP/3 Support Status

### ISSUE THREAD

**Issue by catatsuy** [h2o/h2o#3264]
In the README, it says HTTP/3 is "experimental". Is this still true? Could you please tell me if HTTP/3 is still experimental or if it is now stable?

Thank you.

**Comment by kazuho** [comment]
It is now considered stable. README.md has to be updated.

**Comment by catatsuy** [comment]
Thank you for the quick response and for clarifying that HTTP/3 is now considered stable. That's good to know!

I'm looking forward to the update of README.md.
