### ISSUE TITLE
Question about security report

### ISSUE THREAD

**Issue by mukeran** [h2o/h2o#3279]
I wonder if h2o still accepts security report?
We have sent a report to h2o-vuln@googlegroups.com about a month ago but we didn't receive any response.
I have resent it, please let me know if it is marked as spam.

**Comment by kazuho** [comment]
Hey, thank you for sending us the report, I believe you've received our response sometime before you resent your email?

**Comment by mukeran** [comment]
I received it just now and it is in my spam folder. 
I'm sure that it didn't arrive before. It might be our email system's fault.
Thanks for your response.

**Comment by kazuho** [comment]
Thank you for the report!
