### ISSUE TITLE
general 32-bit (i386) support

### ISSUE THREAD

**Issue by dch** [h2o/h2o#3289]
A user reported build failures on [32-bit FreeBSD](https://pkg-status.freebsd.org/beefy15/data/132i386-default/8b3f09304cc8/logs/h2o-devel-2.3.0.d.20230817.log)
 
```
error: call to undeclared function '_mm_insert_epi64'; ISO C99 and later do not support implicit function declarations [-Werror,-Wimplicit-function-declaration]
    ctr = _mm_insert_epi64(ctr, seq, 0);
          ^
/wrkdirs/usr/ports/www/h2o-devel/work/h2o-70dd2d8/deps/picotls/lib/fusion.c:1129:11: note: did you mean '_mm_set_epi64'?
/usr/lib/clang/16/include/emmintrin.h:3447:46: note: '_mm_set_epi64' declared here
static __inline__ __m128i __DEFAULT_FN_ATTRS _mm_set_epi64(__m64 __q1,
                                             ^
/wrkdirs/usr/ports/www/h2o-devel/work/h2o-70dd2d8/deps/picotls/lib/fusion.c:1129:9: error: assigning to '__m128i' (vector of 2 'long long' values) from incompatible type 'int'
    ctr = _mm_insert_epi64(ctr, seq, 0);
        ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
```

Does h2o support 32-bit platforms or should I just skip this architecture from now on?

**Comment by kazuho** [comment]
Thank you for filing the issue.

Looks like a bug.

Fusion requires use of AVX2, it should be disabled anywhere that does not support it, regardless of that being i386 or Arm or whatever.

**Comment by dch** [comment]
Thanks @kazuho for the hint. I can work around this with `-DWITH_FUSION=OFF` for cmake I think.

**Comment by kazuho** [comment]
As of #3303, we test specifically the availability of `_mm_insert_epi64`, turn fusion on only if the function can be used.

Closing the issue as I believe it is fixed, please reopen if the problem persists.
