### ISSUE TITLE
Documentation for programmatic usage

### ISSUE THREAD

**Issue by h2non** [h2o/h2o#333]
I'm interesting in start hacking h2o. I would like to use the programmatic API.
There's some documentation for the high-level interface to interfact with. I'm specially interested about using the HTTP 2.0 server.

Some examples or recommendations to start with it? 
Cheers!

**Comment by kazuho** [comment]
Unfortunately there is no documentation, and the API is not stable yet.  For the time being I would suggest looking at issues tagged as `libh2o`.

**Comment by h2non** [comment]
All clear, thank you!
