### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by tkatsoulas** [h2o/h2o#3352]
Blank

**Comment by utrenkner** [comment]
I cannot speak to the possibility of a vulnerability here. But if you think you found one, then please do NOT publish it openly.

The devs have a specific e-Mail address you can use to responsibly disclose your finding: h2o-vuln@googlegroups.com. 
(see the bottom of https://github.com/h2o/h2o)

**Comment by tkatsoulas** [comment]
Thanks
