### ISSUE TITLE
Build problem with lib / lib64 naming.

### ISSUE THREAD

**Issue by Roze** [h2o/h2o#337]
There seems to be an issue (at least on OpenSuse (tested on 12.2 and 13.2)) of libdir detection so the Makefiles end up with inconsistent choice.

The libressl config ends up with: libdir='${exec_prefix}/lib64' but all the CMake files contain  libressl-build/lib/libssl.a

So in the end 'make' fails with:

	make[2]: *** No rule to make target 'libressl-build/lib/libssl.a', needed by 'h2o'.  Stop.
	CMakeFiles/Makefile2:247: recipe for target 'CMakeFiles/h2o.dir/all' failed
	make[1]: *** [CMakeFiles/h2o.dir/all] Error 2
	Makefile:117: recipe for target 'all' failed
	make: *** [all] Error 2

Creating a symlink in the 'libressl-build/' directory (or just renaming the lib64 -> lib) fixes the issue.

**Comment by kazuho** [comment]
Thank you for noticing the issue.  Fixed in the linked commit.

Please note that you may need to remove `libressl-2.1.6` and `libressl-build` directories.
