### ISSUE TITLE
support zstd for send-compressed

### ISSUE THREAD

**Issue by Jxck** [h2o/h2o#3372]
currently, `file.send-compressed: ON` only supports "gzip" and "br".
and now some browsers working on support "zstd" in content-encoding.
I'm now planning deploy pre-compiled ".zstd" file on server so it's welcome to include zstd in send-compressed.

- (Intent to Ship: Zstd Content-Encoding](https://groups.google.com/a/chromium.org/g/blink-dev/c/GFFOLCF12a4/m/GuYQ4LRQAgAJ)
- Gecko: Positive (https://github.com/mozilla/standards-positions/issues/775)
- WebKit: Positive (https://github.com/WebKit/standards-positions/issues/168)

**Comment by is-alnilam** [comment]
@kazuho and @Jxck thanks for adding this support! I've spotted a couple of things though that I'd like to check.

Firstly, and most importantly, is the allocated filename buffer large enough? Unless I'm misreading the code, `/lib/handler/file.c` allocates a buffer on line 295 which is three bytes longer than the original pathname, then on line 306 it copies an additional *five* bytes into the buffer (as the file extension is longer than the two bytes used for gzip and brotli).

Secondly, RFC 8478 and the official zstd compressor generate files with extension 'zst' (without the final 'd'). Is there a good way to handle this, other than adding another call to TRY_VARIANT?
