### ISSUE TITLE
Catch all for hosts

### ISSUE THREAD

**Issue by funzoneq** [h2o/h2o#340]
I would like to use a catch-all host that proxies all domains to my backend:

```
user: nobody
hosts:
  "_":
    listen:
      port: 80
    paths:
      "/":
        proxy.reverse.url: "http://127.0.0.1:8080/"
access-log: /var/log/h2o/access.log
error-log: /var/log/h2o/error.log
pid-file: /var/run/h2o/h2o.pid
```

nginx uses _; for this feature: http://nginx.org/en/docs/http/ngx_http_core_module.html#server_name

**Comment by kazuho** [comment]
The first host that is listening to the address becomes the catch-all domain, regardless of the name.

**Comment by funzoneq** [comment]
Thanks. That will work.
