### ISSUE TITLE
Any wrapper class for NSURLRequest

### ISSUE THREAD

**Issue by anchor00** [h2o/h2o#353]
I am mostly work on Mac and iOS. I am using NSURLRequest for post and get.
Is there a wrapper class that I can use to wrap the request and submit to h2o? or should I write a struct to hold the data and attach to the handler?
Thanks,

**Comment by kazuho** [comment]
Would you mind explaining a bit more?  H2O is a HTTP server that supports HTTP/1.x and HTTP/2.  I assue NSURLRequest is a HTTP client, so you can use it to access H2O.

**Comment by anchor00** [comment]
NSURLRequest is URL load request from HTTP client, it wraps the URL, policies and data into an object which will be used to call (POST or GET) the HTTP server. I think my question is that how can I pass binary data and header to HTTP2 server. Should I attach a struct to the handler?
Thanks,

**Comment by kazuho** [comment]
> I think my question is that how can I pass binary data and header to HTTP2 server.

If that is the case, I am afraid the question is off-topic (unrelated to H2O).

Please ask the question to Apple's developer support or at some of the developer forums (e.g. stackoverflow).
