### ISSUE TITLE
mapping certain extensions (e.g. .php) to FastCGI

### ISSUE THREAD

**Issue by kazuho** [h2o/h2o#357]
Many PHP-based apps (esp. those designed for Apache + mod_php) stores `.php` files under document root, expecting that the web-server would determine by looking at the extension if the content should be served statically or if it should be served dynamically (by executing the file).

We would definitely want to do the same in H2O by using php-fpm.

relates to #346

**Comment by gaoyichuan** [comment]
Well, why not implement some kind of the nginx style? (such as config of location)

**Comment by kazuho** [comment]
> Well, why not implement some kind of the nginx style? (such as config of location)

If you are talking about using pattern-matching against URL to detect requests to PHP files, I would say that such approach is broken by design.

If you Google, you would find lengthy discussions on how to mimic the feature on nginx by using directives like `try_files`, `fastcgi_split_path_info`, `fastcgi_index`, etc., and no one is sure what the ideal configuration is.

I would not want to create such a configuration mess with H2O; FastCGI (or PHP) applications should be as easily configurable as it is for the Apache HTTP server; and the logical approach is to support extension-based mapping (which was how Apache was designed / is also what RFC 3875 (which FastCGI is designed pon) expects).
