### ISSUE TITLE
more format directives for access logging

### ISSUE THREAD

**Issue by kazuho** [h2o/h2o#36]
As of now, only a small portion of the CustomLog directive are supported (see https://github.com/kazuho/h2o/blob/master/lib/access_log.c#L34).

We should better cover those defined in http://search.cpan.org/~miyagawa/Plack-1.0031/lib/Plack/Middleware/AccessLog.pm#CONFIGURATION

**Comment by kazuho** [comment]
adding directives to cover interoperability with LTSV might be a good idea, specifically those listed in the exmaple section of [ltsv.org](http://ltsv.org/), and the time format string shown in http://y-ken.hatenablog.com/entry/apache-tips-ltsv-access-log

**Comment by Jxck** [comment]
+1

**Comment by kazuho** [comment]
@Jxck can you elaborate what you want to log?
