### ISSUE TITLE
FreeBSD 10, ocsp error and no logging

### ISSUE THREAD

**Issue by Tintinabula** [h2o/h2o#361]
Pulling the latest h2o code today we noticed two issues on FreeBSD 10-p12.

1. When starting the server the client requests were no longer logging to the "access-log" file. There were no errors to explain why. When we reverted back to the code from May 14th, 2015 logging worked fine.

2. "OpenSSL exitted abnormally" error is seen in the error-log file. Here are two blocks of the log. Again, reverting back to the code from May 14th, 2015 worked fine.

```
starting new worker 15032
[INFO] raised RLIMIT_NOFILE to 203904
h2o server (pid:15032) is ready to serve requests
fetch-ocsp-response (using OpenSSL 1.0.1l-freebsd 15 Jan 2015)
sending OCSP request to http://ocsp.comodoca.com
Can't get connection fd
Error querying OCSP responder
OpenSSL exitted abnormally: openssl ocsp -issuer /tmp/TMY9_Our7T/issuer.crt -cert /ssl_keys/example.org_ssl.crt -url http://ocsp.comodoca.com -header Host ocsp.comodoca.com -noverify -respout /tmp/TMY9_Our7T/resp.der :[OCSP Stapling] reusing old response due to a temporary error occurred while fetching OCSP response for certificate file:/ssl_keys/example.org_ssl.crt

Filehandle STDIN reopened as $fh only for output at /usr/local/share/h2o/start_server line 10.
starting new worker 15312
[INFO] raised RLIMIT_NOFILE to 203904
h2o server (pid:15312) is ready to serve requests
fetch-ocsp-response (using OpenSSL 1.0.1l-freebsd 15 Jan 2015)
sending OCSP request to http://ocsp.comodoca.com
Can't get connection fd
Error querying OCSP responder
OpenSSL exitted abnormally: openssl ocsp -issuer /tmp/GZFZcOl996/issuer.crt -cert /ssl_keys/example.org_ssl.crt -url http://ocsp.comodoca.com -header Host ocsp.comodoca.com -noverify -respout /tmp/GZFZcOl996/resp.der :[OCSP Stapling] reusing old response due to a temporary error occurred while fetching OCSP response for certificate file:/ssl_keys/example.org_ssl.crt
```

FYI, FreeBSD 10 changed the default location of perl to "/usr/local/bin/perl" in case the perl path is important.

**Comment by kazuho** [comment]
Thank you for noticing the issue.  I will look into it.

The issue might be related to https://github.com/kazuho/p5-Server-Starter/pull/30

**Comment by kazuho** [comment]
@Tintinabula I have fixed the second issue (`OpenSSL exitted abnormally` being reported) has been fixed in the commit above.

OTOH I have so far been unable to reproduce the first issue (access-log not emitted) on FreeBSD 10.1.  Would you mind posting the configuration file (and command options passed to H2O) with which the problem can be reproduced?

**Comment by Tintinabula** [comment]
@kazuho  Both problems have been fixed in today's checkout. The error log shows a successful OCSP response and logging is working as expected. Thank you very much!

**Comment by kazuho** [comment]
Glad to hear that.  Thank you for your help!
