### ISSUE TITLE
failed to open wait file descriptor (fd=5):Bad file descriptor PHP

### ISSUE THREAD

**Issue by centminmod** [h2o/h2o#381]
Getting the error on starting h2o 1.3.1 with h2o.conf at https://bitbucket.org/snippets/eva2000/jKxA/revisions/1316863630de0b5959adae021757a100e6f04799 (would be great to have per host yaml config files to make it easier to manage ;) )

    failed to open wait file descriptor (fd=5):Bad file descriptor at /usr/local/share/h2o/kill-on-close line 36.
    start_server (pid:20769) starting now...

version

    h2o -v
    h2o version 1.3.1

php-cgi

    /usr/local/bin/php-cgi -v
    PHP 5.4.28 (cgi-fcgi) (built: May  7 2014 10:03:57)

php-fpm

    /usr/local/bin/php -v    
    PHP 5.4.28 (cli) (built: May  7 2014 10:03:30) 
    Copyright (c) 1997-2014 The PHP Group
    Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies

**Comment by kazuho** [comment]
Thank you for reporting the issue.

I was possible to reproduce the issue when starting H2O with option: `-m daemon`.

OTOH I am happy to find out that the issue does not cause any mis-operation of FastCGI applications.  The message is emitted by an process that has been spawned unnecessarily.  I will address the issue afterwards.

**Comment by kazuho** [comment]
@centminmod The issue has been fixed in the commit above.  Please let me know if you still see the problem.
