### ISSUE TITLE
h2o build fails on smartos

### ISSUE THREAD

**Issue by j-trash** [h2o/h2o#382]
building on smartos fails, after the included openssl finished without any problems.

the previous configuration part looks fine to me so far

cmake output:

-- snip --
-- The C compiler identification is GNU 4.7.4
-- Check for working C compiler: /opt/local/bin/cc
-- Check for working C compiler: /opt/local/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PkgConfig: /opt/local/bin/pkg-config (found version "0.28")
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
-- Found OpenSSL: /opt/local/lib/libssl.so;/opt/local/lib/libcrypto.so (found version "1.0.2a")
-- checking for module 'libuv>=1.0.0'
--   found libuv, version 1.6.1
-- checking for module 'libwslay'
--   found libwslay, version 1.0.1-DEV
-- Configuring done
-- Generating done
-- Build files have been written to: /root/h2o

// -- snip --

make output:

-- snip --

 make
Scanning dependencies of target bundled-ssl
checking build system type... x86_64-pc-solaris2.11
checking host system type... x86_64-pc-solaris2.11
checking for a BSD-compatible install... ./install-sh -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for clock_gettime... yes
checking for dl_iterate_phdr... yes
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking how to print strings... print -r
checking for a sed that does not truncate output... /opt/local/bin/sed
checking for grep that handles long lines and -e... /usr/xpg4/bin/grep
checking for egrep... /usr/xpg4/bin/grep -E
checking for fgrep... /usr/xpg4/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /opt/local/bin/nm -B
checking the name lister (/opt/local/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 786240
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-pc-solaris2.11 file names to x86_64-pc-solaris2.11 format... func_convert_file_noop
checking how to convert x86_64-pc-solaris2.11 file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... print -r --
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /opt/local/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -64) supports shared libraries... yes
checking dynamic linker characteristics... solaris2.11 ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking for gcc option to accept ISO C99... none needed
checking for gcc option to accept ISO Standard C... (cached) none needed
checking if compiling with clang... no
checking if gcc supports "-fno-strict-overflow"... yes
checking if gcc supports "-D_FORTIFY_SOURCE=2"... yes
checking if /usr/bin/ld -64 supports "-Wl,-z,relro"... no
checking if /usr/bin/ld -64 supports "-Wl,-z,now"... yes
checking if gcc supports "-fstack-protector-strong"... no
checking if gcc supports "-fstack-protector-all"... yes
checking whether CC supports -Wno-pointer-sign... yes
checking whether AS supports .note.GNU-stack... yes
checking dependency style of gcc... gcc3
checking for arc4random_buf... yes
checking for asprintf... yes
checking for explicit_bzero... yes
checking for funopen... no
checking for getauxval... no
checking for getentropy... yes
checking for issetugid... yes
checking for memmem... yes
checking for poll... yes
checking for reallocarray... no
checking for strlcat... yes
checking for strlcpy... yes
checking for strndup... yes
checking for strnlen... yes
checking for strsep... yes
checking for strtonum... no
checking for symlink... yes
checking for timingsafe_bcmp... no
checking for timingsafe_memcmp... no
checking whether va_copy exists... yes
checking whether __va_copy exists... yes
checking sys/sysctl.h usability... no
checking sys/sysctl.h presence... no
checking for sys/sysctl.h... no
checking err.h usability... yes
checking err.h presence... yes
checking for err.h... yes
checking if BSWAP4 builds without __STRICT_ALIGNMENT... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating include/Makefile
config.status: creating include/openssl/Makefile
config.status: creating crypto/Makefile
config.status: creating ssl/Makefile
config.status: creating tls/Makefile
config.status: creating tests/Makefile
config.status: creating apps/Makefile
config.status: creating man/Makefile
config.status: creating libcrypto.pc
config.status: creating libssl.pc
config.status: creating libtls.pc
config.status: creating openssl.pc
config.status: executing depfiles commands
config.status: executing libtool commands

### here things start going bad

 ./install-sh -c -m 644 libcrypto.pc libssl.pc libtls.pc openssl.pc '/root/h2o/libressl-build/lib/pkgconfig'
[  0%] Built target bundled-ssl
Scanning dependencies of target h2o
[  0%] Building C object CMakeFiles/h2o.dir/deps/cloexec/cloexec.c.o
[  0%] Building C object CMakeFiles/h2o.dir/deps/picohttpparser/picohttpparser.c.o
[  1%] Building C object CMakeFiles/h2o.dir/lib/common/hostinfo.c.o
[  1%] Building C object CMakeFiles/h2o.dir/lib/common/http1client.c.o
[  3%] Building C object CMakeFiles/h2o.dir/lib/common/memory.c.o
/root/h2o/lib/common/memory.c: In function 'h2o_buffer__do_free':
/root/h2o/lib/common/memory.c:190:9: warning: passing argument 1 of 'munmap' from incompatible pointer type [enabled by default]
In file included from /root/h2o/lib/common/memory.c:30:0:
/usr/include/sys/mman.h:243:12: note: expected 'caddr_t' but argument is of type 'struct h2o_buffer_t *'
/root/h2o/lib/common/memory.c: In function 'h2o_buffer_reserve':
/root/h2o/lib/common/memory.c:232:21: warning: implicit declaration of function 'alloca' [-Wimplicit-function-declaration]
/root/h2o/lib/common/memory.c:232:35: warning: incompatible implicit declaration of built-in function 'alloca' [enabled by default]
/root/h2o/lib/common/memory.c:246:27: warning: assignment from incompatible pointer type [enabled by default]
/root/h2o/lib/common/memory.c:263:21: warning: passing argument 1 of 'munmap' from incompatible pointer type [enabled by default]
In file included from /root/h2o/lib/common/memory.c:30:0:
/usr/include/sys/mman.h:243:12: note: expected 'caddr_t' but argument is of type 'struct h2o_buffer_t *'
[  3%] Building C object CMakeFiles/h2o.dir/lib/common/multithread.c.o
[  3%] Building C object CMakeFiles/h2o.dir/lib/common/serverutil.c.o
[  5%] Building C object CMakeFiles/h2o.dir/lib/common/socket.c.o
In file included from /root/h2o/lib/common/socket.c:77:0:
/root/h2o/lib/common/socket/evloop.c.h: In function 'do_write':
/root/h2o/lib/common/socket/evloop.c.h:262:5: warning: implicit declaration of function 'alloca' [-Wimplicit-function-declaration]
/root/h2o/lib/common/socket/evloop.c.h:262:12: warning: incompatible implicit declaration of built-in function 'alloca' [enabled by default]
[  5%] Building C object CMakeFiles/h2o.dir/lib/common/socketpool.c.o
[  6%] Building C object CMakeFiles/h2o.dir/lib/common/string.c.o
[  6%] Building C object CMakeFiles/h2o.dir/lib/common/time.c.o
/root/h2o/lib/common/time.c: In function 'h2o_time2str_log':
/root/h2o/lib/common/time.c:142:31: error: 'struct tm' has no member named 'tm_gmtoff'
CMakeFiles/h2o.dir/build.make:284: recipe for target 'CMakeFiles/h2o.dir/lib/common/time.c.o' failed
make[2]: *** [CMakeFiles/h2o.dir/lib/common/time.c.o] Error 1
CMakeFiles/Makefile2:249: recipe for target 'CMakeFiles/h2o.dir/all' failed
make[1]: *** [CMakeFiles/h2o.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
-- snip --

Plattform Versions are

SunOS mirror 5.11 joyent_20150320T034246Z i86pc i386 i86pc

Using built-in specs.
COLLECT_GCC=/opt/local/gcc47/bin/gcc
COLLECT_LTO_WRAPPER=/opt/local/gcc47/libexec/gcc/x86_64-sun-solaris2.11/4.7.4/lto-wrapper
Target: x86_64-sun-solaris2.11
Configured with: ../gcc-4.7.4/configure --enable-languages='c obj-c++ objc go fortran c++' --enable-shared --enable-long-long --with-local-prefix=/opt/local --enable-libssp --enable-threads=posix --with-boot-ldflags='-static-libstdc++ -static-libgcc -Wl,-R/opt/local/lib ' --disable-nls --with-gxx-include-dir=/opt/local/gcc47/include/c++/ --without-gnu-ld --with-ld=/usr/bin/ld --with-gnu-as --with-as=/opt/local/bin/gas --prefix=/opt/local/gcc47 --build=x86_64-sun-solaris2.11 --host=x86_64-sun-solaris2.11 --infodir=/opt/local/gcc47/info --mandir=/opt/local/gcc47/man
Thread model: posix
gcc version 4.7.4 (GCC)

anyone got an hint how to get rid of this?

**Comment by j-trash** [comment]
Update.. i managed it to "skip" this error, excuse my noobness but this is trial&error for me. i just kicked out the part of time.c which caused the error. just to see what happens than.

time.c looks like this now at the end of the file

-- snip --
void h2o_time2str_log(char *buf, time_t time)
{

    struct tm localt;
        localtime_r(&time, &localt);

    int len = sprintf(buf, "%02d/%s/%d:%02d:%02d:%02d %c%02d%02d", localt.tm_mday,
                      ("Jan\0Feb\0Mar\0Apr\0May\0Jun\0Jul\0Aug\0Sep\0Oct\0Nov\0Dec\0") + localt.tm_mon * 4, localt.tm_year + 1900,
                      localt.tm_hour, localt.tm_min, localt.tm_sec);
    assert(len == H2O_TIMESTR_LOG_LEN);
}
-- snip --

i am sure this breaks something, but so far make was happy and continued trying to build the fastcgi part and dies again. so far, everything looks platform related to me. time.c & fastcgi 

-- snip --
[  0%] Built target bundled-ssl
[  0%] Building C object CMakeFiles/h2o.dir/lib/handler/configurator/fastcgi.c.o
/root/h2o/lib/handler/configurator/fastcgi.c: In function 'on_config_connect':
/root/h2o/lib/handler/configurator/fastcgi.c:125:28: error: expected identifier or '(' before numeric constant
/root/h2o/lib/handler/configurator/fastcgi.c:126:43: error: request for member 'sun_path' in something not a structure or union
/root/h2o/lib/handler/configurator/fastcgi.c:130:12: error: request for member 'sun_family' in something not a structure or union
/root/h2o/lib/handler/configurator/fastcgi.c:131:19: error: request for member 'sun_path' in something not a structure or union
/root/h2o/lib/handler/configurator/fastcgi.c:132:64: error: lvalue required as unary '&' operand
/root/h2o/lib/handler/configurator/fastcgi.c: At top level:
/root/h2o/lib/handler/configurator/fastcgi.c:150:49: error: expected ';', ',' or ')' before numeric constant
/root/h2o/lib/handler/configurator/fastcgi.c: In function 'on_config_spawn':
/root/h2o/lib/handler/configurator/fastcgi.c:223:24: error: expected identifier or '(' before numeric constant
/root/h2o/lib/handler/configurator/fastcgi.c:235:5: warning: implicit declaration of function 'create_spawnproc' [-Wimplicit-function-declaration]
/root/h2o/lib/handler/configurator/fastcgi.c:235:66: error: lvalue required as unary '&' operand
/root/h2o/lib/handler/configurator/fastcgi.c:242:60: error: lvalue required as unary '&' operand
CMakeFiles/h2o.dir/build.make:813: recipe for target 'CMakeFiles/h2o.dir/lib/handler/configurator/fastcgi.c.o' failed
make[2]: *** [CMakeFiles/h2o.dir/lib/handler/configurator/fastcgi.c.o] Error 1
CMakeFiles/Makefile2:249: recipe for target 'CMakeFiles/h2o.dir/all' failed
make[1]: *** [CMakeFiles/h2o.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2
-- snip --

at this part, my c noobness clearly has no more clue ...

**Comment by kazuho** [comment]
Sorry for being late, it is likely that you would be able to build and use H2O on smartos once #384 gets resolved.

**Comment by j-trash** [comment]
no problem, i am thankful for every hint :) good to hear that someone already takes care of it,, cant wait to start testing with h2o :)

**Comment by kazuho** [comment]
With the merger of #384 you can now build H2O on OpenIndiana, and I assume you also can on SmartOS (note: you need gcc >= 4).

However it is likely that you would see crashes when the max. fd number reaches some threshold; see https://github.com/h2o/h2o/pull/384#issuecomment-117350460 for details.

**Comment by j-trash** [comment]
great thank you! will try right after this and leave feedback here :)

**Comment by j-trash** [comment]
works like a charm, thanks again!

**Comment by kazuho** [comment]
Glad to hear that! :+1:
