### ISSUE TITLE
Can h2o support include directive to include sub config file?

### ISSUE THREAD

**Issue by AssemblyXiang** [h2o/h2o#390]
Can h2o support include directive to include etc config file?

**Comment by kazuho** [comment]
I am sorry but it's not possible for the time being.

**Comment by necrophcodr** [comment]
Any chance of this happening in the future? It would make h2o a more viable product for hosting solutions, where a larger amount of vhosts are required (like apache2 sites-enabled, that kind of thing).

**Comment by deweerdt** [comment]
@i110 implemented this in https://github.com/h2o/h2o/pull/1022
