### ISSUE TITLE
request body issue

### ISSUE THREAD

**Issue by funguru** [h2o/h2o#393]
Please, I noticed that the request body is not freed/memset for the next handled-requests:
the req->entity.base value is :
1st req:
{"A": "11","B": "22","C": "33"}
2nd req
{"A": "1","B": "2","C": "3"}33"}
Is it a normal behavior?

Could you please help me to reset the body for the next request ?
The target is to have a second req like:
{"A": "1","B": "2","C": "3"}

Many thanks in advance.

**Comment by kazuho** [comment]
The buffer pointed by `req->entity.base` is unterminated.  You should obtain the length of the entity by accessing `req->entity.len`.

**Comment by funguru** [comment]
Many thanks for your feedback.
