### ISSUE TITLE
[RFC] Provide pkg-config file

### ISSUE THREAD

**Issue by omasanori** [h2o/h2o#396]
h2o uses pkg-config to find libraries. Shall we use pkg-config to find libh2o from other projects, too?

I'm ready to work on this but, before I really start to do, I'd like to hear your opinions.

Notes:
- Since pkg-config was born in the pre-semver era, its version comparison algorithm cannot recognize Semantic Versioning properly.
- The .pc files provide information about libh2o and its family, so should we use `LIBRARY_VERSION_*` for the Version fields, or `VERSION_*`?
    - If we use `LIBRARY_VERSION_*`, we might be confused: "I installed h2o version 2.0.3 but checking libh2o >= 2.0 fails... Why?" However, `LIBRARY_VERSION_*`, if my understanding is correct, reflects API and/or ABI compatibility (after 1.0.0?), so we can check what we actually want.

**Comment by kazuho** [comment]
Thank you for your offer.  I think it is a good idea to generate pkg-config files.

> * Since pkg-config was born in the pre-semver era, its version comparison algorithm cannot recognize Semantic Versioning properly.

Is there any negative impact with pkg-config in using semantic versioning?  Unless there is I think we should continue using semantic versioning.

> * The .pc files provide information about libh2o and its family, so should we use LIBRARY_VERSION_* for the Version fields, or VERSION_*?

`LIBRARY_VERSION_*` should be used.

**Comment by omasanori** [comment]
@kazuho
Version check well be broken if pre-release version or build metadata is contained. `LIBRARY_VERSION_*` does not contain them, so it works well.

**Comment by kazuho** [comment]
@omasanori Thank you for the clarification.

The limits sounds OK.  In other words, I think using `LIBRARY_VERSION_(MAJOR|MINOR|PATCH)` are fine.

**Comment by quentusrex** [comment]
Any update on this? I can assist with the patch, or with testing it if there is a branch.

**Comment by omasanori** [comment]
@quentusrex I have a preliminary patch in my laptop, but it needs to be modified a little to apply to current code base.
I will take a look on this weekend. I'm sorry for my laziness and Thanks for your ping.

**Comment by quentusrex** [comment]
I'm working with the library right now on a few projects, so if you have your patch in a public branch, or attached here, I can help. If not, then I'll wait for a notification.

**Comment by quentusrex** [comment]
@omasanori ping again. I can help clean up a patch if you already have one.

**Comment by omasanori** [comment]
@quentusrex I pushed the branch to GitHub and sent PR #743 now.
I'm really sorry for being late. Would you review that?

**Comment by quentusrex** [comment]
Looks good after a quick visual review. Just tested the branch locally.
