### ISSUE TITLE
HTTPS header blank when using FastCGI with HHVM

### ISSUE THREAD

**Issue by janit** [h2o/h2o#397]
I run H2O with HHVM with the following configuration: https://www.symfony.fi/entry/serving-php-on-http-2-with-h2o-and-hhvm-symfony-wordpress-drupal#gist23613082

I run a tool called Bolt on it. It relies on the Symfony2 HTTPKernel component (https://github.com/symfony/HttpKernel) underneath. The component relies on headers to set and create URLs correctly (http://example.com vs. https://example.com), but it fails because the HTTPS header is blank:

<img width="272" alt="screen shot 2015-07-14 at 09 04 53" src="https://cloud.githubusercontent.com/assets/198965/8667371/71c0a344-2a07-11e5-8be4-143c4976566c.png">

The HTTPS header should be set to value "on" for this to work.

I also tried to set the header manually using header directives: https://h2o.examp1e.net/configure/headers_directives.html

I also tested setting other headers like "X-Forwarded-Proto https", but they failed to show up in the header dump.

**Comment by kazuho** [comment]
Thank you for noticing the issue.

I have added code to the fastcgi handler that sets `HTTPS` variable to `on` in case the protocol is HTTPS.

> I also tried to set the header manually using header directives: https://h2o.examp1e.net/configure/headers_directives.html

The directive is for setting response headers, it cannot be used for modifying request headers passed to FastCGI applications.
