### ISSUE TITLE
H2O 1.4.0 persistantly running as nobody in Debian 7

### ISSUE THREAD

**Issue by janit** [h2o/h2o#416]
I upgraded from 1.3.1 to 1.4.0 and ran into an issue with HHVM over fastcgi not working. Error log reported:

    [lib/handler/fastcgi.c] in request:/:connection failed:failed to connect to host

I investigated and looks like the unable to access the socket. In my configuration there is a global directive:

    user: www-data

Despite this, h2o process launches as "nobody". Reverted back to 1.3.1 and process runs as www-data. 

Probably related to: https://github.com/h2o/h2o/pull/414

**Comment by kazuho** [comment]
Oh!  Thank you for noticing the issue.  Fixed and released 1.4.1.

**Comment by janit** [comment]
Perfect!
