### ISSUE TITLE
Inconsistency in the attribute name at `ssl-session-resumption` directive

### ISSUE THREAD

**Issue by mochipon** [h2o/h2o#417]
Hi @kazuho san,

There are some inconsistency in describing the attribute name for defining the methods on `ssl-session-resumption`.

According to the code ([ssl.c#L648](https://github.com/h2o/h2o/blob/1a49817912c03c19431102ab68a1387c3ce2d022/src/ssl.c#L648)), the `mode` attribute defines which methods should be used for resuming the TLS sessions. 
However, [the document](https://h2o.examp1e.net/configure/base_directives.html) calls it as `method`.

Thank you very much for your hard work!

**Comment by kazuho** [comment]
Thank for reporting the issue.  Fixed the docs in the reporistory and the one on h2o.examp1e.net.
