### ISSUE TITLE
HTTP/2 for "http" URIs

### ISSUE THREAD

**Issue by JanAndersson** [h2o/h2o#418]
Is HTTP/2 Upgrade mechanism working?

I send the following HTTP/1.1 request to h2o, version 1.3.1:

GET / HTTP/1.1
X-Test: foo
Host: localhost:8080
Accept-Encoding: gzip
Connection: Upgrade, HTTP2-Settings
Upgrade: h2c
HTTP2-Settings: AAQAEAAA

But only get an HTTP/1.1 response back.

My h2o configuration:

hosts:
  "127.0.0.1:8080":
    listen:
      port: 8080
    listen:
      port: 8443
      ssl:
        certificate-file: /usr/local/etc/h2o/server.crt
        key-file: /usr/local/etc/h2o/server.key
    paths:
      "/":
        file.dir: /usr/local/var/h2o/

**Comment by kazuho** [comment]
@JanAndersson It should be working.

With version 1.4.1 and the provided configuration, I get the following response.

```
$ telnet localhost 8080
Trying ::1...
Connected to localhost.
Escape character is '^]'.
GET / HTTP/1.1
X-Test: foo
Host: localhost:8080
Accept-Encoding: gzip
Connection: Upgrade, HTTP2-Settings
Upgrade: h2c
HTTP2-Settings: AAQAEAAA

HTTP/1.1 101 Switching Protocols
Date: Thu, 23 Jul 2015 00:17:17 GMT
Server: h2o/1.4.1
Connection: upgrade
upgrade: h2c

(binary follows)
```

I have no idea why it is not working on your side, but upgrading the server to 1.4.1 might help, though I believe it should be working on 1.3.1 as well (there is a unit test executed on Travis to check if the feature is working).

**Comment by JanAndersson** [comment]
It's working. Sorry...

The problem was my client. It was case sensitive when checking the Connection response header. It only accepted "Upgrade" (capital "U").

**Comment by kazuho** [comment]
no problem :+1:
