### ISSUE TITLE
Can't login with FastCGI

### ISSUE THREAD

**Issue by csmk** [h2o/h2o#424]
Hi Kazuho,

I'm using H2O 1.4.1 and I can't login on PHP applications (Roundcube, RainLoop, phpMyAdmin) through FastCGI. When I try to login, the application says that there is failure in the authentication or the page just goes back to the same page without any error. By the way, the error logs also do not report any errors.

I tried many settings, as well as many different browsers. Though, if I use nginx as a back-end proxy for H2O, I can login normally. Maybe the problem is somehow related to the set-cookie? I'm layman, so forgive my *noobness*.

For reference, this is my configuration files: [h2o.conf](https://gist.github.com/csmk/3c819c3ecdcfef85b00e), [php.ini](https://gist.github.com/csmk/b898eaf9ab1b9be7bee2), [php-fpm.conf](https://gist.github.com/csmk/8cf6201ec31cbeb1a3a1), [nginx.conf](https://gist.github.com/csmk/b8d47f25dfd38e6be5b5)

Thank you in advance for your attention on this matter.

PS: I have a small VPS that I use only for tests, if necessary I can give you SSH access so you can explore the problem above.

**Comment by kazuho** [comment]
Thank you for reporting the issue.

Can you provide the HTTP request (e.g. dump of request headers) that are sent by the client when it tries to logon to the application.

Maybe by replaying the request on my side I would be possible to nail down the cause of the issue, by comparing the output of the proxying backend and FastCGI backend.

**Comment by csmk** [comment]
With RainLoop, I've found that if I clean browser's cookies and try do login, the application says "Invalid token", but if I reload the page and try to login again, the login work fine.

Here is the request header for RainLoop:
```
POST /?/Ajax/&q[]=/0/ HTTP/1.1
Host: webmail.domain.org
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:39.0) Gecko/20100101 Firefox/39.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
DNT: 1
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
X-Requested-With: XMLHttpRequest
Referer: https://webmail.domain.org/?/Admin/
Content-Length: 116
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
```

And the response header for RainLoop:
```
HTTP/2.0 200 OK
Server: h2o/1.4.1, RainLoop
Date: Mon, 27 Jul 2015 11:16:21 GMT
Expires: Mon, 26 Jul 1997 05:00:00 GMT
Last-Modified: Mon, 27 Jul 2015 11:16:21 GMT
Cache-Control: no-store, no-cache, must-revalidate, max-age=0, post-check=0, pre-check=0
Pragma: no-cache
Set-Cookie: rltoken=f3c3daf9c86d509485c4bf45f7db8978; expires=Wed, 26-Aug-2015 11:16:21 GMT; Max-Age=2592000; path=/; httponly
Content-Type: application/json; charset=utf-8
Content-Encoding: gzip
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
x-permitted-cross-domain-policies: master-only
X-XSS-Protection: 1; mode=block
Public-Key-Pins: pin-sha256="***************************"; pin-sha256="***************************"; max-age=14400
Strict-Transport-Security: max-age=315360000
X-Frame-Options: sameorigin
X-Firefox-Spdy: h2
```

For phpMyAdmin there is no error message, the index page just reload with different token in the URL.

Request header for PMA:
```
POST /index.php HTTP/1.1
Host: pma.domain.org
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:39.0) Gecko/20100101 Firefox/39.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
DNT: 1
Referer: https://pma.domain.org/index.php?collation_connection=utf8_general_ci&token=052988ecee3a148e5c61064a5ed247a5
Cookie: pma_lang=en; phpMyAdmin=JQ-ID0nfY4e6YfwTbjUO%2CjYKtG3Ikbc53sUnoxd4RS1; pma_iv-1=k8XARCfZTCIHoKLZDbk4xg%3D%3D; pma_collation_connection=utf8_general_ci
Connection: keep-alive
```

Response header for PMA:
```
HTTP/2.0 302 Found
Server: h2o/1.4.1
Date: Mon, 27 Jul 2015 11:42:18 GMT
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: private, max-age=10800, pre-check=10800
Last-Modified: Mon, 27 Jul 2015 10:34:21 GMT
Set-Cookie: pma_iv-1=wq2Mai2dEjS8nVitCL5UCg%3D%3D; expires=Wed, 26-Aug-2015 11:42:18 GMT; Max-Age=2592000; path=/; secure; httponly, pmaUser-1=6rRv5R04BBJ8o8AqMDG%2FnA%3D%3D; expires=Wed, 26-Aug-2015 11:42:18 GMT; Max-Age=2592000; path=/; secure; httponly, pmaPass-1=Pe7384v09jBf1tFcLVfeHWV%2Bgh8lcdMb0s5BSGvxjMU%3D; path=/; secure; httponly
x-ob_mode: 0
Location: https://pma.domain.org:443/index.php?token=20ea4c0bc5a9d437676ede91043af67e
Content-Encoding: gzip
Vary: Accept-Encoding
Content-Type: text/html; charset=UTF-8
X-Content-Type-Options: nosniff
x-permitted-cross-domain-policies: master-only
X-XSS-Protection: 1; mode=block
Public-Key-Pins: pin-sha256="***************************"; max-age=14400
Strict-Transport-Security: max-age=315360000
X-Frame-Options: sameorigin
X-Firefox-Spdy: h2
```

**Comment by kazuho** [comment]
Thank you for the details.  Together with the information #425 I was possible to nail down and fix the issue.

**Comment by csmk** [comment]
No, I thank you for the fast response and fix. :bow:

I've just finished the build of h2o/1.4.2-alpha1, and the fix is working fine. :ok_hand:
