### ISSUE TITLE
purpose of setuidgid binary unclear

### ISSUE THREAD

**Issue by dch** [h2o/h2o#426]
as part of updating the FreeBSD package to 1.4.1, it's not clear what we need to do with this new binary. If it's omitted entirely from the port, will h2o work fine? For the moment I propose putting it in `/usr/local/share/h2o/`.

**Comment by kazuho** [comment]
Thank you for working on updating the package.

`setuidgid` is a wrapper program used to drop the privileges of the process spawned by `fastcgi.spawn`.  And for the directive to work correctly it needs to be stored under `share/h2o` of the install prefix, next to other helper programs such as `fetch-ocsp-response`.

**Comment by dch** [comment]
no @kazuho thank you & team! I've put it in share/h2o and will be in next package release \o/

**Comment by kazuho** [comment]
Saw the port being released on Twitter.  Thank you for the work!
