### ISSUE TITLE
Gzip in proxy mode

### ISSUE THREAD

**Issue by Roze** [h2o/h2o#429]
Does h2o drop/ignore the accept-encoding header (like gzip, deflate) in proxy mode?
Because currently it seems it does which greatly increases the traffic:

Direct:
```
curl -k -o/dev/null -D - "http://127.0.0.1" -H "Accept-Encoding: gzip"

HTTP/1.1 200 OK
Server: nginx
Date: Thu, 30 Jul 2015 21:34:06 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Content-Encoding: gzip
```
Via h2o:
```
curl -k -o/dev/null -D - "https://127.0.0.1" -H "Accept-Encoding: gzip"

HTTP/1.1 200 OK
Date: Thu, 30 Jul 2015 21:34:12 GMT
Server: h2o
Connection: keep-alive
content-type: text/html; charset=utf-8
expires: Thu, 19 Nov 1981 08:52:00 GMT
cache-control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
pragma: no-cache
transfer-encoding: chunked
```

**Comment by kazuho** [comment]
@Roze I think what you are looking for is #413.  I expect it to get merged to master pretty soon.

**Comment by Roze** [comment]
Looks nice though maybe an option to work in passthrough mode - like in my case the compression is allready done on the backends.so h2o would only just send the response to the client./ less workload on the ssl offloader.

Looking at the code
```
/* skip if content-encoding header is being set */  
if (h2o_find_header(&req->res.headers, H2O_TOKEN_CONTENT_ENCODING, -1) != -1)  
  goto Next;  
```
feels that it is skipped or am I reading it wrong?

**Comment by kazuho** [comment]
@Roze Thank you for the clarification.

So you are not saying that you want H2O to compress the data on the fly, but you are saying that H2O drops the Content-Encoding header that makes your web-app impossible to do any gzip stuff.

Will see if there are any issues in our code.

**Comment by Roze** [comment]
Correct. 
Also as far as I sniffed the traffic between it is being dropped on the response.

If I connect directly to backend (nginx) the response is gzipped.
If I connect to backend via haproxy -> nginx the response is gzipped (also between).
If I connect to h2o -> backend (nginx) while h2o sends the "accept-encoding: gzip" to backend (nginx) it is received in plain text.

**Comment by kazuho** [comment]
@Roze
> If I connect to backend via h2o while h2o sends the "accept-encoding: gzip" to backend (nginx) it is received in plain text (and Content-Encoding dropped for client received headers).

Sounds like a bug in upstream considering the fact that h2o is sending the `accept-encoding` header.

In your web application, is nginx the one that is supposed to compress the response?  Or is it some application behind nginx?

The most likely case is that your application server may be failing to handle header names in lower-case (FWIW H2O sends header names in lower-case, which is preferred within HTTP2 spec).

**Comment by Roze** [comment]
It's nginx.
I made a simple public testcase http://is.ifrype.com/ vs https://is.ifrype.com/ (with the h2o website (I hope you don't mind))

The nginx config is:
```
    gzip  on;
    gzip_comp_level 5;
    gzip_types        text/plain text/xml text/css application/x-javascript;
    gzip_disable msie6;

    server {
        listen       80 default;
        server_name  _;
        root /web/root;
    }
```

The h2o config (ciphers truncated):
```
max-connections: 20480
user: nobody
num-threads: 4
hosts:
  "HTTPS server":
   listen:
      port: 443
      ssl:
        certificate-file: ifrype.crt
        key-file: ifrype.key
        cipher-suite: ECDHE-RSA-CHACHA20-POLY1305:ECDHE-RSA-AES256-GCM-SHA384:...
   paths:
     /:
       proxy.reverse.url: http://127.0.0.1:80/
```

.. and everything is gzipped in http mode but nothing in https - it's easy to check with either curl or for example https://developers.google.com/speed/pagespeed/insights/ where the https version has always the compression issue.

So something odd is going on.

**Comment by Roze** [comment]
I tried to compare the GET headers passed in both cases and it seems that it is caused by the Via header added by h2o. 
By default nginx disables the gzipping  ( http://nginx.org/en/docs/http/ngx_http_gzip_module.html#gzip_proxied ) in such (proxied) cases. 

So as you said it is an "issue" (or caveat) in the upstream.

**Comment by kazuho** [comment]
:+1:
