### ISSUE TITLE
XenForo with H2O+FastCGI

### ISSUE THREAD

**Issue by csmk** [h2o/h2o#437]
Hi,

I'm sorry if this is the wrong place to ask for this kind of help, but I'm having some trouble to run a fresh [XenForo](https://xenforo.com/) with H2O+FastCGI (and this is giving me headache :weary:).

First, I want to use XenForo in a sub-directory called __*community*__, and if I try to enter the URL *https://domain.tld/community/* the page appear totally broken (no css, images, etc., it keep pointing to the root directory, which of course, don't have such resources) and the application says *"The requested page could not be found"*, but if I enter the __index.php__, the page design appear fine and the application works "normally".

Second, I can login as normal user, but not as admin, the admin login page (*https://domain.tld/community/admin.php*) do not work. When I try to login, the page just reload without producing any error. This is similar to the issue I've reported here: https://github.com/h2o/h2o/issues/424

And third, if I try to logout as a normal user, the page just reload, and it looks like I'm still logged-in, even if I go to another pages. The workaround is to do a hard refresh (Ctrl+F5). Maybe this is related to the browser's cache? But this don't happen with nginx.

For reference this is the config files: [h2o.conf](https://gist.github.com/csmk/55e018b3fde3110f2921), [php-fpm.conf](https://gist.github.com/csmk/30a701d0d852dac9d943), [php.ini](https://gist.github.com/csmk/b898eaf9ab1b9be7bee2)

BTW, with nginx, using this [configuration file](https://gist.github.com/csmk/841b0a595c9c58bc0000) the XenForo work perfectly fine.

I hope someone can give me some direction. :pray: If not, I thank you anyway for your time. :bow:

Namaste

**Comment by kazuho** [comment]
@csmk Thank you for using H2O.

I have never used XenForo, but using the `redirect` directive with `internal: ON` might do the trick.

Please see the example at https://github.com/h2o/h2o/wiki/FastCGI-%28Wordpress%29, as well as http://blog.kazuhooku.com/2015/06/h2o-http2-server-version-130-released.html to understand how it is designed.

**Comment by csmk** [comment]
Hi Kazuho,

Thank you for the tip, but unfortunately it didn't work. I give up and moved the application the the root directory. For now, at the root directory, the page design appear perfectly fine. On the other hand, I still can't login on the admin control panel. Also, as I said above, the logout process is not working properly. Every time I need to hard refresh the page to truly logout.

I also tried to use nginx as a back-end proxy for H2O, but I don't know why the application keep trying to access the page resources via http, which the browser is blocking, because it is not safe. So, again, the page appear totally broken.

**Comment by kazuho** [comment]
I am sorry to hear that.

> I also tried to use nginx as a back-end proxy for H2O, but I don't know why the application keep trying to access the page resources via http, in which the browser is blocking because it is not safe. So, again, the page appear totally broken.

At least this part seems like a configuration issue of XenForo (or nginx).  I would suggest consulting their documentation or support.

**Comment by csmk** [comment]
> At least this part seems like a configuration issue of XenForo (or nginx). I would suggest consulting their documentation or support.

You are right, after searching around, I've found that the correct way is to force SSL via config.php `$_SERVER['HTTPS'] = 'on';`. Now, the XenForo is working perfectly.

It's a bummer that I still can not use H2O directly with XenForo without Nginx as a backend proxy.
