### ISSUE TITLE
native server push option for testing ?

### ISSUE THREAD

**Issue by Tintinabula** [h2o/h2o#438]
Is there a directive to tell H2O to always http2 server push a file ?

We are testing server push and would like to have H2O be the native https server. When a client connects an image should always be pushed. Again, this is only to be used in a testing environment.

I noticed some testing was done by hard coding server push. 
https://gist.github.com/kazuho/cb2bb984aad1d5fe33a3

**Comment by kazuho** [comment]
Thank you for the suggestion. I Agree that we need something of the kind (esp. considering the fact that #432 is going to be merged soon).

OTOH I am rather against providing such thing as a configuration directive, since it is natural to expect that every single resource would depend on different set of resources (e.g. all HTML files will depend on` header.jpg` whereas only `index.html` will depend `weclome.jpg`).  I would not want to update the global configuration file every time I add a new HTML file to my website, and I believe that others would feel same.

So the plan is to provide a way to annotate every static file being served, by storing a file alongside the file being served.

For example, for `index.html` you would create `.h2o-files.conf` in the same directory, and define the resources that need to be pushed within the file, like:

```
index.html:
    http2-push:
        welcome.jpg
```

Does such an approach satisfy your requirements?

**Comment by kazuho** [comment]
Thank you for the suggestion. I Agree that we need something of the kind (esp. considering the fact that #432 is going to be merged soon).

OTOH I am rather against providing such thing as a configuration directive, since it is natural to expect that every single resource would depend on different set of resources (e.g. all HTML files will depend on` header.jpg` whereas only `index.html` will depend `weclome.jpg`).  I would not want to update the global configuration file every time I add a new HTML file to my website, and I believe that others would feel same.

So the plan is to provide a way to annotate every static file being served, by storing a file alongside the file being served.  For example, for `index.html` you would create `.h2o-files.conf` in the same directory, and define the resources that need to be pushed within the file, like:

```
index.html:
    http2-push:
        welcome.jpg
```

Does such an approach satisfy your requirements?

**Comment by Tintinabula** [comment]
I agree, the site admin should have the ability to specify the resources pushed for their particular case. I like the plan of having a configuration for each resource for more complicated sites and agree that changing the global config every time an HTML file is added or deleted is not optimal.

Our site is more uniform by design. We have thousands of unique, static html files and every html file requires the client to download the exact same JPG art image once the html code has been parsed. 

A simple glob configuration telling H2O to server push the image.jpg for all *.html file requests would be easier to manage then creating thousands of cloned configurations for each html file.

h2o.conf global config idea. push-files could have multiple arguments. This global config would work fine for our site for example.
```
paths:
  /:
   file.dir: /htdocs/
   http2-push:
        file.mime.type: text/html
        push-files: /image.jpg
```

OR a .h2o-files.conf with file globbing and the ability to override and append a JPG with the index.html file. This idea would work too. 
```
*.html:
    http2-push:
        header.jpg

index.html:
    http2-push:
        welcome.jpg
        happy.jpg

```

If the html file had a global configuration and a .h2o-files.conf entry, the .h2o-files.conf directive could override, or even append the global config.

**Comment by kazuho** [comment]
Thank you for the proposal, and for sharing how you use H2O.  I plan to work on the issue laterwards, but for the meantime #460 might help.

**Comment by Tintinabula** [comment]
@kazuho  I pulled the latest copy of h2o this morning to test the server push option. H2o builds and serves pages without error. When I add the "mruby.handler" directive to the configuration file, the h2o config test fails with, "unknown command: mruby.handler"

I used the same code found in the t/50mruby.t server push test. The server is FreeBSD 10.2

```
  "HTTPS server":
   listen:
     host: 127.0.0.1
     port: 443
     ssl:
      <snip>
   paths:
     /:
       mruby.handler: |
         r = H2O::Request.new
         if r.uri == "/index.html"
           r.http2_push_paths << "/example_image.jpg"
         end
         H2O.return H2O::DECLINED
       file.dir: /htdocs/
       header.add: "cache-control: public, max-age=31556926"
       header.add: "x-frame-options: deny"
```

```
root@example:  /usr/local/bin/h2o -t -c /usr/local/etc/h2o.conf
[OCSP Stapling] testing for certificate file:/ssl_keys/example.org_ssl.crt
fetch-ocsp-response (using OpenSSL 1.0.1p-freebsd 9 Jul 2015)
sending OCSP request to http://ocsp.comodoca.com
/ssl_keys/example.org_ssl.crt: good
        This Update: Aug 26 17:43:02 2015 GMT
        Next Update: Aug 30 17:43:02 2015 GMT
verifying the response signature
verify OK (used: -VAfile /tmp/byYRXrM8z8/issuer.crt)
[OCSP Stapling] stapling works for file:/ssl_keys/example.org_ssl.crt
[/usr/local/etc/h2o.conf:48] unknown command: mruby.handler
```

**Comment by matsumoto-r** [comment]
Did you run `cmake -DWITH_MRUBY=ON .` ?

**Comment by Tintinabula** [comment]
@matsumoto-r . I forgot `cmake -DWITH_MRUBY=ON .` Thank you.

The h2o build fails looking for libmruby . FreeBSD does not have an mruby development package like Linux does, so I will need to look around to see how the library can be built.

```
FreeBSD 10.2

cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_CXX_FLAGS="-Wall -ggdb3 -O2 -fstack-protector-all -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -std=c++0x -fvisibility=hidden" -DCMAKE_C_FLAGS="-Wall -ggdb3 -O2 -fstack-protector-all -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fvisibility=hidden" -DWITH_MRUBY=ON .

Checking connectivity... done.
-- The C compiler identification is Clang 3.4.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found OpenSSL: /usr/lib/libssl.so;/usr/lib/libcrypto.so (found version "1.0.1p") 
-- Found ZLIB: /usr/lib/libz.so (found version "1.2.8") 
-- Could NOT find LIBUV (missing:  LIBUV_LIBRARIES LIBUV_INCLUDE_DIR) 
-- Could NOT find WSLAY (missing:  WSLAY_LIBRARIES WSLAY_INCLUDE_DIR) 
-- Could NOT find MRUBY (missing:  MRUBY_LIBRARIES MRUBY_INCLUDE_DIR) 
FATAL-DWITH_MRUBY=ON was set, but could not find libmruby
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
MRUBY_LIBRARIES
    linked by target "examples-simple" in directory /tmp/h2o
    linked by target "h2o" in directory /tmp/h2o
    linked by target "examples-websocket" in directory /tmp/h2o
    linked by target "examples-http1client" in directory /tmp/h2o
    linked by target "examples-socket-client" in directory /tmp/h2o
    linked by target "t-00unit-libuv.t" in directory /tmp/h2o
    linked by target "t-00unit-evloop.t" in directory /tmp/h2o

-- Configuring incomplete, errors occurred!
See also "/tmp/h2o/CMakeFiles/CMakeOutput.log".
See also "/tmp/h2o/CMakeFiles/CMakeError.log".

```

**Comment by matsumoto-r** [comment]
For example, manual building like .travis.ci.

https://github.com/h2o/h2o/blob/master/.travis.yml#L21-L22

**Comment by Tintinabula** [comment]
Thank you for the tips. 

In our environment, H2O with HTTP2 Server Push reduced client side load times by 27% compared to standard HTTP2 . On mobile devices we noticed load times were reduced by up to 52% depending on network latency; higher latency resulted in better relative load times. When the incoming network bandwidth is saturated, like a DoS, the server is still able to serve pages using server push in 1/4th of the time compared to non-pushed http2.  

For anyone interested, the following instructions will build h2o with mruby support on FreeBSD 10.2 . mruby will allow one to use http2 server push natively in h2o.

```
# download mruby (stable)
wget https://github.com/mruby/mruby/archive/1.1.0.tar.gz
tar zxvf 1.1.0.tar.gz
cd mruby-1.1.0

# edit the build_config.rb file and look for the toolchain lines.
# change the toolchain from gcc to clang. There may be more then one toolchain line.
vi build_config.rb
  toolchain :clang

# FreeBSD pkg install ruby with rake support and bison
pkg install ruby rubygem-rake bison

# build mruby and test. If the build is successful the echo statement will print.
make && make test && echo "BUILD OK"

# copy the mruby libraries to paths under /usr/local/
cp build/host/lib/libmruby.a /usr/local/lib/
cp build/host/lib/libmruby_core.a /usr/local/lib/
cp -R include/mr* /usr/local/include/

# h2o can now be compiled with mruby support on FreeBSD 10.2
git clone https://github.com/h2o/h2o
cd h2o
cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DWITH_MRUBY=ON . && make && echo "BUILD OK"
```

FreeBSD network tuning and optimization
https://calomel.org/freebsd_network_tuning.html

**Comment by kazuho** [comment]
@Tintinabula Wow!  Thank you for sharing the numbers.  They look great.

I will also conduct some benchmark tests myself before releasing 1.5.

**Comment by kazuho** [comment]
FYI the interface has changed, see https://github.com/h2o/h2o/pull/460#issuecomment-139123538
