### ISSUE TITLE
Don't lowercase HTTP headers, for a better HSTS detection

### ISSUE THREAD

**Issue by HLFH** [h2o/h2o#442]
Hi,
 
@kazuho 

According to [RFC 7230](http://www.rfc-editor.org/rfc/rfc7230.txt)

> each header field consists of a case-insensitive field name followed by a colon (":"), optional leading whitespace, the field value, and optional trailing whitespace.

I migrated from nginx to h2o web server. At the moment, I'm using it only on the second-level domain gitnote.eu (the TLDs and other SLDs are not yet configured). For HSTS, I added in h2o.conf: header.add: "Strict-Transport-Security: max-age=15724800; includeSubDomains" but it seems that [SSL Labs](https://www.ssllabs.com/) only supports the HSTS header in the common uppercase writing: Strict-Transport-Security. So, I please ask you to support the uppercase writing. Because it seems that for all HTTP headers, you convert the characters to lowercase.
 
![HSTS detection](https://community.qualys.com/servlet/JiveServlet/downloadImage/2-30625-9890/Screenshot+2015-08-16+at+03.50.00.png) 

HSTS is not detected by SSL Labs, even if HSTS is enabled. They don't seem to respect RFC 7230. And because it's case-insensitive, you don't need to convert the HTTP headers to lowercase.
 
![HSTS lowercase](https://community.qualys.com/servlet/JiveServlet/downloadImage/2-30625-9891/600-52/Screenshot+2015-08-16+at+03.55.24.png)
 
Could you please let the HTTP headers like they are: if I write them in uppercase, could you keep them like that?
 
Thanks.

**Comment by HLFH** [comment]
My mistake. The x-powered-by header was not well written, so [HSTS was not detected/working](https://community.qualys.com/message/30625). I [made the fix for @centminmod](https://github.com/centminmod/h2o_installer/pull/1) because he helped me to configure h2o.conf - excepted for HSTS.

**Comment by kazuho** [comment]
:+1:

**Comment by centminmod** [comment]
cheers @HLFH thanks :+1:
