### ISSUE TITLE
PUSH_PROMISE frame received when ENABLE_PUSH is set to 0

### ISSUE THREAD

**Issue by s0j0urn** [h2o/h2o#464]
Hello,

I was executing the 40server-push.t file under t directory in the h2o project. As per my understanding there are three tests in the script : http, http2 and http2 with TLS. 

To check the frames being received I made a minor change in the script and added -v flag as well.

    $resp = `nghttp $opts -nv --stat '$proto://127.0.0.1:$port/index.txt?resp:link=</index.txt.gz>\%3b\%20rel=preload'`;

The response received for HTTP2 + TLS is :
    
    [  0.000] Connected
    The negotiated protocol: h2
    [  0.006] send SETTINGS frame <length=12, flags=0x00, stream_id=0>
              (niv=2)
              [SETTINGS_MAX_CONCURRENT_STREAMS(0x03):100]
              [SETTINGS_INITIAL_WINDOW_SIZE(0x04):65535]
    [  0.006] send HEADERS frame <length=76, flags=0x05, stream_id=1>
              ; END_STREAM | END_HEADERS
              (padlen=0)
              ; Open new stream
              :method: GET
              :path: /index.txt?resp:link=</index.txt.gz>%3b%20rel=preload
              :scheme: https
              :authority: 127.0.0.1:50767
              accept: */*
              accept-encoding: gzip, deflate
              user-agent: nghttp2/0.7.5
    [  0.006] recv SETTINGS frame <length=18, flags=0x00, stream_id=0>
              (niv=3)
              [SETTINGS_ENABLE_PUSH(0x02):0]
              [SETTINGS_MAX_CONCURRENT_STREAMS(0x03):100]
              [SETTINGS_INITIAL_WINDOW_SIZE(0x04):262144]
    [  0.006] send SETTINGS frame <length=0, flags=0x01, stream_id=0>
              ; ACK
              (niv=0)
    [  0.006] recv SETTINGS frame <length=0, flags=0x01, stream_id=0>
              ; ACK
              (niv=0)
    [  0.009] recv (stream_id=1) :status: 200
    [  0.009] recv (stream_id=1) server: h2o/1.4.4
    [  0.009] recv (stream_id=1) date: Thu, 27 Aug 2015 02:22:28 GMT
    [  0.009] recv (stream_id=1) content-type: text/plain; charset=utf-8
    [  0.009] recv (stream_id=1) last-modified: Mon, 17 Aug 2015 21:46:21 GMT
    [  0.009] recv (stream_id=1) link: </index.txt.gz>; rel=preload
    [  0.009] recv HEADERS frame <length=103, flags=0x04, stream_id=1>
              ; END_HEADERS
              (padlen=0)
              ; First response header
    [  0.009] recv (stream_id=1) :method: GET
    [  0.009] recv (stream_id=1) :scheme: https
    [  0.009] recv (stream_id=1) :authority: 127.0.0.1:50767
    [  0.009] recv (stream_id=1) :path: /index.txt.gz
    [  0.009] recv (stream_id=1) accept: */*
    [  0.009] recv (stream_id=1) accept-encoding: gzip, deflate
    [  0.009] recv (stream_id=1) user-agent: nghttp2/0.7.5
    [  0.009] recv PUSH_PROMISE frame <length=69, flags=0x04, stream_id=1>
              ; END_HEADERS
              (padlen=0, promised_stream_id=2)
    [  0.009] recv DATA frame <length=6, flags=0x01, stream_id=1>
              ; END_STREAM
    [  0.012] recv (stream_id=2) :status: 200
    [  0.012] recv (stream_id=2) server: h2o/1.4.4
    [  0.012] recv (stream_id=2) date: Thu, 27 Aug 2015 02:22:28 GMT
    [  0.012] recv (stream_id=2) content-type: application/x-gzip
    [  0.012] recv (stream_id=2) last-modified: Mon, 17 Aug 2015 21:46:21 GMT
    [  0.012] recv (stream_id=2) x-http2-pushed: 1
    [  0.012] recv HEADERS frame <length=33, flags=0x04, stream_id=2>
              ; END_HEADERS
              (padlen=0)
              ; First push response header
    [  0.012] recv DATA frame <length=26, flags=0x01, stream_id=2>
              ; END_STREAM
    [  0.012] send GOAWAY frame <length=8, flags=0x00, stream_id=0>
              (last_stream_id=2, error_code=NO_ERROR(0x00), opaque_data(0)=[])
    ***** Statistics *****
    
    Request timing:
      responseEnd: the  time  when  last  byte of  response  was  received
                   relative to connectEnd
     requestStart: the time  just before  first byte  of request  was sent
                   relative  to connectEnd.   If  '*' is  shown, this  was
                   pushed by server.
          process: responseEnd - requestStart
             code: HTTP status code
             size: number  of  bytes  received as  response  body  without
                   inflation.
              URI: request URI
    
    see http://www.w3.org/TR/resource-timing/#processing-model
    
    sorted by 'complete'
    
    responseEnd requestStart  process code size request path
        +3.66ms       +144us   3.52ms  200    6 /index.txt?resp:link=</index.txt.gz>%3b%20rel=preload
        +6.21ms *    +3.54ms   2.67ms  200   26 /index.txt.gz

In the initial SETTINGS frame exchanged ENABLE_PUSH has been set it 0. I am considering 0 means disabled. However, I can see a PUSH_PROMISE frame being received later on.  I'd like to know why a PUSH_PROMISE frame has been received when server push is disabled. 
Also, I observed the similar behaviour for http as well as http upgrade tests in the script. HTTP doesn't have server push feature. Why PUSH_PROMISE frame is seen in the http test ?

Another question I have is, according to the issue [#218](https://github.com/h2o/h2o/issues/218) push feature is disabled by default. Why ? and does that mean I should patch the code before compiling if I want to specifically test push ?

I hope I have been able to phrase my question in a polite manner. I am really sorry if this is not the case.

**Comment by kazuho** [comment]
Thank you for opening the issue.

> In the initial SETTINGS frame exchanged ENABLE_PUSH has been set it 0. I am considering 0 means disabled. However, I can see a PUSH_PROMISE frame being received later on. I'd like to know why a PUSH_PROMISE frame has been received when server push is disabled. 

Sounds like a bug.

> Another question I have is, according to the issue #218 push feature is disabled by default. Why ? and does that mean I should patch the code before compiling if I want to specifically test push ?

Actually, server-push is never disabled.  H2O does send a `SETTINGS` frame with `SETTINGS_ENABLE_PUSH` set to zero, which indicates that _clients_ are not allowed to push requests.  Even in such case, my understanding is that servers are allowed to push.  That said, there is no need to send such settings to the client, and I believe it is better to stop doing so.

> I hope I have been able to phrase my question in a polite manner. I am really sorry if this is not the case. 

Thank you for the consideration.  The points you raised are important; I appreciate your help in improving H2O.

**Comment by s0j0urn** [comment]
Thank you for such a quick fix.

Does this fix the issue of PUSH_PROMISE frame being received for the first subtest in the script which as per my understanding is using http/1.1 protocol. HTTP/1.1 doesn't have server push feature and therefore we shouldn't see PUSH_PROMISE frame for the first sub test. However, it is there in the response :

    [  0.000] Connected
    [  0.000] send SETTINGS frame <length=12, flags=0x00, stream_id=0>
              (niv=2)
              [SETTINGS_MAX_CONCURRENT_STREAMS(0x03):100]
              [SETTINGS_INITIAL_WINDOW_SIZE(0x04):65535]
    [  0.000] send HEADERS frame <length=80, flags=0x05, stream_id=1>
              ; END_STREAM | END_HEADERS
              (padlen=0)
              ; Open new stream
              :method: GET
              :path: /index.txt?resp:link=%3C/assets/index.txt%3E%3b%20rel=preload
              :scheme: http
              :authority: 127.0.0.1:51382
              accept: */*
              accept-encoding: gzip, deflate
              user-agent: nghttp2/0.7.5
    [  0.000] recv SETTINGS frame <length=18, flags=0x00, stream_id=0>
              (niv=3)
              [SETTINGS_ENABLE_PUSH(0x02):0]
              [SETTINGS_MAX_CONCURRENT_STREAMS(0x03):100]
              [SETTINGS_INITIAL_WINDOW_SIZE(0x04):262144]
    [  0.000] send SETTINGS frame <length=0, flags=0x01, stream_id=0>
              ; ACK
              (niv=0)
    [  0.000] recv SETTINGS frame <length=0, flags=0x01, stream_id=0>
              ; ACK
              (niv=0)
    [  0.003] recv (stream_id=1) :status: 200
    [  0.003] recv (stream_id=1) server: h2o/1.4.4
    [  0.003] recv (stream_id=1) date: Thu, 27 Aug 2015 22:23:11 GMT
    [  0.003] recv (stream_id=1) content-type: text/plain; charset=utf-8
    [  0.003] recv (stream_id=1) last-modified: Mon, 17 Aug 2015 21:46:21 GMT
    [  0.003] recv (stream_id=1) link: </assets/index.txt>; rel=preload
    [  0.003] recv HEADERS frame <length=105, flags=0x04, stream_id=1>
              ; END_HEADERS
              (padlen=0)
              ; First response header
    [  0.003] recv (stream_id=1) :method: GET
    [  0.003] recv (stream_id=1) :scheme: http
    [  0.003] recv (stream_id=1) :authority: 127.0.0.1:51382
    [  0.004] recv (stream_id=1) :path: /assets/index.txt
    [  0.004] recv (stream_id=1) accept: */*
    [  0.004] recv (stream_id=1) accept-encoding: gzip, deflate
    [  0.004] recv (stream_id=1) user-agent: nghttp2/0.7.5
    [  0.004] recv PUSH_PROMISE frame <length=70, flags=0x04, stream_id=1>
              ; END_HEADERS
              (padlen=0, promised_stream_id=2)
    [  0.004] recv (stream_id=2) :status: 200
    [  0.004] recv (stream_id=2) server: h2o/1.4.4
    [  0.004] recv (stream_id=2) date: Thu, 27 Aug 2015 22:23:11 GMT
    [  0.004] recv (stream_id=2) content-type: text/plain
    [  0.004] recv (stream_id=2) last-modified: Mon, 17 Aug 2015 21:46:21 GMT
    [  0.004] recv (stream_id=2) etag: "55d2562d-6"
    [  0.004] recv (stream_id=2) accept-ranges: bytes
    [  0.004] recv (stream_id=2) x-http2-pushed: 1
    [  0.004] recv HEADERS frame <length=45, flags=0x04, stream_id=2>
              ; END_HEADERS
              (padlen=0)
              ; First push response header
    [  0.004] recv DATA frame <length=6, flags=0x01, stream_id=2>
              ; END_STREAM
    [  0.004] recv DATA frame <length=6, flags=0x01, stream_id=1>
              ; END_STREAM
    [  0.004] send GOAWAY frame <length=8, flags=0x00, stream_id=0>
              (last_stream_id=2, error_code=NO_ERROR(0x00), opaque_data(0)=[])

For the 3rd subtest in the script i.e. HTTP2+TLS, although I can see the PUSH_PROMISE frame being received on checking the value of resp but upon browsing the same url in chromium and checking HTTP2 events I cannot see anything being pushed or a PUSH_PROMISE frame being received. Here are the contents.

**Resp variable (nghttp) :**

    [  0.001] Connected
    The negotiated protocol: h2
    [  0.046] send SETTINGS frame <length=12, flags=0x00, stream_id=0>
              (niv=2)
              [SETTINGS_MAX_CONCURRENT_STREAMS(0x03):100]
              [SETTINGS_INITIAL_WINDOW_SIZE(0x04):65535]
    [  0.046] send HEADERS frame <length=78, flags=0x05, stream_id=1>
              ; END_STREAM | END_HEADERS
              (padlen=0)
              ; Open new stream
              :method: GET
              :path: /index.txt?resp:link=</assets/index.txt>%3b%20rel=preload
              :scheme: https
              :authority: 127.0.0.1:50202
              accept: */*
              accept-encoding: gzip, deflate
              user-agent: nghttp2/0.7.5
    [  0.046] recv SETTINGS frame <length=18, flags=0x00, stream_id=0>
              (niv=3)
              [SETTINGS_ENABLE_PUSH(0x02):0]
              [SETTINGS_MAX_CONCURRENT_STREAMS(0x03):100]
              [SETTINGS_INITIAL_WINDOW_SIZE(0x04):262144]
    [  0.046] send SETTINGS frame <length=0, flags=0x01, stream_id=0>
              ; ACK
              (niv=0)
    [  0.046] recv SETTINGS frame <length=0, flags=0x01, stream_id=0>
              ; ACK
              (niv=0)
    [  0.049] recv (stream_id=1) :status: 200
    [  0.049] recv (stream_id=1) server: h2o/1.4.4
    [  0.049] recv (stream_id=1) date: Thu, 27 Aug 2015 22:24:48 GMT
    [  0.049] recv (stream_id=1) content-type: text/plain; charset=utf-8
    [  0.049] recv (stream_id=1) last-modified: Mon, 17 Aug 2015 21:46:21 GMT
    [  0.049] recv (stream_id=1) link: </assets/index.txt>; rel=preload
    [  0.049] recv HEADERS frame <length=105, flags=0x04, stream_id=1>
              ; END_HEADERS
              (padlen=0)
              ; First response header
    [  0.049] recv (stream_id=1) :method: GET
    [  0.049] recv (stream_id=1) :scheme: https
    [  0.049] recv (stream_id=1) :authority: 127.0.0.1:50202
    [  0.049] recv (stream_id=1) :path: /assets/index.txt
    [  0.049] recv (stream_id=1) accept: */*
    [  0.049] recv (stream_id=1) accept-encoding: gzip, deflate
    [  0.049] recv (stream_id=1) user-agent: nghttp2/0.7.5
    [  0.049] recv PUSH_PROMISE frame <length=71, flags=0x04, stream_id=1>
              ; END_HEADERS
              (padlen=0, promised_stream_id=2)
    [  0.049] recv (stream_id=2) :status: 200
    [  0.049] recv (stream_id=2) server: h2o/1.4.4
    [  0.049] recv (stream_id=2) date: Thu, 27 Aug 2015 22:24:48 GMT
    [  0.049] recv (stream_id=2) content-type: text/plain
    [  0.049] recv (stream_id=2) last-modified: Mon, 17 Aug 2015 21:46:21 GMT
    [  0.049] recv (stream_id=2) etag: "55d2562d-6"
    [  0.049] recv (stream_id=2) accept-ranges: bytes
    [  0.049] recv (stream_id=2) x-http2-pushed: 1
    [  0.049] recv HEADERS frame <length=45, flags=0x04, stream_id=2>
              ; END_HEADERS
              (padlen=0)
              ; First push response header
    [  0.049] recv DATA frame <length=6, flags=0x01, stream_id=2>
              ; END_STREAM
    [  0.049] recv DATA frame <length=6, flags=0x01, stream_id=1>
              ; END_STREAM
    [  0.049] send GOAWAY frame <length=8, flags=0x00, stream_id=0>
              (last_stream_id=2, error_code=NO_ERROR(0x00), opaque_data(0)=[])
    ***** Statistics *****
    
    Request timing:
      responseEnd: the  time  when  last  byte of  response  was  received
                   relative to connectEnd
     requestStart: the time  just before  first byte  of request  was sent
                   relative  to connectEnd.   If  '*' is  shown, this  was
                   pushed by server.
          process: responseEnd - requestStart
             code: HTTP status code
             size: number  of  bytes  received as  response  body  without
                   inflation.
              URI: request URI
    
    see http://www.w3.org/TR/resource-timing/#processing-model
    
    sorted by 'complete'
    
    responseEnd requestStart  process code size request path
        +3.74ms *    +3.61ms    124us  200    6 /assets/index.txt
        +3.75ms       +174us   3.57ms  200    6 /index.txt?resp:link=</assets/index.txt>%3b%20rel=preload

**Chromium events:**

    2894: HTTP2_SESSION
    127.0.0.1:50202 (DIRECT)
    Start Time: 2015-08-27 16:26:18.471
    
    t=364006 [st=    0] +HTTP2_SESSION  [dt=10068]
                         --> host = "127.0.0.1:50202"
                         --> proxy = "DIRECT"
    t=364006 [st=    0]    HTTP2_SESSION_INITIALIZED
                           --> protocol = "h2"
                           --> source_dependency = 2893 (SOCKET)
    t=364006 [st=    0]    HTTP2_SESSION_SEND_SETTINGS
                           --> settings = ["[id:3 flags:0 value:1000]","[id:4 flags:0 value:10485760]"]
    t=364006 [st=    0]    HTTP2_STREAM_UPDATE_RECV_WINDOW
                           --> delta = 10420225
                           --> window_size = 10485760
    t=364006 [st=    0]    HTTP2_SESSION_SENT_WINDOW_UPDATE_FRAME
                           --> delta = 10420225
                           --> stream_id = 0
    t=364007 [st=    1]    HTTP2_SESSION_SEND_HEADERS
                           --> fin = true
                           --> :authority: 127.0.0.1:50202
                               :method: GET
                               :path: /index.txt?resp:link=%3C/assets/index.txt%3E\%3b\%20rel=preload
                               :scheme: https
                               accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
                               accept-encoding: gzip, deflate, sdch
                               accept-language: en-GB,en-US;q=0.8,en;q=0.6
                               https: 1
                               user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/44.0.2403.89 Chrome/44.0.2403.89 Safari/537.36
                           --> priority = 0
                           --> stream_id = 1
                           --> unidirectional = false
    t=364009 [st=    3]    HTTP2_SESSION_RECV_SETTINGS
                           --> clear_persisted = false
                           --> host = "127.0.0.1:50202"
    t=364009 [st=    3]    HTTP2_SESSION_RECV_SETTING
                           --> flags = 0
                           --> id = 2
                           --> value = 0
    t=364009 [st=    3]    HTTP2_SESSION_RECV_SETTING
                           --> flags = 0
                           --> id = 3
                           --> value = 100
    t=364009 [st=    3]    HTTP2_SESSION_UPDATE_STREAMS_SEND_WINDOW_SIZE
                           --> delta_window_size = 196609
    t=364009 [st=    3]    HTTP2_SESSION_RECV_SETTING
                           --> flags = 0
                           --> id = 4
                           --> value = 262144
    t=364010 [st=    4]    HTTP2_SESSION_RECV_HEADERS
                           --> fin = false
                           --> :status: 200
                               content-type: text/plain; charset=utf-8
                               date: Thu, 27 Aug 2015 22:26:18 GMT
                               last-modified: Mon, 17 Aug 2015 21:46:21 GMT
                               link: </assets/index.txt>\;\ rel=preload
                               server: h2o/1.4.4
                           --> stream_id = 1
    t=364011 [st=    5]    HTTP2_SESSION_RECV_DATA
                           --> fin = false
                           --> size = 6
                           --> stream_id = 1
    t=364011 [st=    5]    HTTP2_SESSION_UPDATE_RECV_WINDOW
                           --> delta = -6
                           --> window_size = 10485754
    t=364011 [st=    5]    HTTP2_SESSION_RECV_DATA
                           --> fin = true
                           --> size = 0
                           --> stream_id = 1
    t=364011 [st=    5]    HTTP2_STREAM_UPDATE_RECV_WINDOW
                           --> delta = 6
                           --> window_size = 10485760
    t=364071 [st=   65]    HTTP2_SESSION_SEND_HEADERS
                           --> fin = true
                           --> :authority: 127.0.0.1:50202
                               :method: GET
                               :path: /favicon.ico
                               :scheme: https
                               accept: */*
                               accept-encoding: gzip, deflate, sdch
                               accept-language: en-GB,en-US;q=0.8,en;q=0.6
                               referer: https://127.0.0.1:50202/index.txt?resp:link=%3C/assets/index.txt%3E\%3b\%20rel=preload
                               user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/44.0.2403.89 Chrome/44.0.2403.89 Safari/537.36
                           --> priority = 2
                           --> stream_id = 3
                           --> unidirectional = false
    t=364074 [st=   68]    HTTP2_SESSION_RECV_HEADERS
                           --> fin = false
                           --> :status: 404
                               content-type: text/plain
                               date: Thu, 27 Aug 2015 22:26:18 GMT
                               server: h2o/1.4.4
                           --> stream_id = 3
    t=364074 [st=   68]    HTTP2_SESSION_RECV_DATA
                           --> fin = false
                           --> size = 9
                           --> stream_id = 3
    t=364074 [st=   68]    HTTP2_SESSION_UPDATE_RECV_WINDOW
                           --> delta = -9
                           --> window_size = 10485751
    t=364074 [st=   68]    HTTP2_SESSION_RECV_DATA
                           --> fin = true
                           --> size = 0
                           --> stream_id = 3
    t=364074 [st=   68]    HTTP2_STREAM_UPDATE_RECV_WINDOW
                           --> delta = 9
                           --> window_size = 10485760
    t=374074 [st=10068]    HTTP2_SESSION_GOAWAY
                           --> active_streams = 0
                           --> last_accepted_stream_id = 3
                           --> status = 0
                           --> unclaimed_streams = 0
    t=374074 [st=10068]    HTTP2_SESSION_CLOSE
                           --> description = "Finished going away"
                           --> net_error = 0 (?)
    t=374074 [st=10068]    HTTP2_SESSION_POOL_REMOVE_SESSION
                           --> source_dependency = 2894 (HTTP2_SESSION)
    t=374074 [st=10068] -HTTP2_SESSION

I am a little confused. How should I exactly verify that whether the server push is working correctly or not ?
Is it as simple as setting `header.add: "Link:<index.css>; rel=preload; as=stylesheet"` in the configuration file. Is there any need to mention the resource being pushed in the HTML document as well i.e. using link tags ?

**Comment by kazuho** [comment]
@s0j0urn 
> Does this fix the issue of PUSH_PROMISE frame being received for the first subtest in the script which as per my understanding is using http/1.1 protocol.

First subtest (`h2 direct`) is using HTTP/2, not HTTP/1.1.  If it was actually using HTTP/1.1, it would not be sending any frames; frames in general were introduced in HTTP/2.

> I am a little confused. How should I exactly verify that whether the server push is working correctly or not ?
> Is it as simple as setting header.add: "Link:<index.css>; rel=preload; as=stylesheet" in the configuration file. Is there any need to mention the resource being pushed in the HTML document as well i.e. using link tags ?

Your assumption is correct.  In this case, server push is working, as you can see from the logs emitted by nghttp2.  But for Chrome (or other web browsers) to actually _use_ the pushed resource, it must be referred from the one of the resources being pulled.  It is not until the web browsers actually _tries_ to fetch the resource that the pushed resources are being lookup up (within the web browsers' cache); and that is when the pushed resources appears on the network panel of the web browser.
