### ISSUE TITLE
Why does `uri` of `H2O::Request` return path?

### ISSUE THREAD

**Issue by kazuho** [h2o/h2o#469]
@matsumoto-r Would you mind explaining why `uri` attribute of `H2O::Request` returns path of the URL?

To me it is a bit confusing - I believe it would be more natural to let it return the entire URL.

That said, I am not requesting a change here - I would like to know why it is designed as such, as well as what the consequences would be if it were changed to return the entire URL; do you expect compatibility issues or confusion among users?

**Comment by matsumoto-r** [comment]
Thank you for the question. It's a compatibility issues with mod_mruby for Apache httpd.

In `httpd-2.4.12/include/httpd.h`;

```c
struct request_rec {                                                                                                     
(snip)

    /** The URI without any parsing performed */
    char *unparsed_uri;
    /** The path portion of the URI, or "/" if no path provided */ 
    char *uri;

(snip)
};
```

So, I mapped `r.uri` to `r->uri` and `r.unparsed_uri` to the entire URL.

**Comment by kazuho** [comment]
Thank you for the answer.  I did not know that nginx also names `uri` to represent the path portion of an URI.

> So, I mapped `r.uri` to `r->uri` and `r.unparsed_uri` to the entire URL in both mod_mruby and ngx_mruby.

FWIW `unparsed_uri` of Apache does not always contain entire URL, IIRC it contains the `request-target` of the request line of HTTP/1.1.

**Comment by matsumoto-r** [comment]
>  it contains the request-target of the request line of HTTP/1.1.

Oh, I didn't know that. The purpose of compatibility with mod_mruby is low learning cost. The design of methods are not strict for the compatibility. So, the `r.uri` of h2o_mruby which return the entire URL looks good to me.
