### ISSUE TITLE
bundle and build mruby, with onig-regexp enabled

### ISSUE THREAD

**Issue by kazuho** [h2o/h2o#475]
libmruby must be bundled with certain mrbgems such as mruby-onig-regexp bundled, or users cannot rewrite requests using regular expressions.

**Comment by matsumoto-r** [comment]
In mod_mruby, we build mruby with custom `build_config.rb` in mod_mruby repositry using submodule, then build mod_mruby using `mruby/build/host/lib/libmruby.flags.mak` which include the flags required by mrbgems. `mruby/build/host/lib/libmruby.flags.mak` was generated after building mruby.

**Comment by kazuho** [comment]
#477 has been merged, but at the moment support for mruby handler is off by default on platforms other than Linux or OS X due to upstream bug https://github.com/k-takata/Onigmo/pull/55.

**Comment by szepeviktor** [comment]
Do you know https://github.com/iij/mruby#whats-this ?

**Comment by kazuho** [comment]
@szepeviktor Yes, of course!  Actually I was going to take most of the gems developed as part of iij/mruby in #484.

The reason for not using iij/mruby directly is as follows:
* Unix-specific features (namely in mruby-process) are not necessary in case of H2O, while it may have compatibility issues
 * you can invoke external processes via fastcgi or reverse proxy to handle such tasks
* I am under the impression that mruby-onig-regexp would offer better compatibility with MRI when compared to mruby-pcre-regexp 

But my understanding might be wrong.  I am not familiar with iij-mruby after all.  Do you have any suggestions?

**Comment by kazuho** [comment]
done.

**Comment by szepeviktor** [comment]
I see we are very close to v1.5.
