### ISSUE TITLE
wslay and mruby not found on Alpine Linux after installing wslay. Worked on Ubuntu.

### ISSUE THREAD

**Issue by JohnPittman** [h2o/h2o#479]
I'm moving over to an alpine linux distro for docker containers and now wslay and mruby are not found using same installing as on Ubuntu. 

Install scripts:

WSlay

I would like to /sbin/apk add wslay but it can't find it in the alpine packages even though it's listed in the database on the site under the testing repository. Don't know what to do here and this is the main problem since it's for sockets and I know you're baking ruby into h2o in 1.5. You baking wslay in as well?

# wslay

RUN cd /tmp \
 && wget https://github.com/tatsuhiro-t/wslay/archive/release-1.0.0.tar.gz \
 && tar -xzf release-1.0.0.tar.gz \
 && rm release-1.0.0.tar.gz \
 && cd wslay-release-1.0.0 \
 && autoreconf -i \
 && automake \
 && autoconf \
 && ./configure \
 && make \
 && make install \
 && cd .. \
 && rm -rf wslay-release-1.0.0

Ruby

The ruby part is because I can't find the correct ruby package to replace libmruby-dev on alpine linux. Right now I'm trying with ruby-libs. Any guess there?

# mruby
RUN cd /tmp \
 && wget https://github.com/mruby/mruby/archive/1.1.0.tar.gz \
 && tar -xzf 1.1.0.tar.gz \
 && rm 1.1.0.tar.gz \
 && cd mruby-1.1.0 \
 && ruby ./minirake \
 && cd .. \
 && rm -rf mruby-1.1.0

**Comment by kazuho** [comment]
Maybe you do not need to use those modules.

Support for WebSockets (wslay) is not provided by the standalone server (it is only provided at library level).  Mruby support is experimental, and we are going to change the way it is linked to as we come near towards the next release (see #475).

**Comment by JohnPittman** [comment]
Ok. So I am just discarding the ruby dependency then. 

Can you help me gain some knowledge and elaborate more on "Support for WebSockets (wslay) is not provided by the standalone server (it is only provided at library level)" please?

If traffic is being directed through h2o server to say a node app using socket.io does this effect it at all? Gaining massive devOps and "how things connect" knowledge at the moment so every bit helps.

**Comment by JohnPittman** [comment]
Do I need to even use the libuv dependency when installing? h2o installs fine without it but it sacres me since libuv is the async library sooooo...

**Comment by JohnPittman** [comment]
Finally found knowledge to download from testing repo for alpine that works.

wslay problem fixed below in case anyone else has the same issue:

apk add ca-certificates wslay-dev --update-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/

**Comment by kazuho** [comment]
> Can you help me gain some knowledge and elaborate more on "Support for WebSockets (wslay) is not provided by the standalone server (it is only provided at library level)" please?
> If traffic is being directed through h2o server to say a node app using socket.io does this effect it at all? Gaining massive devOps and "how things connect" knowledge at the moment so every bit helps.

H2O drops unknown `upgrade` header (that is used to upgrade HTTP/1 connection to a websocket connection) when forwarding a requests from client to a backend server.  In other words, it is impossible to establish a websocket connection through H2O running as a reverse proxy.

**Comment by kazuho** [comment]
Proxying websocket connection is supported in #581 (and the feature does not depend on wslay).
