### ISSUE TITLE
prepare for 1.5 release

### ISSUE THREAD

**Issue by kazuho** [h2o/h2o#497]
* [x] update docs
* [ ] collect benchmark numbers for cache-aware server-push
* [x] add support for [Neverbleed](https://github.com/h2o/neverbleed) #520

**Comment by szepeviktor** [comment]
It seems 1.5 is bug-free.

**Comment by szepeviktor** [comment]
Please consider using [Semver](http://semver.org/lang/ja/).

**Comment by kazuho** [comment]
H2O uses semantic versioning.

**Comment by szepeviktor** [comment]
Excuse me, I thought `1.5` is missing the third number.

**Comment by kazuho** [comment]
@szepeviktor no problem :+1:

**Comment by lkwg82** [comment]
seems this can be closed?

**Comment by kazuho** [comment]
@lkwg82 definitely!
