### ISSUE TITLE
pluggable prioritization logic

### ISSUE THREAD

**Issue by kazuho** [h2o/h2o#50]
H2O already implements a tiny prioritization logic based on HTTP/2, that would work fine in terms of browser rendering performance (see #41).

OTOH the prioritization order is not following the guidelines of the HTTP/2 spec.  Following the guidelines would degrade the browser rendering performance unless their implementation gets revised.

Also @igrigorik has suggested at HTTP2 Conference that some people have expressed concerns for a different prioritization logic.

Considering the facts, it might be better to add a hook to customize the prioritization algorithm.

**Comment by kazuho** [comment]
@bagder Thank you for the info.  Starting to implement dependency support on H2O.

**Comment by bagder** [comment]
Patrick also explained it somewhat further in this blogpost: http://bitsup.blogspot.se/2015/01/http2-dependency-priorities-in-firefox.html

**Comment by kazuho** [comment]
Great!  With working implementations and related docs it is so much easier for me to implement dependency-based prioritization.  Kudos to Mozilla and @tatsuhiro-t for leading the works.

**Comment by kazuho** [comment]
Dependency-based prioritization is now supported by H2O with the merge of the PR above.  IMO it would be sufficient to support Firefox.

As of c48089c (on master) there are some leftovers (or behavior inconsistent to the HTTP2 spec.):
* only the streams with highest priority are being sent (in round-robin)
 * spec. says all the streams should be allocated resource proportional to their weights
* does not distribute (instead preserves) the priority of the raised streams when the dependency is being closed
* there is no limit for the number of idle prioritized streams

Regarding the topic of the issue, the scheduler is not pluggable but it would be easy to replace them at compile time, as:
* the interface and the default implementation is pretty independent; it does not depend on the protocol layer or the H2O core
 * [include/h2o/http2/scheduler.h](https://github.com/h2o/h2o/blob/c48089c0b3c0bdb2a4c4508d98bb342b9fcffec4/include/h2o/http2/scheduler.h), [lib/http2/scheduler.c](https://github.com/h2o/h2o/blob/c48089c0b3c0bdb2a4c4508d98bb342b9fcffec4/lib/http2/scheduler.c)
* has its own unit tests in [t/00unit/lib/http2/scheduler.c](https://github.com/h2o/h2o/blob/c48089c0b3c0bdb2a4c4508d98bb342b9fcffec4/t/00unit/lib/http2/scheduler.c)

**Comment by kazuho** [comment]
Regarding the limits raised in the comment above:

> * only the streams with highest priority are being sent (in round-robin)
>  * spec. says all the streams should be allocated resource proportional to their weights

fixed in #135 

> does not distribute (instead preserves) the priority of the raised streams when the dependency is being closed

fixed in cd409f3

> there is no limit for the number of idle prioritized streams

as of 0e011aa the number of idle/closed streams (used for prioritization) is limited to 16 (is configurable at the library level, but not exposed as a directive)

**Comment by kazuho** [comment]
Closing as it is no longer an issue.
