### ISSUE TITLE
Does h2o support websockets?

### ISSUE THREAD

**Issue by a93ushakov** [h2o/h2o#500]
Can I write real-time web app using h2o and socket.io?
https://www.nginx.com/blog/realtime-applications-nginx/

**Comment by kazuho** [comment]
Please refer to https://github.com/h2o/h2o/issues/479#issuecomment-137257934 (and following comments).

**Comment by remoteportal** [comment]
Can you please elaborate?  I don't want to proxy websocket traffic, but rather, I want to use H2O as a platform for websocket app development.  Is that possible?

I'm hoping that H2O is the most scalable "C" language solution for websockets.
