### ISSUE TITLE
Error while trying to compile H2O version 1.5.0-beta1 on Yosemite

### ISSUE THREAD

**Issue by microspino** [h2o/h2o#501]
Trying to *make* (GNU Make 3.81) on OSX 10.10.4 with mruby 1.1.0 (2014-11-19)  installed via homebrew I'm getting this error:
```
No rule to make target `mruby/host/mrbgems/mruby-onig-regexp/Onigmo-Onigmo-5.15.0/.libs/libonig.a', needed by `h2o'
```

I can confirm Oniguruma is installed > **brew list oniguruma**

```
/usr/local/Cellar/oniguruma/5.9.6/bin/onig-config
/usr/local/Cellar/oniguruma/5.9.6/include/ (3 files)
/usr/local/Cellar/oniguruma/5.9.6/lib/libonig.2.dylib
/usr/local/Cellar/oniguruma/5.9.6/lib/pkgconfig/oniguruma.pc
/usr/local/Cellar/oniguruma/5.9.6/lib/ (2 other files)
```
Any clue?
Please don't esitate to ask for more info about my system if you need it.

**Comment by syohex** [comment]
I cannot reproduce on my Yosemite(10.10.5). H2O bundles mruby and required mrbgems and Onigmo(not Oniguruma). It is not necessary to install them for building. Please try again after uninstalling homebrew mruby and oniguruma and installing bison which is necessary for building mruby.

Here is my build log.
- https://gist.github.com/syohex/469d36d9d86ac3e3d42e

**Comment by microspino** [comment]
Hi @syohex and thx for your hints.
uninstalling *mruby* and *Oniguruma* didn't solve the issue with onigmo. *bison* was already installed.
However after a ```brew cleanup``` everything went smoothly.
