### ISSUE TITLE
H2O as library, is it possible?

### ISSUE THREAD

**Issue by silvioprog** [h2o/h2o#502]
Hello,

Firstly, sorry if it is already possible. I don't know C, so I can't check about this just looking on its sources.

I use Free Pascal and Delphi in my company, and I'm searchin a C library to integrate a fast HTTP/HTTPS server to Pascal. I already found many options, but H2O seems a very good alternative because it implements HTTP 2.0 too.

Thank you in advance for any answer!

**Comment by paulpref** [comment]
Yes it can. If you need to show someone else, if you look at the README file, you’ll see this sentence:
“Written in C and licensed under the MIT License, it can also be used as a library.”

And on the projects FAQ page:
https://h2o.examp1e.net/faq.html#libh2o

**Comment by silvioprog** [comment]
Very good information, thank you! I'll try it now. =)
