### ISSUE TITLE
Future plans for Websockets/Socket.io? Back to nginx?

### ISSUE THREAD

**Issue by JohnPittman** [h2o/h2o#516]
This is going to peak a ton of interest and will be a common issue question. Socket.io support for a web server is a must since nginx has full support for it or what's the point of all the speed? We want to stay on your team. =P

Latest nginx release http/2 and more:
https://www.nginx.com/blog/nginx-plus-r7-released/?_ga=1.142078458.951479883.1441256117

Future plans for the standalone web server to handle web sockets with nodejs or is there some configuration I'm missing?

Thank you!

**Comment by gaoyichuan** [comment]
H2O has already supported websockets.

**Comment by JohnPittman** [comment]
I can't get it to work with my nodejs server. Can you post an example .conf of routing to a back-end at the :/ home route? I can only post my static content from the file.dir directive but I don't get connection using the proxy.reverse. Drove my too crazy so was about to image up on the new nginx 1.9.4 since there's plenty of examples out there of showing load balancing web socket servers. Help us out so we're not searching for a baby shark's tooth in a pile of dirt?

**Comment by gaoyichuan** [comment]
Oh sorry, actually I haven't tried out the websocket feature myself. Maybe you can turn to @kazuho for help.

**Comment by kazuho** [comment]
@JohnPittman 
> Future plans for the standalone web server to handle web sockets with nodejs or is there some configuration I'm missing?

I am open to adding support for websockets in the future, but at the moment have no plans doing it myself now.

**Comment by kazuho** [comment]
see also: https://github.com/h2o/h2o/issues/479#issuecomment-137257934

**Comment by kazuho** [comment]
Proxying websocket connection is supported in #581.
