### ISSUE TITLE
Multiple https vhosts on same specified ip

### ISSUE THREAD

**Issue by webhtb** [h2o/h2o#522]
Server have many ips, i need to start some https vhosts in one ip, not all, so i have speciffied same host and port on each host, the server are starting but sites not working

when i set global the host and port and on host only port, server not starting

how to do this?

thanks in advance

**Comment by webhtb** [comment]
example

hosts:
  "host1":
    listen:
      host: 1.1.1.1
      port: 443
      .......

  "host2":
    listen:
      host: 1.1.1.1
      port: 443
      .......

**Comment by kazuho** [comment]
Something is wrong with your configuration.  H2O is known to work with host-named virtual hosting using TLS (and h2o.examp1e.net is configured as such).

Please refer to "Example. Using host-level listeners for HTTPS virtual-hosting" at https://h2o.examp1e.net/configure/base_directives.html#listen.

**Comment by webhtb** [comment]
is now wrong, is just else, in your conf are only port: 443 at listen, two times, but this means ALL IP`s

i can`t use ALL, just one IP because in other ip`s on 443 apache have bindings

**Comment by kazuho** [comment]
As said, if you have problem, please provide the configuration file that does not work (contrary to your expectation that it should) so that we can reproduce the issue.  Without one, it is hard to find out what the issue is (whether it is is the configuration or in the source code).

**Comment by webhtb** [comment]
as i told you the ips before 185.72.242.70 are busy by apache, obly this is free on port 465
when i use only one domain "cloud..." all ok
in this configuration the h2o starting but no si working

tcp-fastopen: 0.1
http2-reprioritize-blocking-assets: ON
http1-request-timeout: 10
http1-upgrade-to-http2: ON
http2-idle-timeout: 10
max-connections: 20480
http2-max-concurrent-requests-per-connection: 512
header.add: "strict-transport-security: max-age=15768000; includesubdomains; preload"
user: apache


hosts:
  "cloud.soft-manager.ro":
    listen:
      host: 185.72.242.70
      port: 443
      ssl:
        certificate-file: /var/www/cloud.soft-manager.ro/ssl/cloud.soft-manager.ro.crt.crt
        key-file: /var/www/cloud.soft-manager.ro/ssl/cloud.soft-manager.ro.key
    paths:
      "/":
        file.dir: /usr/share/owncloud8
        redirect:
          url: /index.php/
          internal: YES
          status: 307
    file.custom-handler:
      extension: .php
      fastcgi.connect:
       port: 9000
       type: tcp

  "analytics.soft-manager.ro":
    listen:
      host: 185.72.242.70
      port: 443
      ssl:
        certificate-file: /var/www/analytics.soft-manager.ro/ssl/analytics.soft-manager.ro.crt.crt
        key-file: /var/www/analytics.soft-manager.ro/ssl/analytics.soft-manager.ro.key
    paths:
      "/":
        file.dir: /var/www/analytics.soft-manager.ro/web
        file.custom-handler:
         extension: .php
         fastcgi.connect:
         port: 9001
         type: tcp

access-log: /var/log/h2o-owncloud/access-log
error-log: /var/log/h2o-owncloud/error-log
pid-file: /var/log/h2o-owncloud/pid-file

ssl-session-resumption:
    mode: all
    cache-store: memcached
    ticket-store: memcached
    cache-memcached-num-threads: 12
    memcached:
        host: 127.0.0.1
        port: 11211

**Comment by kazuho** [comment]
Cannot reproduce.

I tried to reproduce the issue using the supplied configuration file (address changed to 127.0.0.1, certificate files changed, etc.; see https://gist.github.com/kazuho/8945db4738130a323cf9).  Server succeeds to start up.

What is the error message you are seeing?

**Comment by webhtb** [comment]
no error, server started but, no site load in browser, when i remove one site and i restart the server, the remaining site is loaded on browser

**Comment by webhtb** [comment]
when host: 185.72.242.70 is speciffied with more than one, any of sites are not loaded in browsers, if i remove host: 185.72.242.70, the site give error binding because the rest of ips are occupied by apache

**Comment by webhtb** [comment]
now in same configuration i have moved analytics.soft-manager.ro to 185.72.242.69 and i keept cloud.soft-manager.ro on 185.72.242.70, now each on separate ip are loaded, now is ok, but, why one per ip and not virtual on same ip?

**Comment by webhtb** [comment]
tcp-fastopen: 0.1
http2-reprioritize-blocking-assets: ON
http1-request-timeout: 10
http1-upgrade-to-http2: ON
http2-idle-timeout: 10
max-connections: 20480
http2-max-concurrent-requests-per-connection: 512
header.add: "strict-transport-security: max-age=15768000; includesubdomains; preload"
user: apache


hosts:
  "cloud.soft-manager.ro:80":
    listen:
      host: 185.72.242.70
      port: 80
    paths:
      "/":
        redirect: "https://cloud.soft-manager.ro/"


  "cloud.soft-manager.ro:443":
    listen:
      host: 185.72.242.70
      port: 443
      ssl:
        certificate-file: /var/www/cloud.soft-manager.ro/ssl/cloud.soft-manager.ro.crt.crt
        key-file: /var/www/cloud.soft-manager.ro/ssl/cloud.soft-manager.ro.key
    paths:
      "/":
        file.dir: /usr/share/owncloud8
        redirect:
          url: /index.php/
          internal: YES
          status: 307
    file.custom-handler:
      extension: .php
      fastcgi.connect:
       port: 9000
       type: tcp


  "analytics.soft-manager.ro:80":
    listen:
      host: 185.72.242.69
      port: 80
    paths:
      "/":
        file.dir: /var/www/analytics.soft-manager.ro/web
        redirect:
          url: /index.php
          internal: YES
          status: 307
    file.custom-handler:
      extension: .php
      fastcgi.connect:
       port: 9001
       type: tcp

  "analytics.soft-manager.ro:443":
    listen:
      host: 185.72.242.69
      port: 443
      ssl:
        certificate-file: /var/www/analytics.soft-manager.ro/ssl/analytics.soft-manager.ro.crt.crt
        key-file: /var/www/analytics.soft-manager.ro/ssl/analytics.soft-manager.ro.key
    paths:
      "/":
        file.dir: /var/www/analytics.soft-manager.ro/web
        redirect:
          url: /index.php
          internal: YES
          status: 307
    file.custom-handler:
      extension: .php
      fastcgi.connect:
       port: 9001
       type: tcp


access-log: /var/log/h2o-owncloud/access-log
error-log: /var/log/h2o-owncloud/error-log
pid-file: /var/log/h2o-owncloud/pid-file

ssl-session-resumption:
    mode: all
    cache-store: memcached
    ticket-store: memcached
    cache-memcached-num-threads: 12
    memcached:
        host: 127.0.0.1
        port: 11211

**Comment by kazuho** [comment]
> no error, server started but, no site load in browser, when i remove one site and i restart the server, the remaining site is loaded on browser

Cannot reproduce.  With https://gist.github.com/kazuho/c163069571bd628daae1 (uses `mruby.handler` for each host to return their names), I am seeing the same responses.

```
$ curl -k --resolve cloud.soft-manager.ro:443:127.0.0.1 https://cloud.soft-manager.ro/
cloud.soft-manager.ro
```
```
curl -k --resolve analytics.soft-manager.ro:443:127.0.0.1 https://analytics.soft-manager.ro/
analytics.soft-manager.ro
```

**Comment by kazuho** [comment]
One probable cause is that you have a typo on the client-side when specifying `analytics.soft-manager.ro`.  If the hostname supplied by the client does not match _any_ of the names in `hosts` section, then the first one is used for returning the response.

It would be great if you could also consider using GitHub-flavored markdown (specifically its [triple-backticks](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code)) to make the YAML readable.

**Comment by webhtb** [comment]
What part is not clear? When i set another IP for analytics, all OK
In both situations (with same IP or different) the server is starting with no errors

NOW  WITH DIFFERENT IP IS IN LIVE!
Bur this is not OK

How can I contact You to send the server credentials to check by yourself?
Regards

**Comment by kazuho** [comment]
> NOW WITH DIFFERENT IP IS IN LIVE!
> But this is not OK because IPs consumption

In https://github.com/h2o/h2o/issues/522#issuecomment-143363679 I have shown (based on your configuration) that you can run host differently-named hosts using the same IP address.

I suggest you to try running it, and if it runs, try to dissect the issue in your configuration.

> How can I contact You to send the server credentials to check by yourself?

I am sorry but I have no obligation to provide such consultation.

**Comment by webhtb** [comment]
Ok than, thank you for your time and great support and for this fantastic web server, i think is the world faster web server in this momment!

Best regards

**Comment by kazuho** [comment]
> One last question, it is possible to have separated logs for each vhost?

Yes.  Please refer to [Levels of Configuration](https://h2o.examp1e.net/configure/syntax_and_structure.html#config_levels) and [Access Log Directives](https://h2o.examp1e.net/configure/access_log_directives.html).
