### ISSUE TITLE
build on mac os x yosemite

### ISSUE THREAD

**Issue by kidzopa** [h2o/h2o#525]
trying to build on os x yosemite and xcode 7 

is this possible as alternative are there ubuntu build instructions

not a strong linux user use of cmake etc not normal build path for windows visual studio user

**Comment by willemt** [comment]
I would avoid xcode and just use the terminal in os x, eg.

```bash
brew install cmake
cd h2o
make install
```

**Comment by kidzopa** [comment]
thank you 
have refresh what I used to do 20 plus years ago

**Comment by DomT4** [comment]
Homebrew has a `h2o` package [as well](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/h2o.rb) if you'd prefer to use that directly, re willemt's comment.

**Comment by kidzopa** [comment]
will rethink implementation and platform!!
