### ISSUE TITLE
After systemctl reboot, ERR_TIMED_OUT for every h2o host

### ISSUE THREAD

**Issue by HLFH** [h2o/h2o#526]
Hi,

After a *systemctl reboot*, I got ERR_TIMED_OUT for every h2o host. I'm using ArchLinux and a dedicated Dedibox XC 2015 server.
![screenshot 2015-09-26 at 04 14 01](https://cloud.githubusercontent.com/assets/2359059/10115372/0a85a606-6405-11e5-88f4-61290fd58a89.png)

Do you have any idea how to fix this?

```systemd
[Unit]
Description=H2O - the optimized HTTP/1, HTTP/2 server
After=network.target nss-lookup.target remote-fs.target

[Service]
Type=simple
PIDFile=/run/h2o.pid
ExecStart=/usr/bin/h2o --mode master --conf /etc/h2o/h2o.conf
ExecReload=/usr/bin/kill -HUP $MAINPID
ExecStop=/usr/bin/kill -TERM $MAINPID
SyslogLevel=notice
PrivateTmp=true
LimitNOFILE=infinity

[Install]
WantedBy=multi-user.target
```

It's the standard h2o service of the [AUR h2o package](https://aur.archlinux.org/packages/h2o/).

Thanks in advance,

**Comment by HLFH** [comment]
Replacing network.target by network-online.target fixes the issue.

So, here is the correct file:

```systemd
[Unit]
Description=H2O - the optimized HTTP/1, HTTP/2 server
After=network.target nss-lookup.target remote-fs.target

[Service]
Type=simple
PIDFile=/run/h2o.pid
ExecStart=/usr/bin/h2o --mode master --conf /etc/h2o/h2o.conf
ExecReload=/usr/bin/kill -HUP $MAINPID
ExecStop=/usr/bin/kill -TERM $MAINPID
SyslogLevel=notice
PrivateTmp=true
LimitNOFILE=infinity

[Install]
WantedBy=multi-user.target
```

**Comment by HLFH** [comment]
Related to: https://github.com/atweiden/pkgbuilds/pull/3

**Comment by kazuho** [comment]
:+1:

@HLFH noticing that you are the maintainer of the Arch Linux, should I better notify you before I release a security fix so that you can update the aur package in a timely manner? (note: I do not have any security issue in my hands now)

**Comment by HLFH** [comment]
Now it's merged, I'm closing this issue. 

Hi @kazuho. I answered you by email. Yes it is a good idea! Thanks.
