### ISSUE TITLE
H2O ebuild for Gentoo/Funtoo Linux

### ISSUE THREAD

**Issue by csmk** [h2o/h2o#532]
Hello,

Because Gentoo's main repository doesn't yet have an official ebuild for H2O, I'm now maintaining and hosting a H2O ebuild in my _[overlay](https://wiki.gentoo.org/wiki/Overlay)_ that have been approved recently in [Gentoo overlay list](https://overlays.gentoo.org/).

Gentoo and Funtoo users, please, visit my overlay repository for instructions on how to use it: https://gitlab.com/chaoslab/chaoslab-overlay

Cheers

**Comment by kazuho** [comment]
:+1:

**Comment by csmk** [comment]
Hi, I'm sorry for the necrobump. I just want to inform that I successfully became the maintainer of [H2O ebuild](https://packages.gentoo.org/packages/www-servers/h2o) on Gentoo's main tree. _Yay!!_ :smile: 

I'll keep maintaining a separated ebuild on my personal overlay for experimental purpose, as the one in main tree needs to be more conservative.

**Comment by csmk** [comment]
I've retired as maintainer in the main tree. Though I'll continue to maintain the package in my personal overlay.
