### ISSUE TITLE
HTTP/2 depend of certificate type?

### ISSUE THREAD

**Issue by webhtb** [h2o/h2o#535]
I have installed COMODO GGSSL for https://web-email.biz/ but this site shows no support for HTTP/2
Cand be ceause certificate?

https://www.h2check.org/#web-email.biz

**Comment by gaoyichuan** [comment]
HTTP/2 has nothing to do with your ssl certificate. Maybe a configure error causes the problem in http/2.

**Comment by webhtb** [comment]
all ok in conf, thanks for answer
