### ISSUE TITLE
Move setuidgid away from /usr/share

### ISSUE THREAD

**Issue by marhag87** [h2o/h2o#537]
Please consider moving setuidgid away from /usr/share as this folder should only contain architecture independent data files.

"The /usr/share hierarchy is for all read-only architecture independent data files" http://www.pathname.com/fhs/pub/fhs-2.3.html#USRSHAREARCHITECTUREINDEPENDENTDATA

**Comment by kazuho** [comment]
Thank you for reporting the issue.

Is my understanding correct that it should be moved to `${PREFIX}/lib/h2o`?

**Comment by marhag87** [comment]
Architecture dependant files should go in ${PREFIX}/lib or ${PREFIX}/lib64 depending on if they are 32 or 64 bit.
"Libraries should be installed to either /usr/lib or /usr/lib64 depending on the architecture."
https://fedoraproject.org/wiki/How_to_create_an_RPM_package#.25build_section

I don't believe there is a good folder where you could put all the script files.

Thanks for your attention.

**Comment by kazuho** [comment]
@marhag87 sorry for the delay; with #551 and #553 I hope there are no pending issues for creating the package.

**Comment by marhag87** [comment]
This is great, thanks! If I find anything else I'll create a new issue.
