### ISSUE TITLE
Directory listing shuffling

### ISSUE THREAD

**Issue by devlearner** [h2o/h2o#538]
relates to #474 - directory list sorting

Happen to notice that directory list doesn't appear to be alphabetically sorted (as the merged PR suggests to do) all the time, but randomly shuffled at times.

[A live example will be to visit https://h2o.examp1e.net/configure/. Reload the page (or hit F5), the list will appear to be shuffled (at times).

is that kind-of expected?

[Just curious asking; doesn't mean a big issue to me though ;) ]

Thanks.

**Comment by kazuho** [comment]
Thank you for noticing the issue!  Fixed in #539

**Comment by devlearner** [comment]
Thanks! This solves it neatly ;) (Sorry for the late reply)

BTW, is it currently possible to default redirects to keep-alive (in h1)?

I noticed that, say, when I access https://h2o.examp1e.net/configure (a directory), it gives a 301 with a `location: /configure/` header (pointing with a trailing slash), however it also gives a `Connection: close` header (contrary to `Connection: keep-alive` in dir lists). 

Is it possible to also use `Connection: keep-alive` in 30x redirects (so that we can theoretically save one round-trip)?

Thanks a lot!
