### ISSUE TITLE
I can`t upload files bigger than 1GB

### ISSUE THREAD

**Issue by webhtb** [h2o/h2o#547]
Hi, I can`t upload files bigger than 1GB, why?
php.ini and conf for php-fpm have configured up to 4GB, same conf with apache, all are ok
i use xhr forms

thanks

**Comment by kazuho** [comment]
Please use the [limit-request-body](https://h2o.examp1e.net/configure/base_directives.html#limit-request-body) configuration directive to raise the limit of request body above 1GB.

Note: the documentation is incorrectly states that the default is unlimited.  The limit is by default set to 1GB.  It should also be noted that you may have issues when trying to accept large request body on 32-bit systems.

**Comment by webhtb** [comment]
The system is 64bits, ok, I will set "limit-request-body" bigger than 1GB and i will report the results.

**Comment by webhtb** [comment]
Thanks, this solve the problem, now any people can use for free this site for big file transfers: https://file-transfer.site/
Thanks again!
