### ISSUE TITLE
Cannot use h2o as a subdirectory of other project.

### ISSUE THREAD

**Issue by futursolo** [h2o/h2o#548]
I want to use libh2o in my project, but I found that h2o cannot be added as a subdirectory, since there is something like: `CONFIGURE_FILE(${CMAKE_SOURCE_DIR}/version.h.in ${CMAKE_SOURCE_DIR}/include/h2o/version.h)` in h2o's CMakeLists.txt.

This problem can by fixed by replace all ${CMAKE_SOURCE_DIR} and ${CMAKE_BINARY_DIR} by ${CMAKE_CURRENT_SOURCE_DIR} and ${CMAKE_CURRENT_BINARY_DIR}.

Another problem is when h2o is added as a subdirectory, h2o cannot select LibreSSL automatically when OpenSSL is not found or version <= 1.2.0.

**Comment by kazuho** [comment]
@futursolo 

> This problem can by fixed by replace all ${CMAKE_SOURCE_DIR} and ${CMAKE_BINARY_DIR} by ${CMAKE_CURRENT_SOURCE_DIR} and ${CMAKE_CURRENT_BINARY_DIR}.

I am willing to accept the fix if you could create a PR.

> Another problem is when h2o is added as a subdirectory, h2o cannot select LibreSSL automatically when OpenSSL is not found or version <= 1.2.0.

It is intentionally designed as such.  Please refer to the last paragraph of #433.
