### ISSUE TITLE
HTTP2 increases the singe resource load time

### ISSUE THREAD

**Issue by swar0g** [h2o/h2o#554]
Has anyone else experience this issue with HTTP/2. While page load time decreases, the load time (as well as ttfb) of single static resource (image, for instance)  increases significantly. Timing looks like following:

HTTP/1.1

http://snag.gy/dTudw.jpg

HTTP/2.0

http://snag.gy/LsDrb.jpg

So I am not sure if the issue is protocol or implementation related.

**Comment by kazuho** [comment]
This is a non-issue.

In HTTP/1, only a limited number of requests (typically 6 per server) can be issued at the same time.  

OTOH in HTTP/2, it is typical that servers can handle more than one hundred of requests simultaneously.  Requests will be queued by the server, and the response will be sent depending on how the client and server prioritize the responses.

So if you look at each request, it is natural to see what you have found.  The fact that requests are being queued on the server is what makes HTTP/2 faster than HTTP/1.

**Comment by swar0g** [comment]
Thank you for the clarification.
