### ISSUE TITLE
Max_concurrent_streams of HTTP/2

### ISSUE THREAD

**Issue by valour01** [h2o/h2o#563]
My configure

    # to find out the configuration commands, run: h2o --help
    http2-max-concurrent-requests-per-connection: 64
    error-log: /var/log/h2o/error.log
    listen: 8082
    listen:
      port: 8081
      ssl:
        certificate-file: /usr/local/etc/h2o/server.crt
        key-file: /usr/local/etc/h2o/server.key
    hosts:
    #  "127.0.0.1.xip.io:8080":
    #    paths:
    #      /:
    #        file.dir: /usr/local/var/h2o
    #        redirect:
    #          status: 301
    #          url: https://127.0.0.1:8081/
    #    access-log: /var/log/h2o/access.log
      "alternate.127.0.0.1.xip.io:8081":
        listen:
          port: 8081
          ssl:
            certificate-file: /usr/local/etc/h2o/alternate.crt
            key-file: /usr/local/etc/h2o/alternate.key
        paths:
          /:
            mruby.handler: |
              Proc.new do |env|
                push_paths = []
                if env["PATH_INFO"] == "/"
                  push_paths << "js/director.js"
                end
                [399, push_paths.empty? ? {} : {"link" => push_paths.map{|p| "<#{p}>; rel=preload"}.join("\n")}, []]
              end
            file.dir: /var/www/test
    #        proxy.reverse.url: http://127.0.0.1:80/
    #        proxy.preserve-host: ON
        access-log: /var/log/h2o/access.log

But I still receive the settings frame whose max_concurrent_stream is 100 when I use JETTY 9.3.4 to visit h2o 1.5.0-beta3.

    2015-10-20 01:35:54.088:DBUG:oejh.HTTP2Session:qtp1360875712-14: Received     SettingsFrame@2260c72b,reply=false:{3=100, 4=262144}

I did same test on h2o.I send settings frame to h2o to set the max_concurrent_streams as 5; No rst_streams received when I make 100 requests and every stream request a very big file in one connection. It tries to handle as much streams as it can. But I cannot receive all the 100 responses(only 60 received). When the stream request a very small file, all the 100 responses are received. My two possible explanation for the observation. One is that h2o's concurrent capability is so good(for the same 100 big file concurrent requests, h2o complete 60 while nginx complete 5). The other is  h2o may ignore the settings frame the user send( But we didn't receive all the responses, it might be a reflect that the server is crash). I am not sure whether I am right. Could you please help me with it. Free to add more detail information.

**Comment by kazuho** [comment]
`http2-max-concurrent-requests-per-connection` is not a property for capping the number concurrent streams.  It is a property for limiting the resource used per connection.

For example, if the value is set to `5`, only 5 requests will be handled concurrently.  In case of serving files via `file.dir` directive, only 5 files will be open at the same time.

**Comment by valour01** [comment]
Isn't  ` http2-max-concurrent-requests-per-connection ` the max concurrent streams for one connection?
If so. why will I receive a settings frame whose` MAX_CONCURRENT_STREAMS` is 100. 

    2015-10-20 01:35:54.088:DBUG:oejh.HTTP2Session:qtp1360875712-14: Received     SettingsFrame@2260c72b,reply=false:{3=100, 4=262144}

And also I want to when the streams number exceeds, how h2o treat these streams. Nginx will send rst_streams back to the client. It seems h2o will ignore those streams directly.

**Comment by kazuho** [comment]
> Isn't `http2-max-concurrent-requests-per-connection` the max concurrent streams for one connection?

No.  As stated above, they are different.

> And also I want to when the streams number exceeds, how h2o treat these streams. Nginx will send rst_streams back to the client. It seems h2o will ignore those streams directly.

How are you testing the behavior?  Endpoints are permitted to close the stream _at the moment_ it considers itself to have send all the data to client, and the moment is hard to observe from outside.  In case of H2O, the behavior (of sending RST_STREAM) is tested by using [h2spec](https://github.com/summerwind/h2spec).  Note that even the tool had issues doing the check correctly (https://github.com/summerwind/h2spec/pull/19).

**Comment by valour01** [comment]
I think I may understand the difference. One is request and the other is open streams, they are different, am I right? 
And does the 100 I received in the settings frame means `max concurrent streams`? Is there anyway to change the default value.
I tested it manually, I send 100 `headers frame` to open 100 streams to h2o using a for loop without any waiting. And every stream request a big file(3 Mb). I didn't receive any `RST_STREAM` from the h2o. And I got about 60 successful responses(here I mean receive all the data frames). When I tested Nginx using the same client code. I can only receive 5 successful responses(you know, I have sent a settings frame to tell the server the `max_concurrent_stream` is 5). And the other 95 streams will be closed by client because of receiving `RST_STREAM` from the server. 
So I don't know whether h2o received my `settings frame` that `max_current_streams` is 5 or not. I guess h2o may ignore it so that the default value is 100. And because of the `http2-max-concurrent-requests-per-connection` constraints, I may get about 60 successful responses.

**Comment by kazuho** [comment]
> And does the 100 I received in the settings frame means max concurrent streams?

Yes.

> Is there anyway to change the default value.

No.

> So I don't know whether h2o received my settings frame that `max_current_streams` is 5 or not.

Your understanding of the value is incorrect.  You cannot limit the maximum number of streams accepted by server by sending `MAX_CONCURRENT_STREAMS` setting.

> The maximum concurrent streams setting is specific to each endpoint and __applies only to the peer__ that receives the setting. That is, __clients specify__ the maximum number of concurrent streams __the server can initiate__, and servers specify the maximum number of concurrent streams the client can initiate. 
> http://http2.github.io/http2-spec/index.html section 5.4.2

**Comment by valour01** [comment]
>clients specify the maximum number of concurrent streams the server can initiate

I think sending settings frame  from client to server is such a process. Otherwise, how a client tells the server the maximum number of concurrent streams it can initiate. 

At least, server tells the client the maximum concurrent streams the client can initiate by sending settings frame. why client cannot do the same thing?

**Comment by kazuho** [comment]
> Otherwise, how a client tells the server the maximum number of concurrent streams it can initiate.

Why should the client need to?  Clients do not need the help of server to limit the maximum number of concurrent streams _it_ initiates.

Anyways, I would suggest reading through the spec., and ask at https://lists.w3.org/Archives/Public/ietf-http-wg/  if you have questions regarding why the spec. is written as such.

**Comment by valour01** [comment]
I see.  Thanks for your detailed and quick answer.

**Comment by ElijahLynn** [comment]
https://tools.ietf.org/html/rfc7540#section-8.2.2
