### ISSUE TITLE
Trailing slash redirection doesn't work if folder names ends with certain characters

### ISSUE THREAD

**Issue by TheDecryptor** [h2o/h2o#567]
I've found the redirection for adding the trailing slash to a bare folder name can break down if the folder name ends with certain characters, leading to a 404. Emoji seems to trigger it fairly reliably.

"folder" works and gets redirected to "folder/", but "folder]" leads to a 404 (Manually adding the / to the URL and loading it works fine), other characters I've found are [, ?, @, #, ☃, "U+1F4A9" and "U+1F4A3" (Github mangles the last 2)

**Comment by kazuho** [comment]
Thank you for reporting the issue. Will fix in the next release.
