### ISSUE TITLE
Build instructions missing.

### ISSUE THREAD

**Issue by nextgenthemes** [h2o/h2o#589]
I tried to build H2o on Ubuntu 14.04. The guide from the wiki https://github.com/h2o/h2o/wiki/%5Bobsolete%5D-Install-H2O-on-Ubuntu-14.04 says: "obsolete" points the to main page https://h2o.examp1e.net/install.html with its 3 liners that did not work because of libraries missing.

> Thanks to others, H2O is provided as a binary package on some of the operating systems (e.g. yum, apt-get, brew)."

This should include a link to this ppa https://launchpad.net/~h2o-maintainers/+archive/ubuntu/stable

So I went ahead with the obsolete guide because I like the latest version and was stuck at a point where I have missing the libuv files in 
```
ls /usr/local/lib/
libwslay.a  libwslay.la  libwslay.so  libwslay.so.0  libwslay.so.0.0.1  pkgconfig  python2.7  python3.4
```
The steps before that went will, as far as I can tell.

I looked that the libiv-dev package installs but it seems there are only some of the files installed with that package in other folders but not all of the files that are listed in the guide. From the guides perspective its unclear to me where this files supposed to come form. But I am not a expert when in comes to compiling.

Instead of declaring the build guide obsolete I think there should be a script or a updated/betteer/working guide for people to build it on debian and ubuntu, I mean the guy who runs the PPA need to build it anyway or not? Ideally with a up-to-date version that is not 3 weeks old.

Also I am not sure why not keep the documentation on the repo or wiki, this way I would have submitted a change to link the the h2o ppa.

**Comment by nextgenthemes** [comment]
I build libuv myself. And now I can build the server.

**Comment by kazuho** [comment]
> This should include a link to this ppa https://launchpad.net/~h2o-maintainers/+archive/ubuntu/stable

Thank you for the suggestion.  I did not know that somebody has created a ppa.

FWIW libuv is an _optional_ dependency.  You only need it if you are going to use libh2o. (and perhaps that should be mentioned in the install doc).

**Comment by nextgenthemes** [comment]
Well if libuv is optional. Then again, without it I got errors during build and could only build it with the libuv files in /usr/local/lib/

**Comment by dtruffaut** [comment]
For info, on debian I had to build libuv, wslay and cmake myself

```
aptitude upgrade

###########################
####### LETSENCRYPT #######
###########################

/etc/init.d/nginx stop
kill -TERM `cat /run/h2o.pid`

cd /tmp
git clone https://github.com/letsencrypt/letsencrypt.git
cd letsencrypt
./letsencrypt-auto certonly --rsa-key-size 4096 --agree-tos --renew-by-default --email kazuho@gmail.com \
--domain example.com \
--standalone

###########################
########## MRUBY ##########
###########################

cd /tmp
wget https://github.com/mruby/mruby/archive/1.2.0.tar.gz
tar zxvf 1.2.0.tar.gz
cd mruby-1.2.0
aptitude install ruby ruby-dev rubygem-rake bison
make && make test
cp build/host/lib/libmruby.a /usr/local/lib/
cp build/host/lib/libmruby_core.a /usr/local/lib/
cp -R include/mr* /usr/local/include/

###########################
########## LIBUV ##########
###########################

cd /tmp
git clone https://github.com/libuv/libuv
cd libuv
sh autogen.sh
make
make check
make install

###########################
########## WSLAY ##########
###########################
# Web Socket Library in C #

cd /tmp
git clone https://github.com/tatsuhiro-t/wslay
cd wslay
autoreconf -i
automake
autoconf
./configure
make

###########################
###### CMAKE 3.5.2 ########
###########################

cd /tmp
git clone https://github.com/Kitware/CMake
cd CMake
./bootstrap
make 
make install
mv /usr/share/cmake-2.8 /usr/share/cmake-2.8-old
ln -s /usr/local/share/cmake-3.5 /usr/share/cmake-2.8
export CMAKE_ROOT=/usr/local/share/cmake-3.5
/usr/local/bin/cmake --version

###########################
########### H2O ###########
###########################

cd /tmp
git clone https://github.com/h2o/h2o
cd h2o
/usr/local/bin/cmake -DCMAKE_INSTALL_PREFIX=/usr/local  -DCMAKE_CXX_FLAGS="-Wall -O2 -fstack-protector-all -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -std=c++0x -fvisibility=hidden" -DCMAKE_C_FLAGS="-Wall -O2 -fstack-protector-all -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fvisibility=hidden" -DWITH_BUNDLED_SSL=on -DWITH_MRUBY=ON .
make
make install
h2o -v
```

**Comment by nextgenthemes** [comment]
I just wanted to note that I think was taking this 'errors' to seriously. In fact the build process is quite easy and works fine for me now without the optional libs not needed for a the basic webserver.
