### ISSUE TITLE
Building without SSL support

### ISSUE THREAD

**Issue by brandonprry** [h2o/h2o#600]
Hi,

For testing purposes, I am attempting to build h2o without SSL support for the time being. I don't see a simple way to achieve this. Is building without SSL a supported configuration?

Thanks!

**Comment by kazuho** [comment]
No.  SSL is mandatory.

I am backward against making it an compile option, since doing so complicates the code.  FWIW you can use the bundled libressl to build the server easily (see https://h2o.examp1e.net/install.html).

**Comment by brandonprry** [comment]
Thanks, will make do!
