### ISSUE TITLE
Support Proxy Protocol for proxy.reverse.url

### ISSUE THREAD

**Issue by auduny** [h2o/h2o#602]
I hava a setup now of

<internet> h2o -> varnish -> Backend

Varnish supports proxy protocol as a client (just as h2o does) but it would be cool if h2o could also be sending the proxy protocol to varnish

**Comment by kazuho** [comment]
relates to #350

**Comment by kazuho** [comment]
Thank you for the suggestion.  Will do.

**Comment by bax-** [comment]
+1

**Comment by kazuho** [comment]
@auduny @bax- Implemented in the PR above. Please let me know if you find any issue.
