### ISSUE TITLE
ticket_memcached_update_tickets segmentation fault

### ISSUE THREAD

**Issue by Safari77** [h2o/h2o#610]
```
    session_ticket_vector_t tickets = {};
    ...
    if (resp.status == YRMCDS_STATUS_OK) {
          int r = parse_tickets(&tickets, resp.data, resp.data_len, errbuf);
          ...
    }
    qsort(tickets.entries, tickets.size, sizeof(tickets.entries[0]), ticket_sort_compare);
```

so if ```resp.status != YRMCDS_STATUS_OK```, it segfaults in ```qsort``` if it does not check for NULL, or in  ```update_tickets``` otherwise.

**Comment by kazuho** [comment]
Can you provide me a way to reproduce the issue?

My understanding is that `tickets.size` is set to zero in when `tickets = {}` is called, and `qsort` never accesses `ticket.entries` if `tickets.size` is zero.

**Comment by Safari77** [comment]
but it calls ```update_tickets``` after qsort.

**Comment by kazuho** [comment]
My understanding is that update_tickets is also written to take care of such case.

But if it the case that you are experiencing a segfault, I would like to fix the issue.  Therefore I am asking for the way to reproduce the issue.

**Comment by Safari77** [comment]
```
static int update_tickets(session_ticket_vector_t *tickets, uint64_t now)
{
    int altered = 0, has_valid_ticket;

    /* remove old entries */
    while (tickets->size != 0) {
```

does not check for NULL.  I don't know how to reproduce, and only ```YRMCDS_STATUS_OK```  of ```yrmcds_status``` enums seems to be in use.

**Comment by kazuho** [comment]
> does not check for NULL.

In the call path, the argument passed to `tickets` is a variable allocated on stack.  Therefore `tickets` never becomes NULL.

`tickets.entries` might be NULL, but in such case `tickets.size` will be zero, and `tickets.entries` will never be dereferenced.

> I don't know how to reproduce

Q1. did you actually see a crash happening?
Q2. if answer to Q1 is yes, can you provide any log that lead you to believe that there is a bug in how `qsort` or `update_tickets` is being called?

**Comment by Safari77** [comment]
Oops, a little thinko, I was thinking of ```tickets.entries``` when looking at ```update_tickets```. :grimacing:
This code looks fine.  Glibc has defined params 1 and 4 of ```qsort``` as  **nonull**, but it checks ```nmemb``` before accessing ```base```, so some analyzers can warn about that..
