### ISSUE TITLE
h2o site SEO fixes (title + domain)

### ISSUE THREAD

**Issue by janit** [h2o/h2o#612]
A non technical issue. The H2O (http://h2o.examp1e.net) site would gain a lot of improvement in search engine just by fixing the front page document title:

    <title>H2O</title>

Is not very descriptive for a person seeking for a performant HTTP/2 server. Something along the lines of this would be much better:

    <title>H2O - the optimized and fast HTTP/2 server</title>

Also moving to a descriptive domain like h2o-http.net would work better.

**Comment by janit** [comment]
Consider searches like: 

- http://www.google.com/?q=http2+server
- http://www.google.com/?q=http2+web-server
- http://www.google.com/?q=http2+httpd

**Comment by kazuho** [comment]
Thank you for the suggestion!
