### ISSUE TITLE
H2o support for paths regular?

### ISSUE THREAD

**Issue by wangfakang** [h2o/h2o#615]
hi @kimoto: I want to use regex match like it's :

```
   paths:
      ^~ /wap360:
        proxy.reverse.url: "http://ww1.sinaimg.cn"
```

This will match begin with `wap360` ?  may be i'm wrong, please give me some hints thx.  :)

**Comment by kazuho** [comment]
You should use the mruby handler for routing requests based on regex match.

```
paths:
  "/":
    mruby.handler: |
      lambda do |env|
        if /^\/wap360/.match(env["PATH_INFO"])
          return [307, {"x-reproxy-url" => "http://ww1.sinaimg.cn/#{env["PATH_INFO"]}"}, []]
        end
        return [399, {}, []]  # let it be handled by the next handler
      end
    ...
```

Please refer to https://h2o.examp1e.net/configure/mruby_directives.html#delegating-request for detail.

**Comment by wangfakang** [comment]
oh, Thank you for your detailed explanation.

**Comment by RustJason** [comment]
:+1:

**Comment by ndac-todoroki** [comment]
Can I ask something here too:
struggling with regex match. I want to redirect
`http://example.com/room/(.+)`
to
`http://example.com/room/`
internally, so all those requests use the same html file, but shows different URLs. How can I do this?

**Comment by ndac-todoroki** [comment]
I am very sorry... I'd just forgotten to place `reproxy: ON`. Then, I could internally redirect by the same method as kazuho written above. thx

**Comment by sudarsha** [comment]
`
        if /^\/address\//.match(env["PATH_INFO"])
          return [301, {"x-reproxy-url" => "https://domain.name/contact-us"}, []]
        end
`
In the above, how do I make sure that the redirect is not internal. In other words, I want the server to give a real 301 redirect to the client and then the client should refetch the content.
As it stands, the redirect is internal. I know I can use the 'redirect' directive, but this is a simplified example. I will be using a complicated regex that cannot be used with the redirect directive.

**Comment by i110** [comment]
@sudarsha How about sending `location` header instead of `x-reproxy-url`?

**Comment by sudarsha** [comment]
Thank You, I've got the external redirect going.

As  you might have guessed, I'm not a software professional. I'm a blogger and I like to maintain my own blog. 

It used to be on Nginx, but I'm trying to make it faster! (and it works too).

The last stumbling block is converting a regex-based rewrite from Nginx to ruby. I've tried quite a few combinations (given at the bottom). But none works.

essentially, I used to use the following permalink structure (which has been indexed by Google and therefore must be 301ed)

authorname-postID-posttitle

now I use

authorname/postID/posttitle

Since it's wordpress, I need to match only the posttitle value. The others can be dummy values, as long as the '/' is there.

This is what I used to use on Nginx. 

`

location ~ ^/(karma-p|sandy-k)(-|/|_)([0-9]+)-(.*) {return 301 /$1/$3/$4;}

`
and this is what I tried in mruby (thanks to you).

`

        if /^(karma-p|sandy-k)(-|_)([0-9]+)-(.*)/.match(env["PATH_INFO"])

          return [301, {"location" => "https://ultra.news/x/1/{$4}"}, []]

        end

`

Of course, it doesn't work. ( the values 'x' and '1' doesn't matter. They are substituted by Wordpress' PHP for the correct values)

I don't know if the {$4} is the right way to recall that last variable. Hopefully, I won't have to use match.captures and all that, as I'm not familiar at all with that.

I've spent about a day on this -- including getting the supercache rewrite working.

**Comment by i110** [comment]
@sudarsha That's sad, refresh yourself with a cup of tea. The problem you're facing is not for h2o but for ruby (mruby), but I found 2 points that may relieve your mind.

1. `env["PATH_INFO"]` usually starts with `/`, so you have to consider that in your regexp
2. String expansion in mruby is like: `"foo-#{var}-bar"` (`#` is required)

In conclusion, I guess the following code will works.

```
    if /^\/(karma-p|sandy-k)(-|_)([0-9]+)-(.*)/.match(env["PATH_INFO"])
      return [301, {"location" => "https://ultra.news/x/1/#{$4}"}, []]
    end
```

Good luck!

**Comment by sudarsha** [comment]
Thanks I'll try. Btw, do we have to use escape character for hyphen '-' inside the regex? As in, like this (karma\-p|sandy\-k) or is it ok since it's inside the paranthesis?

**Comment by sudarsha** [comment]
Btw, your code works! Thanks much. Let me know if you want any help from a blogger for anything.

**Comment by i110** [comment]
> do we have to use escape character for hyphen '-' inside the regex?

You have to escape hyphens if it's inside *character class* (i.e. `[]`), but otherwise not. So in this case you don't have to.

> Let me know if you want any help from a blogger for anything.

Then please write an article about your migration from nginx to h2o, whenever you feel like 😇

**Comment by sudarsha** [comment]
That's something I'm planning. Btw, I chose H2o after testing caddy and Hiawatha. Caddy didn't support this kind of regex-based redirection, at least not easily. Hiawatha was decent, but h2o trounced it in my testing (using seige http 1.1). 

My blog sometimes (once in three months or so) has thousands of users accessing it at the same time, and often (once a week) hundreds of people at the same time. Most of the time, though, there would be only 30-50 people on it at the same time.

So, being scalable is important for me.

**Comment by RVIRUS0817** [comment]
Help!!!
It works with nginx but, it can not move H2O !!

・nginx 
    location / {
        if (!-e $request_filename){
            rewrite ^(.*)$ /index.php?/$1 break;
        }

・H2O
Please!!

**Comment by i110** [comment]
@RVIRUS0817 
There are multiple ways to achieve it, but most simple one I think is using a sequence of file handlers.

```
paths:
  /:
    - file.dir: /path/to/your/doc_root
    - file.file: /path/to/your/index.php
```

If the requested file doesn't exist in `/path/to/your/doc_root`, the request is delegated to the next handler `file.file` which simply returns `index.php`.

**Comment by RVIRUS0817** [comment]
@i110 
Thanks!!
But It is not moving yet...

・Environment
vagrant 
h2o v2.2.4
php 7.1.13
fuelphp

・h2o.conf
````
paths:
  "/":
      file.dir: /works/public
    file.file: /works/public/index.php
    redirect:
      url: /index.php/
      internal: YES
      status: 307

````
・error
You can see this page because the URL you are accessing cannot be found.

**Comment by i110** [comment]
@RVIRUS0817 ah I understand what you wanted to do. please try this (remove file.file directive):

```
paths:
  "/":
    file.dir: /works/public
    redirect:
      url: /index.php/
      internal: YES
      status: 307
```

The point is still not changed that `file.dir` directive fallbacks the request to the next handler (redirect) if file is not found.
