### ISSUE TITLE
Remove H2O_TOKEN_SERVER from prohibited header tokens

### ISSUE THREAD

**Issue by mrksbrndt** [h2o/h2o#619]
It would be great if H2O_TOKEN_SERVER was removed from the prohibited header tokens. This is an optional HTTP header field. Other servers allow the modification in the config file (some with and some without 3rd party extensions).

If terms of security it is better to remove or spoof this field because revealing such information can be a potential security flaw.

It is easy to change this restriction in the source code but it would be better if it was available to everyone without having to compile their custom version.

**Comment by kazuho** [comment]
Is it duplicate of #239?

**Comment by mrksbrndt** [comment]
I think so, sorry for the 'duplicate post'. However the issue hasn't been updated since April. I think a patch for this would be as simple as:

```
--- a/lib/handler/headers.c
+++ b/lib/handler/headers.c
@@ -141,7 +141,7 @@ int h2o_headers_is_prohibited_name(const h2o_token_t *token)
     if (token == H2O_TOKEN_CONNECTION || token == H2O_TOKEN_CONTENT_LENGTH || token == H2O_TOKEN_TRANSFER_ENCODING)
         return 1;
     /* prohibit headers added at protocol layer */
-    if (token == H2O_TOKEN_DATE || token == H2O_TOKEN_SERVER)
+    if (token == H2O_TOKEN_DATE)
         return 1;
     /* all others are permitted */
     return 0;
```

Your concerns that this header is needed by clients is unfounded. This header was introduced in HTTP 1.0 to provide optional information (like the HINFO record in DNS, which is rarely used).

The code snippet shown in #239 shows a list of _bad_ servers. I'm sure you'll never want to see your server in a list like that.

**Comment by kazuho** [comment]
Let me continue the discussion on #239, so that others can find relevant discussion in a single thread.
