### ISSUE TITLE
Wrong Javascript headers behind a reverse proxy: failed to load UI

### ISSUE THREAD

**Issue by SamuelHassine** [h2o/h2o#620]

**Comment by kazuho** [comment]
What is the URL that H2O is fetching from nginx?  Is it accessing the URL you intended?

To check, I would suggest logging the `host` request header using `$host` (and the `content-type` response header using `$sent_http_content_type`) to your Nginx log file.

**Comment by SamuelHassine** [comment]
Hello,

Yes it is accessing the URL I intended. 

I made another check and it confirmed the bug. I try a direct access to the H2O UI (without any reverse proxy), the UI is loaded but if I check the header of the JS files:

Request: 
> Request URL:http://h2o.local/flow/js/flow.js
> Request Method:GET
> Status Code:200 OK
> Remote Address:XX.XX.XX.XX:80

> Content-Length:501026
> Content-Type:application/octet-stream
> Server:Jetty(8.y.z-SNAPSHOT)
> X-h2o-build-project-version:3.6.0.8
> X-h2o-cluster-id:1449617935048
> X-h2o-rest-api-version-max:3

Jetty is not sending the correct headers for this file.
