### ISSUE TITLE
Is it possible to serve IE11 http2 ?

### ISSUE THREAD

**Issue by utrenkner** [h2o/h2o#653]
From the information I found, IE11 should be able to handle http2. But I do not get this working. My h2o always falls back to HTTP 1.1. Doesn't IE support the correct version? Or is there a trick to make it understand http2?

**Comment by kazuho** [comment]
IIRC HTTP/2 support for IE11 is limited to Windows 10.  Are you using it?
http://caniuse.com/#feat=http2

**Comment by utrenkner** [comment]
Thank you - I had not seen the restriction to Win 10! I tested IE 11 only via webpagetest.org and did not even pay attention to what OS version they were using. But then HTTP/2 on IE will be almost a non-issue: Users of Win 10 will almost always use Edge instead of IE 11.
