### ISSUE TITLE
Possible to suppress or change part of the http header?

### ISSUE THREAD

**Issue by utrenkner** [h2o/h2o#654]
Through webpagetest.org I noticed that Safari, at least on Windows, does not honor my max-age header. As IE has a similar behaviour when the Vary header is present, I would like to test this hypothesis. Can I suppress Vary in the configuration or do I have to recompile for this.

Similarly, I would like to not expose the exact h2o version. Just like I do not advertise the php Version, it makes automated attacks a little bit more difficult. Could I change the header accordingly?

**Comment by kazuho** [comment]
> Through webpagetest.org I noticed that Safari, at least on Windows, does not honor my max-age header. As IE has a similar behaviour when the Vary header is present, I would like to test this hypothesis. Can I suppress Vary in the configuration or do I have to recompile for this.

You'd have to recompile.

Might be related; FWIW H2O's HTTP/1 implementation converts `Vary` to `Cache-Control: private` for IE https://github.com/h2o/h2o/blob/92add70fa7f69c6aa51b5f6114cfce81083610bb/lib/http1.c#L586.

> Similarly, I would like to not expose the exact h2o version. Just like I do not advertise the php Version, it makes automated attacks a little bit more difficult. Could I change the header accordingly?

Not yet.  Tracking issue for the topic is #239.
