### ISSUE TITLE
Additional mime types should be recognised as is_compressible

### ISSUE THREAD

**Issue by utrenkner** [h2o/h2o#655]
The is_compressible attribute is used to determine, which assets would benefit from gzipping. Today, I put in a pull request to include application/javascript.

Now, I went through the list of mime-types in lib/handler/mimemap/defaults.c.h and found these following file/mime types which should also be well compressible, but which do not yet receive the is_compressible attribute:

```
atom => application/atom+xml
js => application/javascript
json => application/json
pl => application/x-perl
rss => application/rss+xml
svg => image/svg+xml
tcl => application/x-tcl
xhtml => application/xhtml+xml
```
But then it might make sense to create a more maintainable list or mapping for the is_compressible attribute. I am not a C-programmer, so I will not propose how to actually do this.

**Comment by kazuho** [comment]
Thank you for reporting the issue (as well as #652).

I agree that it should be done in a better way.  Will look into adding appropriate is_compressible flag to every predefined mime-type in defaults.c.h.

**Comment by utrenkner** [comment]
Thank you for taking this into account.

Maybe you want to be a bit more specific in the mapping: "is_compressible" is very unspecific. It always depends on the used compressing algorithm. Therefore, maybe the flag should indicate per mime-type if it is "plaintext". Then you could later use this to chose "plaintext" as suitable for gzip compression. Maybe in the future other algorithms are added, which can compress e.g. even PDF files.

**Comment by kazuho** [comment]
@utrenkner 

> Maybe you want to be a bit more specific in the mapping: "is_compressible" is very unspecific. It always depends on the used compressing algorithm. Therefore, maybe the flag should indicate per mime-type if it is "plaintext". Then you could later use this to chose "plaintext" as suitable for gzip compression. Maybe in the future other algorithms are added, which can compress e.g. even PDF files.

Sounds like an interesting idea. However, I am not sure if we can see any gain _now_ by using the approach.

For loss-less compression (i.e. gzip, brotli), it doesn't matter whether the file is text or not. Some binary files (e.g. TIFF, WAV) have low entropy, and are known to get compressed well.

Also, at the moment, I do not see other use-cases that we would benefit from distinguishing between text and non-text files.

**Comment by kazuho** [comment]
@utrenkner 
With #1067, I believe that all of the commonly-used mime-types would be properly mapped as compressible (note that we also have a rule for mime-types that end with `+xml`).

Please let me know if you have suggestions or see any issue.

**Comment by utrenkner** [comment]
@kazuho Thanks for taking this up again! I had later found out about "+xml", too. So, yes, most of my proposed compressible files were already handled correctly. And with #1067 the most important ones (javascript, json) are covered, too.

I really think this will help newcomers to h2o, because hardly anyone suspects that javascript and json would be compressed only if you explicitly configure it to be compressible. Many thanks for the changes!
