### ISSUE TITLE
Feature request: file.send-brotli

### ISSUE THREAD

**Issue by utrenkner** [h2o/h2o#660]
Google recently launched the brotli compression algorithm, which is said to be superior to deflate, gzip, zopfli (smaller filesizes for typical files, low demand on client resources).

As compression seems to be more resource intensive than e.g. gzip, I would not want to use on-the-fly compression. But it would be interesting to have a file.send-brotli option similar to file.send-gzip: If browser supports both, brotli and gzip, it should first look for .br file, then for .gz file.

It seems that Firefox will support brotli as of version 44 (to be released in January 2016).

Some interesting articles on brotli:
http://calendar.perfplanet.com/2015/new-years-diet-brotli-compression/
https://blog.cloudflare.com/results-experimenting-brotli/

**Comment by kazuho** [comment]
:+1: will do

**Comment by Tintinabula** [comment]
@kazuho , we statically gzip -9 compress our pages and agree the option to statically compress the pages with brotli --quality 11, .br extension, would be great. We do not mind having uncompressed, .gz and .bz files for different clients.

Our testing shows better static file compression of 11% over gzip -9

Better than Gzip Compression with Brotli
https://hacks.mozilla.org/2015/11/better-than-gzip-compression-with-brotli/

**Comment by utrenkner** [comment]
And a few days ago, the Blink (Chrome) Devs published their "Intent to Ship" for accepting Brotli compressed content https://groups.google.com/a/chromium.org/forum/#!searchin/blink-dev/brotli/blink-dev/JufzX024oy0/WEOGbN43AwAJ

Interestingly, it will be available for HTTPS only. Because - as can be read in the comments - history has shown that new encodings sometimes got mangled on their way to the browser, as the (proxy) servers did not yet know what to do with it. It seems reasonable to follow this strategy in h2o, too (or at least, to make this an option).

**Comment by kazuho** [comment]
> And a few days ago, the Blink (Chrome) Devs published their "Intent to Ship" for accepting Brotli compressed content

Thank you for the update.  Will work on this once we ship 1.7.

> Interestingly, it will be available for HTTPS only. Because - as can be read in the comments - history has shown that new encodings sometimes got mangled on their way to the browser, as the (proxy) servers did not yet know what to do with it. It seems reasonable to follow this strategy in h2o, too (or at least, to make this an option).

Considering the fact that the browsers disable the use of brotli on plain-text HTTP, I think we do not necessarily need to provide an option to disable that on the server side.
