### ISSUE TITLE
Second h2o daemon in sbwait state

### ISSUE THREAD

**Issue by Tintinabula** [h2o/h2o#693]
We noticed today's git checkout of h2o 1.7.0-beta1 on FreeBSD 10.2 is running two(2) h2o daemons. 

One daemon is in the correct state, kqread and the other is in sbwait state. We also see that each process is running with 6-7 threads, which is greater then the number of cpu cores. The cpu is an AMD A8-7600 which has four(4) real cores and no hyper-threading. If the h2o processes are killed, the start-server spawns two(2) new h2o daemons in the same states.

Does this sound like a bug? 

We were expecting a single perl start-server process and a single h2o daemon with 4-5 threads.

The h2o web server is serving out data properly and we do not see any errors in the logs. 

Process list showing the perl start_server and two h2o processes
```
ps -auxfww | grep h2o

USER       PID  %CPU %MEM   VSZ   RSS TT  STAT STARTED        TIME COMMAND
root     27628   0.0  0.2 47648 12244  -  I     4:01PM     0:00.00 perl -x /usr/local/share/h2o/start_server --pid-file=/var/run/h2o.pid --log-file=/var/log/h2o_error.log --daemonize --port=127.0.0.1:80 --port=127.0.0.1:443 -- h2o -c /usr/local/etc/h2o.conf
daemon   27629   0.0  0.2 43372 11184  -  S     4:01PM     0:00.30 h2o -c /usr/local/etc/h2o.conf
daemon   27630   0.0  0.1 39136  5936  -  S     4:01PM     0:00.27 h2o -c /usr/local/etc/h2o.conf
```

top listing showing the states of each process. pid 27630 seems unneeded.
```
  PID   USERNAME    THR PRI NICE   SIZE   RES     STATE    C  TIME    WCPU COMMAND
27628 root          1    23    0   47648K 12244K  wait     1  0:00  0.00%  perl
27629 daemon        7    20    0   43372K 11292K  kqread   2  0:01  0.00%  h2o
27630 daemon        6    20    0   39136K  5936K  sbwait   3  0:01  0.00%  h2o
```

the h2o daemon in kqread state is listening, notice pid 27630 is not listening
```
  sockstat -4l
USER     COMMAND    PID   FD PROTO  LOCAL ADDRESS         FOREIGN ADDRESS      
daemon   h2o        27629 5  tcp4   127.0.0.1:80          *:*
daemon   h2o        27629 6  tcp4   127.0.0.1:443         *:*
daemon   h2o        27629 21 tcp4   127.0.0.1:80          *:*
daemon   h2o        27629 22 tcp4   127.0.0.1:443         *:*
daemon   h2o        27629 23 tcp4   127.0.0.1:80          *:*
daemon   h2o        27629 24 tcp4   127.0.0.1:443         *:*
daemon   h2o        27629 25 tcp4   127.0.0.1:80          *:*
daemon   h2o        27629 26 tcp4   127.0.0.1:443         *:*
```

**Comment by kazuho** [comment]
Starting from version 1.7.0-beta1, [Neverbleed](https://github.com/h2o/neverbleed) has been turned on by default.  What you are seeing is the process dedicated to the private key operations.

You can manually turn the feature of by setting the property of your `ssl` configuration (https://h2o.examp1e.net/configure/base_directives.html#listen-ssl, note that the document does not yet reflect the change of the default value in the beta releases).

refs: https://github.com/h2o/h2o/blob/v1.7.0-beta2/Changes#L21

**Comment by Tintinabula** [comment]
The additional daemon for Neverbleed make sense. We verified that turning Neverbleed off allows H2O to start a single h2o daemon. Setting Neverbleed back to on starts two(2) h2o daemons as expected.

Thanks for the explanation.
