### ISSUE TITLE
Error compiling 1.7 beta 2

### ISSUE THREAD

**Issue by webhtb** [h2o/h2o#700]
[root@soft-manager h2o-1.7.0-beta2]# make
Scanning dependencies of target mruby
(in /root/Desktop/h2o-1.7.0-beta2/deps/mruby)
rake aborted!
cannot load such file -- rake/clean
Rakefile:15:in `load'
make[2]: *** [CMakeFiles/mruby] Error 1
make[1]: *** [CMakeFiles/mruby.dir/all] Error 2
make: *** [all] Error 2
[root@soft-manager h2o-1.7.0-beta2]#

**Comment by syohex** [comment]
This is duplicated with #685 and already fixed on upstream.
You can avoid this issue by installing `rake`.

**Comment by webhtb** [comment]
Yes, now is ok, thanks
