### ISSUE TITLE
x-reproxy-url ignored if given URI is relative

### ISSUE THREAD

**Issue by webhtb** [h2o/h2o#704]
Hello, i try to use some rewrite with mruby but is working only with full link, example:

return [307, {"x-reproxy-url" => "https://domain.com/en/live-rooms/index.php?q=#{$1}" }, []];

and i want to make it work like:

return [307, {"x-reproxy-url" => "/en/live-rooms/index.php?q=#{$1}" }, []];

The problem with full link is when the site is over cloudflare or other CDN, h2o server die.
In short variant the h2o shows me blank, white pages. return [307, {"x-reproxy-url" => "/en/live-rooms/index.php?q=#{$1}" }, []];

**Comment by kazuho** [comment]
If you are using a beta release of 1.7 (or using master), then #706 might have fixed the issue.  If not, can you please provide the entire mruby script you are using?

**Comment by webhtb** [comment]
I use 1.7 beta3, i seen this error from 1.6

<addr>
http2-reprioritize-blocking-assets: ON
http1-request-timeout: 10
http1-upgrade-to-http2: ON
http2-idle-timeout: 100
max-connections: 20480
http2-max-concurrent-requests-per-connection: 256
reproxy: ON
user: apache
file.index: [ 'index.php', 'index.html', 'index.htm', 'index.txt' ]
hosts:

  "video-chat.club:80":
    listen:
      host: 185.72.242.70
      port: 80
    paths:
      "/":
        redirect: "https://video-chat.club/"

  "video-chat.club:80":
    listen:
      host: 2a04:2b87:0001:0000:0000:0000:0000:0002
      port: 80
    paths:
      "/":
        redirect: "https://video-chat.club/"

  "video-chat.club:443":
    listen:
      host: 185.72.242.70
      port: 443
      ssl:
        certificate-file: /var/www/video-chat.club/ssl/video-chat.club.crt.crt
        key-file: /var/www/video-chat.club/ssl/video-chat.club.key
    paths:
      "/":
        mruby.handler: |
          require "#{$H2O_ROOT}/share/h2o/mruby/htpasswd.rb"
          Htpasswd.new("/var/www/video-chat.club/web/.htpasswd", "Under Dev")
        mruby.handler: |
          lambda do |env|
            if /en\/live\/performer\/([^\/]+)/.match(env["PATH_INFO"])
              return [307, {"x-reproxy-url" => "https://video-chat.club/en/live-rooms/index.php?q=#{$1}" }, []];
            end
            if /ro\/live\/performer\/([^\/]+)/.match(env["PATH_INFO"])
              return [307, {"x-reproxy-url" => "https://video-chat.club/ro/live-rooms/index.php?q=#{$1}" }, []];
            end
            if /en\/photo-gallery\/performer\/([^\/]+)/.match(env["PATH_INFO"])
              return [307, {"x-reproxy-url" => "https://video-chat.club/en/photo-g/index.php?q=#{$1}" }, []];
            end
            if /ro\/photo-gallery\/performer\/([^\/]+)/.match(env["PATH_INFO"])
              return [307, {"x-reproxy-url" => "https://video-chat.club/ro/photo-g/index.php?q=#{$1}" }, []];
            end
            return [399, {}, []]
          end
        file.dir: /var/www/video-chat.club/web
    file.custom-handler:
      extension: .php
      fastcgi.connect:
       port: /run/php-fpm/videochat.sock
       type: unix

  "video-chat.club:443":
    listen:
      host: 2a04:2b87:0001:0000:0000:0000:0000:0002
      port: 443
      ssl:
        certificate-file: /var/www/video-chat.club/ssl/video-chat.club.crt.crt
        key-file: /var/www/video-chat.club/ssl/video-chat.club.key
    paths:
      "/":
        mruby.handler: |
          require "#{$H2O_ROOT}/share/h2o/mruby/htpasswd.rb"
          Htpasswd.new("/var/www/video-chat.club/web/.htpasswd", "Under Dev")
        mruby.handler: |
          lambda do |env|
            if /en\/live\/performer\/([^\/]+)/.match(env["PATH_INFO"])
              return [307, {"x-reproxy-url" => "https://video-chat.club/en/live-rooms/index.php?q=#{$1}" }, []];
            end
            if /ro\/live\/performer\/([^\/]+)/.match(env["PATH_INFO"])
              return [307, {"x-reproxy-url" => "https://video-chat.club/ro/live-rooms/index.php?q=#{$1}" }, []];
            end
            if /en\/photo-gallery\/performer\/([^\/]+)/.match(env["PATH_INFO"])
              return [307, {"x-reproxy-url" => "https://video-chat.club/en/photo-g/index.php?q=#{$1}" }, []];
            end
            if /ro\/photo-gallery\/performer\/([^\/]+)/.match(env["PATH_INFO"])
              return [307, {"x-reproxy-url" => "https://video-chat.club/ro/photo-g/index.php?q=#{$1}" }, []];
            end
            return [399, {}, []]
          end
        file.dir: /var/www/video-chat.club/web
    file.custom-handler:
      extension: .php
      fastcgi.connect:
       port: /run/php-fpm/videochat.sock
       type: unix
</addr>

**Comment by kazuho** [comment]
Can you coalesce the redundant definitions for hosts and see if it fixes the issue?

For example, there should be only one definition for host: `video-chat.club:80`, and that should be specified as:

```
  "video-chat.club:80":
    listen:
      host: 185.72.242.70
      port: 80
    listen:
      host: 2a04:2b87:0001:0000:0000:0000:0000:0002
      port: 80
    paths:
      "/":
        redirect: "https://video-chat.club/"
```

The same applies for `video-chat.club:443` as well.

**Comment by webhtb** [comment]
k, I`ll back soon

**Comment by webhtb** [comment]
Same blank page with short: return [307, {"x-reproxy-url" => "/en/live-rooms/index.php?q=#{$1}" }, []];

**Comment by webhtb** [comment]
By the way, set both ips bind v4 and v6 on same host on SSL the server hangs when start:

[root@soft-manager ~]# /usr/local/bin/h2o -c /usr/local/etc/h2o.conf
[/usr/local/etc/h2o.conf:93] in command listen, cannot accept HTTPS; already defined to accept HTTP
[root@soft-manager ~]# fetch-ocsp-response (using OpenSSL 1.0.2d 9 Jul 2015)
sending OCSP request to http://ocsp.comodoca.com
/var/www/video-chat.club/ssl/video-chat.club.crt.crt: good
	This Update: Jan 18 00:46:03 2016 GMT
	Next Update: Jan 22 00:46:03 2016 GMT
verifying the response signature
verify OK (used: -VAfile /tmp/7pBareG5DA/issuer.crt)

**Comment by kazuho** [comment]
Actually the server is not hanging.  It is exiting due to a configuration error after emitting `[/usr/local/etc/h2o.conf:93] in command listen, cannot accept HTTPS; already defined to accept HTTP`.

Please consult your configuration file to fix the issue.

The error message is displayed if you try to use a `listen` directive with a `ssl` attribute for a host-port pair that is previously defined without an `ssl` attribute.  Multiple `listen` directives against a single host-port is only permitted if all the `listen` directives have `ssl` attribute, or if none of them have the attribute.

**Comment by webhtb** [comment]
My conf is ok, same blank page, also i try this on my local linux with just one host, no matter if i use http or https, same result. In order to make this rewite to work i must use only the full link with http:// or https:// . Pls try local as with conf as i described, in php file you just need to put this code: <?php echo $_GET['q'']; ?> , you can put any other code there, will not appear.

**Comment by kazuho** [comment]
Going back to the source code the reason was obvious; at the moment the reproxy handler only supports absolute URIs.  A `x-reproxy-url` header containing a relative URI is ignored.

And in your configuration, you are returning an empty response (the third tuple of the rack response) for the responses in which you are expecting an internal redirect (that never happen in case you supply a relative URI); that is why you are seeing an empty page.

I will tag this issue as _enhancement_ so that in the future we could add support relative URI in the `x-reproxy-url` header.  Until then, please use absolute URIs.

**Comment by kazuho** [comment]
Changed the title to reflect the cause of the issue.

**Comment by kazuho** [comment]
Implemented in the above PR.

@webhtb please reopen the issue if the same issue persists.

**Comment by webhtb** [comment]
Hi, when i set multiple listen on one https host, h2o give me "Secure Connection Failed", "The connection to medgidia.go.ro was interrupted while the page was loading."

I have one ipv4 and one ipv6 for each host, on http all seems to be ok.
Regards

**Comment by kazuho** [comment]
Can you please open a new issue regarding your problem, with the configuration file sufficient to reproduce the issue?
