### ISSUE TITLE
in request... invalid URL supplied for internal redirection

### ISSUE THREAD

**Issue by karantin2020** [h2o/h2o#720]
Hello.
I use libh2o as static lib. I compiled lib well. Compiled simple.c example.
When I send request to `http://localhost:7890/chunked-test/` everything is fine.
But when I send GET request from browser to `http://localhost:7890/reproxy-test/` then client receives 502 Gateway Error status code with no content. Server prints error: `in request... invalid URL supplied for internal redirection:...`

Compiled http1client.c from examples works fine with `/chunked-test/` and `/reproxy-test/`. Client received content from place where proxy goes.
I use h2o 1.7.0-beta4 and the last versions of libuv and libressl.

What is a way to use proxy with browser in libh2o?
What is recommended way to use libh2o library as https, http2 server?
Is there any documentation of h2o API to use h2o as a library?

Thanks

**Comment by kazuho** [comment]
Thank you for reporting the issue.  The error was emitted since:
* the HTTP client used in libh2o does not support HTTPS
* http://www.google.com/ redirects to https
I assume the latter was introduced after the example was implemented.

**Comment by karantin2020** [comment]
> the HTTP client used in libh2o does not support HTTPS

Error was shown by server not client.
I wrote that http1client.c from examples works fine with reproxy. It gets response well even from https.
Error was just in browser.

You wrote that https doesn't work in libh2o. Then how to make it work?
How to proxy from http to https in libh2o?

Thanks
