### ISSUE TITLE
mruby.handler 301 redirect from www to non-www domain

### ISSUE THREAD

**Issue by Tintinabula** [h2o/h2o#747]
What would be the recommended method to redirect a domain from the www name to the non-www domain name? 
 
https://www.example.com -> 301 redirect -> https://example.com 

Would a mruby.handler work?  I tried to construct a redirection, but the following method errors out. 

```
mruby.handler: |
      Proc.new do |env|
           if /www\.example\.com\.?$/.match(env["HTTP_HOST"])
             return [301, { "Location" => "http://example.com/" + env["PATH_INFO"] }, [] ];
      end
end
```

**Comment by kazuho** [comment]
For the purpose, I'd suggest using `redirect` directive.  https://github.com/h2o/h2o/wiki/redirect-HTTP-to-HTTPS might be a good example you could look into.

> Would a mruby.handler work? I tried to construct a redirection, but the following method errors out. 

There are two reasons why your code is not working.  First, you should not `return` from a block (i.e. `do ... end`).  http://stackoverflow.com/a/1435781 might be a good reading regarding why.
Second, it is not evaluating a HTTP response tuple in case the `if` fails.

The code should be written as:

```
mruby.handler: |
  Proc.new do |env|
    if /www\.example\.com\.?$/.match(env["HTTP_HOST"])
      [301, { "Location" => "http://example.com/" + env["PATH_INFO"] }, [] ];
    else
      [399, {}, []]; # delegate to next handler
    end
end
```

**Comment by Tintinabula** [comment]
Thank you the links. I learned quite a bit. I was able to get H2O's built in "redirect:" working as well as properly construct the mruby.handler just like in your example.
