### ISSUE TITLE
start_server message shows incorrect pid

### ISSUE THREAD

**Issue by Jxck** [h2o/h2o#768]
# issue

when start h2o, it shows process id like this.

```
$ sudo h2o -m daemon -c h2o.conf

start_server (pid:2446) starting now...
```

in this case **2446**. but, there is no process of 2446.
saved pid into file shows correct one(in this test case **2448**).

# environment

```
arch: x64
kernel: 3.13.0-74-generic
platform: linux
cpu: Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz
```

# version

h2o version 1.7.0

**Comment by kazuho** [comment]
This is by spec.

When _deamon_-izing a process, you need to close standard output and perform a double-fork - change of the PID is inevitable.

I would suggest _not_ to rely on the PID emitted during the start-up process, but to rely on the PID emitted to `pid-file` if you are using `-m daemon`.

**Comment by Jxck** [comment]
I didn't know that `start_server` was [daemonize program](https://github.com/h2o/h2o/blob/a5723300a011307b158e80f63845275a6093d061/share/h2o/start_server)
that name and message was just confused me.
