### ISSUE TITLE
example h2o.conf doesn't allow running as root user ?

### ISSUE THREAD

**Issue by centminmod** [h2o/h2o#77]
With h2o 0.9.0 your examples h2o.conf doesn't allow running as root user ? can it run as root user ? if you need a user added, maybe add a commented out entry in example h2o.conf ?

    cowardly refusing to run as root; you can use the `user` directive to set the running user

also where in h2o.conf do you add the user as i get

    failed to parse configuration file:/usr/local/h2o/h2o.conf:line 3:mapping values are not allowed in this context

**Comment by kazuho** [comment]
closing as H2O now setuids to `nobody` if launched as `root` and if the `user` directive is not used.
