### ISSUE TITLE
reload command

### ISSUE THREAD

**Issue by bax-** [h2o/h2o#770]
is it possible to have h2o's configs reloaded without restarting the server?
(I'm on FreeBSD)

**Comment by dtruffaut** [comment]
+1
I suggest to bundle a service that launches h2o as a daemon :

Like :
/etc/init.d/h2o start
/etc/init.d/h2o reload
/etc/init.d/h2o stop

**Comment by bax-** [comment]
turned out it is super simple to add in FreeBSD and will be part of the next port update:
thanks @dch
https://github.com/dch/freebsd-ports/blob/42d7e42f6fbbfa8bb1b9a88beb2d0a81c63e1656/www/h2o/files/h2o.in#L33-L34

**Comment by bax-** [comment]
Problem:
h2o doesn't throw errors if `reload` is being used and the configuration isn't correct…
https://github.com/dch/freebsd-ports/commit/6f045000cd35aad0ceaffc367c9725d627086138

I just tried a `reload` after a config change.
No messages at all. A `restart`revealed that there were problems and the server wasn't able to be restarted.

**Comment by kazuho** [comment]
> is it possible to have h2o's configs reloaded without restarting the server?

Yes. General answer is to send SIGHUP to the master process.  See https://h2o.examp1e.net/configure/command_options.html.

> I just tried a reload after a config change.
> No messages at all. A `restart` revealed that there were problems and the server wasn't able to be restarted.

Answered here: https://github.com/dch/freebsd-ports/commit/6f045000cd35aad0ceaffc367c9725d627086138#commitcomment-16086531.
