### ISSUE TITLE
help: mruby handler & FreeBSD

### ISSUE THREAD

**Issue by bax-** [h2o/h2o#773]
I'm trying to wrap my head around these mruby handlers used by h2o.
I'm on h2o 1.7.0 from FreeBSD ports.
This is what I'm trying right now, found at https://github.com/h2o/h2o/pull/405#issuecomment-136281330

```
hosts:
  default:
    paths:
      "/":
        mruby.handler: |
          H2O.return 403, "Access Forbidden", "I will never show you this!"
```

When I try to start h2o, I get:

```
Starting h2o.
[/usr/local/etc/h2o/h2o.conf:58] unknown command: mruby.handler
/usr/local/etc/rc.d/h2o: WARNING: failed to start h2o
```

What am I doing wrong?

**Comment by syohex** [comment]
You should install `ruby` and `bison` for using mruby feature before building h2o.

**Comment by bax-** [comment]
hm…
I'm not building h2o on the same machine as I'm deploying and running it…
Is installing sufficient or do I have to rebuild it?
maybe the FreeBSD port has to be updated?
https://www.freshports.org/www/h2o/ 
Do I need `bison` or `ruby-rbison`?

**Comment by syohex** [comment]
> Is installing sufficient or do I have to rebuild it?

You have to rebuild h2o.

> Do I need bison or ruby-rbison?

bison. bison and ruby are necessary for building mruby.

**Comment by bax-** [comment]
OK, thank you.

@dch think that the FreeBSD port needs some new make options for this?
https://github.com/dch/freebsd-ports/blob/42d7e42f6fbbfa8bb1b9a88beb2d0a81c63e1656/www/h2o/Makefile

**Comment by bax-** [comment]
https://github.com/h2o/h2o/issues/438

**Comment by syohex** [comment]
Yes. mruby option should be enabled by default.

**Comment by dch** [comment]
I did the port for this yesterday, mruby will be on by default https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=211892 will probably land in the next couple of days & public packages will turn up end of the week normally. Feedback welcomed via bugzilla, I just started using this feature myself :-)

@kazuho can we close this issue please?

**Comment by bax-** [comment]
@dch  sounds great, thanks!

**Comment by utrenkner** [comment]
@dch This means, we will have a separate mruby port, soon? Or have you integrated mruby into the h2o port itsefl?

**Comment by dch** [comment]
it will be included in `www/h2o` by default

**Comment by bax-** [comment]
is this already in the latest FreeBSD port (2.0.4)? 
I didn't see anything in the release infos at [freshport](https://www.freshports.org/www/h2o/)

**Comment by bax-** [comment]
any news here?

**Comment by Varbin** [comment]
Mruby is integrated in FreeBSD ports. I'm currently running H²O with Mruby at the moment.

**Comment by bax-** [comment]
@Varbin integrated as in "integrated in H2O"?

**Comment by utrenkner** [comment]
@bax- I think it was meant as "bundled" with the h2o port in FreeBSD. However, I do not see any such change in the Port's makefile in recent months. Therefore, I believe: If someone builds the h2o port, s/he will only have mruby if it was previously installed on the system (h2o picks up that mruby is installed and builds with it if not explicitly configures otherwise).

**Comment by dch** [comment]
I've got a working version already but it was intentionally split off from the 2.0.4 security update & since restarting it I've found that the build binds to whatever SSL it can find, and not just the version of libressl which is shipped with h2o. However, both OpenSSL & LibreSSL are now at 1.0.2j and 2.4.2 respectively, which probably means we don't need the bundled version at all now on *BSD systems.

If you're desperately seeking the changes, the current patch is below. the mruby changes work, the SSL bits as noted above do not yet.

```diff
commit ce0a418206fde5e5a0a12f1190184b6c22464be4
Author: Dave Cottlehuber <dch@skunkwerks.at>
Date:   Mon Sep 26 19:16:36 2016 +0000

    www/h2o: rework cmake options and add mruby

diff --git a/www/h2o/Makefile b/www/h2o/Makefile
index 4f92625..a4414a7 100644
--- a/www/h2o/Makefile
+++ b/www/h2o/Makefile
@@ -4,6 +4,7 @@
 PORTNAME=	h2o
 PORTVERSION=	2.0.4
 DISTVERSIONPREFIX=	v
+PORTREVISION=	1
 CATEGORIES=	www
 
 MAINTAINER=	dch@skunkwerks.at
@@ -35,23 +36,34 @@ H2O_LOGDIR=	/var/log/${PORTNAME}/
 
 USE_RC_SUBR=	${PORTNAME}
 
-OPTIONS_DEFINE=	LIBRESSL
+OPTIONS_DEFINE=	LIBRESSL MRUBY
+OPTIONS_DEFAULT=	LIBRESSL MRUBY
+OPTIONS_SUB=	yes
 LIBRESSL_DESC=	Build with bundled LibreSSL instead of OpenSSL
-OPTIONS_DEFAULT=	LIBRESSL
+MRUBY_DESC=	Build with mruby handler support
 
 CMAKE_ARGS+=	-DEXTRA_LIBRARIES=OFF -DWITHOUT_LIBS=ON
 
 .include <bsd.port.options.mk>
 
+LIBRESSL_CMAKE_ON=	-DWITH_BUNDLED_SSL=ON
+LIBRESSL_CMAKE_OFF=	-DWITH_BUNDLED_SSL=OFF
+MRUBY_CMAKE_ON=		-DWITH_MRUBY=ON
+MRUBY_CMAKE_OFF=		-DWITH_MRUBY=OFF
+
 .if ${PORT_OPTIONS:MLIBRESSL}
-CMAKE_ARGS+=	-DWITH_BUNDLED_SSL=ON
-WITH_OPENSSL_PORT=	no
+USES_SSL=	yes
 .else
-CMAKE_ARGS+=	-DWITH_BUNDLED_SSL=OFF
-WITH_OPENSSL_PORT=	yes
+USES_SSL=	no
+.endif
+
+.if ${PORT_OPTIONS:MMRUBY}
+USE_RUBY=	yes
+BUILD_DEPENDS+=	bison:devel/bison
 .endif
 
 post-patch:
+	@${RM} -f ${WRKSRC}/misc/libressl-*.tar.gz
 	@${REINPLACE_CMD} -e 's|exec perl|exec ${LOCALBASE}/bin/perl|' \
 			${WRKSRC}/share/h2o/annotate-backtrace-symbols \
 			${WRKSRC}/share/h2o/fetch-ocsp-response \
diff --git a/www/h2o/pkg-plist b/www/h2o/pkg-plist
index 43d002b..21bebbc 100644
--- a/www/h2o/pkg-plist
+++ b/www/h2o/pkg-plist
@@ -7,7 +7,7 @@ share/h2o/start_server
 %%DATADIR%%/fastcgi-cgi
 %%DATADIR%%/setuidgid
 %%DATADIR%%/status/index.html
-@dir(%%H2O_USER%%,%%H2O_GROUP%%,0750) %%H2O_LOGDIR%%
+%%MRUBY%%%%DATADIR%%/mruby/htpasswd.rb
 %%PORTDOCS%%%%DOCSDIR%%/assets/8mbps100msec-nginx195-h2o150.png
 %%PORTDOCS%%%%DOCSDIR%%/assets/firstpaintbench.png
 %%PORTDOCS%%%%DOCSDIR%%/assets/remotebench.png
@@ -57,4 +57,5 @@ share/h2o/start_server
 %%PORTDOCS%%%%DOCSDIR%%/search/oktavia-english-search.js
 %%PORTDOCS%%%%DOCSDIR%%/search/oktavia-jquery-ui.js
 %%PORTDOCS%%%%DOCSDIR%%/search/searchindex.js
+@dir(%%H2O_USER%%,%%H2O_GROUP%%,0750) %%H2O_LOGDIR%%
 @sample %%ETCDIR%%/h2o.conf.sample
```

**Comment by utrenkner** [comment]
@dch Thanks for the patch. 

I wanted to give it a try but, unfortunately, it does not work for me. I checked out the latest h2o port version. When I try to apply the patch, it does go through for the pkg-plist file but not the Makefile:
```
Patching file www/h2o/Makefile using Plan A...
Hunk #1 failed at 4.
Hunk #2 failed at 36.
```
I tried patching by hand, but then `make configure` gives me:
```
make: "/usr/ports/www/h2o/Makefile" line 66: Need an operator
make: "/usr/ports/www/h2o/Makefile" line 71: Need an operator
make: Fatal errors encountered -- cannot continue
```
Could you please let me have the Makefile after patching. Thanks!

**Comment by dch** [comment]
@utrenkner here it is - https://github.com/skunkwerks/ports/blob/21cd30ef6610dc5dcf1f0d6181a89aa2ec5da2ad/www/h2o/Makefile I just rebased it again now; I will be working on this tonight in my rubyhabits group, and I'm on IRC at freenode #couchdb or efnet #bsdports if you want to contact me.

**Comment by utrenkner** [comment]
@dch Thanks! Looks good. The build went through (in synth). Unfortunately, I won't have the time to test before sometime next week...

**Comment by dch** [comment]
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=213733 finally logged, sorry for
dragging this out. You can grab the latest patch via
https://github.com/skunkwerks/ports/tree/master/www/h2o/ as usual.

**Comment by dch** [comment]
landed in ports 👍  @bax- can you close this issue?

**Comment by bax-** [comment]
@dch 
I don't see h2o being updated in the ports tree yet. Am I missing something?

**Comment by jj1bdx** [comment]
@bax- Watch here: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=213733

**Comment by utrenkner** [comment]
@jj1bdx Yes, this is the place where we can download a patch. But this is not "landed in ports". If it was in ports, it would appear here: [https://svnweb.freebsd.org/ports/head/www/h2o/](https://svnweb.freebsd.org/ports/head/www/h2o/)

I second @bax : The patch has not yet made it to the ports tree (which seems strange, as @dch is the port maintainer).

@dch can you enlighten us?

**Comment by jj1bdx** [comment]
@utrenkner Yes, it hasn't been landed yet. The comment section in [Bug 213733](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=213733) says the maintainer-feedback flag should be reviewed again.
Can you check it out @dch?

**Comment by dch** [comment]
It appears in here (maintainer approved) 
https://bugs.freebsd.org/bugzilla/buglist.cgi?cmdtype=dorem&list_id=147247&namedcmd=Ports%3A%20Maintainer%20Approved&remaction=run&sharer_id=27730
so I don't think the flag needs to be set again, just committed. I
emailed ports@freebsd asking for a committer to push the button. I'll
hassle people on irc at the end of the week if not.

**Comment by dch** [comment]
sorry about this I honestly thought it was committed several weeks ago
along with my other backlogged patches!

**Comment by dch** [comment]
Finally finally really really landed: https://github.com/freebsd/freebsd-ports/commit/8e42675fae454cc0fe528606902420766e9510fc
