### ISSUE TITLE
help: include file's content for headers

### ISSUE THREAD

**Issue by bax-** [h2o/h2o#774]
I'm trying to have a HKPK header automatically generated when I renew my certificates using [letsencrypt.sh](https://github.com/lukas2511/letsencrypt.sh)

I'm nearly at a point where I could have a file generated which would include the HKPK hash:
https://github.com/lukas2511/letsencrypt.sh/issues/131

But I don't know if there is any possibility to  include such a file's content in a header in h2o.

Any help would greatly be appreciated!

**Comment by kazuho** [comment]
Please refer to https://h2o.examp1e.net/configure/headers_directives.html.  Alternatively, you could use the mruby handler to do apply more complex modifications to the response headers (see file:///mydev/h2o/doc/configure/mruby.html#modifying-response).

**Comment by bax-** [comment]
I might have been unclear:
I know how to implement different headers but I don't know if it is possible to embed a file's content (e.g. a hashed value in this case) in h2o`s configuration…

**Comment by bax-** [comment]
I there any possible way to do this?
I'm thinking of https://github.com/lukas2511/letsencrypt.sh/issues/129
