### ISSUE TITLE
fastcgi.connect statement

### ISSUE THREAD

**Issue by bax-** [h2o/h2o#781]
In the documentation it says 

> If the argument is a scalar, the value is considered as the path to a unix socket.

If I enter a line
```
fastcgi.connect: /tmp/fcgi.sock
```
I always get an error complaining about missing port information when i start h2o.
Could it be that this information is deprecated?

**Comment by kazuho** [comment]
Thank you for noticing the issue.

It is a documentation bug, please explicitly specify the type of the socket using the `type` attribute, as shown in the example of https://h2o.examp1e.net/configure/fastcgi_directives.html#fastcgi.connect.
