### ISSUE TITLE
HTTP 1 - HTTP 1.1 - Server push

### ISSUE THREAD

**Issue by dtruffaut** [h2o/h2o#782]
h2o is known to be able to server push with Mruby
https://h2o.examp1e.net/configure/mruby.html

What happens if I trigger a server push on a http 1 or http 1.1 client ?
http://caniuse.com/#feat=http2

How to detect and prevent this behavior ?
Can it be directly managed by h2o ?

**Comment by kazuho** [comment]
> What happens if I trigger a server push on a http 1 or http 1.1 client ?
> http://caniuse.com/#feat=http2

In case of HTTP/1.x, nothing happens.  The `link: rel=preload` header is just passed to the client (which is generally a good thing; see https://w3c.github.io/preload/).

At the moment, it is impossible for a mruby handler to determine the version of the HTTP protocol being used.  I think we should provide access to `SERVER_PROTOCOL` (defined in [RFC 3875](https://tools.ietf.org/html/rfc3875#section-4.1.16)).

**Comment by dtruffaut** [comment]
Thanks for your fast reply !
