### ISSUE TITLE
h2o benchmarks

### ISSUE THREAD

**Issue by karantin2020** [h2o/h2o#783]
Hello.
h2o benchmarks are good. But there is one question.
In h2o there is used memcached.
Did you test h2o and nginx with the same options of cache?

Thanks

**Comment by kazuho** [comment]
> In h2o there is used memcached.

Memcached was not used in all of the benchmarks https://h2o.examp1e.net/benchmarks.html.

**Comment by chikhpykh** [comment]
Thanks. It's good.
Please, close this issue

**Comment by karantin2020** [comment]
Thanks
