### ISSUE TITLE
qrintf usage

### ISSUE THREAD

**Issue by karantin2020** [h2o/h2o#796]
Hello. In your demonstration on http://www.slideshare.net/kazuho/h2o-20141103pptx described that h2o uses qrintf.
I didn't find it in h2o. How do you use qrintf with h2o? Thanks

**Comment by kazuho** [comment]
You should use `CC` environment variable to specify qrintf + gcc as the compiler; e.g.  `CC='qrintf gcc' cmake ...`.

**Comment by karantin2020** [comment]
Thanks. @kazuho do you use qrintf in h2o?
Will you include `CC='qrintf gcc'` in CMake file?

**Comment by karantin2020** [comment]
@kazuho?

**Comment by kazuho** [comment]
@karantin2020 
> Thanks. @kazuho do you use qrintf in h2o?

In some environments.

> Will you include CC='qrintf gcc' in CMake file?

No. It's an option that should be configured by the user.

**Comment by karantin2020** [comment]
Thanks a lot
