### ISSUE TITLE
libh2o-evloop

### ISSUE THREAD

**Issue by karantin2020** [h2o/h2o#797]
Does libh2o-evloop compile correct?
There are the errors when link libh2o-evloop.a:
```
main.c:(.text+0x47d0): undefined reference to `h2o_evloop_create'
main.c:(.text+0x4a81): undefined reference to `h2o_evloop_socket_create'
main.c:(.text+0x4b25): undefined reference to `h2o_evloop_run'
main.c:(.text+0x4c13): undefined reference to `h2o_evloop_run'
main.c:(.text+0x45cc): undefined reference to `h2o_evloop_socket_accept'
```

`objdump -t libh2o-evloop.a` doesn't show this symbols (`h2o_evloop_create` and etc.) in library.
But the same with `objdump -t h2o` shows this symbols well.

I use the last version of h2o.
Thanks

**Comment by kazuho** [comment]
When I run `objdump -t libh2o-evloop.a` I see outputs like:
```
00000000000013e0 g     F .text  0000000000000059 h2o_evloop_create
```

I'd suggest rebuilding h2o with `make VERBOSE=1` to see what is going on during the build process.

**Comment by karantin2020** [comment]
Sorry. My mistake
