### ISSUE TITLE
can a write response code in another thread?

### ISSUE THREAD

**Issue by greatwar** [h2o/h2o#803]
when i test use curl ,it's fine(curl http://127.0.0.1:7890/threadecho/)
but with apache ab,it's waiting to timeout (ab  -c 1 -n 1 http://127.0.0.1:7890/threadecho/)

[simple hello world echo in simple.c](https://github.com/h2o/h2o/compare/master...greatwar:greatwar/thread)

**Comment by kazuho** [comment]
@greatwar 
> can a write response code in another thread?

You cannot do that.  Downstream connections are maintained per-thread; you must send a response from the thread that owns the connection.

FWIW H2O has and uses an inter-thread messaging queue defined in include/h2o/multithread.h.

**Comment by greatwar** [comment]
it's wonderful,and work fine
i write a simple test code,[thread.c](https://github.com/greatwar/h2o/blob/greatwar/thread/examples/libh2o/thread.c)

**Comment by kazuho** [comment]
@greatwar LGTM!
