### ISSUE TITLE
FreeBSD: exited on signal 11

### ISSUE THREAD

**Issue by bax-** [h2o/h2o#809]
once a day I get an email about kernel messages (FreeBSD security periodic).
h2o is in it nearly every day with something similar to this:

```
+++ /tmp/security.Ea1PDdFq  2016-02-26 03:17:07.409498644 +0100
+pid 79961 (h2o), uid 80: exited on signal 11
```

Since I have two h2o instances running (each in a jail – one as a SSL proxy for several services and one as a backend for one of them) and the `h20-error.log` doesn't have any timestamps in it I'm not sure what to look for.

to be thorough, this is my `newsyslog.conf` for h2o:

```
/var/log/h2o/*.log                      644   7   1024  *   JG  /var/run/h2o.pid
```

**Comment by dch** [comment]
@bax- this is a memory fault. There are a couple of recent memory fixes in h2o.

To help track this down we should

1. use the most recent source available
2. if faults continue, run under debugger to catch failure

Are you in a position to build your own ports - e.g. you already use synth or poudriere?

**Comment by bax-** [comment]
@dch thanks for the response.
I'm on the latest ports version, built with synth (`1.7.0_1`)

**Comment by dch** [comment]
@bax- ok I'm just doing a patch for 1.7.1 from h2o git master, you can apply this & rebuild & test. FWIW I am easy to find on IRC in freenode #swirloproject or efnet #bsdports.

Here's a diff https://github.com/freebsd/freebsd-ports/compare/master...dch:h2o.patch taken from https://github.com/dch/freebsd-ports/tree/h2o

Alternatively you can install from my pkg repo pkg.skunkwerks.at I've only done a 10.2R amd64 tho.

**Comment by bax-** [comment]
thank you, I'll check it out!
Any chance that ruby support will come soon to FreeBSD?

**Comment by dch** [comment]
mruby simply needs a few hours of quiet time for me to look at it. I'm a bit busy atm but give it a month or so and I'll finish it.

FWIW I don't get these segfaults, please note what options you are building with, (in particular any openssl settings in the port) and maybe post as much of your yml config as is safe, in case there's anything special there.

**Comment by bax-** [comment]
no settings settings beside using LibreSSL instead of OpenSSL:
```
WITH_OPENSSL_PORT=	yes
OPENSSL_PORT=           security/libressl
WANT_MYSQL_VER=	101m
```

**Comment by dch** [comment]
hmmm maybe thats related. h2o comes with embedded libressl (at least for the moment I have not removed it to depend on ports version).

**Comment by kazuho** [comment]
@bax- as suggested by @dch, having a backtrace obtained from a core dump by using a debugger would help a lot.

**Comment by bax-** [comment]
I never used a debugger…
I hope I will get to this but I can't make any promises.

**Comment by dch** [comment]
@bax- 1.7.3 & soon 2.0.0 will be out, if you're still experiencing this issue please share more details incl config etc to see if we can replicate the fauilt.

**Comment by bax-** [comment]
I still have the same issue from time to time but I still can't reproduce…

**Comment by bax-** [comment]
I only have this in my FreeBSD SSL proxy jail – not in the jails running the backends…

**Comment by bax-** [comment]
I'm so sorry:
I had this in my `newsy slog.con` – apparently I missed the last bit when I checked and posted it here:

```
/var/log/h2o/*.log                      644   7   1024  *   JG  /var/run/h2o.pid 30
```

Deleting the `30` stopped the logs and everything sill seems to work as intended.
