### ISSUE TITLE
Again about trailing slashes

### ISSUE THREAD

**Issue by karantin2020** [h2o/h2o#817]
Here are few issues about trailing slashes.
I saw it. I do not understand why you included adding trailing slashes in h2o_config_init_pathconf.
```c
void h2o_config_init_pathconf(h2o_pathconf_t *pathconf, h2o_globalconf_t *globalconf, const char *path, h2o_mimemap_t *mimemap)
{
    memset(pathconf, 0, sizeof(*pathconf));
    pathconf->global = globalconf;
    h2o_chunked_register(pathconf);
    if (path != NULL)
        pathconf->path = h2o_strdup_slashed(NULL, path, SIZE_MAX);
    h2o_mem_addref_shared(mimemap);
    pathconf->mimemap = mimemap;
}
h2o_iovec_t h2o_strdup_slashed(h2o_mem_pool_t *pool, const char *src, size_t len)
{
    h2o_iovec_t ret;

    ret.len = len != SIZE_MAX ? len : strlen(src);
    ret.base = pool != NULL ? h2o_mem_alloc_pool(pool, ret.len + 2) : h2o_mem_alloc(ret.len + 2);
    memcpy(ret.base, src, ret.len);
    if (ret.len != 0 && ret.base[ret.len - 1] != '/')
        ret.base[ret.len++] = '/';
    ret.base[ret.len] = '\0';

    return ret;
}
```

May be standalone server needs it but in libh2o this feature in not good. When I add path `/name` I expect that path will be right `/name` but not `/name/`.
I think the same is actual for standalone server too.

May be you will make this optional? Default option value in config: with or without trailing slash. And make possible choose another value.

Another one question is case-sensitive paths. Didn't you want to make it configurable option (I mean option in config file)?

Thanks

**Comment by kazuho** [comment]
Thank you for the suggestion.

I see ground in the request to remove addition of `/` outside of the core.  That said, let me close this issue in favor of #711 - I do not want to get the same topic discussed in multiple issues.

> Another one question is case-sensitive paths. Didn't you want to make it configurable option (I mean option in config file)?

I do not think that should be the default, but I am open to discussing how such feature should be implemented as an option (if you are willing to do the work).
