### ISSUE TITLE
ssl-session-resumption directive not working as expected

### ISSUE THREAD

**Issue by rc65** [h2o/h2o#819]
# Issue

`ssl-session-resumption` configuration directive does not seem to be working as expected. I have it set to `off` in my config file and it does not seem to have any effect. According to wireshark network traces, an abbreviated SSL handshake is still being used with a previous session key.

Not sure if I'm setting this incorrectly in the config file, or if the feature isn't working as intended.

## Config File

```
hosts:
  "localhost":
    listen:
      port: 8080
    listen:
      port: 8443
      ssl:
        certificate-file: /root/tls/cert-file.crt
        key-file:         /root/tls/key-file.key
    paths:
      "/":
        mruby.handler: |
          Proc.new do |env|
            push_paths = []
            if env["PATH_INFO"] == "/test_sites/ManySmallItems/"
              push_paths << "/test_sites/ManySmallItems/css/main.css"
              push_paths << "/test_sites/ManySmallItems/css/bootstrap.min.css"
              push_paths << "/test_sites/ManySmallItems/css/font-awesome.min.css"
              push_paths << "/test_sites/ManySmallItems/css/devicon.min.css"
              push_paths << "/test_sites/ManySmallItems/js/bootstrap.min.js"
              push_paths << "/test_sites/ManySmallItems/js/jquery-2.1.4.min.js"
              push_paths << "/test_sites/ManySmallItems/js/main.js"
              push_paths << "/test_sites/ManySmallItems/images/check.png"
            end
            [399, push_paths.empty? ? {} : {"link" => push_paths.map{|p| "<#{p}>; rel=preload"}.join("\n")}, []]
          end
        file.dir: /usr/local/share/h2o/doc_root

access-log: /var/log/h2o/access.log
error-log: /var/log/h2o/error.log
pid-file: /var/run/h2o/h2o.pid
http2-reprioritize-blocking-assets: ON   # performance tuning option
ssl-session-resumption:
  mode: off
```

## Screenshot of Wireshark

![Image of Wireshark Output](http://i.imgur.com/zZFEGwP.png)

I can provide the whole Wireshark capture file if you'd prefer.

**Comment by kazuho** [comment]
@rc65 Looking at the log I agree that we are seeing abbreviated handshake is being performed.  Let me try to reproduce the issue.

**Comment by kazuho** [comment]
@rc65 Thank you for reporting the issue.  I have fixed the bug in the PR above.  Please let me know if the issue still persists on your side.

**Comment by rc65** [comment]
@kazuho Apologies for my late reply. No problem, thanks for putting in a fix so quickly! I will check if the problem persists on my end.
