### ISSUE TITLE
h2o.conf separate vhost files ?

### ISSUE THREAD

**Issue by centminmod** [h2o/h2o#82]
Rather than have all vhost/sites' settings in the one h2o.conf file, is it possible to split each site into it's own conf file and/or have an include directory in h2o.conf to look for additional vhost conf files ? Similar to apache and nginx sites-available/sites-enabled method ?

**Comment by centminmod** [comment]
any work on separate vhost files or include file directives ? for multiple ssl hosts with an extensive ssl cipher list the h2o.conf is getting very busy https://github.com/h2o/h2o/issues/256

include file for ssl ciphers and ssl settings would be nice :)

**Comment by szepeviktor** [comment]
:+1: on *include*.

**Comment by dtruffaut** [comment]
+1 

Some `include`/`import`/`require`/... directive would definitively ease management of several sites on the a same server. With such a directive, when you're working on a site and perform some adjustments on its configuration, you only see what is pertinent considering the given site. That helps a lot to prevent problems, as to reduce complexity.

How-to :

Realizing such a feature may require to fix indentation of the included file (as YAML might rely on indentation ?). 

You also have to prevent include recursion (or leave user the freedom to explode its server)

**Comment by bax-** [comment]
+1
https://github.com/h2o/h2o/issues/774

**Comment by kazuho** [comment]
Now that we have #786 merged, it would be easy to provide a directive for including files, like:
```yaml
hosts:
  foo.example.com:
    <<: !include foo.conf
```

**Comment by kazuho** [comment]
Will be addressed by #1022.

**Comment by deweerdt** [comment]
#1022 was merged, i believe this can be closed.

**Comment by kazuho** [comment]
Yes!!!!!
