### ISSUE TITLE
problems with big files (upload and download)

### ISSUE THREAD

**Issue by bax-** [h2o/h2o#821]
I'm trying out h2o as a replacement for nginx as a ssl reverse-proxy.
One of the applications is a nginx backend which servers as a file exchange server (pydio).
I never had problems with big download on nginx but h2o seems to create some.
I'm trying to download a big file (3,6 GB). The limit-request-body parameter in the h2o reverse-proxy is set to 20GB.
The download finishes but the -zip file always ends up too small end corrupted.
There are no error logs on any side so I don't know where to start.

**Comment by kazuho** [comment]
@bax- Interesting.  Can you please clarify the following:
* Q1. am I right that you are trying to download a 3.6GB file from nginx, through h2o acting as a reverse proxy?
* Q2. (if Q1 is correct) can you check if the HTTP response emitted by nginx includes a `content-length` header (or a `transfer-encoding: chunked`) header?
* Q3. is nginx or h2o configured to perform on-the-fly compression (in case of H2O, the question boils down to if you are using `gzip` directive (or `compress`)).
* Q4. what OS are you using? (I assume its FreeBSD 10R)
* Q5. are you compiling H2O for 64-bit?  Or is it 32-bit?

**Comment by bax-** [comment]
> Q1. am I right that you are trying to download a 3.6GB file from nginx, through h2o acting as a reverse proxy?

yes


> Q2. (if Q1 is correct) can you check if the HTTP response emitted by nginx includes a content-length header (or a transfer-encoding: chunked) header?

The browser gets
```
[…]
content-length:3582292604
content-range:bytes 0-3582292603/3582292604;
content-transfer-encoding:binary
[…]
server:h2o/1.7.0
status:200
strict-transport-security:max-age=15768000; includesubdomains; preload
x-content-type-options:nosniff
x-frame-options:SAMEORIGIN
x-xss-protection:1; mode=block
[…]
```


> Q3. is nginx or h2o configured to perform on-the-fly compression (in case of H2O, the question boils down to if you are using gzip directive (or compress)).

Both are. nginx shouldn't compress files that big (and it worked in the past). I also already tried to disable it in h2o but it didn't seem to make a difference

> Q4. what OS are you using? (I assume its FreeBSD 10R)

correct. 10.2-RELEASE-p12


> Q5. are you compiling H2O for 64-bit? Or is it 32-bit?

I compile the version from the ports tree using synth. It should be 64-bit I guess…

> Q6. what is the version of H2O?

```
❯ h2o -v
h2o version 1.7.0
OpenSSL: LibreSSL 2.2.6
```

I also tried adding
```
proxy.timeout.io: 600000
proxy.timeout.keepalive: 30000
```

**Comment by kazuho** [comment]
@bax- Thank you for the answers.  I will try to reproduce the issue.

OTOH the response looks pretty odd to me:
> ```
> content-length:3582292604
> content-range:bytes 0-3582292603/3582292604;
> content-transfer-encoding:binary
> […]
> status:200
> ```

When running as a reverse proxy, H2O simply forwards these headers passed from upstream.

* `content-length` header looks OK.
* `content-range` header should only be used for a 206 response (not 200)
* `content-range` header looks broken, it should not have `;` at its tail
* `content-transfer-encoding` header is not used in HTTP, its for E-mail

How are you generating the response in nginx?

**Comment by bax-** [comment]
As I said, these are not the headers necessarily generated by nginx but those the client gets.
I'm using the php app [pydio](https://pydio.com) which by itself might generate some of those headers…

In my nginx config there are no headers added besides `X-Frame-Options SAMEORIGIN`

**Comment by kazuho** [comment]
Please let me know if the issue has not been resolved with the PR.
