### ISSUE TITLE
Valgrind tests

### ISSUE THREAD

**Issue by karantin2020** [h2o/h2o#837]
Hello. There are some memory leaks in valgrind report.
```sh
==22102== LEAK SUMMARY:
==22102==    definitely lost: 16,384 bytes in 4 blocks
==22102==    indirectly lost: 0 bytes in 0 blocks
==22102==      possibly lost: 22,887 bytes in 194 blocks
==22102==    still reachable: 215,614 bytes in 3,668 blocks
==22102==         suppressed: 0 bytes in 0 blocks
==22102== Reachable blocks (those to which a pointer was found) are not shown.
==22102== To see them, rerun with: --leak-check=full --show-leak-kinds=all
```

h2o version 2.0.0-DEV

**Comment by kazuho** [comment]
The standalone server relies on the OS to clean up the resources.

In other words, it is not an issue _unless_ you see a constant increase in memory footprint as the server processes incoming requests (note that memory and other resources may be cached by H2O to be used in later requests).

**Comment by karantin2020** [comment]
Ok
