### ISSUE TITLE
Path to /usr/bin/perl hardcoded

### ISSUE THREAD

**Issue by utrenkner** [h2o/h2o#838]
Yesterday, I compiled h2o from source on a new FreeBSD 10.2 system and ran into a problem, because somewhere in the code used by h2o, the Perl path is hard coded to /usr/bin/perl. But on a FreeBSD system perl is typically installed under /usr/**local/**bin/perl.

Once I found the cause, it was easy to fix with an additional symlink. The official FreeBSD port does it differently and replaces every occurrence of `exec perl` with the appropriate path (which resolves to `/usr/local/bin/perl`). 

If this hard coded path cannot be changed easily, then a  hint in the installation instructions might be useful for others who want to build h2o from source.

**Comment by kazuho** [comment]
Can you please name which script is causing the issue?  Looking at CMakeLists.txt, I could not find any rule that invokes a perl script (with `/usr/bin/perl` being hard-coded).

**Comment by utrenkner** [comment]
Sorry, I do not know how exactly to identify the script. But when I go into the directory with the Git-sources from which I built, I can find a few occurrences of `/usr/bin/perl`
```
$ grep -r '/usr/bin/perl' ./
./deps/libyrmcds/Doxyfile:PERL_PATH              = /usr/bin/perl
./deps/yaml/doc/doxygen.cfg:PERL_PATH              = /usr/bin/perl
./misc/dump-github-repository.pl:#! /usr/bin/perl
./misc/fastcgi-cgi.pl:#! /usr/bin/perl
./misc/install-perl-module.pl:#! /usr/bin/perl
./misc/p5-net-fastcgi/eg/runfcgi.pl:#!/usr/bin/perl
./misc/p5-net-fastcgi/eg/server.pl:#!/usr/bin/perl
./misc/tokens.pl:#! /usr/bin/perl
```
Hope, this helps.

**Comment by utrenkner** [comment]
Maybe I should have been more specific: The compilation works fine. But then, h2o cannot be started because perl is not found.

**Comment by kazuho** [comment]
@utrenkner 
> But when I go into the directory with the Git-sources from which I built, I can find a few occurrences of `/usr/bin/perl`
> Maybe I should have been more specific: The compilation works fine. But then, h2o cannot be started because perl is not found.

It is true that the some files have `/usr/bin/perl` hard-coded.  However, my understanding is that they are neither used during make or after installation.

When I install 2.0.0-DEV using `make install` and look into the files in `/path/to/install-dir/share/h2o`, all of the script files install there use the following shebang which is path-indedendent:
```
#! /bin/sh
exec perl -x $0 "$@"
#! perl
```

**Comment by utrenkner** [comment]
@kazuho I see. Then it really seems to be a FreeBSD specific challenge. At startup or when calling `service h2o start` the PATH does not include `/usr/local/bin`. Thus `exec perl` looks only for `/usr/bin/perl` and does not find perl there. That's why the FreeBSD port rewrites `exec perl` to `exec /usr/local/bin/perl`. Another solution would be to append the PATH, but I assume this is discouraged for RC scripts.

Thank you for your help.

**Comment by kazuho** [comment]
@utrenkner 
> Then it really seems to be a FreeBSD specific challenge. At startup or when calling `service h2o start` the PATH does not include `/usr/local/bin`. Thus exec perl looks only for `/usr/bin/perl` and does not find perl there.

Interesting.

Maybe I should alter the default shebang used in the perl scripts bundled with H2O.  For example, I could change it to:
```
#! /bin/sh
PERLPROG=perl
which ${PERLPROG} > /dev/null
if [ "$?" -ne 0 -a -x /usr/local/bin/perl ] ; then
    PERLPROG=/usr/local/bin/perl
fi
exec ${PERLPROG} -x $0 "$@"
#! perl
```

@dch Does this look sufficient and make it easy to maintain the FreeBSD port?  Or should we implement a more FreeBSD-specific way for determining the path of perl?

**Comment by dch** [comment]
hey folks, the port uses a factored-out function "shebang fix" https://github.com/freebsd/freebsd-ports/blob/master/www/h2o/Makefile#L17 as this is a generic linuxism in ports. I'm cool either way, it's no drama to change this if it makes source builds easier for people.

**Comment by utrenkner** [comment]
@kazuho @dch I think we are talking of different things here:
My understanding is, that the ["shebangfix"](https://www.freebsd.org/doc/en/books/porters-handbook/uses-shebangfix.html) in FreeBSD ports can fix the "shebang" at the beginning of a script. It would ensure that `#!/usr/bin/perl` is rewritten to `#!/usr/local/bin/perl`. However, this is not the problem here, as the shebang does not need to be fixed - it is `#!/bin/sh`

The problem lies with `exec perl`. And thus the port's Makefile additionally rewrites each occurrence in the shell scripts to `exec /usr/local/bin/perl`, see https://github.com/freebsd/freebsd-ports/blob/master/www/h2o/Makefile#L55-L59

I would appreciate a fix that allowed FreeBSD users to compile directly from source. Or else, a tip in the [install documentation](https://h2o.examp1e.net/install.html)

**Comment by kazuho** [comment]
@utrenkner agreed.

Considering the following facts, I am leaning towards _not_ fixing it within H2O.
* LOCALBASE can be something other than `/usr/local` (and it actually happens - the default is `/usr/pkg` for NetBSD)
* which perl should be used depends on the user, and this would be especially the case if it cannot be found in `PATH`

I am considering of changing the shebang we use from
```
#! /bin/sh
exec perl -x $0 "$@"
#! perl
```
to
```
#! /bin/sh
exec ${H2O_PERL:-perl} -x $0 "$@"
#! perl
```
so that launch scripts can set the `H2O_PERL` environment variable to define the path of the interpreter.

In case of the FreeBSD port, the environment variable could be set in the startup script.

**Comment by kazuho** [comment]
@dch With #847 merged that implements supports `H2O_PERL` environment variable, I think you can make the following changes which will make our lives easier.
* add `export H2O_PERL="%%LOCALBASE%%/bin/perl"` to h2o.in
* remove the perl-path rewrite hack from the Makefile
