### ISSUE TITLE
Compiling H2O with mruby_mongo gem fails

### ISSUE THREAD

**Issue by ianchen06** [h2o/h2o#881]
Hello,

I tried to compile H2O with mruby_mongo gem, I am sure that I have libmongoc installed on my machine, but I always get the undefined reference error. 

Here are the steps to reproduce.

```
git clone  https://github.com/h2o/h2o
cd deps
git clone https://github.com/vessi/mruby-mongo
cd ..
cmake -DWITH_BUNDLED_SSL=on .
```

The error message is as follows

```
[  0%] Linking CXX executable h2o
mruby/host/lib/libmruby.a(mrb_mongo.o): In function `mrb_mruby_mongo_gem_init':
/home/ian/Code/h2o/deps/mruby-mongo/src/mrb_mongo.c:50: undefined reference to `mongoc_init'
...
mruby/host/lib/libmruby.a(types.o): In function `mrb_mongo_bson_data_free':
/home/ian/Code/h2o/deps/mruby-mongo/src/types.c:5: undefined reference to `bson_destroy'
mruby/host/lib/libmruby.a(types.o): In function `mrb_mongo_client_data_free':
/home/ian/Code/h2o/deps/mruby-mongo/src/types.c:10: undefined reference to `mongoc_client_destroy'
mruby/host/lib/libmruby.a(types.o): In function `mrb_mongo_database_data_free':
/home/ian/Code/h2o/deps/mruby-mongo/src/types.c:15: undefined reference to `mongoc_database_destroy'
mruby/host/lib/libmruby.a(types.o): In function `mrb_mongo_collection_data_free':
/home/ian/Code/h2o/deps/mruby-mongo/src/types.c:20: undefined reference to `mongoc_collection_destroy'
collect2: error: ld returned 1 exit status
make[2]: *** [h2o] Error 1
make[1]: *** [CMakeFiles/h2o.dir/all] Error 2
make: *** [all] Error 2

```

Am I including additional mruby_gems the wrong way?
Thanks,

**Comment by kazuho** [comment]
You'd need to specify the library using the `EXTRA_LIBS` environment variable.

In your case, I assume `cmake -DWITH_BUNDLED_SSL=on -DEXTRA_LIBS=-lmongoc` will do the work.

relates to #793

**Comment by ianchen06** [comment]
@kazuho Thank you for your prompt reply. Indeed the issue is solved. 
Thanks for such a great software!

**Comment by ruprict** [comment]
So, I can't get this to work, mainly b/c I am a noob at this.  I have built the mongo-c-driver and have added mruby-mongo to `deps` I had to pass `-DEXTRA_LIBS=-lmongoc-1.0` to get it to make, but it does. However, mruby can't find the `Mongo` class/module.  

```
LD_LIBRARY_PATH=/usr/local/lib ./mruby/host/bin/mirb

> Mongo
(mirb):1: uninitialized constant Mongo (NameError)
```

Any chance someone could nudge me in the right direction?

**Comment by ruprict** [comment]
so, if I build mruby in `deps/mruby`, the binaries there seem to have the right stuff, meaning, I `PG` is an object, I can connect to postgresql, etc. (I switched to trying postgresql), but the binaries in `mruby/host/bin` don't.  Again, I know this is b/c I am ignorant to the right way to build h2o and mruby with a added gem.

**Comment by ruprict** [comment]
So...I figured out why I'm dumb (at least, in this case). Need to rm the `mruby` dir to make it rebuild all the things. Works  now.

Sorry for the noise.

**Comment by pyros2097** [comment]
Can someone make this a package or project so that we can test it out? It might end up becoming something like openresty.
