### ISSUE TITLE
X-Forwarded-Proto when behind another Proxy

### ISSUE THREAD

**Issue by dstufft** [h2o/h2o#883]
Currently h2o will append to the end of the ``X-Forwarded-For`` header whenever it sees that header already exists, however it will not do the same for the ``X-Forwarded-Proto``, which means that if there is another processing terminating TLS and adding ``X-Forwarded-Proto`` then we lose the information about what protocol was being used on the "edge" of the request.

Would it be possible to add a setting to suppress h2o adding it's own ``x-forwarded-*`` headers?

**Comment by kazuho** [comment]
@dstufft Done in #892.  Please let me know if you still have issues.

**Comment by dstufft** [comment]
Awesome! Thanks a lot for the quick turn around too :)
