### ISSUE TITLE
window update on session and stream for H2

### ISSUE THREAD

**Issue by valour01** [h2o/h2o#894]
I use h2o `1.6.2`. And I observed the following 

- I send the settings frame to set a zero initial window(without window update automatically)

- I send some requests out

- after all the requests have been sent out, I send a window update on stream 0(session), I noticed I received no data. But when I send a window update on stream i without sending window update on session, I can receive the data on stream i

Maybe I understood RFC wrong. I think session flow control and stream flow control are combined to limit the flow. But it seems that session flow control has no influence on the stream.

**Comment by kazuho** [comment]
I believe H2O is behaving according to the specification.

[Section 6.5.2 of the HTTP/2 specification](http://http2.github.io/http2-spec/index.html#rfc.section.6.5.2) states that SETTINGS_INITIAL_WINDOW_SIZE of the SETTINGS frame only affects the default of the streams, but not that of the connection.

Therefore, when you set SETTINGS_INITIAL_WINDOW_SIZE to zero, you will not receive the responses until you send a stream-level WINDOW_UPDATE frame.

**Comment by valour01** [comment]
If so, is it available to  set the connection window to be 0 at the beginning of the connection. I think a server can send data only when there are enough session window and stream window.

**Comment by kazuho** [comment]
> If so, is it available to set the connection window to be 0 at the beginning of the connection.

No.  Providing such an option would violate the HTTP/2 specification.  Initial size of the connection window size is defined as 65,536 in [Section 6.9.2](http://http2.github.io/http2-spec/index.html#rfc.section.6.9.2).

> I think a server can send data only when there are enough session window and stream window.

Correct.

**Comment by valour01** [comment]
I see, thanks
