### ISSUE TITLE
Speed up Reverse Proxy

### ISSUE THREAD

**Issue by karantin2020** [h2o/h2o#904]
Hello. H2O Reverse Proxy request per second is to low when compare to direct access.

Is it possible to speed up Reverse Proxy by some way? Thanks

**Comment by kazuho** [comment]
It's not suprising that reverse proxying is much slower than direct access, considering the number of operations that must be performed.

Generally speaking, H2O has the best-of-class proxy implementation (thanks to it's ultra-fast HTTP/1 parser and buffer management).

**Comment by karantin2020** [comment]
Ok, thanks
