### ISSUE TITLE
h2o always return with [h2o.conf:2] node must be a MAPPING

### ISSUE THREAD

**Issue by aliefarlingga** [h2o/h2o#915]
Hello Mr. Kazuho
My name is Alief.

After installing h2o, I run the configuration like this and it works like charm. But when I change some of the configuration it always return with error : 
` [h2o.conf:2] node must be a MAPPING`

Even when I try the other configuration of example or an empty configuration, it still returns with the same error.

I already look to an #246 , and I copied it but still not working.
Do you have any solution sir?

here is my configuration : 
```
listen:
  port: 8080
user: www-data
hosts:
  "localhost":
    paths:
      /:
         file.dir: /home/alief/http2rulez/public

# for handling PHP
file.custom-handler:
  extension: .php
  fastcgi.connect:
    port: /var/run/php5-fpm.sock
    type: unix


access-log: /home/alief/h2o/access-log
error-log: /home/alief/h2o/error-log
pid-file: /home/alief/h2o/pid-file
```

Best regards 
~ Alief

**Comment by kazuho** [comment]
How did you edit the configuration file?

If you edited the file on Windows and uploaded it, then you might be using CR-LF as the line terminator of the configuration file.  Changing it to LF-only might help.

**Comment by aliefarlingga** [comment]
well I edit the the configuration using command vim and after i check the file endline type using
```
$ file h2o.conf
h2o.conf: ASCII text
```
no CRLF detected.

Well I tried to reinstall it by using  `make install` again, it works but only once. Then it returned with the same error again.
It's kinda like there is some mechanism that the binary h2o save some cookies from the last configuration used.
But it's just my theory.

**Comment by kazuho** [comment]
Maybe I could look at it if you could upload the configuration file that causes the error somewhere (possible after zipping it so that the original file would be retained).

**Comment by aliefarlingga** [comment]
here is the download link sir : [simple.conf](https://drive.google.com/open?id=0ByWuAFAa3BnqOEh5VTJJMHpyTWM)
I didn't compress, hope you can find out what's happening.

**Comment by kazuho** [comment]
@aliefarlingga Thank you for the link. YAML error is not reported on my side.

Another possibility of this strange error is that a wrong version of header file is used when building H2O.

Can you please see if yaml.h exists in one of the default include directories of gcc?

The list of default include directories can be determined by running `gcc -v -x c -E - < /dev/null`.  On my Linux box, it emits [this output](https://gist.github.com/kazuho/a19fb5328339127a19243d0094fe5772#file-gistfile1-txt-L12-L18), which means that the following four are the default directories.
```
 /usr/lib/gcc/x86_64-linux-gnu/4.8/include
 /usr/local/include
 /usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed
 /usr/include/x86_64-linux-gnu
 /usr/include
```

**Comment by aliefarlingga** [comment]
here is the result : [output-debug-h2o-1](https://gist.github.com/aliefarlingga/0421d9d1b3acf5db2db952ada860aea1#file-h2o-debug-1)
same output as yours with i386 architecture since I'm using it now.

Honestly, I haven't installed libyaml, sorry for my foolishnes.
Then when I run `h2o`, I only use command `h2o` without args `--conf`.

So now it's working again like charm, by adding `--conf`.
I don't know this sir, but last time without that args, the `h2o `worked just fine.

Conclusion :
- Don't forget to add args `--conf` when running the bin `h2o`
- Make sure all libraries have been installed before. In my case : libyaml

I think it's already cleared and this issue is solved.
Thanks for your suggestion sir @kazuho .

**Comment by aliefarlingga** [comment]
closed

**Comment by aliefarlingga** [comment]
closed
