### ISSUE TITLE
After las updates we get this  Assertion `thread_notify_signo != 0' failed.

### ISSUE THREAD

**Issue by mingodad** [h2o/h2o#93]
The variable thread_notify_signo is not set anywhere !

/h2o/lib/serverutil.c:68: h2o_thread_notify: Assertion `thread_notify_signo != 0' failed.

Aafter 6 runs of   "ab -n 100000 -c 400 -k http://127.0.0.1:8080/" .

h2o.config
--------------
max-connections: 4096
num-threads: 2
listen: 8080
listen:
  port: 8081
  ssl:
    certificate-file: examples/h2o/server.crt
    key-file: examples/h2o/server.key

hosts:
  "127.0.0.1:8080":
    paths:
      /--xxx--:
        file.dir: examples/doc_root
    access-log: /dev/null

  "127.0.0.1.xip.io:8080":
    paths:
      /:
        file.dir: examples/doc_root
    access-log: /dev/null

  "alternate.127.0.0.1.xip.io:8081":
    listen:
      port: 8081
      #port: h2o_unix
      #type: unix
      ssl:
        certificate-file: examples/h2o/alternate.crt
        key-file: examples/h2o/alternate.key
    paths:
      /:
        file.dir: examples/doc_root.alternate
    access-log: /dev/null

**Comment by kazuho** [comment]
My bad.  Fixed the issue / added test that covers the behaviour of max-connections.
