### ISSUE TITLE
wrong declaration in simple.c

### ISSUE THREAD

**Issue by 9il** [h2o/h2o#939]
`static void on_accept(h2o_socket_t *listener, int status)` is passed to `void h2o_socket_read_start(h2o_socket_t *sock, h2o_socket_cb cb)` (second argument), but `h2o_socket_cb` is `void function(h2o_socket_t *sock, const (char) *err)`

**Comment by kazuho** [comment]
Thank you for reporting the issue.  Fixed in the commit above.
