### ISSUE TITLE
issues bet. master branch and Safari

### ISSUE THREAD

**Issue by kazuho** [h2o/h2o#953]
It became impossible to browse h2o.examp1e.net when we updated the website to the latest master.

Rolling back to 2.0 fixed the issue.

**Comment by deweerdt** [comment]
FWIW, I couldn't repro the issue here with Safari 9.1.1 (11601.6.17). Any ideas on what might be going on?

**Comment by kazuho** [comment]
Sorry for taking your time, I fixed this in d92bca0 but forgot to close the issue.
