### ISSUE TITLE
how to write a database driver

### ISSUE THREAD

**Issue by yannick** [h2o/h2o#954]
is there some documentation on how within a request handler evloop sockets
can be opened and calls e.g. to database drivers can be made?

i dont understand the overall pattern that needs to be followed so that the result is a single 
function call results in data being available in a request handler but the calls behind it are made in non blocking fashion.

and/or how do i "yield" to evloop?

**Comment by kazuho** [comment]
> is there some documentation on how within a request handler evloop sockets can be opened and calls e.g. to database drivers can be made?

Unfortunately there is no documentation. You might be interested in reading examples/libh2o/socket-client.c.
