### ISSUE TITLE
Firefox v48 not negotiating with ChaCha20

### ISSUE THREAD

**Issue by Tintinabula** [h2o/h2o#975]
I noticed that Firefox version 48 on Ubuntu 16.04 does not negotiate with https://h2o.examp1e.net using ChaCha20.

I tested the connection by disabling all ciphers in Firefox v48 (about:config) other than security.ssl3.ecdhe_rsa_chacha20_poly1305_sha256 and the connection to https://h2o.examp1e.net failed with, "no cipher overlap". h2o.examp1e.net is using an RSA certificate, but perhaps ChaCha20 is not enabled.

My second test was to setup my own H2O webserver using an ECDSA certificate and only allow ChaCha20 with "cipher-suite: ECDHE-ECDSA-CHACHA20-POLY1305". Firefox v48 refused to connect to my server with ChaCha20 and reported the error, "no cipher overlap". Google Chrome v51 connected to my H2O web server using ChaCha20 without error according to my logs.

My third test used Nginx with their HTTP/2 module. Both Firefox v48 and Google Chrome v51 connected to nginx using ChaCha20 when ChaCha20 was the preferred server side cipher or the only cipher allowed.

Could there be a bug somewhere which interferes with Firefox v48 from using ChaCha20 with H20 (h2o/2.1.0-DEV) ?

**Comment by TheDecryptor** [comment]
h2o uses an older version of LibreSSL that doesn't support the final version of ChaCha20, Firefox only supports the final version, while Chrome supports the final and earlier versions.

You can see [here](https://www.ssllabs.com/ssltest/analyze.html?d=h2o.examp1e.net) that the ChaCha20 suite is prefixed with "OLD", meaning the earlier version.

**Comment by kazuho** [comment]
@TheDecryptor Thank you for your comment. My understanding is that it describes the case where h2o is built using the bundled libressl.

@Tintinabula If you are interested in using the finalized version of CHACHA20-POLY1305, I'd suggest building OpenSSL 1.0.2 with https://github.com/cloudflare/sslconfig/blob/master/patches/openssl__chacha20_poly1305_draft_and_rfc_ossl102f.patch and build h2o against the openssl.

**Comment by TheDecryptor** [comment]
@kazuho Ahh, right, sorry. I keep forgetting that the distro package I use (for Arch) forces the bundled LibreSSL copy, which isn't the default configuration.

**Comment by kazuho** [comment]
@TheDecryptor Never mind. I always feel very grateful for your suggestions on the issue list. Thank you very much.

And for this matter, without your comment I couldn't have recalled my memory that the ID for chacha20 had changed :-)

**Comment by Tintinabula** [comment]
Ah, I see now. I am building H2O from source (git clone) using the bundled version of Libressl 2.2.7 which only supports the pre-RFC version of ChaCha20. 

I built the latest version of Libressl 2.4.1 and noticed that support for both the "-OLD" and final RFC versions of ChaCha20 were listed.

```
#  ./apps/openssl/openssl ciphers -V CHACHA20
  0xCC,0xA9 - ECDHE-ECDSA-CHACHA20-POLY1305 TLSv1.2 Kx=ECDH     Au=ECDSA Enc=ChaCha20-Poly1305 Mac=AEAD
  0xCC,0xA8 - ECDHE-RSA-CHACHA20-POLY1305 TLSv1.2 Kx=ECDH     Au=RSA  Enc=ChaCha20-Poly1305 Mac=AEAD
  0xCC,0xAA - DHE-RSA-CHACHA20-POLY1305 TLSv1.2 Kx=DH       Au=RSA  Enc=ChaCha20-Poly1305 Mac=AEAD
  0xCC,0x14 - ECDHE-ECDSA-CHACHA20-POLY1305-OLD TLSv1.2 Kx=ECDH     Au=ECDSA Enc=ChaCha20-Poly1305-Old Mac=AEAD
  0xCC,0x13 - ECDHE-RSA-CHACHA20-POLY1305-OLD TLSv1.2 Kx=ECDH     Au=RSA  Enc=ChaCha20-Poly1305-Old Mac=AEAD
  0xCC,0x15 - DHE-RSA-CHACHA20-POLY1305-OLD TLSv1.2 Kx=DH       Au=RSA  Enc=ChaCha20-Poly1305-Old Mac=AEAD
```
Thanks for the clarification and the links.
