### ISSUE TITLE
t/50sni.t fails when building on a system without public internet access.

### ISSUE THREAD

**Issue by quentusrex** [h2o/h2o#978]
Seems the test doesn't confirm that DNS resolution works before moving forward with the test. In this use case the library is attempting to be packaged for Debian, and that package would require being built without public internet access. 

The rest of the tests appear to be passing.

**Comment by quentusrex** [comment]
t/50sni.t .......................................... 
    # Subtest: basic
spawning /usr/src/libh2o-2.0.0/obj-x86_64-linux-gnu/h2o... [INFO] raised RLIMIT_NOFILE to 65536
h2o server (pid:13583) is ready to serve requests
fetch-ocsp-response (using OpenSSL 1.0.1k 8 Jan 2015)
fetch-ocsp-response (using OpenSSL 1.0.1k 8 Jan 2015)
fetch-ocsp-response (using OpenSSL 1.0.1k 8 Jan 2015)
failed to extract ocsp URI from examples/h2o/server.crt
failed to extract ocsp URI from examples/h2o/alternate.crt
[OCSP Stapling] disabled for certificate file:examples/h2o/server.crt
[OCSP Stapling] disabled for certificate file:examples/h2o/alternate.crt
failed to extract ocsp URI from examples/h2o/alternate.crt
[OCSP Stapling] disabled for certificate file:examples/h2o/alternate.crt
done
wget: unable to resolve host address ‘127.0.0.1.xip.io’
    not ok 1 - wget returns success
    
    #   Failed test 'wget returns success'
    #   at t/50sni.t line 86.
    #          got: '1024'
    #     expected: '0'
    not ok 2 - content is as expected
    
    #   Failed test 'content is as expected'
    #   at t/50sni.t line 87.
    #          got: 'd41d8cd98f00b204e9800998ecf8427e'
    #     expected: '77b3f0dda60a1838f25632f7e507a234'
2016-07-07 09:24:53 URL:https://alternate.127.0.0.1.xip.io:50986/ [6/6] -> "-" [1]
    ok 3 - wget returns success
    ok 4 - content is as expected
killing /usr/src/libh2o-2.0.0/obj-x86_64-linux-gnu/h2o... killed (got 0)
    1..4
    # Looks like you failed 2 tests of 4.
not ok 1 - basic

#   Failed test 'basic'
#   at t/50sni.t line 46.
    # Subtest: wildcard

**Comment by quentusrex** [comment]
Should be as simple as adding the 1-2 lines to have that test marked as a live test.

**Comment by kazuho** [comment]
> the library is attempting to be packaged for Debian, and that package would require being built without public internet access.

Is it a requirement to get all the tests passed? While it would be possible to skip t/50sni.t, I am not sure if that would resolve your issue, since there are other issues that might cause a test to fail.

For example, most of the test case uses Test::TCP to find an empty port, and then spawns h2o configured to use that port. Unfortunately, there is an inevitable interval between the two, therefore TOCTOU issue exists here. We occasionally see this (esp. on Travis).

**Comment by quentusrex** [comment]
In this case, once I had installed all of the required perl modules, all of the non live tests were passing. This one needed a local patch to move it to a live category test since it does require working DNS where the other tests appear to work properly without public internet access.

**Comment by kazuho** [comment]
Can you submit a PR that marks t/50sni.t as a live test? I assume you used `LIVE_TESTS` environment variable. I would appreciate it if you could change the prefix of the test from `50` to `90live-` as well.

**Comment by quentusrex** [comment]
Yeah, I can get a PR created today.

**Comment by kazuho** [comment]
Thank you for the PR!
