### ISSUE TITLE
Few heavy locks on socketpool.c

### ISSUE THREAD

**Issue by mingodad** [h2o/h2o#98]
Hello !

I found 3 places on socketpool.c where a full mutex lock/unlock are used to only update an integer variable:

pthread_mutex_lock(&pool->_mutex);
--pool->_shared.count;
pthread_mutex_unlock(&pool->_mutex);

Wouldn't be a good fit for "__sync_fetch_and_add(pool->_shared.count, +- 1)" ?

Cheers !

**Comment by nickdesaulniers** [comment]
Cool! Thanks for pointing this out, was inspired by a recent talk I saw about atomics vs mutexes.  Just curious, I know the qrintf stuff requires gcc extensions, but wouldn't c11 atomics be preferred?  If so, I'd be happy to rewrite my patch.

**Comment by nickdesaulniers** [comment]
Would it be faster to use `__sync_add_and_fetch` in place of `__sync_fetch_and_add` based on the [documentation](https://gcc.gnu.org/onlinedocs/gcc-4.1.2/gcc/Atomic-Builtins.html)?

**Comment by nickdesaulniers** [comment]
Let's look at the emitted instructions: `gobjdump -d CMakeFiles/h2o.dir/lib/common/socketpool.c.o | less`
then `/on_close`

fetch and add:
```
0000000000000610 <_on_close>:
 610:   55                      push   %rbp
 611:   48 89 e5                mov    %rsp,%rbp
 614:   f0 48 ff 8f b8 00 00    lock decq 0xb8(%rdi)
 61b:   00
 61c:   5d                      pop    %rbp
 61d:   c3                      retq
 61e:   66 90                   xchg   %ax,%ax
```

add and fetch:
```
0000000000000610 <_on_close>:
 610:   55                      push   %rbp
 611:   48 89 e5                mov    %rsp,%rbp
 614:   f0 48 ff 8f b8 00 00    lock decq 0xb8(%rdi)
 61b:   00
 61c:   5d                      pop    %rbp
 61d:   c3                      retq
 61e:   66 90                   xchg   %ax,%ax
```
