### ISSUE TITLE
Odd ECDSA error

### ISSUE THREAD

**Issue by NightDevel** [h2o/h2o#989]
I'm trying to load an ECC key, but get the following error:
 in command listen, failed to load private key file:/keys/ecc/mydomain.ecc:failed to parse the private key

However, it is able to load my RSA keys just fine, same permissions, no password set on any of these keys.

I saw #812, and attempted to put in "neverbleed: off"

However, I then received the following error:
:2] unknown command: neverbleed

The key file is of format

-----BEGIN EC PRIVATE KEY-----
#ECC STUFF HERE
-----END EC PRIVATE KEY-----

Anything I could be missing?

# h2o -v
h2o version 2.1.0-DEV
OpenSSL: LibreSSL 2.4.1

**Comment by kazuho** [comment]
Please set `neverbleed: OFF` to your ssl configuration. OpenSSL 1.0.2 / LibreSSL does not provide abstractions that can be used to perform private key operations outside the libraries.

https://h2o.examp1e.net/configure/base_directives.html#neverbleed

**Comment by NightDevel** [comment]
Does h2o compile with neverbleed by default?  h2o doesn't seem to recognize the neverbleed: off directive, so I had assumed that it was not compiled and therefore wouldn't be the same issue as #812 

!! :2] unknown command: neverbleed


I will check again and see if I am making a mistake

**Comment by NightDevel** [comment]
Upon further investigation, a yaml error caused the neverbleed directive to appear outside of the ssl: block.

Apologies.
