### ISSUE TITLE
How to prevent processing requests with undefined server names?

### ISSUE THREAD

**Issue by ramsingla** [h2o/h2o#990]
In nginx we can define 

server {
    listen      80;
    server_name "";
    return      444;
}

Here, the server name is set to an empty string that will match requests without the “Host” header field, and a special nginx’s non-standard code 444 is returned that closes the connection.

Is there a mechanism to do similar thing in h2o?

**Comment by kazuho** [comment]
You can define a catch-all host, but there is no way to instruct the server to close the connection (note: if the host header is not specified or if no matching host was found within the hosts that binds to the connected address:port, then the request is handled by first host entry that binds to the connected address:port).

Would you mind elaborating under what circumstances you would want to close the connection?

**Comment by ramsingla** [comment]
It is generally when some malicious domain points to another domain's ip address. There are two options I can think of - a/ Redirect to the correct domain or b/ Terminate the connection.

**Comment by ramsingla** [comment]
I don't think this issue needs to be implemented, the simplicity of h2o is better. will close this issue.

**Comment by kazuho** [comment]
@ramsingla Great.

Just a note: if we are to implement this kind of feature, it should be done by the server automatically; i.e. start closing connections as their numbers become near to `max-connections`.
