### ISSUE TITLE
Can we use h2o to proxy long polling endpoints?

### ISSUE THREAD

**Issue by ramsingla** [h2o/h2o#991]
I am using XMPP in our web app for messaging and supporting both web sockets and bosh. I am not sure whether long polling requests of bosh would work correctly with h2o?

**Comment by kazuho** [comment]
It should work. You may want to alter the proxy.io.timeout value to meet your needs.

**Comment by ramsingla** [comment]
Thanks for the update appreciate it. So far my experience of playing with h2o has been awesome. I am closing this comment.
